Repository espoon-voltti/evaka, pull requests merged in 2024-07, with the labels that each got.

#5325 ES2022-yhteensopivuus
  frontend/src/e2e-test/pages/admin/application-workbench-page.ts
  frontend/src/e2e-test/pages/citizen/citizen-applications.ts
  frontend/src/e2e-test/pages/citizen/citizen-assistance-need-decision.ts
  frontend/src/e2e-test/pages/citizen/citizen-calendar.ts
  frontend/src/e2e-test/pages/citizen/citizen-child-income.ts
  frontend/src/e2e-test/pages/citizen/citizen-children.ts
  frontend/src/e2e-test/pages/citizen/citizen-decisions.ts
  frontend/src/e2e-test/pages/citizen/citizen-income.ts
  frontend/src/e2e-test/pages/citizen/citizen-map.ts
  frontend/src/e2e-test/pages/citizen/citizen-messages.ts
  frontend/src/e2e-test/pages/employee/IncomeStatementPage.ts
  frontend/src/e2e-test/pages/employee/applications.ts
  frontend/src/e2e-test/pages/employee/applications/application-list-view.ts
  frontend/src/e2e-test/pages/employee/documents/document-templates.ts
  frontend/src/e2e-test/pages/employee/finance-basics.ts
  frontend/src/e2e-test/pages/employee/finance/finance-page.ts
  frontend/src/e2e-test/pages/employee/holiday-term-periods.ts
  frontend/src/e2e-test/pages/employee/person-search.ts
  frontend/src/e2e-test/pages/employee/reports.ts
  frontend/src/e2e-test/pages/employee/units/unit-calendar-page-base.ts
  frontend/src/e2e-test/pages/employee/units/unit-groups-page.ts
  frontend/src/e2e-test/pages/employee/units/unit.ts
  frontend/src/e2e-test/pages/employee/vasu/vasu-templates-list.ts
  frontend/src/e2e-test/pages/employee/vasu/vasu.ts
  frontend/src/e2e-test/pages/mobile/absences-page.ts
  frontend/src/e2e-test/pages/mobile/child-attendance-page.ts
  frontend/src/e2e-test/pages/mobile/child-page.ts
  frontend/src/e2e-test/pages/mobile/note-page.ts
  frontend/src/e2e-test/pages/mobile/staff-page.ts
  frontend/src/e2e-test/pages/mobile/thread-view.ts
  frontend/src/e2e-test/specs/0_citizen/citizen-decisions.spec.ts
  frontend/tsconfig.base.json
Labels: tech

#5337 Korjaus laskujen luontiin (kiinteä päivähinnan jakaja + lyhyt kuukausi + maksuttomat poissaolot)
  service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/service/InvoiceGeneratorIntegrationTest.kt
  service/src/main/kotlin/fi/espoo/evaka/invoicing/service/DraftInvoiceGenerator.kt
Labels: bug

#5321 Henkilökunta voi editoida ainoastaan omia läsnäolojaan
  frontend/src/e2e-test/pages/employee/units/unit-week-calendar-page.ts
  frontend/src/e2e-test/specs/5_employee/realtime-attendances.spec.ts
  frontend/src/employee-frontend/components/unit/unit-reservations/StaffAttendanceTable.tsx
  frontend/src/lib-common/generated/api-types/attendance.ts
  service/src/integrationTest/kotlin/fi/espoo/evaka/attendance/RealtimeStaffAttendanceControllerIntegrationTest.kt
  service/src/main/kotlin/fi/espoo/evaka/attendance/RealtimeStaffAttendanceController.kt
  service/src/main/kotlin/fi/espoo/evaka/attendance/StaffAttendance.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/security/Action.kt
Labels: enhancement

#5338 Korjaus raportin ACL-koodiin
  service/src/main/kotlin/fi/espoo/evaka/reports/NonSsnChildrenReportController.kt
Labels: bug

#5343 Päivitetään Gradle OWASP plugin versioon 10.0.1
  service/gradle/libs.versions.toml
Labels: dependencies

#5342 Lisätään osoitesivun tuki Suomi.FI REST -pilottikoodiin
  service/src/integrationTest/kotlin/fi/espoo/evaka/sficlient/rest/SfiMessagesRestClientIntegrationTest.kt
  service/src/main/kotlin/fi/espoo/evaka/sficlient/rest/RestSchema.kt
  service/src/main/kotlin/fi/espoo/evaka/sficlient/rest/SfiMessagesRestClient.kt
Labels: tech

#5340 E2E-testit kuntalaisen Keycloakin rekisteröitymiselle ja unohdin salasanani -toiminnolle
  compose/docker-compose.yml
  compose/e2e/playwright/bin/run-tests.sh
  frontend/package.json
  frontend/src/e2e-test/pages/citizen/citizen-dummy-suomifi.ts
  frontend/src/e2e-test/pages/citizen/citizen-keycloak.ts
  frontend/src/e2e-test/specs/0_citizen/citizen-auth.spec.ts
  frontend/src/e2e-test/specs/0_citizen/citizen-child-page.spec.ts
  frontend/src/e2e-test/specs/0_citizen/citizen-keycloak.spec.ts
  frontend/src/e2e-test/specs/0_citizen/citizen-personal-details.spec.ts
  frontend/src/e2e-test/specs/7_messaging/messaging-by-staff.spec.ts
  frontend/src/e2e-test/specs/7_messaging/messaging.spec.ts
  frontend/src/e2e-test/utils/dummy-suomifi.ts
  frontend/src/e2e-test/utils/keycloak.ts
  frontend/src/e2e-test/utils/mailhog.ts
  frontend/src/e2e-test/utils/user.ts
  frontend/yarn.lock
  keycloak/Dockerfile
  keycloak/compose-resources/configuration/evaka.json
  keycloak/docker-compose.yml
  keycloak/dummy-suomifi/.dockerignore
  keycloak/dummy-suomifi/.gitignore
  keycloak/dummy-suomifi/Dockerfile
  keycloak/dummy-suomifi/build.gradle.kts
  keycloak/dummy-suomifi/gradle.properties
  keycloak/dummy-suomifi/gradle/libs.versions.toml
  keycloak/dummy-suomifi/gradle/wrapper/gradle-wrapper.jar
  keycloak/dummy-suomifi/gradle/wrapper/gradle-wrapper.properties
  keycloak/dummy-suomifi/gradlew
  keycloak/dummy-suomifi/gradlew.bat
  keycloak/dummy-suomifi/settings.gradle.kts
  keycloak/dummy-suomifi/src/main/kotlin/dummy_suomifi/App.kt
  keycloak/dummy-suomifi/src/main/kotlin/dummy_suomifi/Config.kt
  keycloak/dummy-suomifi/src/main/kotlin/dummy_suomifi/Saml.kt
  keycloak/dummy-suomifi/src/main/kotlin/dummy_suomifi/User.kt
  keycloak/dummy-suomifi/src/main/kotlin/dummy_suomifi/Utils.kt
Labels: tech

#5345 Päivitetään Keycloak versioon 25.0.1
  keycloak/Dockerfile
  keycloak/docker-compose.yml
  keycloak/evaka-logging/pom.xml
  keycloak/evaka-review-profile/pom.xml
  keycloak/evaka-review-profile/src/main/java/com/espoo/keycloak/authenticator/EvakaReviewProfileAuthenticator.java.diff
  keycloak/evaka-review-profile/src/main/java/com/espoo/keycloak/authenticator/EvakaReviewProfileAuthenticatorFactory.java.diff
Labels: tech

#5341 Korjauksia palse-arvoeditoriin
  frontend/src/employee-frontend/components/finance-basics/ServiceNeedItem.tsx
  frontend/src/employee-frontend/components/finance-basics/VoucherValueEditor.tsx
  frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
  service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/VoucherValueIntegrationTest.kt
  service/src/main/kotlin/fi/espoo/evaka/invoicing/controller/FinanceBasicsController.kt
Labels: bug

#5357 Bump yarn from 4.1.1 to 4.3.1
  apigw/.yarn/releases/yarn-4.1.1.cjs
  apigw/.yarn/releases/yarn-4.3.1.cjs
  apigw/.yarnrc.yml
  apigw/package.json
  apigw/yarn.lock
  frontend/.yarn/releases/yarn-4.1.1.cjs
  frontend/.yarn/releases/yarn-4.3.1.cjs
  frontend/.yarnrc.yml
  frontend/package.json
  frontend/yarn.lock
Labels: dependencies

#5358 Upgrade lint packages
  frontend/package.json
  frontend/yarn.lock
Labels: dependencies

#5363 Korjataan digitransit API-virheiden lokitusformaatti
  apigw/src/enduser/mapRoutes.ts
Labels: tech

#5326 Loma-aikojen varausten lukitseminen
  frontend/src/citizen-frontend/calendar/CalendarNotifications.tsx
  frontend/src/citizen-frontend/calendar/CalendarPage.tsx
  frontend/src/citizen-frontend/calendar/DayView.tsx
  frontend/src/citizen-frontend/calendar/ReservationModal.tsx
  frontend/src/citizen-frontend/calendar/calendar-elements.tsx
  frontend/src/citizen-frontend/calendar/reservation-modal/TimeInputs.tsx
  frontend/src/citizen-frontend/calendar/reservation-modal/form.spec.ts
  frontend/src/citizen-frontend/calendar/reservation-modal/form.ts
  frontend/src/e2e-test/dev-api/fixtures.ts
  frontend/src/e2e-test/generated/api-clients.ts
  frontend/src/e2e-test/generated/api-types.ts
  frontend/src/e2e-test/pages/citizen/citizen-calendar.ts
  frontend/src/e2e-test/pages/employee/holiday-term-periods.ts
  frontend/src/e2e-test/specs/0_citizen/citizen-holiday-reservations.spec.ts
  frontend/src/e2e-test/specs/0_citizen/citizen-reservations.spec.ts
  frontend/src/e2e-test/specs/0_citizen/citizen-start-after-holiday-deadline.spec.ts
  frontend/src/e2e-test/specs/0_citizen/feature-flag-citizen-reservations-intermittent-shif-care.spec.ts
  frontend/src/e2e-test/specs/0_citizen/foster-parents.spec.ts
  frontend/src/e2e-test/specs/5_employee/holiday-term-period.spec.ts
  frontend/src/e2e-test/utils/page.ts
  frontend/src/employee-frontend/components/holiday-term-periods/HolidayAndTermPeriodsPage.tsx
  frontend/src/employee-frontend/components/holiday-term-periods/HolidayPeriodForm.tsx
  frontend/src/lib-common/generated/api-types/holidayperiod.ts
  frontend/src/lib-common/generated/api-types/reservations.ts
  frontend/src/lib-components/molecules/ExpandingInfo.tsx
  frontend/src/lib-components/molecules/date-picker/DatePickerLowLevel.tsx
  frontend/src/lib-components/molecules/date-picker/DateRangePicker.tsx
  frontend/src/lib-customizations/defaults/citizen/i18n/en.tsx
  frontend/src/lib-customizations/defaults/citizen/i18n/fi.tsx
  frontend/src/lib-customizations/defaults/citizen/i18n/sv.tsx
  frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
  service/src/integrationTest/kotlin/fi/espoo/evaka/absence/AbsenceControllerIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/absence/AbsenceServiceIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/dailyservicetimes/DailyServiceTimesIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/holidayperiod/HolidayPeriodControllerCitizenIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/holidayperiod/HolidayPeriodControllerIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/holidayperiod/HolidayPeriodFixtures.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/holidayperiod/HolidayPeriodIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/holidayperiod/HolidayPeriodQuestionnaireIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/reservations/AttendanceReservationsControllerIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/reservations/CreateReservationsAndAbsencesTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/reservations/MissingHolidayReservationsRemindersTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/reservations/ReservationControllerCitizenIntegrationTest.kt
  service/src/main/kotlin/fi/espoo/evaka/holidayperiod/HolidayPeriod.kt
  service/src/main/kotlin/fi/espoo/evaka/holidayperiod/HolidayPeriodController.kt
  service/src/main/kotlin/fi/espoo/evaka/holidayperiod/HolidayPeriodQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/reservations/AttendanceReservationController.kt
  service/src/main/kotlin/fi/espoo/evaka/reservations/ReservationControllerCitizen.kt
  service/src/main/kotlin/fi/espoo/evaka/reservations/Reservations.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/config/JacksonConfig.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/dev/DataInitializers.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/dev/DevApi.kt
  service/src/main/resources/db/migration/V426__holiday_period_reservations_open_on.sql
  service/src/main/resources/migrations.txt
Labels: enhancement

#5364 Bump org.owasp.dependencycheck from 10.0.1 to 10.0.2
  service/gradle/libs.versions.toml
Labels: dependencies

#5380 Loma-ajan infotekstin muutos kuntalaisille
  frontend/src/lib-customizations/defaults/citizen/i18n/en.tsx
  frontend/src/lib-customizations/defaults/citizen/i18n/fi.tsx
  frontend/src/lib-customizations/defaults/citizen/i18n/sv.tsx
Labels: enhancement

#5385 Korjataan e2e-testien ositus
  .github/workflows/build.yml
  bin/test-timings.sh
  bin/timings.sh
Labels: tech

#5389 Fix e2e job for forks
  .github/workflows/build.yml
Labels: no-changelog

#5386 Keskusteluvarausten varaaminen ja peruminen kuntalaiselle
  frontend/src/citizen-frontend/calendar/ActionPickerModal.tsx
  frontend/src/citizen-frontend/calendar/CalendarGridView.tsx
  frontend/src/citizen-frontend/calendar/CalendarNotifications.tsx
  frontend/src/citizen-frontend/calendar/CalendarPage.tsx
  frontend/src/citizen-frontend/calendar/DayElem.tsx
  frontend/src/citizen-frontend/calendar/DayView.tsx
  frontend/src/citizen-frontend/calendar/discussion-reservation-modal/DiscussionReservationModal.tsx
  frontend/src/citizen-frontend/calendar/discussion-reservation-modal/DiscussionSurveyModal.tsx
  frontend/src/citizen-frontend/calendar/discussion-reservation-modal/discussion-survey.ts
  frontend/src/citizen-frontend/calendar/queries.ts
  frontend/src/citizen-frontend/personal-details/NotificationSettingsSection.tsx
  frontend/src/e2e-test/generated/api-types.ts
  frontend/src/e2e-test/pages/citizen/citizen-calendar.ts
  frontend/src/e2e-test/pages/citizen/citizen-discussion-surveys.ts
  frontend/src/e2e-test/pages/citizen/citizen-personal-details.ts
  frontend/src/e2e-test/specs/0_citizen/citizen-discussion-surveys.spec.ts
  frontend/src/e2e-test/specs/0_citizen/citizen-personal-details.spec.ts
  frontend/src/lib-common/generated/api-types/calendarevent.ts
  frontend/src/lib-common/generated/api-types/pis.ts
  frontend/src/lib-components/molecules/Toast.tsx
  frontend/src/lib-customizations/defaults/citizen/i18n/en.tsx
  frontend/src/lib-customizations/defaults/citizen/i18n/fi.tsx
  frontend/src/lib-customizations/defaults/citizen/i18n/sv.tsx
  service/src/integrationTest/kotlin/fi/espoo/evaka/calendarevent/CalendarEventServiceIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/pis/controller/PersonalDataControllerCitizenIntegrationTest.kt
  service/src/main/kotlin/fi/espoo/evaka/calendarevent/CalendarEvent.kt
  service/src/main/kotlin/fi/espoo/evaka/calendarevent/CalendarEventController.kt
  service/src/main/kotlin/fi/espoo/evaka/calendarevent/CalendarEventNotificationService.kt
  service/src/main/kotlin/fi/espoo/evaka/calendarevent/CalendarEventQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/emailclient/EvakaEmailMessageProvider.kt
  service/src/main/kotlin/fi/espoo/evaka/emailclient/IEmailMessageProvider.kt
  service/src/main/kotlin/fi/espoo/evaka/pis/PersonalData.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/async/AsyncJob.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/dev/DevApi.kt
Labels: enhancement

#5390 Estetään yksikön sulkeminen jos sille on sijoituksia tai varasijoituksia sulkemispäivän jälkeen
  frontend/src/e2e-test/pages/employee/units/unit.ts
  frontend/src/e2e-test/specs/5_employee/unit-editor.spec.ts
  frontend/src/e2e-test/utils/page.ts
  frontend/src/employee-frontend/components/unit/unit-details/CreateUnitPage.tsx
  frontend/src/employee-frontend/components/unit/unit-details/UnitDetailsPage.tsx
  frontend/src/employee-frontend/components/unit/unit-details/UnitEditor.tsx
  frontend/src/lib-common/generated/api-types/daycare.ts
  frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
  service/src/integrationTest/kotlin/fi/espoo/evaka/daycare/controllers/DaycareControllerIntegrationTest.kt
  service/src/main/kotlin/fi/espoo/evaka/daycare/DaycareQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/daycare/controllers/DaycareController.kt
Labels: enhancement

#5391 Tekstikorjaus keskusteluajan perumiseen
  frontend/src/lib-customizations/defaults/citizen/i18n/fi.tsx
Labels: bug

#5400 Lisätty oletuspalveluntarve näkyviin ryhmät-taulukoihin
  frontend/src/employee-frontend/components/unit/tab-groups/MissingGroupPlacements.tsx
  frontend/src/employee-frontend/components/unit/tab-groups/groups/Group.tsx
  frontend/src/employee-frontend/types/unit.ts
  frontend/src/lib-common/generated/api-types/placement.ts
  service/src/integrationTest/kotlin/fi/espoo/evaka/placement/PlacementServiceIntegrationTest.kt
  service/src/main/kotlin/fi/espoo/evaka/placement/PlacementService.kt
Labels: enhancement

#5402 Lisätty OID:t yksiköt-raportille
  frontend/src/employee-frontend/components/reports/Units.tsx
  frontend/src/lib-common/generated/api-types/reports.ts
  frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
  service/src/main/kotlin/fi/espoo/evaka/reports/UnitsReport.kt
Labels: enhancement

#5401 Lisätty varasijoituksen ikoni mobiilin Seuraavat päivät -näkymään
  frontend/src/employee-mobile-frontend/child-attendance/ChildReservationList.tsx
  frontend/src/employee-mobile-frontend/child-attendance/ChildSubListItem.tsx
  frontend/src/lib-common/generated/api-types/reservations.ts
  service/src/integrationTest/kotlin/fi/espoo/evaka/reservations/AttendanceReservationsControllerIntegrationTest.kt
  service/src/main/kotlin/fi/espoo/evaka/reservations/AttendanceReservationController.kt
  service/src/main/kotlin/fi/espoo/evaka/reservations/ReservationQueries.kt
Labels: enhancement

#5404 Lisätään ohjeistuksia olla kääntämättä automaattisesti erisnimiä
  frontend/src/citizen-frontend/applications/ApplicationCreation.tsx
  frontend/src/citizen-frontend/applications/ChildApplicationsBlock.tsx
  frontend/src/citizen-frontend/applications/editor/Heading.tsx
  frontend/src/citizen-frontend/applications/editor/contact-info/ChildSubSection.tsx
  frontend/src/citizen-frontend/applications/editor/contact-info/GuardianSubSection.tsx
  frontend/src/citizen-frontend/applications/editor/contact-info/OtherChildrenSubSection.tsx
  frontend/src/citizen-frontend/applications/editor/unit-preference/SiblingBasisSubSection.tsx
  frontend/src/citizen-frontend/applications/editor/verification/BasicsSection.tsx
  frontend/src/citizen-frontend/applications/editor/verification/ContactInfoSecondGuardian.tsx
  frontend/src/citizen-frontend/applications/editor/verification/ContactInfoSection.tsx
  frontend/src/citizen-frontend/applications/editor/verification/UnitPreferenceSection.tsx
  frontend/src/citizen-frontend/calendar/AbsenceModal.tsx
  frontend/src/citizen-frontend/calendar/DayView.tsx
  frontend/src/citizen-frontend/calendar/ReservationModal.tsx
  frontend/src/citizen-frontend/calendar/discussion-reservation-modal/DiscussionReservationModal.tsx
  frontend/src/citizen-frontend/calendar/discussion-reservation-modal/DiscussionSurveyModal.tsx
  frontend/src/citizen-frontend/calendar/holiday-modal/FixedPeriodSelectionModal.tsx
  frontend/src/citizen-frontend/child-documents/ChildDocumentPage.tsx
  frontend/src/citizen-frontend/children/ChildHeader.tsx
  frontend/src/citizen-frontend/children/sections/service-need-and-daily-service-time/ServiceNeedTable.tsx
  frontend/src/citizen-frontend/children/sections/vasu-and-leops/vasu/components/StaticInfoSubsection.tsx
  frontend/src/citizen-frontend/children/sections/vasu-and-leops/vasu/sections/CitizenBasicsSection.tsx
  frontend/src/citizen-frontend/children/sections/vasu-and-leops/vasu/sections/CitizenVasuHeader.tsx
  frontend/src/citizen-frontend/decisions/decision-response-page/DecisionResponse.tsx
  frontend/src/citizen-frontend/decisions/decisions-page/AssistanceDecision.tsx
  frontend/src/citizen-frontend/decisions/decisions-page/AssistancePreschoolDecision.tsx
  frontend/src/citizen-frontend/decisions/decisions-page/Decisions.tsx
  frontend/src/citizen-frontend/decisions/decisions-page/FinanceDecision.tsx
  frontend/src/citizen-frontend/income-statements/ChildrenIncomeStatements.tsx
  frontend/src/citizen-frontend/income-statements/IncomeStatementView.tsx
  frontend/src/citizen-frontend/map/MapBox.tsx
  frontend/src/citizen-frontend/map/UnitDetailsPanel.tsx
  frontend/src/citizen-frontend/map/UnitListItem.tsx
  frontend/src/citizen-frontend/messages/MessageEditor.tsx
  frontend/src/citizen-frontend/messages/ThreadListItem.tsx
  frontend/src/citizen-frontend/messages/ThreadView.tsx
  frontend/src/citizen-frontend/navigation/DesktopNav.tsx
  frontend/src/citizen-frontend/navigation/MobileNav.tsx
  frontend/src/citizen-frontend/personal-details/LoginDetailsSection.tsx
  frontend/src/citizen-frontend/personal-details/PersonalDetailsSection.tsx
  frontend/src/lib-components/assistance-need-decision/AssistanceNeedDecisionReadOnly.tsx
  frontend/src/lib-components/assistance-need-decision/AssistanceNeedPreschoolDecisionReadOnly.tsx
  frontend/src/lib-components/atoms/Chip.tsx
  frontend/src/lib-components/atoms/form/Checkbox.tsx
  frontend/src/lib-components/atoms/form/Radio.tsx
Labels: enhancement

#5403 Näytetään työntekijän mobiilin lapsilistassa ikoni myös Huom-muistiinpanosta
  frontend/src/employee-mobile-frontend/child-attendance/ChildListItem.tsx
Labels: enhancement

#5424 Sallitaan varausten luonti lapsille jotka eivät ole voineet vastata lomakyselyyn
  frontend/src/e2e-test/specs/0_citizen/citizen-start-after-holiday-deadline.spec.ts
  service/src/main/kotlin/fi/espoo/evaka/holidayperiod/HolidayPeriod.kt
  service/src/main/kotlin/fi/espoo/evaka/reservations/ReservationControllerCitizen.kt
  service/src/main/kotlin/fi/espoo/evaka/reservations/ReservationQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/reservations/Reservations.kt
Labels: bug

#5417 Siirretään henkilökunnan läsnäolot lasten alapuolelle viikkokalenterissa
  frontend/src/employee-frontend/components/unit/unit-reservations/UnitAttendanceReservationsView.tsx
Labels: enhancement

#5418 Muutetaan "ei ryhmää" oletusvalinnaksi yksikön kalenterissa
  frontend/src/employee-frontend/components/unit/TabCalendar.tsx
Labels: enhancement

#5339 Käytetään kunnallisen tiedotteen otsikkoa sähköpostiherätteen kuvauksessa
  service/src/integrationTest/kotlin/fi/espoo/evaka/messaging/MessageNotificationEmailServiceIntegrationTest.kt
  service/src/main/kotlin/fi/espoo/evaka/emailclient/EvakaEmailMessageProvider.kt
  service/src/main/kotlin/fi/espoo/evaka/emailclient/IEmailMessageProvider.kt
  service/src/main/kotlin/fi/espoo/evaka/messaging/MessageNotificationEmailService.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/async/AsyncJob.kt
Labels: enhancement

#5419 Yhteystietokoosteessa voi valita päivämäärän jolta tiedot haetaan
  frontend/src/employee-frontend/components/reports/FamilyContacts.tsx
  frontend/src/employee-frontend/generated/api-clients/reports.ts
  frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
  service/src/main/kotlin/fi/espoo/evaka/reports/FamilyContactReport.kt
Labels: enhancement
