Repository espoon-voltti/evaka, pull requests merged in 2024-08, with the labels that each got.

#5427 Viitataan hakijaan/aikuiseen eikä huoltajaan työntekijöiden hakemusnäkymässä jotta pätee kaikissa tapauksissa
  frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
Labels: enhancement

#5429 Näytetään testiympäristöissä ympäristön nimi jotta erottuu selkeämmin tuotannosta
  frontend/src/citizen-frontend/App.tsx
  frontend/src/employee-frontend/App.tsx
  frontend/src/employee-mobile-frontend/App.tsx
  frontend/src/lib-components/atoms/EnvironmentLabel.tsx
  frontend/src/lib-customizations/espoo/featureFlags.tsx
  frontend/src/lib-customizations/types.d.ts
Labels: enhancement

#5428 Korjaus henkilökunnan mobiiliviestintään back-napin käyttöön
  frontend/src/employee-mobile-frontend/messages/MessagesPage.tsx
Labels: bug

#5420 Tuen päätöksellä saa valita vain yhden tuen tason
  frontend/src/employee-frontend/components/child-information/assistance-need/decision/AssistanceNeedDecisionEditPage.tsx
  frontend/src/employee-frontend/components/child-information/assistance-need/decision/AssistanceNeededDecisionForm.tsx
  frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
Labels: enhancement

#5439 Update dependabot groupings
  .github/dependabot.yml
Labels: no-changelog

#5423 Piilotetaan laskunäkymästä tili ja laskulaji niiltä kunnilta jossa niitä ei käytetä
  frontend/src/employee-frontend/components/invoice/InvoiceDetailsSection.tsx
  frontend/src/lib-customizations/espoo/featureFlags.tsx
  frontend/src/lib-customizations/types.d.ts
Labels: enhancement

#5425 Näytetään kasvatusvastuullisuus-ikoni mobiilissa
  frontend/src/employee-mobile-frontend/staff-attendance/StaffAttendancesPage.tsx
  frontend/src/employee-mobile-frontend/staff-attendance/StaffListItem.tsx
  frontend/src/lib-common/generated/api-types/attendance.ts
  service/src/main/kotlin/fi/espoo/evaka/attendance/StaffAttendance.kt
  service/src/main/kotlin/fi/espoo/evaka/attendance/StaffAttendanceQueries.kt
Labels: enhancement

#5430 Lisätään mobiilin uusi viesti -notifikaatioon lähettäjän nimi
  service/src/main/kotlin/fi/espoo/evaka/messaging/MessagePushNotifications.kt
Labels: enhancement

#5440 Poistetaan myös PDF samalla jos pääkäyttäjä poistaa julkaistun lomakeluonnoksen
  service/src/main/kotlin/fi/espoo/evaka/document/childdocument/ChildDocumentController.kt
  service/src/main/kotlin/fi/espoo/evaka/document/childdocument/ChildDocumentService.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/async/AsyncJob.kt
Labels: enhancement

#5426 Kuntalaisen poissaolo-modaalin peruuta-nappi palaa sinne mistä tultiin
  frontend/src/citizen-frontend/calendar/AbsenceModal.tsx
  frontend/src/citizen-frontend/calendar/CalendarPage.tsx
Labels: enhancement

#5446 Siivotaan varaukset ja poissaolot kun kuntalainen irtisanoo sijoituksen tai sen liittyvän osuuden
  service/src/integrationTest/kotlin/fi/espoo/evaka/placement/PlacementControllerCitizenIntegrationTest.kt
  service/src/main/kotlin/fi/espoo/evaka/placement/PlacementControllerCitizen.kt
Labels: enhancement

#5447 Espoo: esiopetuksen tuen päätösten TOS-numero
  service/src/main/kotlin/fi/espoo/evaka/EspooConfig.kt
Labels: no-changelog

#5449 Inaktiivisten henkilöiden poistokyselyn optimointi
  service/src/main/kotlin/fi/espoo/evaka/pis/InactivePeopleCleanup.kt
Labels: tech

#5451 Kuntalaisen poissaolomodaalin päättymispäivän maksimiarvolle validaatio käyttöliittymään
  frontend/src/citizen-frontend/calendar/AbsenceModal.tsx
Labels: enhancement

#5450 Automaattikatkaistaan myös päivälasten läsnäolot vuorohoitoyksiköissä
  service/src/main/kotlin/fi/espoo/evaka/shared/job/ScheduledJobs.kt
Labels: enhancement

#5455 Korjaa tuen päätökset -raportin linkin esiopetuksen tuen päätöksille
  service/src/main/kotlin/fi/espoo/evaka/reports/ReportPermissions.kt
Labels: bug

#5453 Päivitetään Keycloak versioon 25.0.2 (Espoo)
  keycloak/Dockerfile
  keycloak/dummy-suomifi/gradle/libs.versions.toml
  keycloak/evaka-logging/pom.xml
  keycloak/evaka-review-profile/pom.xml
  keycloak/evaka-review-profile/src/main/java/com/espoo/keycloak/authenticator/EvakaReviewProfileAuthenticator.java.diff
  keycloak/evaka-review-profile/src/main/java/com/espoo/keycloak/authenticator/EvakaReviewProfileAuthenticatorFactory.java.diff
Labels: tech

#5456 Poistetaan viestien perumiseen liittyvä vanha koodi
  frontend/src/employee-frontend/components/messages/MessageContext.tsx
  frontend/src/employee-frontend/components/messages/UndoMessageNotification.tsx
  frontend/src/employee-frontend/generated/api-clients/messaging.ts
  frontend/src/employee-mobile-frontend/generated/api-clients/messaging.ts
  service/src/integrationTest/kotlin/fi/espoo/evaka/messaging/MessageIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/messaging/MessageNotificationEmailServiceIntegrationTest.kt
  service/src/main/kotlin/fi/espoo/evaka/Audit.kt
  service/src/main/kotlin/fi/espoo/evaka/messaging/MessageController.kt
  service/src/main/kotlin/fi/espoo/evaka/messaging/MessageNotificationEmailService.kt
  service/src/main/kotlin/fi/espoo/evaka/messaging/MessageQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/messaging/MessageService.kt
Labels: tech

#5457 Poistetaan manuaalinen AWS SDK region-konffi
  service/src/integrationTest/resources/application-integration-test.yaml
  service/src/main/kotlin/fi/espoo/evaka/EvakaEnv.kt
  service/src/main/kotlin/fi/espoo/evaka/emailclient/EmailConfig.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/config/AwsConfig.kt
  service/src/main/resources/application-local.yaml
Labels: tech

#5459 Tyyliparannus ympäristöindikaattoriin
  frontend/src/lib-components/atoms/EnvironmentLabel.tsx
Labels: enhancement

#5462 Otetaan vuorohoito huomioon päivittäisten vaka-aikojen poissaolojen luonnissa
  service/src/integrationTest/kotlin/fi/espoo/evaka/dailyservicetimes/DailyServiceTimesIntegrationTest.kt
  service/src/main/kotlin/fi/espoo/evaka/absence/AbsenceService.kt
  service/src/main/kotlin/fi/espoo/evaka/daycare/DaycareQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/placement/PlacementQueries.kt
Labels: bug

#5461 Lisätään metadatan käsittely vasumigraatioon
  frontend/src/employee-frontend/components/vasu/templates/MigrateTemplateModal.tsx
  frontend/src/employee-frontend/components/vasu/templates/VasuTemplatesPage.tsx
  frontend/src/employee-frontend/generated/api-clients/vasu.ts
  frontend/src/lib-common/generated/api-types/vasu.ts
  frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
  service/src/integrationTest/kotlin/fi/espoo/evaka/vasu/DocumentMigratorTest.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/async/AsyncJob.kt
  service/src/main/kotlin/fi/espoo/evaka/vasu/DocumentMigrator.kt
  service/src/main/kotlin/fi/espoo/evaka/vasu/Vasu.kt
  service/src/main/kotlin/fi/espoo/evaka/vasu/VasuQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/vasu/VasuTemplateController.kt
Labels: enhancement

#5467 Korjaus käyttöoikeuksiin
  service/src/main/kotlin/fi/espoo/evaka/assistanceneed/preschooldecision/AssistanceNeedPreschoolDecisionCitizenController.kt
Labels: tech

#5481 Migratoidaan vasuista huoltajien lukukuittaukset
  service/src/main/kotlin/fi/espoo/evaka/vasu/DocumentMigrator.kt
Labels: enhancement

#5460 Datadog seurannan lisäys Keycloak:iin
  .github/dependabot.yml
  compose/docker-compose.yml
  keycloak/.dockerignore
  keycloak/Dockerfile
  keycloak/dd-fetch/pom.xml
Labels: tech

#5431 Siirretään viestiketjut ja uusi viesti omiin routeihin
  frontend/src/employee-mobile-frontend/App.tsx
  frontend/src/employee-mobile-frontend/child-attendance/AttendancePageWrapper.tsx
  frontend/src/employee-mobile-frontend/child-attendance/ChildList.tsx
  frontend/src/employee-mobile-frontend/child-attendance/ChildListItem.tsx
  frontend/src/employee-mobile-frontend/common/BottomNavbar.tsx
  frontend/src/employee-mobile-frontend/common/unit-or-group.ts
  frontend/src/employee-mobile-frontend/messages/DraftMessagesList.tsx
  frontend/src/employee-mobile-frontend/messages/MessageEditor.tsx
  frontend/src/employee-mobile-frontend/messages/MessagesPage.tsx
  frontend/src/employee-mobile-frontend/messages/NewChildMessagePage.tsx
  frontend/src/employee-mobile-frontend/messages/NewMessagePage.tsx
  frontend/src/employee-mobile-frontend/messages/ReceivedThreadsList.tsx
  frontend/src/employee-mobile-frontend/messages/SentMessagesList.tsx
  frontend/src/employee-mobile-frontend/messages/ThreadView.tsx
  frontend/src/employee-mobile-frontend/messages/UnreadMessagesPage.tsx
  frontend/src/employee-mobile-frontend/messages/state.tsx
  frontend/src/employee-mobile-frontend/pairing/MobileLander.tsx
  frontend/src/employee-mobile-frontend/settings/SettingsPage.tsx
  frontend/src/employee-mobile-frontend/staff-attendance/StaffAttendancesPage.tsx
  frontend/src/employee-mobile-frontend/staff/StaffPage.tsx
  frontend/src/employee-mobile-frontend/units/UnitList.tsx
  frontend/src/lib-common/query.ts
Labels: enhancement

#5484 Varaudutaan rikkinäisiin henkilöviitteisiin vasu-migraatiossa
  frontend/src/lib-common/generated/api-types/vasu.ts
  service/src/main/kotlin/fi/espoo/evaka/vasu/DocumentMigrator.kt
  service/src/main/kotlin/fi/espoo/evaka/vasu/Vasu.kt
Labels: bug

#5490 Näytetään onnistuneesti migratoitujen dokumenttien määrät
  frontend/src/employee-frontend/components/vasu/templates/VasuTemplatesPage.tsx
  frontend/src/lib-common/generated/api-types/vasu.ts
  frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
  service/src/integrationTest/kotlin/fi/espoo/evaka/vasu/VasuTemplateTest.kt
  service/src/main/kotlin/fi/espoo/evaka/vasu/VasuTemplate.kt
  service/src/main/kotlin/fi/espoo/evaka/vasu/VasuTemplateQueries.kt
Labels: enhancement

#5491 Tuetaan puutteellisia vastauksia sisältävää vanhaa dataa vasumigraatiossa
  service/src/main/kotlin/fi/espoo/evaka/vasu/DocumentMigrator.kt
Labels: enhancement

#5479 Korjataan koko päivän poissaolon näyttäminen kuntalaiselle
  frontend/src/citizen-frontend/calendar/DayView.tsx
  frontend/src/citizen-frontend/calendar/calendar-elements.tsx
  frontend/src/e2e-test/pages/citizen/citizen-calendar.ts
  frontend/src/e2e-test/specs/0_citizen/citizen-reservations.spec.ts
  frontend/src/e2e-test/specs/0_citizen/citizen-start-after-holiday-deadline.spec.ts
  frontend/src/e2e-test/specs/0_citizen/feature-flag-citizen-reservations-intermittent-shif-care.spec.ts
  service/src/main/kotlin/fi/espoo/evaka/reservations/ReservationControllerCitizen.kt
Labels: bug

#5492 Tulotiedon editoiminen avaa tulotiedon näkyviin
  frontend/src/employee-frontend/components/person-profile/income/IncomeItemHeader.tsx
Labels: bug

#5463 Kielletään nullable API response-sisällöt koska Spring toimii oudosti niiden kanssa
  apigw/src/shared/service-client.ts
  frontend/src/employee-frontend/components/ApplicationPage.tsx
  frontend/src/employee-frontend/components/messages/MessagesPage.tsx
  frontend/src/employee-frontend/components/unit/unit-reservations/ChildDateModal.tsx
  frontend/src/employee-frontend/generated/api-clients/assistance.ts
  frontend/src/employee-frontend/generated/api-clients/attendance.ts
  frontend/src/employee-frontend/generated/api-clients/messaging.ts
  frontend/src/employee-frontend/generated/api-clients/reservations.ts
  frontend/src/employee-mobile-frontend/child-attendance/actions/MarkDeparted.tsx
  frontend/src/employee-mobile-frontend/generated/api-clients/attendance.ts
  frontend/src/employee-mobile-frontend/generated/api-clients/messaging.ts
  frontend/src/lib-common/generated/api-types/attendance.ts
  frontend/src/lib-common/generated/api-types/messaging.ts
  frontend/src/lib-common/generated/api-types/reservations.ts
  service/codegen/src/main/kotlin/evaka/codegen/api/Controllers.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/attendance/AttendanceTransitionsIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/dvv/MockDvvModificationsService.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/messaging/MessageIntegrationTest.kt
  service/src/main/kotlin/fi/espoo/evaka/assistance/AssistanceController.kt
  service/src/main/kotlin/fi/espoo/evaka/attendance/ChildAttendanceController.kt
  service/src/main/kotlin/fi/espoo/evaka/messaging/MessageController.kt
  service/src/main/kotlin/fi/espoo/evaka/pis/SystemController.kt
  service/src/main/kotlin/fi/espoo/evaka/reservations/AttendanceReservationController.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/config/SpringMvcConfig.kt
  service/src/main/kotlin/fi/espoo/evaka/varda/integration/MockVardaIntegrationEndpoint.kt
Labels: tech

#5347 Käytetään Keycloakin Hostname v2 -konfiguraatiota paikallisessa ympäristössä
  compose/docker-compose.yml
  keycloak/docker-compose.yml
Labels: tech

#5494 Propagoidaan tracing-konteksti proxyltä keycloakille
  frontend/proxy/files/etc/nginx/keycloak-proxy.conf.template
Labels: tech

#5493 Keskusteluaikavarausten kuntalaisen ruotsinnokset
  frontend/src/lib-customizations/defaults/citizen/i18n/sv.tsx
  service/src/main/kotlin/fi/espoo/evaka/emailclient/EvakaEmailMessageProvider.kt
Labels: enhancement

#5497 Mobiilissa Tänään ja Seuraavat päivät näkyy yhtä aikaa aktiivisina
  frontend/src/employee-mobile-frontend/App.tsx
  frontend/src/employee-mobile-frontend/child-attendance/AttendancePageWrapper.tsx
Labels: bug

#5498 E2E-testiajon korjaus
  .github/workflows/build.yml
  frontend/src/e2e-test/browser.ts
  frontend/src/e2e-test/generated/api-clients.ts
  frontend/src/e2e-test/pages/employee/units/unit-calendar-page-base.ts
  frontend/src/e2e-test/pages/employee/units/unit-week-calendar-page.ts
  frontend/src/e2e-test/pages/employee/units/unit.ts
  frontend/src/e2e-test/pages/mobile/unread-message-counts.ts
  frontend/src/e2e-test/specs/5_employee/realtime-attendances.spec.ts
  frontend/src/e2e-test/specs/5_employee/reservation-calendar-child-date-modal.spec.ts
  frontend/src/e2e-test/specs/5_employee/reservation-calendar.spec.ts
  frontend/src/e2e-test/specs/5_employee/unit-calendar-events.spec.ts
  frontend/src/e2e-test/specs/5_employee/units.spec.ts
  frontend/src/e2e-test/specs/6_mobile/child-attendances.spec.ts
  frontend/src/e2e-test/specs/6_mobile/messages.spec.ts
  frontend/src/e2e-test/specs/6_mobile/notification-settings.spec.ts
  frontend/src/e2e-test/specs/6_mobile/pin-login.spec.ts
  frontend/src/e2e-test/specs/6_mobile/realtime-staff-attendances.spec.ts
  frontend/src/e2e-test/specs/6_mobile/reservations.spec.ts
  service/src/integrationTest/kotlin/fi/espoo/evaka/placement/PlacementControllerCitizenIntegrationTest.kt
  service/src/main/kotlin/fi/espoo/evaka/placement/PlacementControllerCitizen.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/dev/DevApi.kt
Labels: tech

#5452 Lisää hakemuksen testejä kun palveluntarpeet ovat käytössä
  frontend/src/citizen-frontend/applications/editor/service-need/ServiceTimeSubSectionPreschool.tsx
  frontend/src/e2e-test/pages/citizen/citizen-applications.ts
  frontend/src/e2e-test/specs/0_citizen/citizen-application-service-need-option.spec.ts
  frontend/src/e2e-test/utils/application-forms.ts
Labels: tech

#5464 Ei poisteta varauksia kun päivittäinen varhaiskasvatusaika muuttuu
  frontend/src/citizen-frontend/calendar/DailyServiceTimeNotifications.tsx
  frontend/src/citizen-frontend/generated/api-clients/dailyservicetimes.ts
  frontend/src/e2e-test/dev-api/fixtures.ts
  frontend/src/e2e-test/generated/api-types.ts
  frontend/src/e2e-test/specs/0_citizen/citizen-daily-service-times.spec.ts
  frontend/src/employee-frontend/components/child-information/DailyServiceTimesSection.tsx
  frontend/src/employee-frontend/components/child-information/daily-service-times/DailyServiceTimesForms.tsx
  frontend/src/lib-common/generated/api-types/dailyservicetimes.ts
  frontend/src/lib-customizations/defaults/citizen/i18n/en.tsx
  frontend/src/lib-customizations/defaults/citizen/i18n/fi.tsx
  frontend/src/lib-customizations/defaults/citizen/i18n/sv.tsx
  frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
  service/src/integrationTest/kotlin/fi/espoo/evaka/absence/AbsenceGenerationIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/dailyservicetimes/DailyServiceTimesIntegrationTest.kt
  service/src/main/kotlin/fi/espoo/evaka/absence/AbsenceQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/absence/AbsenceService.kt
  service/src/main/kotlin/fi/espoo/evaka/attendance/ChildAttendanceQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/dailyservicetimes/DailyServiceTimes.kt
  service/src/main/kotlin/fi/espoo/evaka/dailyservicetimes/DailyServiceTimesCitizenController.kt
  service/src/main/kotlin/fi/espoo/evaka/dailyservicetimes/DailyServiceTimesController.kt
  service/src/main/kotlin/fi/espoo/evaka/reservations/ReservationQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/dev/DevApi.kt
  service/src/main/resources/db/migration/V427__less_columns_in_daily_service_time_notifications.sql
  service/src/main/resources/migrations.txt
Labels: enhancement

#5496 Päivitetään deprekoidut env-nimet compose e2e:ssä
  compose/docker-compose.e2e.yml
Labels: tech

#5483 Korjataan laskugeneroinnin suorituskyky, ja parannellaan koodia
  service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/data/InvoiceQueriesTest.kt
  service/src/main/kotlin/fi/espoo/evaka/invoicing/domain/FeeDecisions.kt
  service/src/main/kotlin/fi/espoo/evaka/invoicing/service/DraftInvoiceGenerator.kt
  service/src/main/kotlin/fi/espoo/evaka/invoicing/service/FeeDecisionService.kt
  service/src/main/kotlin/fi/espoo/evaka/invoicing/service/InvoiceGenerator.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/Tracing.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/data/DateSet.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/data/RangeBasedSet.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/utils/Kotlin.kt
Labels: tech

#5504 Estä ylimääräisten keskusteluaikojen näyttäminen varausmodaalissa
  frontend/src/citizen-frontend/calendar/discussion-reservation-modal/DiscussionReservationModal.tsx
Labels: bug

#5509 Päivitetään spring-framework-bom, korjaa CVE-hälytyksen
  service/evaka-bom/build.gradle.kts
Labels: dependencies

#5507 Discover all integration tests in CI
  bin/split-integration-tests.sh
  service/src/integrationTest/kotlin/fi/espoo/evaka/reports/ReportSmokeTests.kt
Labels: no-changelog

#5508 Lokitetaan User-Agent proxyssä
  frontend/proxy/files/etc/nginx/conf.d/nginx.conf.template
Labels: tech

#5514 Poistetaan lapsen sivulta Lapseen liittyvä viestintä -osio
  frontend/src/e2e-test/pages/employee/child-information.ts
  frontend/src/e2e-test/specs/6_mobile/messages.spec.ts
  frontend/src/e2e-test/specs/7_messaging/messaging.spec.ts
  frontend/src/e2e-test/specs/8_access/access.spec.ts
  frontend/src/employee-frontend/components/ChildInformation.tsx
  frontend/src/employee-frontend/components/child-information/MessageBlocklist.tsx
  frontend/src/employee-frontend/generated/api-clients/messaging.ts
  frontend/src/employee-mobile-frontend/generated/api-clients/messaging.ts
  frontend/src/lib-common/generated/action.d.ts
  frontend/src/lib-common/generated/api-types/messaging.ts
  frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
  service/src/integrationTest/kotlin/fi/espoo/evaka/messaging/MessageQueriesTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/pis/PersonIntegrationTest.kt
  service/src/main/kotlin/fi/espoo/evaka/Audit.kt
  service/src/main/kotlin/fi/espoo/evaka/messaging/ChildRecipientQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/messaging/ChildRecipientsController.kt
  service/src/main/kotlin/fi/espoo/evaka/messaging/MessageQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/pedagogicaldocument/PedagogicalDocumentNotificationService.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/security/AccessControlCitizen.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/security/Action.kt
  service/src/main/resources/db/migration/V428__remove_messaging_blocklist.sql
  service/src/main/resources/migrations.txt
Labels: breaking

#5510 Näytetään henkilökunnan mobiilista luodut varaukset henkilökunnan luomina
  service/src/main/kotlin/fi/espoo/evaka/reservations/AttendanceReservationController.kt
  service/src/main/kotlin/fi/espoo/evaka/reservations/ReservationQueries.kt
Labels: bug

#5511 Sallitaan varausten muokkaus henkilökunnan mobiilista myös loma-ajalla
  service/src/main/kotlin/fi/espoo/evaka/reservations/AttendanceReservationController.kt
  service/src/main/kotlin/fi/espoo/evaka/reservations/ReservationQueries.kt
Labels: bug

#5344 Tulotietojen päättymispäivä pakolliseksi jos muu kuin suostumus korkeimpaan
  frontend/src/citizen-frontend/income-statements/ChildIncomeStatementEditor.tsx
  frontend/src/citizen-frontend/income-statements/ChildIncomeStatementForm.tsx
  frontend/src/citizen-frontend/income-statements/IncomeStatementForm.tsx
  frontend/src/citizen-frontend/income-statements/types/body.ts
  frontend/src/citizen-frontend/income-statements/types/form.ts
  frontend/src/e2e-test/pages/citizen/citizen-income.ts
  frontend/src/e2e-test/specs/0_citizen/citizen-income-statement.spec.ts
  service/src/integrationTest/kotlin/fi/espoo/evaka/incomestatement/IncomeStatementControllerCitizenIntegrationTest.kt
  service/src/main/kotlin/fi/espoo/evaka/incomestatement/IncomeStatement.kt
Labels: enhancement

#5512 Tuki keskustelukyselyjen tietojen näyttämiselle kasvattajan kalenterissa
  frontend/src/e2e-test/pages/employee/units/unit.ts
  frontend/src/e2e-test/specs/5_employee/unit-calendar-events.spec.ts
  frontend/src/employee-frontend/components/unit/tab-calendar/CalendarEventsSection.tsx
  frontend/src/employee-frontend/components/unit/tab-calendar/discussion-surveys/DiscussionSurveyView.tsx
  frontend/src/employee-frontend/components/unit/tab-calendar/discussion-surveys/survey-editor/DiscussionSurveyForm.tsx
  frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
Labels: bug

#5513 Käyttö/täyttöastekyselyn tekninen parannus
  service/src/main/kotlin/fi/espoo/evaka/occupancy/Occupancy.kt
Labels: tech

#5522 Korjauksia esiopetuksen poissaoloraporttiin
  frontend/src/e2e-test/specs/5_employee/preschool-absence-report.spec.ts
  service/src/integrationTest/kotlin/fi/espoo/evaka/reports/PreschoolAbsenceReportTest.kt
  service/src/main/kotlin/fi/espoo/evaka/reports/PreschoolAbsenceReport.kt
Labels: bug

#5523 Ilmaisen heinäkuun saa jos aloitus oli elokuussa + ilmaisuuden sääntö konfiguroitavaksi
  service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/service/InvoiceCorrectionsIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/service/InvoiceGeneratorIntegrationTest.kt
  service/src/main/kotlin/fi/espoo/evaka/EspooConfig.kt
  service/src/main/kotlin/fi/espoo/evaka/invoicing/service/InvoiceGenerator.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/FeatureConfig.kt
Labels: enhancement

#5521 Kuntalaisen kalenterin päivämodaalin saavutettavuusparannuksia
  frontend/src/citizen-frontend/calendar/CalendarGridView.tsx
  frontend/src/citizen-frontend/calendar/DayView.tsx
Labels: enhancement

#5525 Saavutettavuusparannus kuntalaisen poissaolodialogin validointivirheeseen
  frontend/src/citizen-frontend/calendar/AbsenceModal.tsx
Labels: enhancement

#5503 Varausten ja poissaolojen siivous sijoitusten muuttuessa
  service/src/integrationTest/kotlin/fi/espoo/evaka/placement/PlacementControllerCitizenIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/placement/PlacementQueriesIntegrationTest.kt
  service/src/main/kotlin/fi/espoo/evaka/absence/AbsenceQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/absence/AbsenceService.kt
  service/src/main/kotlin/fi/espoo/evaka/placement/PlacementController.kt
  service/src/main/kotlin/fi/espoo/evaka/placement/PlacementControllerCitizen.kt
  service/src/main/kotlin/fi/espoo/evaka/placement/PlacementPlanService.kt
  service/src/main/kotlin/fi/espoo/evaka/placement/PlacementQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/placement/PlacementType.kt
Labels: enhancement

#5505 Korjaus käytetyn tuntimäärän keskiarvolaskentaan ilmaisten läsnäolojen tapauksessa
  service/src/integrationTest/kotlin/fi/espoo/evaka/reports/ExceededServiceNeedsReportTest.kt
  service/src/main/kotlin/fi/espoo/evaka/absence/AbsenceService.kt
  service/src/main/kotlin/fi/espoo/evaka/reports/ExceededServiceNeedsReport.kt
  service/src/main/kotlin/fi/espoo/evaka/reservations/ReservationControllerCitizen.kt
  service/src/main/kotlin/fi/espoo/evaka/reservations/Reservations.kt
  service/src/test/kotlin/fi/espoo/evaka/reservations/UsedServiceTests.kt
Labels: enhancement

#5534 Yksikön päättymispäivä on inklusiivinen eli viimeinen päivä kun on yhä toiminnassa
  service/src/main/kotlin/fi/espoo/evaka/daycare/DaycareQueries.kt
Labels: bug

#5530 Korjauksia esiopetuksen poissaoloraporttiin
  service/src/integrationTest/kotlin/fi/espoo/evaka/reports/PreschoolAbsenceReportTest.kt
  service/src/main/kotlin/fi/espoo/evaka/reports/PreschoolAbsenceReport.kt
Labels: bug

#5531 Sallitaan varaukset lapsille, joiden sijoitus on ollut katkolla kesken loma-ajan
  service/src/main/kotlin/fi/espoo/evaka/holidayperiod/HolidayPeriod.kt
  service/src/main/kotlin/fi/espoo/evaka/reservations/ReservationQueries.kt
  service/src/test/kotlin/fi/espoo/evaka/holidayperiod/HolidayPeriodTest.kt
Labels: enhancement

#5529 Lisätään uusi suomi.fi testipuolen IDP-sertifikaatti
  apigw/config/certificates/saml-signing-testi.apro.tunnistus.fi.2024.pem
  apigw/src/shared/certificates.ts
Labels: tech

#5539 Korjataan sähköpostien esikatselu
  service/src/main/kotlin/fi/espoo/evaka/shared/dev/DevApi.kt
Labels: tech

#5535 Varoitetaan kuntalaista jos on merkitsemässä poissaoloa suljetun lomakyselyn ajalle
  frontend/src/citizen-frontend/calendar/AbsenceModal.tsx
  frontend/src/citizen-frontend/calendar/CalendarPage.tsx
  frontend/src/citizen-frontend/calendar/DayView.tsx
  frontend/src/citizen-frontend/calendar/ReservationModal.tsx
  frontend/src/lib-customizations/defaults/citizen/i18n/en.tsx
  frontend/src/lib-customizations/defaults/citizen/i18n/fi.tsx
  frontend/src/lib-customizations/defaults/citizen/i18n/sv.tsx
Labels: enhancement

#5537 Poistetaan deaktiivisen työntekijän oikeudet 8 viikon jälkeen
  service/src/integrationTest/kotlin/fi/espoo/evaka/pis/InactiveEmployeesRoleResetIntegrationTest.kt
  service/src/main/kotlin/fi/espoo/evaka/pis/EmployeeQueries.kt
Labels: enhancement

#5543 Lisätään `NOT NULL` constraint `placement`-taulun `created` ja `updated` -sarakkeille
  service/src/main/resources/db/migration/V429__placement_created_updated_not_null.sql
  service/src/main/resources/migrations.txt
Labels: tech

#5540 Käytetään `jsonb_build_object` aina `json_build_object` sijaan
  service/src/main/kotlin/fi/espoo/evaka/calendarevent/CalendarEventQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/incomestatement/IncomeStatementQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/invoicing/data/FeeAlterationQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/invoicing/data/FeeDecisionQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/invoicing/data/IncomeQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/messaging/DraftQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/pedagogicaldocument/PedagogicalDocumentQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/reports/DuplicatePeopleReport.kt
  service/src/main/kotlin/fi/espoo/evaka/reservations/AttendanceReservationController.kt
  service/src/main/kotlin/fi/espoo/evaka/reservations/ReservationQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/vasu/VasuQueries.kt
Labels: tech

#5526 Yksinkertaistetaan kuntalaisen Keycloakin "idp review profile"-vaihetta
  frontend/src/e2e-test/pages/citizen/citizen-keycloak.ts
  frontend/src/e2e-test/specs/0_citizen/citizen-keycloak.spec.ts
  keycloak/Dockerfile
  keycloak/README.md
  keycloak/compose-resources/configuration/entrypoint.sh
  keycloak/compose-resources/configuration/evaka.json
  keycloak/evaka-review-profile/pom.xml
  keycloak/evaka-review-profile/src/main/java/com/espoo/keycloak/authenticator/EvakaReviewProfileAuthenticator.java
  keycloak/evaka-review-profile/src/main/java/com/espoo/keycloak/authenticator/EvakaReviewProfileAuthenticator.java.diff
  keycloak/evaka-review-profile/src/main/java/com/espoo/keycloak/authenticator/EvakaReviewProfileAuthenticatorFactory.java
  keycloak/evaka-review-profile/src/main/java/com/espoo/keycloak/authenticator/EvakaReviewProfileAuthenticatorFactory.java.diff
  keycloak/evaka-review-profile/src/main/java/com/espoo/keycloak/authenticator/diffs.sh
  keycloak/evaka-review-profile/src/main/resources/META-INF/services/org.keycloak.authentication.AuthenticatorFactory
  keycloak/theme/evaka/login/idp-review-user-profile.ftl
  keycloak/theme/evaka/login/messages/messages_en.properties
  keycloak/theme/evaka/login/messages/messages_fi.properties
  keycloak/theme/evaka/login/messages/messages_sv.properties
  keycloak/update.sh
Labels: tech

#5536 Parannuksia tulotietojen aikavälin valintaan
  frontend/src/e2e-test/specs/5_employee/income.spec.ts
  frontend/src/employee-frontend/components/person-profile/income/IncomeItemEditor.tsx
Labels: enhancement

#5541 Päivän käyttöastegraafin parannuksia
  frontend/src/employee-frontend/components/unit/TabCalendar.tsx
  frontend/src/employee-frontend/components/unit/queries.ts
  frontend/src/employee-frontend/components/unit/tab-unit-information/Occupancy.tsx
  frontend/src/employee-frontend/components/unit/tab-unit-information/occupancy/ChartTooltip.tsx
  frontend/src/employee-frontend/components/unit/tab-unit-information/occupancy/OccupanciesForDateRange.tsx
  frontend/src/employee-frontend/components/unit/tab-unit-information/occupancy/OccupanciesForSingleDay.tsx
  frontend/src/employee-frontend/components/unit/tab-unit-information/occupancy/OccupancyDayGraph.tsx
  frontend/src/employee-frontend/components/unit/tab-unit-information/occupancy/OccupancySingleDay.tsx
  frontend/src/employee-frontend/generated/api-clients/occupancy.ts
  frontend/src/lib-common/generated/api-types/occupancy.ts
  frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
  service/src/integrationTest/kotlin/fi/espoo/evaka/occupancy/OccupancyControllerIntegrationTest.kt
  service/src/main/kotlin/fi/espoo/evaka/occupancy/Occupancy.kt
  service/src/main/kotlin/fi/espoo/evaka/occupancy/OccupancyController.kt
  service/src/main/kotlin/fi/espoo/evaka/occupancy/RealtimeOccupancy.kt
Labels: enhancement

#5524 Kuntalainen voi lisätä uuteen viestiin liitteen jos lapsi on vuorohoidossa
  frontend/src/citizen-frontend/attachments.ts
  frontend/src/citizen-frontend/generated/api-clients/messaging.ts
  frontend/src/citizen-frontend/messages/MessageEditor.tsx
  frontend/src/citizen-frontend/messages/MessagesPage.tsx
  frontend/src/citizen-frontend/messages/state.tsx
  frontend/src/e2e-test/pages/citizen/citizen-messages.ts
  frontend/src/e2e-test/pages/employee/messages/messages-page.ts
  frontend/src/e2e-test/specs/6_mobile/messages.spec.ts
  frontend/src/e2e-test/specs/7_messaging/messaging.spec.ts
  frontend/src/employee-frontend/components/messages/MessageEditor.tsx
  frontend/src/lib-common/generated/api-types/messaging.ts
  frontend/src/lib-components/molecules/FileUpload.tsx
  frontend/src/lib-customizations/defaults/citizen/i18n/en.tsx
  frontend/src/lib-customizations/defaults/citizen/i18n/fi.tsx
  frontend/src/lib-customizations/defaults/citizen/i18n/sv.tsx
  service/src/integrationTest/kotlin/fi/espoo/evaka/messaging/MessageIntegrationTest.kt
  service/src/main/kotlin/fi/espoo/evaka/Audit.kt
  service/src/main/kotlin/fi/espoo/evaka/attachment/AttachmentsController.kt
  service/src/main/kotlin/fi/espoo/evaka/messaging/MessageControllerCitizen.kt
  service/src/main/kotlin/fi/espoo/evaka/messaging/MessageQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/messaging/MessageService.kt
Labels: enhancement

#5563 Lisää lomakepohjien ohjeteksteihin monirivituen
  frontend/src/employee-frontend/components/document-templates/template-editor/TemplateSectionModal.tsx
  frontend/src/lib-components/document-templates/question-descriptors/CheckboxGroupQuestionDescriptor.tsx
  frontend/src/lib-components/document-templates/question-descriptors/CheckboxQuestionDescriptor.tsx
  frontend/src/lib-components/document-templates/question-descriptors/DateQuestionDescriptor.tsx
  frontend/src/lib-components/document-templates/question-descriptors/GroupedTextFieldsQuestionDescriptor.tsx
  frontend/src/lib-components/document-templates/question-descriptors/RadioButtonGroupQuestionDescriptor.tsx
  frontend/src/lib-components/document-templates/question-descriptors/StaticTextDisplayQuestionDescriptor.tsx
  frontend/src/lib-components/document-templates/question-descriptors/TextQuestionDescriptor.tsx
Labels: enhancement

#5538 Lähetä huoltajalle sähköpostiviestit uudesta keskustelukyselystä ja lähestyvästä keskusteluaikavarauksesta
  frontend/src/citizen-frontend/personal-details/NotificationSettingsSection.tsx
  frontend/src/e2e-test/generated/api-types.ts
  frontend/src/e2e-test/pages/citizen/citizen-personal-details.ts
  frontend/src/e2e-test/specs/0_citizen/citizen-personal-details.spec.ts
  frontend/src/lib-common/generated/api-types/pis.ts
  frontend/src/lib-customizations/defaults/citizen/i18n/en.tsx
  frontend/src/lib-customizations/defaults/citizen/i18n/fi.tsx
  frontend/src/lib-customizations/defaults/citizen/i18n/sv.tsx
  service/src/integrationTest/kotlin/fi/espoo/evaka/calendarevent/CalendarEventServiceIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/pis/controller/PersonalDataControllerCitizenIntegrationTest.kt
  service/src/main/kotlin/fi/espoo/evaka/calendarevent/CalendarEventController.kt
  service/src/main/kotlin/fi/espoo/evaka/calendarevent/CalendarEventNotificationService.kt
  service/src/main/kotlin/fi/espoo/evaka/calendarevent/CalendarEventQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/emailclient/EvakaEmailMessageProvider.kt
  service/src/main/kotlin/fi/espoo/evaka/emailclient/IEmailMessageProvider.kt
  service/src/main/kotlin/fi/espoo/evaka/pis/PersonalData.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/async/AsyncJob.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/dev/DevApi.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/job/ScheduledJobs.kt
Labels: breaking

#5567 Korjataan päivämääräriippuvainen integraatiotesti
  service/src/integrationTest/kotlin/fi/espoo/evaka/placement/PlacementControllerCitizenIntegrationTest.kt
Labels: no-changelog

#5566 Bump com.ncorti.ktfmt.gradle from 0.20.0 to 0.20.1 in /service
  service/build.gradle.kts
  service/codegen/build.gradle.kts
  service/custom-ktlint-rules/build.gradle.kts
  service/gradle/libs.versions.toml
Labels: dependencies, java

#5561 Piilotetaan muutama sensitiivinen tieto lokitukselta virhetilanteissa
  service/src/main/kotlin/fi/espoo/evaka/assistanceneed/decision/AssistanceNeedDecision.kt
  service/src/main/kotlin/fi/espoo/evaka/assistanceneed/preschooldecision/AssistanceNeedPreschoolDecision.kt
  service/src/main/kotlin/fi/espoo/evaka/document/childdocument/ChildDocument.kt
Labels: tech

#5545 Poistetaan vain Espoon käytössä olleet SAML-sertifikaatit
  apigw/config/certificates/espooad-internal-prod.2022.pem
  apigw/config/certificates/espooad-internal-staging.2022.pem
  apigw/config/certificates/idp.staging.espoon-voltti.fi.pem
  apigw/config/certificates/idp.test.espoon-voltti.fi.pem
  apigw/src/shared/certificates.ts
Labels: tech

#5568 Lomakauden aikaväliä ei voi muokata jälkeenpäin
  frontend/src/e2e-test/generated/api-clients.ts
  frontend/src/e2e-test/pages/employee/holiday-term-periods.ts
  frontend/src/e2e-test/specs/5_employee/holiday-term-period.spec.ts
  frontend/src/employee-frontend/components/holiday-term-periods/HolidayAndTermPeriodsPage.tsx
  frontend/src/employee-frontend/components/holiday-term-periods/HolidayPeriodForm.tsx
  frontend/src/employee-frontend/generated/api-clients/holidayperiod.ts
  frontend/src/lib-common/generated/api-types/holidayperiod.ts
  service/src/integrationTest/kotlin/fi/espoo/evaka/holidayperiod/HolidayPeriodControllerIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/holidayperiod/HolidayPeriodIntegrationTest.kt
  service/src/main/kotlin/fi/espoo/evaka/holidayperiod/HolidayPeriod.kt
  service/src/main/kotlin/fi/espoo/evaka/holidayperiod/HolidayPeriodController.kt
  service/src/main/kotlin/fi/espoo/evaka/holidayperiod/HolidayPeriodQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/dev/DevApi.kt
Labels: enhancement

#5571 Järjestetään loma-ajat uusimmasta vanhimpaan
  frontend/src/e2e-test/specs/5_employee/holiday-term-period.spec.ts
  frontend/src/employee-frontend/components/holiday-term-periods/HolidayAndTermPeriodsPage.tsx
Labels: enhancement

#5562 Ei lähetetä sähköpostia kalenteritapahtumista jos sijoitus on päättynyt
  service/src/integrationTest/kotlin/fi/espoo/evaka/calendarevent/CalendarEventNotificationQueriesTest.kt
  service/src/main/kotlin/fi/espoo/evaka/calendarevent/CalendarEventNotificationService.kt
  service/src/main/kotlin/fi/espoo/evaka/calendarevent/CalendarEventQueries.kt
Labels: bug

#5573 Korjataan turhat varoitukset päiväkirjamodaalissa
  frontend/src/employee-frontend/components/unit/unit-reservations/ChildDateModal.tsx
Labels: bug

#5495 Korvataan opentracing opentelemetryllä evaka-servicessä
  service/build.gradle.kts
  service/entrypoint.sh
  service/evaka-bom/build.gradle.kts
  service/gradle/libs.versions.toml
  service/src/integrationTest/kotlin/fi/espoo/evaka/FullApplicationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/PureJdbiTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/children/ChildControllerCitizenTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/dailyservicetimes/DailyServiceTimesIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/daycare/controllers/ChildrenControllerIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/reservations/CreateReservationsAndAbsencesTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/reservations/ReservationControllerCitizenIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/shared/config/SharedIntegrationTestConfig.kt
  service/src/main/kotlin/fi/espoo/evaka/EspooConfig.kt
  service/src/main/kotlin/fi/espoo/evaka/invoicing/service/DraftInvoiceGenerator.kt
  service/src/main/kotlin/fi/espoo/evaka/invoicing/service/InvoiceGenerator.kt
  service/src/main/kotlin/fi/espoo/evaka/pdfgen/PdfGenerator.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/Tracing.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/async/AsyncJobPool.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/async/AsyncJobRunner.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/auth/RequestToAuthenticatedUser.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/config/ActuatorConfig.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/config/AsyncJobConfig.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/config/HttpFilterConfig.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/config/ScheduledJobConfig.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/config/SecurityConfig.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/config/SpringMvcConfig.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/config/TracingConfig.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/db/Database.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/db/DevDataInitializer.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/job/ScheduledJobRunner.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/security/AccessControl.kt
Labels: tech

#5575 Suorituskykykorjauksia
  service/src/integrationTest/kotlin/fi/espoo/evaka/daycare/dao/CaretakerQueriesIntegrationTest.kt
  service/src/main/kotlin/fi/espoo/evaka/attendance/ChildAttendanceQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/daycare/CaretakerQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/daycare/controllers/DaycareController.kt
  service/src/main/kotlin/fi/espoo/evaka/daycare/service/DaycareService.kt
  service/src/main/kotlin/fi/espoo/evaka/occupancy/Occupancy.kt
  service/src/main/kotlin/fi/espoo/evaka/occupancy/OccupancyController.kt
  service/src/main/kotlin/fi/espoo/evaka/occupancy/RealtimeOccupancy.kt
  service/src/main/resources/db/migration/V430__child_attendance_timestamps.sql
  service/src/main/resources/db/migration/V431__child_attendance_range_index.sql
  service/src/main/resources/migrations.txt
Labels: tech

#5577 Korjaus OpenTelemetryn spanien käyttöön
  service/src/main/kotlin/fi/espoo/evaka/shared/Tracing.kt
Labels: tech

#5580 Päivitetään Suomi.fi REST AccessTokenResponse uuden speksin mukaiseksi
  service/src/integrationTest/kotlin/fi/espoo/evaka/sficlient/rest/MockSfiMessagesRestEndpoint.kt
  service/src/main/kotlin/fi/espoo/evaka/sficlient/rest/RestSchema.kt
  service/src/main/kotlin/fi/espoo/evaka/sficlient/rest/SfiMessagesRestClient.kt
Labels: tech

#5576 Korjaus lapsen kuvan lisäykseen
  frontend/package.json
  frontend/src/employee-mobile-frontend/child-info/ImageEditor.tsx
  frontend/yarn.lock
Labels: bug

#5569 Korjauksia sähköpostien lähetykseen
  service/src/integrationTest/kotlin/fi/espoo/evaka/calendarevent/CalendarEventNotificationQueriesTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/calendarevent/CalendarEventServiceIntegrationTest.kt
  service/src/main/kotlin/fi/espoo/evaka/assistanceneed/decision/AssistanceNeedDecisionService.kt
  service/src/main/kotlin/fi/espoo/evaka/assistanceneed/preschooldecision/AssistanceNeedPreschoolDecisionService.kt
  service/src/main/kotlin/fi/espoo/evaka/calendarevent/CalendarEventNotificationService.kt
  service/src/main/kotlin/fi/espoo/evaka/calendarevent/CalendarEventQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/invoicing/service/FeeDecisionService.kt
  service/src/main/kotlin/fi/espoo/evaka/invoicing/service/VoucherValueDecisionService.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/async/AsyncJob.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/job/ScheduledJobs.kt
Labels: tech

#5582 Korjaus uuden keskustelukyselyn huoltajakutsujen kohdentamiseen
  service/src/integrationTest/kotlin/fi/espoo/evaka/calendarevent/CalendarEventServiceIntegrationTest.kt
  service/src/main/kotlin/fi/espoo/evaka/calendarevent/CalendarEventQueries.kt
Labels: bug

#5583 Varhaiskasvatuksessa lopettavat lapset raportille lisätty aluefiltteri
  frontend/src/employee-frontend/components/reports/EndedPlacements.tsx
Labels: enhancement

#5527 Lisätään kaikki puuttuvat API-endpoint prefixit paikoilleen
  frontend/src/employee-frontend/generated/api-clients/absence.ts
  frontend/src/employee-frontend/generated/api-clients/attendance.ts
  frontend/src/employee-frontend/generated/api-clients/backupcare.ts
  frontend/src/employee-frontend/generated/api-clients/childimages.ts
  frontend/src/employee-frontend/generated/api-clients/daycare.ts
  frontend/src/employee-frontend/generated/api-clients/decision.ts
  frontend/src/employee-frontend/generated/api-clients/messaging.ts
  frontend/src/employee-frontend/generated/api-clients/note.ts
  frontend/src/employee-frontend/generated/api-clients/placement.ts
  frontend/src/employee-mobile-frontend/generated/api-clients/assistanceneed.ts
  frontend/src/employee-mobile-frontend/generated/api-clients/attendance.ts
  frontend/src/employee-mobile-frontend/generated/api-clients/daycare.ts
  frontend/src/employee-mobile-frontend/generated/api-clients/holidayperiod.ts
  frontend/src/employee-mobile-frontend/generated/api-clients/invoicing.ts
  frontend/src/employee-mobile-frontend/generated/api-clients/messaging.ts
  frontend/src/employee-mobile-frontend/generated/api-clients/note.ts
  frontend/src/employee-mobile-frontend/generated/api-clients/pairing.ts
  frontend/src/employee-mobile-frontend/generated/api-clients/pis.ts
  frontend/src/lib-common/generated/api-types/absence.ts
  frontend/src/lib-common/generated/api-types/backupcare.ts
  service/codegen/src/main/kotlin/evaka/codegen/api/Config.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/attendance/GetAttendancesIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/backupcare/BackupCareIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/childimages/ChildImageTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/daycare/controllers/ChildrenControllerIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/daycare/controllers/UnitAclControllerIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/pis/service/MergeServiceIntegrationTest.kt
  service/src/main/kotlin/fi/espoo/evaka/absence/AbsenceController.kt
  service/src/main/kotlin/fi/espoo/evaka/assistanceneed/decision/AssistanceNeedDecisionController.kt
  service/src/main/kotlin/fi/espoo/evaka/assistanceneed/preschooldecision/AssistanceNeedPreschoolDecisionController.kt
  service/src/main/kotlin/fi/espoo/evaka/assistanceneed/vouchercoefficient/AssistanceNeedVoucherCoefficientController.kt
  service/src/main/kotlin/fi/espoo/evaka/attendance/ChildAttendanceController.kt
  service/src/main/kotlin/fi/espoo/evaka/attendance/RealtimeStaffAttendanceController.kt
  service/src/main/kotlin/fi/espoo/evaka/backupcare/BackupCareController.kt
  service/src/main/kotlin/fi/espoo/evaka/childimages/ChildImageController.kt
  service/src/main/kotlin/fi/espoo/evaka/daycare/controllers/ChildController.kt
  service/src/main/kotlin/fi/espoo/evaka/daycare/controllers/DaycareController.kt
  service/src/main/kotlin/fi/espoo/evaka/daycare/controllers/StaffAttendanceController.kt
  service/src/main/kotlin/fi/espoo/evaka/daycare/controllers/UnitAclController.kt
  service/src/main/kotlin/fi/espoo/evaka/decision/DecisionController.kt
  service/src/main/kotlin/fi/espoo/evaka/holidayperiod/HolidayQuestionnaireController.kt
  service/src/main/kotlin/fi/espoo/evaka/invoicing/controller/FeeDecisionGeneratorController.kt
  service/src/main/kotlin/fi/espoo/evaka/invoicing/controller/FinanceDecisionController.kt
  service/src/main/kotlin/fi/espoo/evaka/messaging/MessageController.kt
  service/src/main/kotlin/fi/espoo/evaka/note/NotesController.kt
  service/src/main/kotlin/fi/espoo/evaka/note/child/daily/ChildDailyNoteController.kt
  service/src/main/kotlin/fi/espoo/evaka/note/child/sticky/ChildStickyNoteController.kt
  service/src/main/kotlin/fi/espoo/evaka/note/group/GroupNoteController.kt
  service/src/main/kotlin/fi/espoo/evaka/pairing/MobileDevicesController.kt
  service/src/main/kotlin/fi/espoo/evaka/pis/controllers/PersonController.kt
  service/src/main/kotlin/fi/espoo/evaka/placement/PlacementController.kt
  service/src/main/kotlin/fi/espoo/evaka/reports/ExceededServiceNeedsReport.kt
  service/src/main/kotlin/fi/espoo/evaka/reports/ReportPermissions.kt
  service/src/main/kotlin/fi/espoo/evaka/specialdiet/SpecialDietController.kt
Labels: tech
