Repository espoon-voltti/evaka, pull requests merged in 2024-12, with the labels that each got.

#5993 Tuloilmoituksen voi tallentaa luonnoksena
  frontend/src/citizen-frontend/generated/api-clients/incomestatement.ts
  frontend/src/citizen-frontend/income-statements/ChildIncomeStatementEditor.tsx
  frontend/src/citizen-frontend/income-statements/ChildIncomeStatementForm.tsx
  frontend/src/citizen-frontend/income-statements/ChildIncomeStatementView.tsx
  frontend/src/citizen-frontend/income-statements/ChildrenIncomeStatements.tsx
  frontend/src/citizen-frontend/income-statements/IncomeStatementComponents.tsx
  frontend/src/citizen-frontend/income-statements/IncomeStatementEditor.tsx
  frontend/src/citizen-frontend/income-statements/IncomeStatementForm.tsx
  frontend/src/citizen-frontend/income-statements/IncomeStatementView.tsx
  frontend/src/citizen-frontend/income-statements/IncomeStatements.tsx
  frontend/src/citizen-frontend/income-statements/types/body.ts
  frontend/src/e2e-test/dev-api/fixtures.ts
  frontend/src/e2e-test/generated/api-clients.ts
  frontend/src/e2e-test/generated/api-types.ts
  frontend/src/e2e-test/pages/citizen/citizen-child-income.ts
  frontend/src/e2e-test/pages/citizen/citizen-income.ts
  frontend/src/e2e-test/specs/0_citizen/citizen-child-income-statement.spec.ts
  frontend/src/e2e-test/specs/0_citizen/citizen-income-statement.spec.ts
  frontend/src/e2e-test/specs/4_finance/income-staments.spec.ts
  frontend/src/e2e-test/specs/5_employee/child-income-statements.spec.ts
  frontend/src/e2e-test/specs/5_employee/guardian-income-statements.spec.ts
  frontend/src/employee-frontend/components/IncomeStatementPage.tsx
  frontend/src/employee-frontend/components/income-statements/IncomeStatementsPage.tsx
  frontend/src/employee-frontend/components/person-profile/IncomeStatementsTable.tsx
  frontend/src/lib-common/generated/api-types/incomestatement.ts
  frontend/src/lib-customizations/defaults/citizen/i18n/en.tsx
  frontend/src/lib-customizations/defaults/citizen/i18n/fi.tsx
  frontend/src/lib-customizations/defaults/citizen/i18n/sv.tsx
  frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
  service/src/integrationTest/kotlin/fi/espoo/evaka/absence/AbsenceServiceIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/attachments/AttachmentsControllerIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/incomestatement/IncomeStatementControllerCitizenIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/incomestatement/IncomeStatementControllerIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/FeeDecisionIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/service/OutdatedIncomeNotificationsIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/pis/InactivePeopleCleanupIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/shared/db/SchemaConventionsTest.kt
  service/src/main/kotlin/fi/espoo/evaka/incomestatement/IncomeStatement.kt
  service/src/main/kotlin/fi/espoo/evaka/incomestatement/IncomeStatementController.kt
  service/src/main/kotlin/fi/espoo/evaka/incomestatement/IncomeStatementControllerCitizen.kt
  service/src/main/kotlin/fi/espoo/evaka/incomestatement/IncomeStatementQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/invoicing/data/FeeDecisionQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/invoicing/service/IncomeQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/dev/DataInitializers.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/dev/DevApi.kt
  service/src/main/resources/db/migration/V469__income_statement_status.sql
  service/src/main/resources/migrations.txt
Labels: enhancement

#6057 Korjataan palveluntarvemuutoshakemuksen näkyvyys kevytkirjautumisella
  frontend/src/citizen-frontend/children/sections/service-need-and-daily-service-time/ServiceNeedAndDailyServiceTimeSection.tsx
  frontend/src/lib-common/generated/api-types/children.ts
  service/src/integrationTest/kotlin/fi/espoo/evaka/children/ChildControllerCitizenTest.kt
  service/src/main/kotlin/fi/espoo/evaka/children/ChildControllerCitizen.kt
  service/src/main/kotlin/fi/espoo/evaka/children/Children.kt
Labels: enhancement

#6075 Mocked time -tuki generoiduille dev-API-clienteille
  frontend/src/e2e-test/dev-api/index.ts
  frontend/src/e2e-test/generated/api-clients.ts
  service/codegen/src/main/kotlin/evaka/codegen/api/ApiFiles.kt
Labels: tech

#6045 Espoon hakemusten tekstipäivityksiä (saattaa rikkoa buildit)
  frontend/src/citizen-frontend/applications/editor/service-need/AssistanceNeedSubSection.tsx
  frontend/src/citizen-frontend/applications/editor/service-need/ServiceTimeSubSectionDaycare.tsx
  frontend/src/citizen-frontend/applications/editor/service-need/ServiceTimeSubSectionPreschool.tsx
  frontend/src/citizen-frontend/applications/editor/unit-preference/PreferredUnitBox.tsx
  frontend/src/lib-components/atoms/buttons/button-visuals.tsx
  frontend/src/lib-customizations/defaults/citizen/i18n/en.tsx
  frontend/src/lib-customizations/defaults/citizen/i18n/fi.tsx
  frontend/src/lib-customizations/defaults/citizen/i18n/sv.tsx
  frontend/src/lib-customizations/espoo/citizen.tsx
Labels: enhancement

#6055 Palveluntarpeen muutoshakemuksen käännökset
  frontend/src/lib-customizations/defaults/citizen/i18n/en.tsx
  frontend/src/lib-customizations/defaults/citizen/i18n/sv.tsx
  service/src/integrationTest/kotlin/fi/espoo/evaka/serviceneed/application/ServiceApplicationIntegrationTest.kt
  service/src/main/kotlin/fi/espoo/evaka/emailclient/EvakaEmailMessageProvider.kt
Labels: enhancement

#6059 Tehdään `Map`-tyyppien käsittelystä turvallisempaa
  frontend/src/citizen-frontend/calendar/CalendarMonthView.tsx
  frontend/src/citizen-frontend/calendar/CalendarPage.tsx
  frontend/src/citizen-frontend/calendar/discussion-reservation-modal/DiscussionReservationModal.tsx
  frontend/src/citizen-frontend/calendar/discussion-reservation-modal/DiscussionSurveyModal.tsx
  frontend/src/citizen-frontend/calendar/discussion-reservation-modal/discussion-survey.ts
  frontend/src/citizen-frontend/calendar/holiday-modal/FixedPeriodSelectionModal.tsx
  frontend/src/citizen-frontend/generated/api-clients/application.ts
  frontend/src/citizen-frontend/generated/api-clients/document.ts
  frontend/src/citizen-frontend/generated/api-clients/pedagogicaldocument.ts
  frontend/src/citizen-frontend/messages/ThreadView.tsx
  frontend/src/e2e-test/generated/api-types.ts
  frontend/src/e2e-test/specs/0_citizen/citizen-reservations.spec.ts
  frontend/src/employee-frontend/components/child-information/placements/PlacementRow.tsx
  frontend/src/employee-frontend/components/child-information/placements/ServiceNeeds.tsx
  frontend/src/employee-frontend/components/finance-basics/PlacementTypeItem.tsx
  frontend/src/employee-frontend/components/person-profile/income/IncomeItemEditor.tsx
  frontend/src/employee-frontend/components/person-profile/income/IncomeList.tsx
  frontend/src/employee-frontend/components/reports/PreschoolAbsenceReport.tsx
  frontend/src/employee-frontend/components/unit/tab-groups/Groups.tsx
  frontend/src/employee-frontend/components/unit/tab-groups/MissingGroupPlacements.tsx
  frontend/src/employee-frontend/components/unit/tab-groups/groups/Group.tsx
  frontend/src/employee-frontend/generated/api-clients/invoicing.ts
  frontend/src/employee-frontend/generated/api-clients/setting.ts
  frontend/src/employee-mobile-frontend/child-attendance/ChildReservationList.tsx
  frontend/src/employee-mobile-frontend/generated/api-clients/attendance.ts
  frontend/src/lib-common/generated/api-types/application.ts
  frontend/src/lib-common/generated/api-types/attendance.ts
  frontend/src/lib-common/generated/api-types/calendarevent.ts
  frontend/src/lib-common/generated/api-types/daycare.ts
  frontend/src/lib-common/generated/api-types/holidayperiod.ts
  frontend/src/lib-common/generated/api-types/invoicing.ts
  frontend/src/lib-common/generated/api-types/messaging.ts
  frontend/src/lib-common/generated/api-types/placement.ts
  frontend/src/lib-common/generated/api-types/reports.ts
  frontend/src/lib-common/generated/api-types/reservations.ts
  service/codegen/src/main/kotlin/evaka/codegen/api/TsCodeGenerator.kt
  service/codegen/src/test/kotlin/evaka/codegen/api/TsCodeGeneratorTest.kt
Labels: tech

#6078 Poistetaan citizen_user-taulun rivi jos person-taulun rivi poistuu
  service/src/main/resources/db/migration/V470__cascade_citizen_user_delete.sql
  service/src/main/resources/migrations.txt
Labels: tech

#6052 Istunnon aikakatkaisun esto käyttäjän aktiivisuudesta muuaallakin kuin viestieditorissa
  frontend/src/citizen-frontend/App.tsx
  frontend/src/citizen-frontend/RequireAuth.tsx
  frontend/src/citizen-frontend/auth/utils.ts
  frontend/src/citizen-frontend/messages/MessageEditor.tsx
  frontend/src/citizen-frontend/messages/ThreadView.tsx
  frontend/src/employee-frontend/App.tsx
  frontend/src/employee-frontend/components/common/sessionKeepalive.ts
  frontend/src/employee-frontend/components/messages/MessageEditor.tsx
  frontend/src/employee-frontend/components/messages/SingleThreadView.tsx
  frontend/src/lib-components/messages/MessageReplyEditor.tsx
  frontend/src/lib-components/useKeepSessionAlive.ts
  frontend/src/lib-customizations/defaults/components/i18n/en.tsx
  frontend/src/lib-customizations/defaults/components/i18n/fi.tsx
  frontend/src/lib-customizations/defaults/components/i18n/sv.tsx
Labels: enhancement

#6060 Tehdään tuloilmoituksen draft-parametrista pakollinen
  frontend/src/citizen-frontend/generated/api-clients/incomestatement.ts
  service/src/main/kotlin/fi/espoo/evaka/incomestatement/IncomeStatementControllerCitizen.kt
Labels: tech

#6084 Korjaus tuloilmoitusluonnosten näkyvyyteen virkailijoille
  service/src/integrationTest/kotlin/fi/espoo/evaka/incomestatement/IncomeStatementControllerIntegrationTest.kt
  service/src/main/kotlin/fi/espoo/evaka/incomestatement/IncomeStatement.kt
  service/src/main/kotlin/fi/espoo/evaka/incomestatement/IncomeStatementController.kt
  service/src/main/kotlin/fi/espoo/evaka/incomestatement/IncomeStatementControllerCitizen.kt
  service/src/main/kotlin/fi/espoo/evaka/incomestatement/IncomeStatementQueries.kt
Labels: bug

#6087 New static bucket
  .github/workflows/build.yml
  bin/ci-login-cloud
  bin/ci-login-registry
Labels: no-changelog

#6053 Korvataan passport yksinkertaisemmalla toteutuksella
  apigw/package.json
  apigw/src/enduser/app.ts
  apigw/src/enduser/dev-sfi-auth.ts
  apigw/src/enduser/keycloak-citizen-saml.ts
  apigw/src/enduser/mapRoutes.ts
  apigw/src/enduser/routes/auth-status.ts
  apigw/src/enduser/routes/auth-weak-login.ts
  apigw/src/enduser/suomi-fi-saml.ts
  apigw/src/index.ts
  apigw/src/internal/__tests__/mobile-device-session.ts
  apigw/src/internal/ad-saml.ts
  apigw/src/internal/app.ts
  apigw/src/internal/dev-ad-auth.ts
  apigw/src/internal/keycloak-employee-saml.ts
  apigw/src/internal/mobile-device-session.ts
  apigw/src/internal/routes/auth-status.ts
  apigw/src/shared/auth/dev-auth.ts
  apigw/src/shared/auth/index.ts
  apigw/src/shared/express.ts
  apigw/src/shared/proxy-utils.ts
  apigw/src/shared/routes/csp.ts
  apigw/src/shared/routes/saml.ts
  apigw/src/shared/saml/index.ts
  apigw/src/shared/service-client.ts
  apigw/src/shared/session.ts
  apigw/src/shared/test/gateway-tester.ts
  apigw/src/shared/types.d.ts
  apigw/yarn.lock
Labels: tech

#6081 Varaukset näytetään kuntalaisen kalenterissa toteumien yhteydessä
  frontend/src/citizen-frontend/calendar/calendar-elements.tsx
Labels: enhancement

#6044 Palveluohjaaja merkitsee onko hakemus salassapidettävä mikäli sitä ei voida päätellä automaattisesti
  frontend/src/e2e-test/dev-api/fixtures.ts
  frontend/src/e2e-test/dev-api/index.ts
  frontend/src/e2e-test/generated/api-clients.ts
  frontend/src/e2e-test/generated/api-types.ts
  frontend/src/e2e-test/pages/admin/application-workbench-page.ts
  frontend/src/e2e-test/pages/employee/applications/application-list-view.ts
  frontend/src/e2e-test/pages/employee/applications/application-read-view.ts
  frontend/src/e2e-test/specs/0_citizen/citizen-applications-list.spec.ts
  frontend/src/e2e-test/specs/0_citizen/citizen-daycare-application.spec.ts
  frontend/src/e2e-test/specs/0_citizen/citizen-decisions.spec.ts
  frontend/src/e2e-test/specs/0_citizen/foster-parents.spec.ts
  frontend/src/e2e-test/specs/5_employee/application-attachments.spec.ts
  frontend/src/e2e-test/specs/5_employee/application-details.spec.ts
  frontend/src/e2e-test/specs/5_employee/application-transitions.spec.ts
  frontend/src/e2e-test/specs/5_employee/applications.spec.ts
  frontend/src/e2e-test/specs/5_employee/feature-flag-decision-draft-multiple-units.spec.ts
  frontend/src/e2e-test/specs/5_employee/search-person.spec.ts
  frontend/src/e2e-test/utils/page.ts
  frontend/src/employee-frontend/components/application-page/ApplicationActionsBar.tsx
  frontend/src/employee-frontend/components/applications/ActionBar.tsx
  frontend/src/employee-frontend/components/applications/ApplicationActions.tsx
  frontend/src/employee-frontend/components/applications/ApplicationsPage.tsx
  frontend/src/employee-frontend/generated/api-clients/application.ts
  frontend/src/lib-common/generated/api-types/application.ts
  frontend/src/lib-components/molecules/modals/BaseModal.tsx
  frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
  service/src/integrationTest/kotlin/fi/espoo/evaka/TestFixtures.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/application/ApplicationStateServiceIntegrationTests.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/application/GetApplicationIntegrationTests.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/decision/DecisionControllerIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/decision/DecisionCreationIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/placement/PlacementPlanIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/shared/job/ScheduledJobsTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/test/TestData.kt
  service/src/main/kotlin/fi/espoo/evaka/application/Application.kt
  service/src/main/kotlin/fi/espoo/evaka/application/ApplicationControllerCitizen.kt
  service/src/main/kotlin/fi/espoo/evaka/application/ApplicationControllerV2.kt
  service/src/main/kotlin/fi/espoo/evaka/application/ApplicationQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/application/ApplicationStateService.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/dev/DataInitializers.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/dev/DevApi.kt
  service/src/main/resources/db/migration/V471__application_confidentiality.sql
  service/src/main/resources/migrations.txt
Labels: enhancement

#6076 Korjaus läsnäolon näkyvyyteen mobiilissa
  frontend/src/e2e-test/specs/6_mobile/reservations.spec.ts
  service/src/integrationTest/kotlin/fi/espoo/evaka/reservations/AttendanceReservationsControllerIntegrationTest.kt
  service/src/main/kotlin/fi/espoo/evaka/reservations/AttendanceReservationController.kt
Labels: bug

#6088 Lisätään ehdottavan EO:n sijoitustietojen syöttöön tuki Excel-peräisille CSV-tiedostoille (BOM)
  service/src/integrationTest/kotlin/fi/espoo/evaka/application/PlacementToolServiceIntegrationTest.kt
  service/src/main/kotlin/fi/espoo/evaka/application/PlacementToolService.kt
Labels: enhancement

#6046 Lomakyselyraportin tuki ryhmäkohtaisille tuloksille
  frontend/src/e2e-test/pages/employee/reports.ts
  frontend/src/e2e-test/specs/5_employee/holiday-period-attendance-report.spec.ts
  frontend/src/employee-frontend/components/reports/HolidayPeriodAttendanceReport.tsx
  frontend/src/employee-frontend/generated/api-clients/reports.ts
  frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
  service/src/integrationTest/kotlin/fi/espoo/evaka/reports/HolidayPeriodAttendanceReportTest.kt
  service/src/main/kotlin/fi/espoo/evaka/reports/HolidayPeriodAttendanceReport.kt
Labels: enhancement

#6098 Päivitetään Node.js versioon LTS 22.12
  .nvmrc
  apigw/Dockerfile
  apigw/README.md
  apigw/package.json
  compose/README.md
  frontend/Dockerfile
  frontend/README.md
  frontend/package.json
Labels: dependencies

#6058 Kuntalaisen kalenterinäkymä menneisyyteen
  frontend/src/citizen-frontend/calendar/CalendarListView.tsx
  frontend/src/citizen-frontend/calendar/CalendarMonthView.tsx
  frontend/src/citizen-frontend/calendar/CalendarPage.tsx
  frontend/src/citizen-frontend/calendar/DayElem.tsx
  frontend/src/citizen-frontend/calendar/MonthElem.tsx
  frontend/src/citizen-frontend/calendar/hooks.ts
  frontend/src/e2e-test/pages/citizen/citizen-calendar.ts
  frontend/src/e2e-test/specs/0_citizen/citizen-reservations.spec.ts
  frontend/src/lib-customizations/defaults/citizen/i18n/en.tsx
  frontend/src/lib-customizations/defaults/citizen/i18n/fi.tsx
  frontend/src/lib-customizations/defaults/citizen/i18n/sv.tsx
  frontend/src/lib-icons/fontawesome.d.ts
  frontend/src/lib-icons/free-icons.ts
  frontend/src/lib-icons/pro-icons.ts
Labels: enhancement

#6102 Parannuksia osoitteiden vertailuun
  service/src/integrationTest/kotlin/fi/espoo/evaka/pis/service/DVVBatchRefreshServiceIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/pis/service/FridgeFamilyServiceIntegrationTest.kt
  service/src/main/kotlin/fi/espoo/evaka/pis/service/FridgeFamilyService.kt
  service/src/main/kotlin/fi/espoo/evaka/pis/service/PersonService.kt
Labels: bug

#6099 Näytetään hakemuksen salassapidettävyys metatiedoissa oikein
  frontend/src/employee-frontend/components/ApplicationPage.tsx
  frontend/src/employee-frontend/components/archive-metadata/MetadataSection.tsx
  frontend/src/lib-common/generated/api-types/process.ts
  frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
  service/src/main/kotlin/fi/espoo/evaka/process/ProcessMetadataController.kt
Labels: bug

#6079 Korjataan tukitoimien laskenta raportissa
  frontend/src/e2e-test/pages/employee/reports.ts
  frontend/src/e2e-test/specs/5_employee/assistance-need-and-actions-report.spec.ts
  frontend/src/employee-frontend/components/reports/AssistanceNeedsAndActions.tsx
  frontend/src/employee-frontend/components/reports/queries.ts
  frontend/src/employee-frontend/generated/api-clients/reports.ts
  frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
  service/src/integrationTest/kotlin/fi/espoo/evaka/reports/AssistanceNeedsAndActionsReportControllerTest.kt
  service/src/main/kotlin/fi/espoo/evaka/reports/AssistanceNeedsAndActionsReportController.kt
Labels: bug

#6100 Piilota pedagogisten asiakirjojen luonti käyttäjiltä, joilla vain lukuoikeus
  frontend/src/employee-frontend/components/child-information/ChildDocuments.tsx
  frontend/src/employee-frontend/components/child-information/ChildDocumentsSection.tsx
Labels: enhancement

#6108 Muistutetaan dokumentaatiosta PR-templatessa
  .github/PULL_REQUEST_TEMPLATE.md
Labels: no-changelog

#6109 Lisätään sisäinen rajapinta palvelutuottajien suomi.fi-kirjautumiselle
  apigw/src/shared/service-client.ts
  service/src/main/kotlin/fi/espoo/evaka/Audit.kt
  service/src/main/kotlin/fi/espoo/evaka/pis/EmployeeQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/pis/SystemController.kt
  service/src/main/resources/db/migration/V472__employee_ssn.sql
  service/src/main/resources/migrations.txt
Labels: enhancement

#6086 Lisätään kotikunta
  frontend/src/e2e-test/dev-api/fixtures.ts
  frontend/src/e2e-test/generated/api-types.ts
  frontend/src/e2e-test/specs/5_employee/create-person.spec.ts
  frontend/src/employee-frontend/components/person-profile/PersonDependants.tsx
  frontend/src/employee-frontend/components/person-shared/PersonDetails.tsx
  frontend/src/lib-common/generated/api-types/pis.ts
  frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
  service/src/integrationTest/kotlin/fi/espoo/evaka/dvv/DvvModificationsServiceIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/pdfgen/PdfGeneratorTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/pis/PersonIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/pis/dao/PersonQueriesIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/pis/service/DVVBatchRefreshServiceIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/vtjclient/VtjClientServiceTest.kt
  service/src/main/kotlin/fi/espoo/evaka/dvv/DvvModificationsService.kt
  service/src/main/kotlin/fi/espoo/evaka/pis/PersonQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/pis/controllers/PersonController.kt
  service/src/main/kotlin/fi/espoo/evaka/pis/service/PersonService.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/dev/DevApi.kt
  service/src/main/kotlin/fi/espoo/evaka/vtjclient/dto/VtjPerson.kt
  service/src/main/kotlin/fi/espoo/evaka/vtjclient/dto/VtjPersonDTO.kt
  service/src/main/kotlin/fi/espoo/evaka/vtjclient/mapper/VtjHenkiloMapper.kt
  service/src/main/kotlin/fi/espoo/evaka/vtjclient/service/persondetails/MockPersonDetailsService.kt
  service/src/main/resources/db/migration/V473__person_municipality_of_residence.sql
  service/src/main/resources/migrations.txt
  service/src/test/kotlin/fi/espoo/evaka/vtjclient/service/VtjClientServiceTest.kt
  service/src/test/kotlin/fi/espoo/evaka/vtjclient/service/persondetails/DVVPersonDetailsServiceTest.kt
Labels: enhancement

#6110 Oikaisulaskujen generointijobi oletuksena päälle
  service/src/main/kotlin/fi/espoo/evaka/shared/job/ScheduledJobs.kt
Labels: enhancement

#6111 Korjaa ajoitusriippuvainen keskusteluvarausajan e2e testi
  frontend/src/e2e-test/pages/citizen/citizen-discussion-surveys.ts
Labels: tech

#6107 Muutetaan pedagogisten asiakirjojen asianhallinnan tilahistoria lineaariseksi
  service/src/integrationTest/kotlin/fi/espoo/evaka/document/childdocument/ChildDocumentControllerIntegrationTest.kt
  service/src/main/kotlin/fi/espoo/evaka/process/ArchivedProcesses.kt
Labels: bug

#6116 Pieniä korjauksia oikaisulaskuihin
  frontend/src/employee-frontend/components/invoice/ReplacementDraftInfo.tsx
  service/src/main/kotlin/fi/espoo/evaka/invoicing/controller/InvoiceController.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/security/Action.kt
Labels: enhancement

#6105 Hakemus siirretään odottamaan sijoitusta jos johtaja hylkää sijoitusehdotuksen
  docs/diagrams/src/evaka-application.puml
  frontend/src/e2e-test/pages/admin/application-workbench-page.ts
  frontend/src/e2e-test/specs/5_employee/application-transitions.spec.ts
  frontend/src/employee-frontend/components/applications/ApplicationsList.tsx
  service/src/integrationTest/kotlin/fi/espoo/evaka/application/ApplicationStateServiceIntegrationTests.kt
  service/src/main/kotlin/fi/espoo/evaka/application/ApplicationStateService.kt
Labels: enhancement

#6115 Muutetaan laskujen täsmäysraportin päivävalitsin kuukausivalitsimeen
  frontend/src/employee-frontend/components/reports/Invoices.tsx
  frontend/src/employee-frontend/components/reports/queries.ts
  frontend/src/employee-frontend/generated/api-clients/reports.ts
  service/src/integrationTest/kotlin/fi/espoo/evaka/reports/InvoicingReportTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/reports/ReportSmokeTests.kt
  service/src/main/kotlin/fi/espoo/evaka/reports/InvoiceReport.kt
Labels: enhancement

#6112 Palveluseteliraportille lasketaan erikseen perusosa ja tuen tarpeen korotusosa (feature flagin takana)
  frontend/src/employee-frontend/components/reports/VoucherServiceProviderUnit.tsx
  frontend/src/employee-frontend/components/reports/VoucherServiceProviders.tsx
  frontend/src/lib-common/generated/api-types/reports.ts
  frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
  frontend/src/lib-customizations/espoo/featureFlags.tsx
  frontend/src/lib-customizations/types.d.ts
  service/src/integrationTest/kotlin/fi/espoo/evaka/reports/ServiceVoucherValueUnitReportTest.kt
  service/src/main/kotlin/fi/espoo/evaka/reports/ServiceVoucherValueReport.kt
  service/src/test/kotlin/fi/espoo/evaka/reports/ServiceVoucherValueReportTests.kt
Labels: enhancement

#6119 Parannus satunnaisesti epäonnistuvaan istunnon aikakatkaisun e2e testiin
  frontend/src/e2e-test/specs/7_messaging/messaging.spec.ts
Labels: tech

#6117 Päivämääräkentän saavutettavuus
  frontend/src/lib-components/i18n.tsx
  frontend/src/lib-components/molecules/date-picker/DatePicker.spec.tsx
  frontend/src/lib-components/molecules/date-picker/DatePickerDay.tsx
  frontend/src/lib-components/molecules/date-picker/DatePickerInput.tsx
  frontend/src/lib-components/molecules/date-picker/DatePickerLowLevel.tsx
  frontend/src/lib-components/molecules/date-picker/DateRangePicker.spec.tsx
  frontend/src/lib-components/utils/TestContextProvider.tsx
  frontend/src/lib-customizations/defaults/components/i18n/en.tsx
  frontend/src/lib-customizations/defaults/components/i18n/fi.tsx
  frontend/src/lib-customizations/defaults/components/i18n/sv.tsx
Labels: enhancement

#6120 Korjataan regressio kartan hakutoiminnossa
  frontend/src/citizen-frontend/map/api.ts
Labels: bug

#6083 Näytetään hakemuksen muokkaajan nimi hakemusnäkymässä (nyt näkyy vain aikaleima)
  frontend/src/citizen-frontend/applications/editor/verification/BasicsSection.tsx
  frontend/src/e2e-test/dev-api/fixtures.ts
  frontend/src/e2e-test/generated/api-types.ts
  frontend/src/employee-frontend/components/application-page/ApplicationStatusSection.tsx
  frontend/src/lib-common/generated/api-types/application.ts
  frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
  service/src/integrationTest/kotlin/fi/espoo/evaka/TestFixtures.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/application/GetApplicationIntegrationTests.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/shared/db/SchemaConventionsTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/shared/job/ScheduledJobsTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/test/TestData.kt
  service/src/main/kotlin/fi/espoo/evaka/application/Application.kt
  service/src/main/kotlin/fi/espoo/evaka/application/ApplicationQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/application/ApplicationStateService.kt
  service/src/main/kotlin/fi/espoo/evaka/espoo/bi/EspooBi.kt
  service/src/main/kotlin/fi/espoo/evaka/espoo/bi/EspooBiModels.kt
  service/src/main/kotlin/fi/espoo/evaka/pis/ParentshipQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/pis/PartnershipQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/process/ProcessMetadataController.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/dev/DataInitializers.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/dev/DevApi.kt
  service/src/main/resources/db/migration/R__application_view.sql
  service/src/main/resources/db/migration/V475__application_modified_metadata.sql
  service/src/main/resources/migrations.txt
Labels: enhancement

#6114 Lisätään "jatkava lapsi"-huomio hakemushakuun
  frontend/src/employee-frontend/components/applications/ApplicationsFilters.tsx
  frontend/src/employee-frontend/components/applications/ApplicationsList.tsx
  frontend/src/employee-frontend/components/common/Filters.tsx
  frontend/src/employee-frontend/state/application-ui.tsx
  frontend/src/lib-common/generated/api-types/application.ts
  frontend/src/lib-customizations/common.tsx
  frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
  service/src/integrationTest/kotlin/fi/espoo/evaka/application/ApplicationSearchIntegrationTest.kt
  service/src/main/kotlin/fi/espoo/evaka/application/Application.kt
  service/src/main/kotlin/fi/espoo/evaka/application/ApplicationQueries.kt
Labels: enhancement

#6118 Poistetaan vanhat turhat käytöstä poistuneet roolit
  apigw/src/shared/service-client.ts
  frontend/src/lib-common/generated/api-types/shared.ts
  frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
  service/src/integrationTest/kotlin/fi/espoo/evaka/decision/DecisionCreationIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/placement/PlacementPlanIntegrationTest.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/auth/UserRole.kt
Labels: tech

#6126 Korjataan päivämäärävalitsimen virheviestit
  frontend/src/lib-components/molecules/date-picker/DatePicker.tsx
Labels: enhancement

#6142 Palveluohjauksen hakemuksen viestiin muutos
  frontend/src/lib-customizations/defaults/citizen/i18n/en.tsx
  frontend/src/lib-customizations/defaults/citizen/i18n/fi.tsx
  frontend/src/lib-customizations/defaults/citizen/i18n/sv.tsx
  service/src/main/resources/application-espoo_evaka.yaml
Labels: no-changelog

#6125 Siirron saaneiden lasten näkyminen irtisanottujen listalla
  frontend/src/employee-frontend/components/unit/tab-groups/TerminatedPlacements.tsx
  frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
  service/src/integrationTest/kotlin/fi/espoo/evaka/daycare/controllers/DaycareControllerIntegrationTest.kt
  service/src/main/kotlin/fi/espoo/evaka/application/ApplicationQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/daycare/controllers/DaycareController.kt
Labels: enhancement

#6123 Tekstimuutoksia varhaiskasvatuksen tuen päätökselle Espoossa
  frontend/src/e2e-test/specs/0_citizen/citizen-decisions.spec.ts
  frontend/src/e2e-test/specs/5_employee/assistance-need-decision.spec.ts
  frontend/src/lib-customizations/espoo/citizen.tsx
  frontend/src/lib-customizations/espoo/employee.tsx
Labels: no-changelog

#6145 Korjataan regressioita apigw:n poluissa
  apigw/src/app.ts
Labels: bug

#6147 Korjataan palvelutuottajien Keycloak-uloskirjautuminen toimimaan myös Keycloakin puolella oikein
  apigw/src/app.ts
Labels: bug

#6149 Päivitetään sijoitusten hahmotteluraportin nimi
  frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
Labels: enhancement

#6146 Käytetään standardimallisia UUID:itä testidatassa
  frontend/src/e2e-test/pages/employee/employees.ts
  frontend/src/e2e-test/specs/5_employee/employees.spec.ts
  service/src/main/kotlin/fi/espoo/evaka/shared/dev/DevApi.kt
  service/src/main/resources/dev-data/employees.sql
Labels: tech

#6152 Korjataan tuen päätöksen otsikko
  frontend/src/lib-customizations/defaults/citizen/i18n/en.tsx
  frontend/src/lib-customizations/defaults/citizen/i18n/fi.tsx
Labels: enhancement

#6151 Korjaus ryhmäpostilaatikon näkyvyyteen kun työntekijä luvitettiin toiseen ryhmään
  service/src/integrationTest/kotlin/fi/espoo/evaka/attendance/MobileRealtimeStaffAttendanceControllerIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/attendance/RealtimeStaffAttendanceControllerIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/daycare/controllers/UnitAclControllerIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/messaging/MessageAccountQueriesTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/messaging/MessageIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/pis/InactiveEmployeesRoleResetIntegrationTest.kt
  service/src/main/kotlin/fi/espoo/evaka/daycare/UnitAcl.kt
  service/src/main/kotlin/fi/espoo/evaka/daycare/controllers/UnitAclController.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/auth/AclQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/dev/DataInitializers.kt
Labels: bug

#6157 Kirjastopäivityksiä joilla korjataan CVE-hälyjä
  service/evaka-bom/build.gradle.kts
  service/owasp-suppressions.xml
Labels: dependencies

#6150 Kerrotaan async jobien virheet OpenTelemetrylle
  service/src/main/kotlin/fi/espoo/evaka/shared/async/AsyncJobPool.kt
Labels: tech

#6140 Titania raportin jatkokehitys
  frontend/src/employee-frontend/components/reports/TitaniaErrors.tsx
  frontend/src/employee-frontend/components/reports/queries.ts
  frontend/src/employee-frontend/generated/api-clients/reports.ts
  frontend/src/lib-common/generated/api-types/reports.ts
  frontend/src/lib-common/generated/api-types/shared.ts
  service/src/main/kotlin/fi/espoo/evaka/Audit.kt
  service/src/main/kotlin/fi/espoo/evaka/reports/TitaniaErrorsReport.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/Id.kt
  service/src/main/kotlin/fi/espoo/evaka/titania/TitaniaService.kt
  service/src/main/resources/db/migration/V477__titania_errors_id.sql
  service/src/main/resources/migrations.txt
Labels: enhancement

#6161 Korjaus lasten näkymiseen päätyvien sijoitusten listalla
  service/src/integrationTest/kotlin/fi/espoo/evaka/daycare/controllers/DaycareControllerIntegrationTest.kt
  service/src/main/kotlin/fi/espoo/evaka/application/ApplicationQueries.kt
Labels: bug

#6154 Vain liitteitä ja lisätietoja saa muokata tuloilmoituksen lähetyksen jälkeen
  frontend/src/citizen-frontend/income-statements/ChildIncomeStatementForm.tsx
  frontend/src/citizen-frontend/income-statements/IncomeStatementComponents.tsx
  frontend/src/citizen-frontend/income-statements/IncomeStatementForm.tsx
  frontend/src/e2e-test/pages/citizen/citizen-child-income.ts
  frontend/src/e2e-test/specs/0_citizen/citizen-child-income-statement.spec.ts
  frontend/src/e2e-test/specs/0_citizen/citizen-income-statement.spec.ts
  service/src/integrationTest/kotlin/fi/espoo/evaka/incomestatement/IncomeStatementControllerCitizenIntegrationTest.kt
  service/src/main/kotlin/fi/espoo/evaka/incomestatement/IncomeStatementControllerCitizen.kt
Labels: enhancement

#6160 Pyöristyskorjaus palveluseteliraportin perusosan ja tuen kertoimen vaikutuksen laskentaan
  service/src/integrationTest/kotlin/fi/espoo/evaka/reports/ServiceVoucherValueUnitReportTest.kt
  service/src/main/kotlin/fi/espoo/evaka/reports/ServiceVoucherValueReport.kt
Labels: bug

#6163 Päivämääräkentän validointivirhe ruudunlukijalle
  frontend/src/citizen-frontend/calendar/AbsenceModal.tsx
  frontend/src/citizen-frontend/calendar/ReservationModal.tsx
  frontend/src/lib-components/atoms/form/InputField.tsx
  frontend/src/lib-components/molecules/date-picker/DateRangePicker.tsx
  frontend/src/lib-components/molecules/date-picker/DateRangePickerLowLevel.tsx
Labels: enhancement

#6164 Lisätään sähköposti-ilmoitus uudesta paikkapäätöksestä
  service/src/integrationTest/kotlin/fi/espoo/evaka/application/ApplicationStateServiceIntegrationTests.kt
  service/src/main/kotlin/fi/espoo/evaka/application/ApplicationStateService.kt
  service/src/main/kotlin/fi/espoo/evaka/application/DecisionMessageProcessor.kt
  service/src/main/kotlin/fi/espoo/evaka/decision/DecisionService.kt
  service/src/main/kotlin/fi/espoo/evaka/emailclient/EvakaEmailMessageProvider.kt
  service/src/main/kotlin/fi/espoo/evaka/emailclient/IEmailMessageProvider.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/async/AsyncJob.kt
Labels: enhancement

#6156 Korjataan CSP-raporttiendpointin polku
  apigw/src/app.ts
Labels: tech

#6101 Palvelutuottajien suomi.fi -kirjautuminen (ei vielä käytössä)
  apigw/src/app.ts
  apigw/src/enduser/keycloak-citizen-saml.ts
  apigw/src/enduser/suomi-fi-saml.ts
  apigw/src/internal/ad-saml.ts
  apigw/src/internal/dev-sfi-auth.ts
  apigw/src/internal/keycloak-employee-saml.ts
  apigw/src/shared/auth/dev-auth.ts
  apigw/src/shared/auth/index.ts
  apigw/src/shared/config.ts
  apigw/src/shared/dev-api.ts
  apigw/src/shared/routes/saml.ts
  apigw/src/shared/saml/index.ts
  apigw/src/shared/test/gateway-tester.ts
  frontend/src/citizen-frontend/navigation/DesktopNav.tsx
  frontend/src/citizen-frontend/navigation/MobileNav.tsx
  frontend/src/citizen-frontend/navigation/const.ts
  frontend/src/e2e-test/config.ts
  frontend/src/e2e-test/generated/api-clients.ts
  frontend/src/e2e-test/generated/api-types.ts
  frontend/src/e2e-test/utils/user.ts
  frontend/src/employee-frontend/api/auth.ts
  frontend/src/employee-frontend/components/login-page/Login.tsx
  frontend/src/lib-customizations/espoo/featureFlags.tsx
  frontend/src/lib-customizations/types.d.ts
  service/src/main/kotlin/fi/espoo/evaka/shared/dev/DevApi.kt
  service/src/main/resources/dev-data/employees.sql
Labels: enhancement

#6162 Espoo: käyttöoikeusmuutoksia
  frontend/src/e2e-test/specs/5_employee/non-ssn-children-report.spec.ts
  service/src/main/kotlin/fi/espoo/evaka/espoo/EspooActionRuleMapping.kt
Labels: no-changelog

#6169 Pedagogisen asiakirjan lataaminen PDF:nä
  frontend/src/employee-frontend/components/child-documents/ChildDocumentEditor.tsx
  frontend/src/lib-common/generated/api-types/document.ts
  frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
  service/src/integrationTest/kotlin/fi/espoo/evaka/document/childdocument/ChildDocumentControllerIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/pdfgen/PdfGeneratorTest.kt
  service/src/main/kotlin/fi/espoo/evaka/document/childdocument/ChildDocument.kt
  service/src/main/kotlin/fi/espoo/evaka/document/childdocument/ChildDocumentQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/security/Action.kt
Labels: enhancement

#6143 Lisätään modaali yksikön päättymispäivän asettamiselle
  frontend/src/e2e-test/pages/employee/units/unit.ts
  frontend/src/e2e-test/specs/5_employee/unit-editor.spec.ts
  frontend/src/e2e-test/utils/page.ts
  frontend/src/employee-frontend/components/unit/queries.ts
  frontend/src/employee-frontend/components/unit/unit-details/UnitClosingDateModal.tsx
  frontend/src/employee-frontend/components/unit/unit-details/UnitEditor.tsx
  frontend/src/employee-frontend/generated/api-clients/daycare.ts
  frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
  service/src/integrationTest/kotlin/fi/espoo/evaka/daycare/controllers/DaycareControllerIntegrationTest.kt
  service/src/main/kotlin/fi/espoo/evaka/daycare/DaycareQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/daycare/controllers/DaycareController.kt
Labels: enhancement

#6158 Korjataan sijoitusten hahmotteluraportin suorituskyky
  frontend/src/employee-frontend/components/reports/PlacementSketching.tsx
  frontend/src/employee-frontend/components/reports/queries.ts
Labels: enhancement

#6165 Korjataan huoltajien käyttöliittymään lukemattomien päätöksien ilmoitusmerkki
  frontend/src/citizen-frontend/navigation/DesktopNav.tsx
  frontend/src/citizen-frontend/navigation/Header.tsx
  frontend/src/citizen-frontend/navigation/MobileNav.tsx
  frontend/src/citizen-frontend/navigation/utils.ts
Labels: enhancement

#6166 Refaktoroidaan päätöksen luonnin integraatiotestit
  service/src/integrationTest/kotlin/fi/espoo/evaka/decision/DecisionCreationIntegrationTest.kt
Labels: tech

#6153 Korjataan apigw:n kontin tiedosto-oikeudet
  apigw/Dockerfile
Labels: tech

#6159 Lisätty tuki palveluohjauksen sisäisille liitteille hakemuksilla
  frontend/src/employee-frontend/components/application-page/ApplicationEditView.tsx
  frontend/src/employee-frontend/components/application-page/ApplicationReadView.tsx
  frontend/src/lib-common/generated/api-types/attachment.ts
  frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
  service/src/main/kotlin/fi/espoo/evaka/attachment/Attachment.kt
Labels: enhancement

#6173 Remove old frontend files bucket
  .github/workflows/build.yml
Labels: no-changelog

#6172 Käyttäjien haku roolien mukaan
  frontend/src/employee-frontend/components/employees/EmployeesPage.tsx
  frontend/src/employee-frontend/components/employees/queries.ts
  frontend/src/lib-common/generated/api-types/pis.ts
  frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
  service/src/integrationTest/kotlin/fi/espoo/evaka/pis/controller/EmployeeControllerSearchIntegrationTest.kt
  service/src/main/kotlin/fi/espoo/evaka/pis/EmployeeQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/pis/controllers/EmployeeController.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/auth/UserRole.kt
Labels: enhancement

#6171 Lisätty palveluohjaukselle mahdollisuus muuttaa hakemuksen hakutoiveiden järjestystä
  frontend/src/employee-frontend/components/application-page/ApplicationEditView.tsx
  frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
Labels: enhancement

#6189 Lisätään toiset huoltajat ehdottavan esiopetuksen hakemuksiin
  service/src/main/kotlin/fi/espoo/evaka/application/PlacementToolService.kt
Labels: bug

#6191 Korjataan OWASP-tietoturvahälyjä päivityksillä
  service/build.gradle.kts
  service/evaka-bom/build.gradle.kts
  service/gradle/libs.versions.toml
Labels: dependencies

#6175 Englanninkielisen hakemuksen palveluntarpeen nimet käännetty englanniksi
  frontend/src/lib-customizations/defaults/citizen/i18n/en.tsx
Labels: bug

#6192 Kirjastopäivityksiä (Gradle, HikariCP, CXF, Tomcat)
  keycloak/dummy-suomifi/gradle/wrapper/gradle-wrapper.jar
  keycloak/dummy-suomifi/gradle/wrapper/gradle-wrapper.properties
  keycloak/dummy-suomifi/gradlew
  keycloak/dummy-suomifi/gradlew.bat
  service/build.gradle.kts
  service/evaka-bom/build.gradle.kts
  service/gradle/wrapper/gradle-wrapper.jar
  service/gradle/wrapper/gradle-wrapper.properties
  service/gradlew
  service/gradlew.bat
  service/owasp-suppressions.xml
Labels: dependencies

#6177 Arvopäätöksien hakuun uusi hakuehto: ei avoimia tuloselvityksiä
  frontend/src/lib-common/generated/api-types/invoicing.ts
  service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/data/VoucherValueDecisionQueriesTest.kt
  service/src/main/kotlin/fi/espoo/evaka/invoicing/controller/VoucherValueDecisionController.kt
  service/src/main/kotlin/fi/espoo/evaka/invoicing/data/VoucherValueDecisionQueries.kt
  service/src/test/kotlin/fi/espoo/evaka/invoicing/TestFixtures.kt
Labels: enhancement

#6176 Hakemusten lähetyksen validointi ruudunlukijalla
  frontend/src/citizen-frontend/applications/editor/unit-preference/UnitsSubSection.tsx
  frontend/src/lib-components/atoms/form/MultiSelect.tsx
  frontend/src/lib-components/molecules/MessageBoxes.tsx
Labels: enhancement

#6124 Ei sallita henkilökohtaisia mobiililaitteita muille kuin kunnallisten yksiköiden johtajille
  frontend/src/e2e-test/pages/mobile/staff-page.ts
  frontend/src/e2e-test/specs/6_mobile/staff.spec.ts
  frontend/src/employee-frontend/components/absences/StaffAttendance.tsx
  frontend/src/employee-mobile-frontend/App.tsx
  frontend/src/employee-mobile-frontend/common/BottomNavbar.tsx
  frontend/src/employee-mobile-frontend/generated/api-clients/daycare.ts
  frontend/src/employee-mobile-frontend/generated/api-clients/occupancy.ts
  frontend/src/employee-mobile-frontend/staff/PlusMinus.tsx
  frontend/src/employee-mobile-frontend/staff/StaffAttendanceEditor.tsx
  frontend/src/employee-mobile-frontend/staff/StaffPage.tsx
  frontend/src/employee-mobile-frontend/staff/api.ts
  frontend/src/employee-mobile-frontend/staff/utils.ts
  frontend/src/employee-mobile-frontend/units/UnitList.tsx
  frontend/src/lib-common/generated/api-types/attendance.ts
  frontend/src/lib-common/generated/api-types/daycare.ts
  frontend/src/lib-common/generated/api-types/occupancy.ts
  service/src/integrationTest/kotlin/fi/espoo/evaka/daycare/controllers/UnitAclControllerIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/daycare/service/StaffAttendanceServiceIntegrationTest.kt
  service/src/main/kotlin/fi/espoo/evaka/attendance/MobileUnitController.kt
  service/src/main/kotlin/fi/espoo/evaka/daycare/UnitAcl.kt
  service/src/main/kotlin/fi/espoo/evaka/daycare/controllers/StaffAttendanceController.kt
  service/src/main/kotlin/fi/espoo/evaka/daycare/controllers/UnitAclController.kt
  service/src/main/kotlin/fi/espoo/evaka/daycare/service/StaffAttendanceService.kt
  service/src/main/kotlin/fi/espoo/evaka/occupancy/OccupancyController.kt
  service/src/main/kotlin/fi/espoo/evaka/pairing/MobileDeviceQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/async/AsyncJob.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/auth/AuthenticatedUser.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/security/Action.kt
  service/src/main/resources/db/migration/V478__delete_disallowed_personal_mobile_pairings.sql
  service/src/main/resources/db/migration/V479__drop_staff_attendance_count_other.sql
  service/src/main/resources/migrations.txt
Labels: enhancement

#6167 Lisätään lähettäjän nimi sähköpostinotifikaatioihin eVaka-viesteistä
  service/src/integrationTest/kotlin/fi/espoo/evaka/messaging/MessageNotificationEmailServiceIntegrationTest.kt
  service/src/main/kotlin/fi/espoo/evaka/emailclient/EvakaEmailMessageProvider.kt
  service/src/main/kotlin/fi/espoo/evaka/emailclient/IEmailMessageProvider.kt
  service/src/main/kotlin/fi/espoo/evaka/messaging/MessageAccountQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/messaging/MessageNotificationEmailService.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/dev/DevApi.kt
Labels: enhancement

#6174 Lisätään maksatushakuun käyttöikeustarkastus ja audit-lokitus
  frontend/src/lib-common/generated/action.d.ts
  service/src/main/kotlin/fi/espoo/evaka/Audit.kt
  service/src/main/kotlin/fi/espoo/evaka/invoicing/controller/PaymentController.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/security/Action.kt
Labels: bug
