Repository espoon-voltti/evaka, pull requests merged in 2024-04, with the labels that each got.

#5005 Bugikorjaus vasumigraatioon
  service/src/integrationTest/kotlin/fi/espoo/evaka/vasu/DocumentMigratorTest.kt
  service/src/main/kotlin/fi/espoo/evaka/vasu/DocumentMigrator.kt
Labels: bug

#4974 Keycloakin päivitys versioon 24.0.2
  keycloak/Dockerfile
  keycloak/evaka-logging/pom.xml
  keycloak/evaka-review-profile/pom.xml
Labels: dependencies

#4971 Yarnin päivitys versioon 4.1.1
  apigw/.yarn/releases/yarn-4.0.1.cjs
  apigw/.yarn/releases/yarn-4.1.1.cjs
  apigw/.yarnrc.yml
  apigw/package.json
  apigw/yarn.lock
  frontend/.yarn/releases/yarn-4.0.1.cjs
  frontend/.yarn/releases/yarn-4.1.1.cjs
  frontend/.yarnrc.yml
  frontend/package.json
  frontend/yarn.lock
Labels: dependencies

#4968 Näytetään yksikön kalenterissa puuttuva lomavarausindikaatio vain jos yksiköllä on varaukset päällä
  service/src/integrationTest/kotlin/fi/espoo/evaka/absence/AbsenceServiceIntegrationTest.kt
  service/src/main/kotlin/fi/espoo/evaka/absence/AbsenceService.kt
Labels: bug

#4998 Kun tuleva sijoitus poistetaan poistetaan ainoastaan siihen osuvat varaukset
  service/src/integrationTest/kotlin/fi/espoo/evaka/placement/PlacementControllerIntegrationTest.kt
  service/src/main/kotlin/fi/espoo/evaka/placement/PlacementController.kt
Labels: bug

#4967 List voucher values for each service need
  frontend/src/employee-frontend/components/finance-basics/PlacementTypeItem.tsx
  frontend/src/employee-frontend/components/finance-basics/ServiceNeedItem.tsx
  frontend/src/employee-frontend/components/finance-basics/ServiceNeedsSection.tsx
  frontend/src/employee-frontend/components/finance-basics/queries.ts
  frontend/src/employee-frontend/generated/api-clients/invoicing.ts
  frontend/src/lib-common/generated/action.d.ts
  frontend/src/lib-common/generated/api-types/invoicing.ts
  frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
  service/src/main/kotlin/fi/espoo/evaka/Audit.kt
  service/src/main/kotlin/fi/espoo/evaka/invoicing/controller/FinanceBasicsController.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/security/Action.kt
Labels: enhancement

#4996 Muutoksia työntekijöiden deaktivointiin
  frontend/src/lib-components/i18n.tsx
  frontend/src/lib-components/molecules/modals/LoginErrorModal.tsx
  frontend/src/lib-components/utils/TestContextProvider.tsx
  frontend/src/lib-customizations/defaults/components/i18n/en.tsx
  frontend/src/lib-customizations/defaults/components/i18n/fi.tsx
  frontend/src/lib-customizations/defaults/components/i18n/sv.tsx
  service/src/integrationTest/kotlin/fi/espoo/evaka/daycare/controllers/UnitAclControllerIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/pis/InactiveEmployeesRoleResetIntegrationTest.kt
  service/src/main/kotlin/fi/espoo/evaka/pis/EmployeeQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/pis/SystemController.kt
  service/src/main/kotlin/fi/espoo/evaka/pis/controllers/EmployeeController.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/job/ScheduledJobs.kt
Labels: enhancement

#4993 Näytetään viestin vastaanottajamäärä ja varoitetaan jos enemmän kuin kaksi
  frontend/src/e2e-test/pages/employee/messages/messages-page.ts
  frontend/src/e2e-test/specs/7_messaging/messaging-by-staff.spec.ts
  frontend/src/e2e-test/specs/7_messaging/messaging.spec.ts
  frontend/src/e2e-test/specs/7_messaging/municipal-messaging.spec.ts
  frontend/src/employee-frontend/components/messages/MessageEditor.tsx
  frontend/src/employee-frontend/components/messages/MessagesPage.tsx
  frontend/src/employee-frontend/components/messages/queries.ts
  frontend/src/employee-frontend/generated/api-clients/messaging.ts
  frontend/src/employee-frontend/query.ts
  frontend/src/employee-mobile-frontend/generated/api-clients/messaging.ts
  frontend/src/lib-common/generated/api-types/messaging.ts
  frontend/src/lib-components/i18n.tsx
  frontend/src/lib-components/utils/TestContextProvider.tsx
  frontend/src/lib-customizations/defaults/components/i18n/en.tsx
  frontend/src/lib-customizations/defaults/components/i18n/fi.tsx
  frontend/src/lib-customizations/defaults/components/i18n/sv.tsx
  frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
  service/src/integrationTest/kotlin/fi/espoo/evaka/messaging/MessageIntegrationTest.kt
  service/src/main/kotlin/fi/espoo/evaka/Audit.kt
  service/src/main/kotlin/fi/espoo/evaka/messaging/MessageController.kt
Labels: enhancement

#5002 HTTP-pyyntöjen rate limittien kasvatus ja parempi dokumentointi
  frontend/proxy/files/etc/nginx/conf.d/nginx.conf.template
Labels: tech

#5006 Korjauksia uuteen Varda-integraatioon (ei vielä käytössä)
  service/src/main/kotlin/fi/espoo/evaka/varda/new/Varda.kt
  service/src/main/kotlin/fi/espoo/evaka/varda/new/VardaClient.kt
  service/src/main/kotlin/fi/espoo/evaka/varda/new/VardaQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/varda/new/VardaUpdateServiceNew.kt
Labels: tech

#5003 Uudet dokumenttityypit: Vasu ja leops
  frontend/src/employee-frontend/components/child-documents/statuses.ts
  frontend/src/lib-common/generated/api-types/document.ts
  frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
  service/src/main/kotlin/fi/espoo/evaka/document/DocumentTemplate.kt
Labels: enhancement

#5004 Skripti muutoslokin muodostamiseksi
  .github/workflows/release.yml
  bin/changelog.js
Labels: tech

#5021 Korjauksia automaattiseen julkaisuajoon
  .github/workflows/release.yml
Labels: tech

#5026 Lisätty vasu- ja leops- `document_type`:t
  service/src/main/resources/db/migration/V396__vasu_leops_types.sql
  service/src/main/resources/migrations.txt
Labels: bug, no-changelog

#5022 Poistetaan sunnuntain ajastettu build
  .github/workflows/build.yml
Labels: no-changelog

#5028 Päivitä `PULL_REQUEST_TEMPLATE.md`
  .github/PULL_REQUEST_TEMPLATE.md
Labels: no-changelog

#5027 Jätetään `no-changelog`-labeloidut PR:t pois muutoslokilta
  bin/changelog.js
Labels: tech

#5025 Julkaisu-workflown hienosäätöä
  .github/workflows/release.yml
Labels: no-changelog

#5008 Korjaus sopimuspäivälaskurin näkymiseen
  frontend/src/citizen-frontend/generated/api-clients/children.ts
  service/codegen/src/main/kotlin/evaka/codegen/api/Config.kt
Labels: bug

#4970 Keycloak-lokituskoodin parannuksia
  keycloak/evaka-logging/pom.xml
  keycloak/evaka-logging/src/main/java/com/espoo/keycloak/events/EvakaLoggingEventListenerProvider.java
  keycloak/evaka-logging/src/main/java/com/espoo/keycloak/events/EvakaLoggingEventListenerProviderFactory.java
  keycloak/evaka-logging/src/main/java/com/espoo/keycloak/events/PreprocessMode.java
  keycloak/evaka-logging/src/main/java/com/espoo/keycloak/events/Preprocessor.java
  keycloak/evaka-logging/src/test/java/com/espoo/keycloak/events/PreprocessorTest.java
Labels: tech

#5023 Raportti ruokalijoiden määrästä
  frontend/src/employee-frontend/App.tsx
  frontend/src/employee-frontend/components/Reports.tsx
  frontend/src/employee-frontend/components/reports/MealReport.tsx
  frontend/src/employee-frontend/components/reports/queries.ts
  frontend/src/employee-frontend/generated/api-clients/reports.ts
  frontend/src/employee-mobile-frontend/generated/api-clients/reports.ts
  frontend/src/lib-common/generated/action.d.ts
  frontend/src/lib-common/generated/api-types/reports.ts
  frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
  frontend/src/lib-icons/fontawesome.d.ts
  frontend/src/lib-icons/free-icons.ts
  frontend/src/lib-icons/pro-icons.ts
  service/src/main/kotlin/fi/espoo/evaka/Audit.kt
  service/src/main/kotlin/fi/espoo/evaka/placement/PlacementType.kt
  service/src/main/kotlin/fi/espoo/evaka/reports/MealReportController.kt
  service/src/main/kotlin/fi/espoo/evaka/reports/ReportPermissions.kt
  service/src/main/kotlin/fi/espoo/evaka/reservations/AttendanceReservationController.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/security/Action.kt
Labels: enhancement

#5035 Lisätty lapsen ID päätöksen hyväksymis/hylkäämis lokiviestiin
  service/src/main/kotlin/fi/espoo/evaka/application/ApplicationStateService.kt
Labels: tech

#5030 Hakemusten/päätösten toisten huoltajien käsitteen iso remontti
  frontend/src/citizen-frontend/applications/editor/ApplicationEditor.tsx
  frontend/src/citizen-frontend/applications/editor/ApplicationFormClub.tsx
  frontend/src/citizen-frontend/applications/editor/ApplicationFormDaycare.tsx
  frontend/src/citizen-frontend/applications/editor/ApplicationFormPreschool.tsx
  frontend/src/citizen-frontend/applications/editor/validations.ts
  frontend/src/e2e-test/dev-api/fixtures.ts
  frontend/src/e2e-test/dev-api/types.ts
  frontend/src/e2e-test/generated/api-types.ts
  frontend/src/lib-common/api-types/application/ApplicationFormData.ts
  frontend/src/lib-common/generated/api-types/application.ts
  frontend/src/lib-common/generated/api-types/decision.ts
  service/src/integrationTest/kotlin/fi/espoo/evaka/TestFixtures.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/application/ApplicationOtherGuardianIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/application/ApplicationStateServiceIntegrationTests.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/application/GetApplicationIntegrationTests.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/decision/DecisionCreationIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/pdfgen/PdfGeneratorTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/pis/InactivePeopleCleanupIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/pis/PersonIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/reports/ManualDuplicationReportTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/shared/job/ScheduledJobsTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/test/TestData.kt
  service/src/main/kotlin/fi/espoo/evaka/absence/AbsenceQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/application/Application.kt
  service/src/main/kotlin/fi/espoo/evaka/application/ApplicationControllerV2.kt
  service/src/main/kotlin/fi/espoo/evaka/application/ApplicationQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/application/ApplicationStateService.kt
  service/src/main/kotlin/fi/espoo/evaka/application/DecisionMessageProcessor.kt
  service/src/main/kotlin/fi/espoo/evaka/assistance/AssistanceQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/daycare/DaycareQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/decision/Decision.kt
  service/src/main/kotlin/fi/espoo/evaka/decision/DecisionQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/decision/DecisionService.kt
  service/src/main/kotlin/fi/espoo/evaka/invoicing/data/FeeDecisionQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/koski/KoskiQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/messaging/MessagePushNotifications.kt
  service/src/main/kotlin/fi/espoo/evaka/pis/InactivePeopleCleanup.kt
  service/src/main/kotlin/fi/espoo/evaka/reservations/MissingReservationsReminders.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/db/Database.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/dev/DataInitializers.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/dev/DevApi.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/security/AccessControl.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/security/AccessControlQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/security/actionrule/HasGlobalRole.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/security/actionrule/HasGroupRole.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/security/actionrule/HasUnitRole.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/security/actionrule/IsCitizen.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/security/actionrule/IsEmployee.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/security/actionrule/IsMobile.kt
  service/src/main/resources/WEB-INF/templates/shared/layout.html
  service/src/main/resources/db/migration/R__application_view.sql
  service/src/main/resources/db/migration/V397__document_contains_contact_info.sql
  service/src/main/resources/db/migration/V398__application_other_guardian.sql
  service/src/main/resources/migrations.txt
Labels: enhancement

#5040 Korjaus tietokantamigraatioon V398
  service/src/main/resources/db/migration/V398__application_other_guardian.sql
Labels: no-changelog

#5024 Palveluntarvetyypin voimassaoloaika
  frontend/src/citizen-frontend/applications/editor/ApplicationFormClub.tsx
  frontend/src/citizen-frontend/applications/editor/ApplicationFormDaycare.tsx
  frontend/src/citizen-frontend/applications/editor/service-need/ServiceNeedSection.tsx
  frontend/src/citizen-frontend/applications/editor/service-need/ServiceTimeSubSectionDaycare.tsx
  frontend/src/citizen-frontend/applications/editor/service-need/ServiceTimeSubSectionPreschool.tsx
  frontend/src/citizen-frontend/applications/editor/validations.ts
  frontend/src/citizen-frontend/generated/api-clients/serviceneed.ts
  frontend/src/e2e-test/dev-api/fixtures.ts
  frontend/src/e2e-test/pages/employee/child-information.ts
  frontend/src/e2e-test/specs/5_employee/service-need.spec.ts
  frontend/src/employee-frontend/components/child-information/placements/ServiceNeeds.tsx
  frontend/src/employee-frontend/components/child-information/placements/service-needs/ServiceNeedEditorRow.tsx
  frontend/src/employee-frontend/generated/api-clients/serviceneed.ts
  frontend/src/employee-mobile-frontend/generated/api-clients/serviceneed.ts
  frontend/src/lib-common/date-range.spec.ts
  frontend/src/lib-common/date-range.ts
  frontend/src/lib-common/generated/api-types/serviceneed.ts
  frontend/src/lib-customizations/defaults/citizen/i18n/en.tsx
  frontend/src/lib-customizations/defaults/citizen/i18n/fi.tsx
  frontend/src/lib-customizations/defaults/citizen/i18n/sv.tsx
  frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
  frontend/src/lib-customizations/espoo/featureFlags.tsx
  frontend/src/lib-customizations/types.d.ts
  service/src/integrationTest/kotlin/fi/espoo/evaka/ServiceNeedTestFixtures.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/TestFixtures.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/application/ApplicationStateServiceIntegrationTests.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/espoo/bi/EspooBiTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/serviceneed/ServiceNeedIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/shared/config/SharedIntegrationTestConfig.kt
  service/src/main/kotlin/fi/espoo/evaka/EspooConfig.kt
  service/src/main/kotlin/fi/espoo/evaka/application/ApplicationStateService.kt
  service/src/main/kotlin/fi/espoo/evaka/serviceneed/ServiceNeed.kt
  service/src/main/kotlin/fi/espoo/evaka/serviceneed/ServiceNeedQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/FeatureConfig.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/dev/DataInitializers.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/dev/DevApi.kt
  service/src/main/resources/db/migration/V399__service_need_option_validity_period.sql
  service/src/main/resources/dev-data/service-need-options.sql
  service/src/main/resources/migrations.txt
  service/src/test/kotlin/fi/espoo/evaka/invoicing/service/generator/FeeDecisionGeneratorV2Test.kt
  service/src/test/kotlin/fi/espoo/evaka/invoicing/service/generator/VoucherValueDecisionGeneratorV2Test.kt
Labels: breaking

#5042 Korjaus kääntäjävaroituksiin + kaikki varoitukset on jatkossa virheitä
  service/build.gradle.kts
  service/src/integrationTest/kotlin/fi/espoo/evaka/absence/AbsenceServiceIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/childimages/ChildImageTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/daycare/controllers/DaycareControllerIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/holidayperiod/HolidayPeriodControllerIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/data/FeeAlterationQueriesTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/data/FeeDecisionQueriesTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/data/IncomeQueriesTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/service/FinanceDecisionGeneratorIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/service/VoucherValueDecisionGeneratorIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/placement/PlacementControllerIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/reports/ServiceVoucherValueUnitReportTest.kt
Labels: tech

#5052 Korjaus käyttöliittymän kääntämiseen
  frontend/src/citizen-frontend/applications/editor/ApplicationFormDaycare.tsx
Labels: tech

#5029 Testi lisätty että uuden asiakkaan tulotietomuistutus näkyy profiilisivulla
  frontend/src/e2e-test/specs/5_employee/income.spec.ts
Labels: tech, no-changelog

#5041 Lisätty puuttuvat DatabaseEnum-toteutukset
  service/src/main/kotlin/fi/espoo/evaka/assistance/Assistance.kt
  service/src/main/kotlin/fi/espoo/evaka/assistanceneed/preschooldecision/AssistanceNeedPreschoolDecision.kt
  service/src/main/kotlin/fi/espoo/evaka/dailyservicetimes/DailyServiceTimes.kt
  service/src/main/kotlin/fi/espoo/evaka/decision/DecisionStatus.kt
  service/src/main/kotlin/fi/espoo/evaka/document/DocumentTemplate.kt
  service/src/main/kotlin/fi/espoo/evaka/document/childdocument/ChildDocument.kt
  service/src/main/kotlin/fi/espoo/evaka/holidayperiod/HolidayQuestionnaires.kt
  service/src/main/kotlin/fi/espoo/evaka/incomestatement/IncomeStatement.kt
  service/src/main/kotlin/fi/espoo/evaka/incomestatement/IncomeStatementQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/invoicing/domain/FeeAlterations.kt
  service/src/main/kotlin/fi/espoo/evaka/invoicing/domain/FeeDecisions.kt
  service/src/main/kotlin/fi/espoo/evaka/invoicing/domain/Incomes.kt
  service/src/main/kotlin/fi/espoo/evaka/invoicing/domain/VoucherValueDecisions.kt
  service/src/main/kotlin/fi/espoo/evaka/invoicing/service/IncomeQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/messaging/Message.kt
  service/src/main/kotlin/fi/espoo/evaka/note/child/daily/ChildDailyNote.kt
  service/src/main/kotlin/fi/espoo/evaka/pairing/Pairing.kt
  service/src/main/kotlin/fi/espoo/evaka/placement/PlacementPlan.kt
  service/src/main/kotlin/fi/espoo/evaka/reports/ServiceVoucherValueReport.kt
  service/src/main/kotlin/fi/espoo/evaka/setting/SettingType.kt
  service/src/main/kotlin/fi/espoo/evaka/user/EvakaUser.kt
  service/src/main/kotlin/fi/espoo/evaka/vasu/Vasu.kt
  service/src/main/resources/db/migration/V400__drop_child_consent_type.sql
  service/src/main/resources/migrations.txt
Labels: tech

#5034 Parannuksia tietokanta-API:in: execute/executeBatch/prepareBatch
  service/src/integrationTest/kotlin/fi/espoo/evaka/TestFixtures.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/absence/AbsenceServiceIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/daycare/controllers/ChildrenControllerIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/daycare/dao/CaretakerQueriesIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/daycare/dao/ChildDAOIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/daycare/service/CaretakerServiceIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/FeeDecisionIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/VoucherValueDecisionIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/service/FeeDecisionGeneratorIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/service/InvoiceGeneratorIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/koski/KoskiIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/pis/InactivePeopleCleanupIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/pis/controller/PersonControllerIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/reports/ServiceVoucherValueUnitReportTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/serviceneed/ServiceNeedQueriesTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/shared/auth/AclIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/shared/db/DatabaseTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/shared/db/PGUtilsTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/shared/security/ApplicationAccessControlTest.kt
  service/src/main/kotlin/fi/espoo/evaka/absence/AbsenceQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/assistanceaction/AssistanceActionQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/assistanceneed/decision/AssistanceNeedDecisionQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/assistanceneed/preschooldecision/AssistanceNeedPreschoolDecisionQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/calendarevent/CalendarEventQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/decision/DecisionDraftService.kt
  service/src/main/kotlin/fi/espoo/evaka/document/childdocument/ChildDocumentQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/holidayperiod/HolidayQuestionnaireQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/invoicing/data/FeeDecisionQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/invoicing/data/InvoiceQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/invoicing/data/PaymentQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/invoicing/data/VoucherValueDecisionQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/invoicing/domain/FeeDecisions.kt
  service/src/main/kotlin/fi/espoo/evaka/invoicing/service/InvoiceService.kt
  service/src/main/kotlin/fi/espoo/evaka/messaging/MessageQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/pis/EmployeeQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/pis/controllers/FamilyController.kt
  service/src/main/kotlin/fi/espoo/evaka/pis/service/GuardianQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/placement/PlacementPlanQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/reports/ServiceVoucherValueReport.kt
  service/src/main/kotlin/fi/espoo/evaka/reservations/ReservationQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/setting/SettingQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/auth/AclQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/db/Database.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/db/Predicate.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/dev/DataInitializers.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/dev/DevApi.kt
  service/src/main/kotlin/fi/espoo/evaka/titania/TitaniaQueries.kt
Labels: tech

#5055 Siiretään Ruokailijamäärät-raportti feature flagin taakse
  frontend/src/employee-frontend/components/Reports.tsx
Labels: bug

#5036 Espoo: päivityksiä päätösten teksteihin
  service/src/main/resources/WEB-INF/templates/club/decision.properties
  service/src/main/resources/WEB-INF/templates/fee-decision/voucher-value-decision.properties
  service/src/main/resources/WEB-INF/templates/fee-decision/voucher-value-decision_sv.properties
  service/src/main/resources/WEB-INF/templates/shared/daycare-correction.html
  service/src/main/resources/WEB-INF/templates/shared/daycare-correction_fi.properties
  service/src/main/resources/WEB-INF/templates/shared/daycare-correction_sv.properties
Labels: no-changelog

#5054 Piilotetaan hakemuksen tuen tarpeen kuvaus toiselta huoltajalta
  frontend/src/citizen-frontend/applications/editor/verification/ServiceNeedSection.tsx
  frontend/src/e2e-test/pages/citizen/citizen-applications.ts
  frontend/src/e2e-test/specs/0_citizen/citizen-daycare-application.spec.ts
  service/src/main/kotlin/fi/espoo/evaka/application/ApplicationControllerCitizen.kt
Labels: enhancement

#5056 Yksikköeditori kadottaa muutokset välilehteä vaihtaessa
  frontend/src/employee-frontend/components/unit/unit-details/UnitEditor.tsx
Labels: bug

#5058 Korjaus henkilökunnan työvuorojen automaattikatkaisuun
  service/src/integrationTest/kotlin/fi/espoo/evaka/attendance/RealtimeStaffAttendanceQueriesTest.kt
  service/src/main/kotlin/fi/espoo/evaka/attendance/StaffAttendanceQueries.kt
Labels: bug

#5063 Korjauksia Varda-integraatioon
  service/src/integrationTest/kotlin/fi/espoo/evaka/varda/new/VardaUpdateServiceIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/varda/new/VardaUpdaterIntegrationTest.kt
  service/src/main/kotlin/fi/espoo/evaka/varda/new/VardaQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/varda/new/VardaUpdateServiceNew.kt
Labels: no-changelog

#5057 Piilotetaan viestin peruutustoiminto mahdollista tulevaa poistoa varten
  frontend/src/e2e-test/pages/employee/messages/messages-page.ts
  frontend/src/e2e-test/specs/7_messaging/messaging.spec.ts
  frontend/src/e2e-test/specs/7_messaging/service-worker-messaging.spec.ts
  frontend/src/employee-frontend/components/messages/MessageContext.tsx
  frontend/src/employee-frontend/components/messages/MessagesPage.tsx
Labels: enhancement

#4933 Lapsen muut huoltajat ja sijaishuoltajat saa nähdä hakemukset/päätökset
  docs/diagrams/src/evaka-application.puml
  frontend/src/citizen-frontend/applications/ChildApplicationsBlock.tsx
  frontend/src/citizen-frontend/decisions/decision-response-page/DecisionResponse.tsx
  frontend/src/citizen-frontend/decisions/decision-response-page/DecisionResponseList.tsx
  frontend/src/citizen-frontend/decisions/decisions-page/ApplicationDecision.tsx
  frontend/src/citizen-frontend/decisions/decisions-page/Decisions.tsx
  frontend/src/citizen-frontend/generated/api-clients/application.ts
  frontend/src/e2e-test/dev-api/fixtures.ts
  frontend/src/e2e-test/dev-api/index.ts
  frontend/src/e2e-test/specs/0_citizen/citizen-applications-list.spec.ts
  frontend/src/e2e-test/specs/0_citizen/citizen-decisions.spec.ts
  frontend/src/lib-common/generated/action.d.ts
  frontend/src/lib-common/generated/api-types/application.ts
  service/codegen/src/main/kotlin/evaka/codegen/actionenum/Definitions.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/decision/DecisionCreationIntegrationTest.kt
  service/src/main/kotlin/fi/espoo/evaka/application/Application.kt
  service/src/main/kotlin/fi/espoo/evaka/application/ApplicationControllerCitizen.kt
  service/src/main/kotlin/fi/espoo/evaka/decision/DecisionQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/security/Action.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/security/actionrule/IsCitizen.kt
Labels: enhancement

#5060 Turvakieltoesto ei koske päätöstiedostoja joissa ei ole henkilöiden osoitetietoja
  frontend/src/lib-common/generated/api-types/invoicing.ts
  service/src/integrationTest/kotlin/fi/espoo/evaka/decision/DecisionControllerIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/FeeDecisionIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/Helpers.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/VoucherValueDecisionIntegrationTest.kt
  service/src/main/kotlin/fi/espoo/evaka/decision/DecisionController.kt
  service/src/main/kotlin/fi/espoo/evaka/invoicing/controller/FeeDecisionController.kt
  service/src/main/kotlin/fi/espoo/evaka/invoicing/controller/VoucherValueDecisionController.kt
  service/src/main/kotlin/fi/espoo/evaka/invoicing/data/FeeDecisionQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/invoicing/domain/FeeDecisions.kt
  service/src/main/kotlin/fi/espoo/evaka/invoicing/domain/VoucherValueDecisions.kt
  service/src/test/kotlin/fi/espoo/evaka/invoicing/service/PdfGenerationTest.kt
Labels: enhancement

#5059 Henkilökunnan läsnäolokirjauksen kasvatusvastuullisuuden parempi oletusarvo
  frontend/src/employee-frontend/components/unit/unit-reservations/StaffAttendanceDetailsModal.tsx
  frontend/src/employee-frontend/components/unit/unit-reservations/StaffAttendanceTable.tsx
Labels: enhancement

#5065 Espoo: huojennuspäätöksen tekstipäivitys
  service/src/main/resources/WEB-INF/templates/fee-decision/voucher-value-decision.properties
  service/src/main/resources/WEB-INF/templates/fee-decision/voucher-value-decision_sv.properties
Labels: no-changelog

#5068 Kytketään päälle eslint-sääntö no-constant-binary-expression
  frontend/package.json
  frontend/src/lib-common/api-types/application/ApplicationFormData.ts
Labels: tech

#5072 Pinkoodin lukittu-tila ei voi olla null
  service/src/main/resources/db/migration/V405__employee_pin_locked_not_null.sql
  service/src/main/resources/migrations.txt
Labels: tech

#5080 Näytetään uuden Varda-integraation virheet Varda-virheet -raportilla
  frontend/src/employee-frontend/components/reports/VardaErrors.tsx
  frontend/src/lib-common/generated/api-types/reports.ts
  service/src/integrationTest/kotlin/fi/espoo/evaka/varda/new/VardaUpdaterIntegrationTest.kt
  service/src/main/kotlin/fi/espoo/evaka/reports/VardaErrorsReport.kt
  service/src/main/kotlin/fi/espoo/evaka/varda/VardaController.kt
  service/src/main/kotlin/fi/espoo/evaka/varda/new/VardaQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/varda/new/VardaUpdateServiceNew.kt
  service/src/main/resources/db/migration/V406__varda_state_error.sql
  service/src/main/resources/migrations.txt
Labels: enhancement

#5083 Haetaan enemmän PR:iä julkaisua luodessa
  .github/workflows/release.yml
Labels: no-changelog

#5082 Pääkäyttäjä voi poistaa käyttäjän henkilökohtaisen mobiililaitteen parituksen
  frontend/src/employee-frontend/components/employees/EmployeePage.tsx
  frontend/src/employee-frontend/components/employees/queries.ts
  frontend/src/lib-common/generated/api-types/pis.ts
  frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
  service/src/integrationTest/kotlin/fi/espoo/evaka/pis/InactiveEmployeesRoleResetIntegrationTest.kt
  service/src/main/kotlin/fi/espoo/evaka/pis/EmployeeQueries.kt
Labels: enhancement

#5070 Ladataan DataDog agent gradlella
  service/Dockerfile
  service/build.gradle.kts
  service/gradle/libs.versions.toml
Labels: tech

#5069 Vaihdetaan evaka-service käyttämään Azul Zulu OpenJDK JRE nykyisen Eclipse Temurin JDK:n sijaan (koskee vain ydintä)
  service/Dockerfile
Labels: tech

#5084 Korjaus Keycloak-rekisteröintiin
  keycloak/evaka-review-profile/src/main/java/com/espoo/keycloak/authenticator/EvakaReviewProfileAuthenticator.java
  keycloak/evaka-review-profile/src/main/java/com/espoo/keycloak/authenticator/EvakaReviewProfileAuthenticator.java.diff
  keycloak/evaka-review-profile/src/main/java/com/espoo/keycloak/authenticator/EvakaReviewProfileAuthenticatorFactory.java.diff
Labels: bug
