Repository espoon-voltti/evaka, pull requests merged in 2024-05, with the labels that each got.

#5085 Bugikorjaus tyhjään request param listaan ja lint/validaatiosääntö codegeniin
  frontend/src/citizen-frontend/applications/queries.ts
  frontend/src/citizen-frontend/generated/api-clients/serviceneed.ts
  frontend/src/employee-frontend/generated/api-clients/attendance.ts
  frontend/src/employee-frontend/generated/api-clients/serviceneed.ts
  frontend/src/employee-mobile-frontend/generated/api-clients/attendance.ts
  frontend/src/employee-mobile-frontend/generated/api-clients/serviceneed.ts
  frontend/src/employee-mobile-frontend/units/queries.ts
  service/codegen/src/main/kotlin/evaka/codegen/api/Controllers.kt
  service/src/main/kotlin/fi/espoo/evaka/attendance/MobileUnitController.kt
  service/src/main/kotlin/fi/espoo/evaka/serviceneed/ServiceNeedController.kt
Labels: bug

#5090 React-varoituksen korjaus
  frontend/src/lib-components/atoms/form/TextArea.tsx
Labels: tech

#5086 Tieto erityisruokavalioista ruokailijaraporttiin
  frontend/src/employee-frontend/components/reports/MealReport.tsx
  frontend/src/employee-frontend/components/unit/unit-details/UnitEditor.tsx
  frontend/src/lib-common/generated/api-types/daycare.ts
  frontend/src/lib-common/generated/api-types/reports.ts
  frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
  service/src/integrationTest/kotlin/fi/espoo/evaka/daycare/DaycareEditIntegrationTest.kt
  service/src/main/kotlin/fi/espoo/evaka/daycare/CareArea.kt
  service/src/main/kotlin/fi/espoo/evaka/daycare/DaycareQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/reports/MealReportController.kt
  service/src/main/kotlin/fi/espoo/evaka/reports/MealReportQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/reports/MealReportUtil.kt
  service/src/test/kotlin/fi/espoo/evaka/reports/MealReportTests.kt
Labels: enhancement

#5088 Raakaraportti katsoo tuen tasoa vakassa ja tukitoimia nyt oikein
  service/src/main/kotlin/fi/espoo/evaka/reports/RawReport.kt
Labels: bug

#5081 Korvataan vanhat sekavat FI/SV- kielienumit yhdellä OfficialLanguage-enumilla
  frontend/src/e2e-test/dev-api/index.ts
  frontend/src/e2e-test/generated/api-types.ts
  frontend/src/employee-frontend/components/child-information/assistance-need/decision/AssistanceNeedDecisionEditPage.tsx
  frontend/src/employee-frontend/components/child-information/assistance-need/decision/AssistanceNeedPreschoolDecisionEditPage.tsx
  frontend/src/employee-frontend/components/document-templates/template-editor/TemplateContentEditor.tsx
  frontend/src/employee-frontend/components/document-templates/template-editor/TemplateModal.tsx
  frontend/src/employee-frontend/components/vasu/components/RadioGroupQuestion.tsx
  frontend/src/employee-frontend/components/vasu/components/RadioGroupQuestionOption.tsx
  frontend/src/employee-frontend/components/vasu/templates/CreateOrEditTemplateModal.tsx
  frontend/src/lib-common/generated/api-types/assistanceneed.ts
  frontend/src/lib-common/generated/api-types/document.ts
  frontend/src/lib-common/generated/api-types/shared.ts
  frontend/src/lib-common/generated/api-types/vasu.ts
  service/src/integrationTest/kotlin/fi/espoo/evaka/assistanceneed/decision/AssistanceNeedDecisionIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/assistanceneed/decision/AssistanceNeedPreschoolDecisionIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/document/DocumentTemplateIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/espoo/bi/EspooBiTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/pdfgen/PdfGeneratorTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/reports/AssistanceNeedDecisionsReportTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/sficlient/SoapStackIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/shared/security/AssistanceNeedDecisionAccessControlTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/vasu/DocumentMigratorTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/vasu/VasuIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/vasu/VasuTemplateIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/vasu/VasuTemplateQueriesTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/vasu/VasuTemplateTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/vasu/VasuTest.kt
  service/src/main/kotlin/fi/espoo/evaka/assistanceneed/decision/AssistanceNeedDecision.kt
  service/src/main/kotlin/fi/espoo/evaka/assistanceneed/decision/AssistanceNeedDecisionService.kt
  service/src/main/kotlin/fi/espoo/evaka/assistanceneed/preschooldecision/AssistanceNeedPreschoolDecision.kt
  service/src/main/kotlin/fi/espoo/evaka/assistanceneed/preschooldecision/AssistanceNeedPreschoolDecisionQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/assistanceneed/preschooldecision/AssistanceNeedPreschoolDecisionService.kt
  service/src/main/kotlin/fi/espoo/evaka/decision/DecisionQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/decision/DecisionSendAddress.kt
  service/src/main/kotlin/fi/espoo/evaka/decision/DecisionService.kt
  service/src/main/kotlin/fi/espoo/evaka/document/DocumentTemplate.kt
  service/src/main/kotlin/fi/espoo/evaka/document/childdocument/DocumentHtmlGenerator.kt
  service/src/main/kotlin/fi/espoo/evaka/espoo/bi/EspooBiModels.kt
  service/src/main/kotlin/fi/espoo/evaka/invoicing/service/FeeDecisionService.kt
  service/src/main/kotlin/fi/espoo/evaka/invoicing/service/PdfGeneration.kt
  service/src/main/kotlin/fi/espoo/evaka/invoicing/service/VoucherValueDecisionService.kt
  service/src/main/kotlin/fi/espoo/evaka/pdfgen/PdfGenerator.kt
  service/src/main/kotlin/fi/espoo/evaka/sficlient/SfiMessagesClient.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/dev/DevApi.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/domain/Languages.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/domain/OfficialLanguage.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/message/EvakaMessageProvider.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/message/MessageProvider.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/template/EvakaTemplateProvider.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/template/ITemplateProvider.kt
  service/src/main/kotlin/fi/espoo/evaka/vasu/DocumentMigrator.kt
  service/src/main/kotlin/fi/espoo/evaka/vasu/OphQuestion.kt
  service/src/main/kotlin/fi/espoo/evaka/vasu/Vasu.kt
  service/src/main/kotlin/fi/espoo/evaka/vasu/VasuTemplate.kt
  service/src/main/kotlin/fi/espoo/evaka/vasu/VasuTemplateController.kt
  service/src/main/kotlin/fi/espoo/evaka/vasu/VasuTemplateQueries.kt
  service/src/main/resources/db/migration/V407__official_language.sql
  service/src/main/resources/migrations.txt
  service/src/test/kotlin/fi/espoo/evaka/invoicing/service/PdfGenerationTest.kt
Labels: tech

#5094 Jamix-integraatio
  frontend/src/e2e-test/dev-api/fixtures.ts
  frontend/src/e2e-test/generated/api-types.ts
  frontend/src/e2e-test/specs/7_messaging/messaging.spec.ts
  service/src/integrationTest/kotlin/fi/espoo/evaka/jamix/JamixIntegrationTest.kt
  service/src/main/kotlin/fi/espoo/evaka/EvakaEnv.kt
  service/src/main/kotlin/fi/espoo/evaka/daycare/CareArea.kt
  service/src/main/kotlin/fi/espoo/evaka/daycare/DaycareQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/jamix/JamixQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/jamix/JamixService.kt
  service/src/main/kotlin/fi/espoo/evaka/reports/MealReportUtil.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/async/AsyncJob.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/config/EnvConfig.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/dev/DataInitializers.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/dev/DevApi.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/job/ScheduledJobs.kt
  service/src/test/kotlin/fi/espoo/evaka/reports/MealReportTests.kt
Labels: enhancement

#5111 E2E-testien korjaus: käytetään vanhempaa s3mock-versiota
  compose/docker-compose.yml
Labels: no-changelog

#5112 Korjauksia Varda-integraatioon
  service/src/main/kotlin/fi/espoo/evaka/varda/VardaController.kt
  service/src/main/kotlin/fi/espoo/evaka/varda/new/VardaQueries.kt
Labels: bug

#5113 Bump @typescript-eslint/* from 7.4.0 to 7.8.0 in /frontend
  frontend/package.json
  frontend/yarn.lock
Labels: dependencies, javascript

#5114 Ei päivitetä `node`- ja `java` -major versioita automaattisesti
  .github/dependabot.yml
Labels: no-changelog

#5115 Bump nginx from 1.25.1 to 1.26.0 in /frontend
  frontend/Dockerfile
Labels: dependencies, docker

#5120 Korjaus Jamix-integraation tausta-ajoon kun customer id puuttuu
  service/src/integrationTest/kotlin/fi/espoo/evaka/jamix/JamixIntegrationTest.kt
  service/src/main/kotlin/fi/espoo/evaka/jamix/JamixQueries.kt
Labels: bug

#5095 Erillisen osoitesivun latausnappi aikuisen henkilösivun perustietoihin
  frontend/src/employee-frontend/components/person-shared/PersonDetails.tsx
  frontend/src/lib-common/generated/action.d.ts
  frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
  service/src/integrationTest/kotlin/fi/espoo/evaka/pdfgen/PdfGeneratorTest.kt
  service/src/main/kotlin/fi/espoo/evaka/Audit.kt
  service/src/main/kotlin/fi/espoo/evaka/pis/controllers/PersonController.kt
  service/src/main/kotlin/fi/espoo/evaka/pis/service/PersonService.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/security/Action.kt
  service/src/main/resources/WEB-INF/templates/address-page/address-page.html
Labels: enhancement

#5123 Jamix-integraatio: Käsitellään asiakasnumeroita
  frontend/src/e2e-test/dev-api/fixtures.ts
  frontend/src/e2e-test/generated/api-types.ts
  frontend/src/e2e-test/specs/7_messaging/messaging.spec.ts
  frontend/src/employee-frontend/components/unit/tab-groups/groups/group/GroupUpdateModal.tsx
  frontend/src/lib-common/generated/api-types/daycare.ts
  frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
  service/src/integrationTest/kotlin/fi/espoo/evaka/jamix/JamixIntegrationTest.kt
  service/src/main/kotlin/fi/espoo/evaka/daycare/DaycareGroupQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/daycare/controllers/DaycareController.kt
  service/src/main/kotlin/fi/espoo/evaka/daycare/service/DaycareService.kt
  service/src/main/kotlin/fi/espoo/evaka/jamix/JamixQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/jamix/JamixService.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/async/AsyncJob.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/dev/DataInitializers.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/dev/DevApi.kt
  service/src/main/resources/db/migration/V409__jamix_customer_number.sql
  service/src/main/resources/migrations.txt
Labels: enhancement

#5125 Migratoidaan myös lasten OPH OID:t vanhasta Varda-integraatiosta uuteen
  service/src/integrationTest/kotlin/fi/espoo/evaka/varda/new/VardaUpdateServiceIntegrationTest.kt
  service/src/main/kotlin/fi/espoo/evaka/varda/new/VardaQueries.kt
Labels: tech

#5129 Fix ktlint errors
  service/src/main/kotlin/fi/espoo/evaka/jamix/JamixService.kt
Labels: no-changelog

#5132 Korjauksia audit-lokitukseen
  service/src/main/kotlin/fi/espoo/evaka/messaging/MessageControllerCitizen.kt
  service/src/main/kotlin/fi/espoo/evaka/note/group/GroupNoteController.kt
Labels: tech

#5066 Tallennetaan ja näytetään talouden aikajanalla tieto päämiessuhteen lisääjästä/muokkaajasta
  frontend/src/employee-frontend/components/timeline/renderers.tsx
  frontend/src/employee-mobile-frontend/generated/api-clients/pis.ts
  frontend/src/employee-mobile-frontend/generated/api-clients/timeline.ts
  frontend/src/lib-common/generated/api-types/pis.ts
  frontend/src/lib-common/generated/api-types/timeline.ts
  service/src/integrationTest/kotlin/fi/espoo/evaka/dvv/DvvModificationsServiceIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/messaging/MessageReceiversIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/occupancy/OccupancyControllerIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/pedagogicaldocument/PedagogicalDocumentNotificationServiceIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/pis/controller/FamilyOverviewTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/pis/controller/ParentshipControllerIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/pis/controller/PartnershipsControllerIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/pis/dao/FamilySchemaConstraintsIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/pis/dao/ParentshipDAOIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/pis/dao/PartnershipDAOIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/pis/service/DVVBatchRefreshServiceIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/pis/service/FridgeFamilyServiceIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/pis/service/ParentshipServiceIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/timeline/TimelineControllerIntegrationTest.kt
  service/src/main/kotlin/fi/espoo/evaka/dvv/DvvModificationsService.kt
  service/src/main/kotlin/fi/espoo/evaka/pis/CreatorsAndModifiers.kt
  service/src/main/kotlin/fi/espoo/evaka/pis/ParentshipQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/pis/PartnershipQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/pis/controllers/ParentshipController.kt
  service/src/main/kotlin/fi/espoo/evaka/pis/service/FamilyInitializerService.kt
  service/src/main/kotlin/fi/espoo/evaka/pis/service/FridgeFamilyService.kt
  service/src/main/kotlin/fi/espoo/evaka/pis/service/ParentshipService.kt
  service/src/main/kotlin/fi/espoo/evaka/pis/service/PartnershipService.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/dev/DataInitializers.kt
  service/src/main/kotlin/fi/espoo/evaka/timeline/TimelineController.kt
  service/src/main/resources/db/migration/V410__parentship_meta_data.sql
  service/src/main/resources/migrations.txt
  service/src/test/kotlin/fi/espoo/evaka/vtjclient/service/persondetails/DVVPersonDetailsServiceTest.kt
Labels: enhancement

#5091 Yksikön viikkonäkymän läsnäolokalenterin UI korjaus
  frontend/src/employee-frontend/components/unit/unit-reservations/StaffAttendanceTable.tsx
Labels: bug

#5061 Yksikölle erilliset vuorohoidon aukioloajat
  frontend/src/e2e-test/pages/employee/units/unit.ts
  frontend/src/e2e-test/specs/5_employee/unit-editor.spec.ts
  frontend/src/employee-frontend/components/unit/unit-details/UnitEditor.tsx
  frontend/src/lib-common/generated/api-types/daycare.ts
  frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
  service/src/integrationTest/kotlin/fi/espoo/evaka/daycare/DaycareEditIntegrationTest.kt
  service/src/main/kotlin/fi/espoo/evaka/daycare/CareArea.kt
  service/src/main/kotlin/fi/espoo/evaka/daycare/DaycareQueries.kt
  service/src/main/resources/db/migration/V411__daycare_shiftcare_operation_times.sql
  service/src/main/resources/migrations.txt
Labels: enhancement

#5131 Laajennetaan query API:n käyttöä lapsen tiedot -sivulla
  frontend/src/employee-frontend/components/ChildInformation.tsx
  frontend/src/employee-frontend/components/child-information/Assistance.tsx
  frontend/src/employee-frontend/components/child-information/AssistanceNeedVoucherCoefficientSection.tsx
  frontend/src/employee-frontend/components/child-information/BackupCare.tsx
  frontend/src/employee-frontend/components/child-information/BackupPickup.tsx
  frontend/src/employee-frontend/components/child-information/ChildApplications.tsx
  frontend/src/employee-frontend/components/child-information/ChildDetails.tsx
  frontend/src/employee-frontend/components/child-information/ChildDocumentsSection.tsx
  frontend/src/employee-frontend/components/child-information/ChildIncome.tsx
  frontend/src/employee-frontend/components/child-information/DailyServiceTimesSection.tsx
  frontend/src/employee-frontend/components/child-information/FamilyContacts.tsx
  frontend/src/employee-frontend/components/child-information/FeeAlteration.tsx
  frontend/src/employee-frontend/components/child-information/FosterParents.tsx
  frontend/src/employee-frontend/components/child-information/GuardiansAndParents.tsx
  frontend/src/employee-frontend/components/child-information/MessageBlocklist.tsx
  frontend/src/employee-frontend/components/child-information/PedagogicalDocuments.tsx
  frontend/src/employee-frontend/components/child-information/Placements.tsx
  frontend/src/employee-frontend/components/child-information/assistance-need/decision/AssistanceNeedPreschoolDecisionEditPage.tsx
  frontend/src/employee-frontend/components/child-information/assistance-need/decision/AssistanceNeededDecisionForm.tsx
  frontend/src/employee-frontend/components/child-information/assistance-need/voucher-coefficient/AssistanceNeedVoucherCoefficientForm.tsx
  frontend/src/employee-frontend/components/child-information/assistance-need/voucher-coefficient/AssistanceNeedVoucherCoefficientRow.tsx
  frontend/src/employee-frontend/components/child-information/assistance/AssistanceActionSection.tsx
  frontend/src/employee-frontend/components/child-information/backup-care/BackupCareForm.tsx
  frontend/src/employee-frontend/components/child-information/daily-service-times/DailyServiceTimesForms.tsx
  frontend/src/employee-frontend/components/child-information/daily-service-times/DailyServiceTimesRow.tsx
  frontend/src/employee-frontend/components/child-information/person-details/AdditionalInformation.tsx
  frontend/src/employee-frontend/components/child-information/placements/CreatePlacementModal.tsx
  frontend/src/employee-frontend/components/child-information/queries.ts
  frontend/src/employee-frontend/components/finance-basics/ServiceNeedsSection.tsx
  frontend/src/employee-frontend/components/finance-basics/queries.ts
  frontend/src/employee-frontend/components/unit/tab-unit-information/UnitAccessControl.tsx
  frontend/src/employee-frontend/components/unit/unit-details/CreateUnitPage.tsx
  frontend/src/employee-frontend/components/unit/unit-details/UnitDetailsPage.tsx
  frontend/src/employee-frontend/queries.ts
  frontend/src/employee-frontend/query.ts
Labels: tech

#5133 Siirrytään käyttämään uusia endpoint-polkuja
  apigw/src/enduser/publicRoutes.ts
  apigw/src/internal/app.ts
  frontend/src/citizen-frontend/generated/api-clients/daycare.ts
  frontend/src/citizen-frontend/generated/api-clients/pairing.ts
  frontend/src/citizen-frontend/generated/api-clients/serviceneed.ts
  frontend/src/employee-frontend/generated/api-clients/daycare.ts
  frontend/src/employee-frontend/generated/api-clients/pairing.ts
  frontend/src/employee-frontend/generated/api-clients/serviceneed.ts
  frontend/src/employee-mobile-frontend/generated/api-clients/daycare.ts
  frontend/src/employee-mobile-frontend/generated/api-clients/pairing.ts
  frontend/src/employee-mobile-frontend/generated/api-clients/pis.ts
  frontend/src/employee-mobile-frontend/generated/api-clients/serviceneed.ts
  frontend/src/employee-mobile-frontend/pairing/PairingWizard.tsx
  frontend/src/employee-mobile-frontend/pairing/api.ts
  service/codegen/src/main/kotlin/evaka/codegen/api/ApiFiles.kt
  service/codegen/src/main/kotlin/evaka/codegen/api/Config.kt
  service/src/main/kotlin/fi/espoo/evaka/pairing/PairingsController.kt
Labels: tech

#5134 Käytetään eri Varda-rajapintaa hetullisten henkilöiden hakuun
  service/src/integrationTest/kotlin/fi/espoo/evaka/varda/new/VardaUpdaterIntegrationTest.kt
  service/src/main/kotlin/fi/espoo/evaka/varda/new/Varda.kt
  service/src/main/kotlin/fi/espoo/evaka/varda/new/VardaClient.kt
  service/src/main/kotlin/fi/espoo/evaka/varda/new/VardaUpdateServiceNew.kt
Labels: tech

#5122 Kuntalaisen omat asetukset -parannuksia
  frontend/src/citizen-frontend/personal-details/PersonalDetailsSection.tsx
  frontend/src/e2e-test/pages/citizen/citizen-personal-details.ts
  frontend/src/lib-customizations/defaults/citizen/i18n/fi.tsx
Labels: enhancement

#5137 Hakemuksia voi hakea myös toissijaisten toiveiden palvelualueiden perusteella
  frontend/src/employee-frontend/components/applications/ApplicationsFilters.tsx
  service/src/main/kotlin/fi/espoo/evaka/application/ApplicationQueries.kt
Labels: enhancement

#5130 Tallennetaan ja näytetään laskuun liittyvät maksupäätökset
  frontend/src/employee-frontend/components/invoice/InvoiceDetailsSection.tsx
  frontend/src/lib-common/generated/api-types/invoicing.ts
  frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
  service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/Helpers.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/InvoiceIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/data/InvoiceQueriesTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/service/InvoiceCorrectionsIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/reports/InvoicingReportTest.kt
  service/src/main/kotlin/fi/espoo/evaka/invoicing/controller/InvoiceController.kt
  service/src/main/kotlin/fi/espoo/evaka/invoicing/data/InvoiceQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/invoicing/domain/Invoices.kt
  service/src/main/kotlin/fi/espoo/evaka/invoicing/service/InvoiceGenerator.kt
  service/src/main/kotlin/fi/espoo/evaka/invoicing/service/InvoiceService.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/dev/DevApi.kt
  service/src/main/resources/db/migration/V413__invoiced_fee_decision.sql
  service/src/main/resources/migrations.txt
  service/src/test/kotlin/fi/espoo/evaka/invoicing/integration/EspooInvoiceIntegrationClientTest.kt
Labels: enhancement

#5152 Vaihdetaan Varda-integraation käyttämä HTTP client -kirjasto
  service/build.gradle.kts
  service/evaka-bom/build.gradle.kts
  service/src/main/kotlin/fi/espoo/evaka/varda/new/VardaClient.kt
  service/src/main/kotlin/fi/espoo/evaka/varda/new/VardaUpdateServiceNew.kt
Labels: tech

#5139 Ei lähetetä push-notifikaatioita mobiiliin tiedotteista
  service/src/integrationTest/kotlin/fi/espoo/evaka/messaging/MessagePushNotificationsTest.kt
  service/src/main/kotlin/fi/espoo/evaka/messaging/MessagePushNotifications.kt
Labels: enhancement

#5141 Käytetään vieläkin enemmän generoituja API-funktioita E2E-testeissä
  frontend/src/e2e-test/dev-api/data-init.ts
  frontend/src/e2e-test/dev-api/fixtures.ts
  frontend/src/e2e-test/dev-api/index.ts
  frontend/src/e2e-test/dev-api/types.ts
  frontend/src/e2e-test/generated/api-clients.ts
  frontend/src/e2e-test/pages/citizen/citizen-map.ts
  frontend/src/e2e-test/pages/mobile/child-page.ts
  frontend/src/e2e-test/specs/0_citizen/citizen-applications-list.spec.ts
  frontend/src/e2e-test/specs/0_citizen/citizen-child-page.spec.ts
  frontend/src/e2e-test/specs/0_citizen/citizen-daycare-application.spec.ts
  frontend/src/e2e-test/specs/0_citizen/citizen-decisions.spec.ts
  frontend/src/e2e-test/specs/0_citizen/citizen-finance-decisions.spec.ts
  frontend/src/e2e-test/specs/0_citizen/citizen-map.spec.ts
  frontend/src/e2e-test/specs/0_citizen/citizen-vasu.spec.ts
  frontend/src/e2e-test/specs/0_citizen/feature-flag-citizen-reservations-intermittent-shif-care.spec.ts
  frontend/src/e2e-test/specs/0_citizen/foster-parents.spec.ts
  frontend/src/e2e-test/specs/4_finance/fee-decisions.spec.ts
  frontend/src/e2e-test/specs/4_finance/finance-basics.spec.ts
  frontend/src/e2e-test/specs/4_finance/income-staments.spec.ts
  frontend/src/e2e-test/specs/4_finance/invoices.spec.ts
  frontend/src/e2e-test/specs/4_finance/person-finance-decisions.spec.ts
  frontend/src/e2e-test/specs/4_finance/value-decisions.spec.ts
  frontend/src/e2e-test/specs/4_finance/voucher-reports.spec.ts
  frontend/src/e2e-test/specs/5_employee/application-attachments.spec.ts
  frontend/src/e2e-test/specs/5_employee/application-details.spec.ts
  frontend/src/e2e-test/specs/5_employee/application-search.spec.ts
  frontend/src/e2e-test/specs/5_employee/application-transitions.spec.ts
  frontend/src/e2e-test/specs/5_employee/applications.spec.ts
  frontend/src/e2e-test/specs/5_employee/assistance-need-decision.spec.ts
  frontend/src/e2e-test/specs/5_employee/child-income-statements.spec.ts
  frontend/src/e2e-test/specs/5_employee/curriculum-document.spec.ts
  frontend/src/e2e-test/specs/5_employee/employee-reads-application.spec.ts
  frontend/src/e2e-test/specs/5_employee/feature-flag-decision-draft-multiple-units.spec.ts
  frontend/src/e2e-test/specs/5_employee/fridge-head-information.spec.ts
  frontend/src/e2e-test/specs/5_employee/guardian-income-statements.spec.ts
  frontend/src/e2e-test/specs/5_employee/guardian-information-page.spec.ts
  frontend/src/e2e-test/specs/5_employee/manual-duplication-report.spec.ts
  frontend/src/e2e-test/specs/5_employee/month-calendar.spec.ts
  frontend/src/e2e-test/specs/5_employee/placement-sketching-report.spec.ts
  frontend/src/e2e-test/specs/5_employee/realtime-attendances.spec.ts
  frontend/src/e2e-test/specs/5_employee/reservation-calendar.spec.ts
  frontend/src/e2e-test/specs/5_employee/search-person.spec.ts
  frontend/src/e2e-test/specs/5_employee/unit-application-process.spec.ts
  frontend/src/e2e-test/specs/5_employee/unit-calendar-events.spec.ts
  frontend/src/e2e-test/specs/5_employee/unit-editor.spec.ts
  frontend/src/e2e-test/specs/5_employee/unit-groups.spec.ts
  frontend/src/e2e-test/specs/5_employee/units.spec.ts
  frontend/src/e2e-test/specs/5_employee/vasu.spec.ts
  frontend/src/e2e-test/specs/6_mobile/pin-login.spec.ts
  frontend/src/e2e-test/specs/7_messaging/service-worker-messaging.spec.ts
  service/src/main/kotlin/fi/espoo/evaka/shared/dev/DevApi.kt
Labels: tech

#5155 Korjaus audit-lokitukseen
  service/src/main/kotlin/fi/espoo/evaka/messaging/MessageController.kt
Labels: tech

#5157 Nostetaan Jamix-integraation HTTP timeoutia
  service/src/main/kotlin/fi/espoo/evaka/jamix/JamixService.kt
Labels: tech

#5092 Näytetään viestinnässä vastaanottajan lisäfiltterit kun viestiä lähetetään henkilökohtaiselta tai kunnalliselta tililtä
  frontend/src/e2e-test/pages/employee/messages/messages-page.ts
  frontend/src/e2e-test/specs/7_messaging/messaging-by-staff.spec.ts
  frontend/src/e2e-test/specs/7_messaging/municipal-messaging.spec.ts
  frontend/src/employee-frontend/components/messages/MessageEditor.tsx
  frontend/src/employee-frontend/components/messages/MessagesPage.tsx
  frontend/src/employee-mobile-frontend/messages/MessageEditor.tsx
  frontend/src/lib-common/generated/api-types/messaging.ts
  frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
  service/src/integrationTest/kotlin/fi/espoo/evaka/messaging/MessageIntegrationTest.kt
  service/src/main/kotlin/fi/espoo/evaka/messaging/MessageController.kt
  service/src/main/kotlin/fi/espoo/evaka/messaging/MessageQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/messaging/MessageService.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/security/Action.kt
Labels: enhancement

#5161 fix: add missing parameter to push notification test
  service/src/integrationTest/kotlin/fi/espoo/evaka/messaging/MessagePushNotificationsTest.kt
Labels: no-changelog

#5127 Mahdollista palse-arvojen lisäys ja poisto
  frontend/src/employee-frontend/components/finance-basics/PlacementTypeItem.tsx
  frontend/src/employee-frontend/components/finance-basics/ServiceNeedItem.tsx
  frontend/src/employee-frontend/components/finance-basics/ServiceNeedsSection.tsx
  frontend/src/employee-frontend/components/finance-basics/VoucherValueEditor.tsx
  frontend/src/employee-frontend/components/finance-basics/queries.ts
  frontend/src/employee-frontend/generated/api-clients/invoicing.ts
  frontend/src/employee-mobile-frontend/generated/api-clients/invoicing.ts
  frontend/src/lib-common/generated/action.d.ts
  frontend/src/lib-common/generated/api-types/invoicing.ts
  frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
  service/src/integrationTest/kotlin/fi/espoo/evaka/ServiceNeedTestFixtures.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/VoucherValueDecisionIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/VoucherValueIntegrationTest.kt
  service/src/main/kotlin/fi/espoo/evaka/Audit.kt
  service/src/main/kotlin/fi/espoo/evaka/invoicing/controller/FinanceBasicsController.kt
  service/src/main/kotlin/fi/espoo/evaka/invoicing/service/generator/Domain.kt
  service/src/main/kotlin/fi/espoo/evaka/invoicing/service/generator/Queries.kt
  service/src/main/kotlin/fi/espoo/evaka/invoicing/service/generator/SharedLogic.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/dev/DevApi.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/security/Action.kt
  service/src/test/kotlin/fi/espoo/evaka/invoicing/service/generator/VoucherValueDecisionGeneratorV2Test.kt
Labels: enhancement

#5156 Lokitetaan varoitus jos Suomi.fi lähettää meille virheellisen hetun
  apigw/src/enduser/suomi-fi-saml.ts
Labels: tech

#5160 Scheduled jobit näkyy omina spaneina DataDogissa
  service/src/main/kotlin/fi/espoo/evaka/shared/job/ScheduledJobRunner.kt
Labels: tech

#5163 Luodaan security.txt template-mekanismilla ja generoidaan sinne Expires-kenttä
  frontend/proxy/files/bin/proxy-entrypoint.sh
  frontend/proxy/files/etc/nginx/conf.d/nginx.conf.template
  frontend/proxy/files/internal/security.txt.template
  frontend/proxy/files/internal/security.txt.template.license
Labels: tech

#5154 Muutos tuen kertoimien päättämiseen
  service/src/integrationTest/kotlin/fi/espoo/evaka/assistance/AssistanceQueriesTest.kt
  service/src/main/kotlin/fi/espoo/evaka/assistance/AssistanceQueries.kt
Labels: enhancement

#5181 Bump lint packages in /frontend
  frontend/package.json
  frontend/yarn.lock
Labels: dependencies, javascript

#5185 Ruokatilausintegraatio: lounaan ateriatyyppi esiopetuksessa
  service/src/main/kotlin/fi/espoo/evaka/reports/MealReportUtil.kt
  service/src/test/kotlin/fi/espoo/evaka/reports/MealReportTests.kt
Labels: bug

#5169 Käytetään uutta SQL query API:a, osa 3
  service/src/integrationTest/kotlin/fi/espoo/evaka/attendance/RealtimeStaffAttendanceQueriesTest.kt
  service/src/main/kotlin/fi/espoo/evaka/application/ApplicationQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/application/ApplicationStateService.kt
  service/src/main/kotlin/fi/espoo/evaka/application/PendingDecisionEmailService.kt
  service/src/main/kotlin/fi/espoo/evaka/application/notes/ApplicationNoteQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/assistance/AssistanceQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/assistanceaction/AssistanceActionQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/assistanceaction/AssistanceActionService.kt
  service/src/main/kotlin/fi/espoo/evaka/assistanceneed/decision/AssistanceNeedDecisionQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/assistanceneed/preschooldecision/AssistanceNeedPreschoolDecisionQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/assistanceneed/vouchercoefficient/AssistanceNeedVoucherCoefficientQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/attachment/AttachmentQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/attendance/ChildAttendanceController.kt
  service/src/main/kotlin/fi/espoo/evaka/attendance/ChildAttendanceQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/attendance/MobileRealtimeStaffAttendanceController.kt
  service/src/main/kotlin/fi/espoo/evaka/attendance/MobileUnitController.kt
  service/src/main/kotlin/fi/espoo/evaka/attendance/RealtimeStaffAttendanceController.kt
  service/src/main/kotlin/fi/espoo/evaka/attendance/StaffAttendanceQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/attendance/StaffOccupancyCoefficientQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/backupcare/BackupCareQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/backuppickup/BackupPickupController.kt
  service/src/main/kotlin/fi/espoo/evaka/calendarevent/CalendarEventController.kt
  service/src/main/kotlin/fi/espoo/evaka/calendarevent/CalendarEventQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/childimages/ChildImageQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/children/ChildrenQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/dailyservicetimes/DailyServiceTimes.kt
  service/src/main/kotlin/fi/espoo/evaka/dailyservicetimes/DailyServiceTimesCitizenController.kt
  service/src/main/kotlin/fi/espoo/evaka/daycare/Caretaker.kt
  service/src/main/kotlin/fi/espoo/evaka/daycare/CaretakerQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/daycare/ChildQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/daycare/ClubTermQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/daycare/DaycareGroupQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/daycare/DaycareQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/daycare/controllers/LocationController.kt
  service/src/main/kotlin/fi/espoo/evaka/daycare/service/StaffAttendanceService.kt
  service/src/main/kotlin/fi/espoo/evaka/decision/DecisionDraftService.kt
  service/src/main/kotlin/fi/espoo/evaka/decision/DecisionQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/reports/MealReportController.kt
Labels: tech

#5188 Korjaus audit-lokitukseen
  service/src/main/kotlin/fi/espoo/evaka/attendance/MobileRealtimeStaffAttendanceController.kt
Labels: tech

#5187 Korjaus Varda-yksiköiden vientiin virhetilanteen jälkeen
  service/src/main/kotlin/fi/espoo/evaka/varda/VardaUnits.kt
Labels: bug

#5192 Korjaus palse-arvoeditorin ongelmiin
  frontend/src/employee-frontend/components/finance-basics/VoucherValueEditor.tsx
  frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
Labels: bug

#5194 Korjattu tuen tarpeen päätöksen hyväksyminen
  service/src/main/kotlin/fi/espoo/evaka/assistanceneed/decision/AssistanceNeedDecisionQueries.kt
Labels: bug

#5191 Säädettävä sijainti ja koko henkilön osoitesivun kirjekuori-ikkunalle
  service/src/integrationTest/kotlin/fi/espoo/evaka/pdfgen/PdfGeneratorTest.kt
  service/src/main/kotlin/fi/espoo/evaka/EvakaEnv.kt
  service/src/main/kotlin/fi/espoo/evaka/pis/controllers/PersonController.kt
  service/src/main/kotlin/fi/espoo/evaka/pis/service/PersonService.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/domain/Rectangle.kt
  service/src/main/resources/WEB-INF/templates/address-page/address-page.html
  service/src/test/kotlin/fi/espoo/evaka/shared/domain/RectangleTest.kt
Labels: enhancement

#5182 Poistetaan `timeUsageInfo` feature flag
  frontend/src/citizen-frontend/calendar/AttendanceInfo.tsx
  frontend/src/citizen-frontend/calendar/CalendarGridView.tsx
  frontend/src/citizen-frontend/calendar/MonthElem.tsx
  frontend/src/citizen-frontend/calendar/calendar-elements.tsx
  frontend/src/citizen-frontend/calendar/hooks.ts
  frontend/src/e2e-test/specs/5_employee/month-calendar.spec.ts
  frontend/src/employee-frontend/components/absences/MonthCalendarTable.tsx
  frontend/src/lib-customizations/espoo/featureFlags.tsx
  frontend/src/lib-customizations/types.d.ts
Labels: tech

#5186 Ruokatilausintegraatio: Ruoan rakenne
  frontend/src/e2e-test/dev-api/data-init.ts
  frontend/src/e2e-test/dev-api/fixtures.ts
  frontend/src/e2e-test/generated/api-types.ts
  frontend/src/employee-frontend/components/child-information/person-details/AdditionalInformation.tsx
  frontend/src/employee-frontend/components/child-information/person-details/queries.ts
  frontend/src/employee-frontend/components/reports/MealReport.tsx
  frontend/src/employee-frontend/generated/api-clients/specialdiet.ts
  frontend/src/lib-common/generated/api-types/daycare.ts
  frontend/src/lib-common/generated/api-types/jamix.ts
  frontend/src/lib-common/generated/api-types/reports.ts
  frontend/src/lib-common/generated/api-types/specialdiet.ts
  frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
  service/src/integrationTest/kotlin/fi/espoo/evaka/daycare/controllers/ChildrenControllerIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/daycare/dao/ChildDAOIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/jamix/JamixIntegrationTest.kt
  service/src/main/kotlin/fi/espoo/evaka/Audit.kt
  service/src/main/kotlin/fi/espoo/evaka/daycare/ChildQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/daycare/controllers/ChildController.kt
  service/src/main/kotlin/fi/espoo/evaka/jamix/JamixService.kt
  service/src/main/kotlin/fi/espoo/evaka/reports/MealReportController.kt
  service/src/main/kotlin/fi/espoo/evaka/reports/MealReportQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/reports/MealReportUtil.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/dev/DataInitializers.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/dev/DevApi.kt
  service/src/main/kotlin/fi/espoo/evaka/specialdiet/MealTexturesController.kt
  service/src/main/kotlin/fi/espoo/evaka/specialdiet/SpecialDietController.kt
  service/src/main/kotlin/fi/espoo/evaka/specialdiet/SpecialDietQueries.kt
  service/src/main/resources/db/migration/V415__meal_texture.sql
  service/src/main/resources/migrations.txt
  service/src/test/kotlin/fi/espoo/evaka/jamix/JamixServiceTest.kt
  service/src/test/kotlin/fi/espoo/evaka/reports/MealReportTests.kt
Labels: enhancement

#5196 Lisätään palvelusetelikerroin raakaraportille
  frontend/src/employee-frontend/components/reports/Raw.tsx
  frontend/src/lib-common/generated/api-types/reports.ts
  service/src/main/kotlin/fi/espoo/evaka/reports/RawReport.kt
Labels: enhancement

#5199 Tekstikorjaus ruokailijaraporttiin
  frontend/src/employee-frontend/components/reports/MealReport.tsx
Labels: bug

#5190 Päivitetään Keycloak versioon 24.0.4
  keycloak/Dockerfile
  keycloak/evaka-logging/pom.xml
  keycloak/evaka-review-profile/pom.xml
  keycloak/evaka-review-profile/src/main/java/com/espoo/keycloak/authenticator/EvakaReviewProfileAuthenticator.java.diff
  keycloak/evaka-review-profile/src/main/java/com/espoo/keycloak/authenticator/EvakaReviewProfileAuthenticatorFactory.java.diff
Labels: dependencies

#5202 Hotfix: Korjaus migratioon V416 (vuorohoidon aukioloajat)
  service/src/main/resources/db/migration/V416__shift_care_operation_times_improvements.sql
Labels: no-changelog

#5207 Korjaus päivittäiseen säännölliseen varhaiskasvatusaikaan
  service/src/main/resources/db/migration/R__child_absences_functions.sql
Labels: bug

#5206 Näytetään kuukausikalenterissa vain lapsen mahdolliset toimintapäivät
  frontend/src/e2e-test/specs/5_employee/reservation-calendar.spec.ts
  service/src/integrationTest/kotlin/fi/espoo/evaka/absence/AbsenceServiceIntegrationTest.kt
  service/src/main/kotlin/fi/espoo/evaka/absence/AbsenceService.kt
Labels: bug

#5219 Gradle-päivitys ja korjaus riippuvuuksien hakuun
  service/build.gradle.kts
  service/gradle/wrapper/gradle-wrapper.jar
  service/gradle/wrapper/gradle-wrapper.properties
  service/gradlew.bat
Labels: tech

#5201 Koko viikon ruokailijaraportti
  frontend/src/employee-frontend/components/reports/MealReport.tsx
  frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
Labels: enhancement

#5222 Varda-yksikköpäivitys perustuu nyt OID:hen
  service/src/integrationTest/kotlin/fi/espoo/evaka/varda/VardaPlacementsIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/varda/VardaUnitIntegrationTest.kt
  service/src/main/kotlin/fi/espoo/evaka/varda/VardaUnits.kt
  service/src/main/kotlin/fi/espoo/evaka/varda/integration/VardaClient.kt
  service/src/main/kotlin/fi/espoo/evaka/varda/new/VardaClient.kt
  service/src/main/resources/db/migration/V417__varda_unit_remove_id.sql
  service/src/main/resources/migrations.txt
  service/src/test/kotlin/fi/espoo/evaka/varda/VardaUnitModelTest.kt
Labels: enhancement

#5221 Keskusteluajanvaraukset käyttöön Espoon staging-ympäristössä
  frontend/src/lib-customizations/espoo/featureFlags.tsx
Labels: no-changelog

#5204 Korjaus null pointer exceptioniin palse-arvojen luonnissa
  service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/VoucherValueIntegrationTest.kt
  service/src/main/kotlin/fi/espoo/evaka/invoicing/controller/FinanceBasicsController.kt
Labels: bug

#5168 Kuntalaisen sähköposti-ilmoituksen lähettäminen uusista talouspäätöksistä
  service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/FeeDecisionIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/VoucherValueDecisionIntegrationTest.kt
  service/src/main/kotlin/fi/espoo/evaka/emailclient/EvakaEmailMessageProvider.kt
  service/src/main/kotlin/fi/espoo/evaka/emailclient/IEmailMessageProvider.kt
  service/src/main/kotlin/fi/espoo/evaka/invoicing/controller/FeeDecisionController.kt
  service/src/main/kotlin/fi/espoo/evaka/invoicing/controller/VoucherValueDecisionController.kt
  service/src/main/kotlin/fi/espoo/evaka/invoicing/service/FeeDecisionService.kt
  service/src/main/kotlin/fi/espoo/evaka/invoicing/service/VoucherValueDecisionService.kt
  service/src/main/kotlin/fi/espoo/evaka/pis/PersonalData.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/async/AsyncJob.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/dev/DevApi.kt
Labels: enhancement

#5224 Parannuksia sähköpostien lähetykseen
  service/src/integrationTest/kotlin/fi/espoo/evaka/messaging/MessageNotificationEmailServiceIntegrationTest.kt
  service/src/main/kotlin/fi/espoo/evaka/emailclient/EmailClient.kt
  service/src/main/kotlin/fi/espoo/evaka/messaging/MessageNotificationEmailService.kt
  service/src/main/kotlin/fi/espoo/evaka/messaging/MessageQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/messaging/MessageService.kt
Labels: enhancement

#5184 Tehdään hakemuksen lomake-sarakkeista ei-nullableja
  frontend/src/e2e-test/dev-api/fixtures.ts
  frontend/src/e2e-test/generated/api-types.ts
  service/src/integrationTest/kotlin/fi/espoo/evaka/TestFixtures.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/application/ApplicationOtherGuardianIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/application/ApplicationQueriesSmokeTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/application/ApplicationReceivedEmailIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/application/ApplicationSearchIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/application/ApplicationStateServiceIntegrationTests.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/application/ApplicationUpdateIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/application/DuplicateApplicationIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/application/GetApplicationIntegrationTests.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/application/PendingDecisionEmailServiceIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/attachments/AttachmentQueriesTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/decision/DecisionControllerIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/decision/DecisionCreationIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/decision/DecisionResolutionIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/espoo/bi/EspooBiTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/messaging/MessageIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/occupancy/OccupancyControllerIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/occupancy/OccupancyTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/pis/InactivePeopleCleanupIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/placement/PlacementPlanIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/reports/ManualDuplicationReportTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/reports/PlacementSketchingReportControllerTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/shared/auth/AclIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/shared/job/ScheduledJobsTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/shared/security/ApplicationAccessControlTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/shared/security/AttachmentAccessControlTest.kt
  service/src/main/kotlin/fi/espoo/evaka/application/ApplicationControllerCitizen.kt
  service/src/main/kotlin/fi/espoo/evaka/application/ApplicationControllerV2.kt
  service/src/main/kotlin/fi/espoo/evaka/application/ApplicationQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/application/ApplicationStateService.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/dev/DataInitializers.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/dev/DevApi.kt
  service/src/main/resources/db/migration/V418__application_non_nullable_fields.sql
  service/src/main/resources/migrations.txt
Labels: tech

#5195 Pidetään enintään yksi Jamix-ruokavaliosynkki kerrallaan
  service/src/main/kotlin/fi/espoo/evaka/jamix/JamixService.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/async/AsyncJob.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/job/ScheduledJobs.kt
Labels: tech

#5225 Lisätty yksikön järjestämismuoto laskutustietoihin
  frontend/src/employee-frontend/components/invoice/InvoiceRowsSection.tsx
  frontend/src/lib-common/generated/api-types/invoicing.ts
  service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/Helpers.kt
  service/src/main/kotlin/fi/espoo/evaka/invoicing/data/InvoiceQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/invoicing/domain/Invoices.kt
  service/src/test/kotlin/fi/espoo/evaka/invoicing/integration/EspooInvoiceIntegrationClientTest.kt
Labels: enhancement

#5215 Käytetään enemmän generoituja API-funktioita mobiilissa
  frontend/src/employee-mobile-frontend/App.tsx
  frontend/src/employee-mobile-frontend/auth/api.ts
  frontend/src/employee-mobile-frontend/child-attendance/AttendancePageWrapper.tsx
  frontend/src/employee-mobile-frontend/child-attendance/ChildListItem.tsx
  frontend/src/employee-mobile-frontend/child-attendance/ChildReservationList.tsx
  frontend/src/employee-mobile-frontend/child-attendance/ConfimedReservationDaysWrapper.tsx
  frontend/src/employee-mobile-frontend/child-attendance/actions/MarkAbsent.tsx
  frontend/src/employee-mobile-frontend/child-attendance/actions/MarkAbsentBeforehand.tsx
  frontend/src/employee-mobile-frontend/child-attendance/actions/MarkDeparted.tsx
  frontend/src/employee-mobile-frontend/child-attendance/actions/MarkPresent.tsx
  frontend/src/employee-mobile-frontend/child-attendance/actions/MarkReservations.tsx
  frontend/src/employee-mobile-frontend/child-attendance/api.ts
  frontend/src/employee-mobile-frontend/child-attendance/queries.ts
  frontend/src/employee-mobile-frontend/child-info/AttendanceChildPage.tsx
  frontend/src/employee-mobile-frontend/child-info/ChildSensitiveInfoPage.tsx
  frontend/src/employee-mobile-frontend/child-info/api.ts
  frontend/src/employee-mobile-frontend/child-notes/ChildNotes.tsx
  frontend/src/employee-mobile-frontend/child-notes/ChildStickyNotesTab.tsx
  frontend/src/employee-mobile-frontend/child-notes/DailyNotesTab.tsx
  frontend/src/employee-mobile-frontend/child-notes/GroupNotesTab.tsx
  frontend/src/employee-mobile-frontend/child-notes/api.ts
  frontend/src/employee-mobile-frontend/child-notes/queries.ts
  frontend/src/employee-mobile-frontend/common/BottomNavbar.tsx
  frontend/src/employee-mobile-frontend/common/service-worker.tsx
  frontend/src/employee-mobile-frontend/messages/DraftMessagesList.tsx
  frontend/src/employee-mobile-frontend/messages/MessageEditor.tsx
  frontend/src/employee-mobile-frontend/messages/ReceivedThreadsList.tsx
  frontend/src/employee-mobile-frontend/messages/ThreadView.tsx
  frontend/src/employee-mobile-frontend/messages/UnreadMessagesPage.tsx
  frontend/src/employee-mobile-frontend/messages/api.ts
  frontend/src/employee-mobile-frontend/messages/queries.ts
  frontend/src/employee-mobile-frontend/pairing/PairingWizard.tsx
  frontend/src/employee-mobile-frontend/pairing/api.ts
  frontend/src/employee-mobile-frontend/settings/NotificationSettings.tsx
  frontend/src/employee-mobile-frontend/settings/api.ts
  frontend/src/employee-mobile-frontend/settings/queries.ts
  frontend/src/employee-mobile-frontend/staff-attendance/ExternalStaffMemberPage.tsx
  frontend/src/employee-mobile-frontend/staff-attendance/MarkExternalStaffMemberArrivalPage.tsx
  frontend/src/employee-mobile-frontend/staff-attendance/StaffAttendanceEditPage.tsx
  frontend/src/employee-mobile-frontend/staff-attendance/StaffAttendancesPage.tsx
  frontend/src/employee-mobile-frontend/staff-attendance/StaffMarkArrivedPage.tsx
  frontend/src/employee-mobile-frontend/staff-attendance/StaffMarkDepartedPage.tsx
  frontend/src/employee-mobile-frontend/staff-attendance/StaffMemberPage.tsx
  frontend/src/employee-mobile-frontend/staff-attendance/api.ts
  frontend/src/employee-mobile-frontend/staff-attendance/queries.ts
  frontend/src/employee-mobile-frontend/staff/StaffPage.tsx
  frontend/src/employee-mobile-frontend/staff/api.ts
  frontend/src/lib-common/api-types/messaging.ts
Labels: tech

#5227 Lisätty frontend-kontin versio Datadog-integraatioon
  frontend/proxy/files/etc/nginx/dd-config.json.template
Labels: tech

#5220 Päiväkohtaiset lapsen tulo- ja lähtöajat raportin pitää vuorohoitoyksiköllä sisältää viikonloput
  service/src/main/kotlin/fi/espoo/evaka/reports/AttendanceReservationReportController.kt
Labels: bug
