Repository espoon-voltti/evaka, pull requests merged in 2024-10, with the labels that each got.

#5722 Näytetään työntekijälle sijoituksen viimeisimmän muokkauksen aikaleima ja tekijä
  frontend/src/employee-frontend/components/child-information/placements/PlacementRow.tsx
  frontend/src/lib-common/generated/api-types/placement.ts
  frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
  service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/service/FeeDecisionGenerationForDataChangesIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/service/VoucherValueDecisionGenerationForDataChangesIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/placement/FiveYearOldDaycarePlacementsIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/placement/PlacementServiceIntegrationTest.kt
  service/src/main/kotlin/fi/espoo/evaka/application/ApplicationStateService.kt
  service/src/main/kotlin/fi/espoo/evaka/placement/Placement.kt
  service/src/main/kotlin/fi/espoo/evaka/placement/PlacementController.kt
  service/src/main/kotlin/fi/espoo/evaka/placement/PlacementControllerCitizen.kt
  service/src/main/kotlin/fi/espoo/evaka/placement/PlacementPlanService.kt
  service/src/main/kotlin/fi/espoo/evaka/placement/PlacementQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/placement/PlacementService.kt
  service/src/main/kotlin/fi/espoo/evaka/placement/PlacementTermination.kt
  service/src/main/kotlin/fi/espoo/evaka/serviceneed/application/ServiceApplicationController.kt
  service/src/main/resources/db/migration/V441__placement_modification_user_and_timestamp.sql
  service/src/main/resources/migrations.txt
Labels: enhancement

#5693 Tuen päätöksen tukipalveluiden voimassaoloaika valinnaiseksi
  frontend/src/e2e-test/dev-api/fixtures.ts
  frontend/src/e2e-test/generated/api-types.ts
  frontend/src/e2e-test/pages/employee/assistance-need-decision/assistance-need-decision-edit-page.ts
  frontend/src/e2e-test/specs/5_employee/assistance-need-decision.spec.ts
  frontend/src/employee-frontend/components/child-information/AssistanceNeedDecisionSection.tsx
  frontend/src/employee-frontend/components/child-information/assistance-need/decision/AssistanceNeedDecisionEditPage.tsx
  frontend/src/employee-frontend/components/child-information/assistance-need/decision/AssistanceNeededDecisionForm.tsx
  frontend/src/lib-common/generated/api-types/assistanceneed.ts
  frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
  service/src/integrationTest/kotlin/fi/espoo/evaka/assistanceneed/decision/AssistanceNeedDecisionIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/espoo/bi/EspooBiTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/pis/InactivePeopleCleanupIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/reports/AssistanceNeedDecisionsReportTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/shared/security/AssistanceNeedDecisionAccessControlTest.kt
  service/src/main/kotlin/fi/espoo/evaka/assistanceneed/decision/AssistanceNeedDecision.kt
  service/src/main/kotlin/fi/espoo/evaka/assistanceneed/decision/AssistanceNeedDecisionQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/dev/DataInitializers.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/dev/DevApi.kt
  service/src/main/resources/db/migration/V442__assistance_need_decision_no_end_date.sql
  service/src/main/resources/migrations.txt
Labels: enhancement

#5754 Henkilökunnan ei-reaaliaikaisen läsnäolokirjauksen voi tyhjentää
  frontend/src/e2e-test/pages/employee/units/unit-month-calendar-page.ts
  frontend/src/e2e-test/specs/5_employee/month-calendar.spec.ts
  frontend/src/employee-frontend/components/absences/StaffAttendance.tsx
  service/src/main/kotlin/fi/espoo/evaka/daycare/controllers/StaffAttendanceController.kt
  service/src/main/kotlin/fi/espoo/evaka/daycare/service/StaffAttendanceService.kt
Labels: bug

#5751 Parannetaan kalenteritapahtumien tietokantakyselyiden suorituskykyä
  service/src/main/kotlin/fi/espoo/evaka/calendarevent/CalendarEventQueries.kt
  service/src/main/resources/db/migration/V443__calendar_event_indexes.sql
  service/src/main/resources/migrations.txt
Labels: tech

#5757 Toisella perhepäivähoitajalla varahoidossa oleva lapsi nousee perhepäivähoidossa olevien lasten ateriaraportille
  service/src/integrationTest/kotlin/fi/espoo/evaka/reports/FamilyDaycareMealReportTest.kt
  service/src/main/kotlin/fi/espoo/evaka/reports/FamilyDaycareMealReport.kt
Labels: enhancement

#5733 Työntekijän mobiliin seuraavat päivät näkymä ottaa huomioon lapsen toimintapäivät (vuorohoitopalveluntarve)
  service/src/integrationTest/kotlin/fi/espoo/evaka/reservations/AttendanceReservationsControllerIntegrationTest.kt
  service/src/main/kotlin/fi/espoo/evaka/reservations/AttendanceReservationController.kt
Labels: bug

#5758 Lisätään validateMigrationNaming-asetus kaikkiin flyway-konfiguraatioihin
  service/gradle.properties
  service/src/integrationTest/kotlin/fi/espoo/evaka/shared/config/SharedIntegrationTestConfig.kt
Labels: tech

#5764 Vahvan tunnistautumisen vaatimus palveluntarpeen muutoshakemuksen luontirajapintaan
  service/src/integrationTest/kotlin/fi/espoo/evaka/serviceneed/application/ServiceApplicationIntegrationTest.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/security/Action.kt
Labels: bug

#5647 Lomakyselyjen läsnäoloraportti
  frontend/src/e2e-test/pages/employee/reports.ts
  frontend/src/e2e-test/specs/5_employee/holiday-period-attendance-report.spec.ts
  frontend/src/employee-frontend/App.tsx
  frontend/src/employee-frontend/components/Reports.tsx
  frontend/src/employee-frontend/components/reports/HolidayPeriodAttendanceReport.tsx
  frontend/src/employee-frontend/components/reports/queries.ts
  frontend/src/employee-frontend/generated/api-clients/reports.ts
  frontend/src/lib-common/generated/action.d.ts
  frontend/src/lib-common/generated/api-types/reports.ts
  frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
  service/src/integrationTest/kotlin/fi/espoo/evaka/reports/HolidayPeriodAttendanceReportTest.kt
  service/src/main/kotlin/fi/espoo/evaka/Audit.kt
  service/src/main/kotlin/fi/espoo/evaka/assistance/AssistanceQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/reports/HolidayPeriodAttendanceReport.kt
  service/src/main/kotlin/fi/espoo/evaka/reports/ReportPermissions.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/security/Action.kt
Labels: enhancement

#5753 Lisätään integraatiotesti joilla tarkistetaan tietokantaskeeman rakennetta
  service/src/integrationTest/kotlin/fi/espoo/evaka/shared/db/SchemaConventionsTest.kt
Labels: tech

#5725 Salasanan rotatointi Suomi.fi viestit REST-toteutukseen + tiukempi integraatio SSM:n kanssa
  service/build.gradle.kts
  service/src/integrationTest/kotlin/fi/espoo/evaka/sficlient/SoapStackIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/sficlient/rest/MockPasswordStore.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/sficlient/rest/MockSfiMessagesRestEndpoint.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/sficlient/rest/SfiMessagesRestClientIntegrationTest.kt
  service/src/integrationTest/resources/application-integration-test.yaml
  service/src/main/kotlin/fi/espoo/evaka/EvakaEnv.kt
  service/src/main/kotlin/fi/espoo/evaka/sficlient/MockSfiMessagesClient.kt
  service/src/main/kotlin/fi/espoo/evaka/sficlient/SfiMessagesClient.kt
  service/src/main/kotlin/fi/espoo/evaka/sficlient/SfiMessagesSoapClient.kt
  service/src/main/kotlin/fi/espoo/evaka/sficlient/rest/PasswordStore.kt
  service/src/main/kotlin/fi/espoo/evaka/sficlient/rest/RestSchema.kt
  service/src/main/kotlin/fi/espoo/evaka/sficlient/rest/SfiMessagesRestClient.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/config/AwsConfig.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/config/SfiConfig.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/job/ScheduledJobs.kt
Labels: tech

#5782 Upgrade sentry packages
  frontend/package.json
  frontend/yarn.lock
Labels: dependencies

#5767 Kuntalaisen uuden viestin editori pysyy paikallaan skrollatessa
  frontend/src/citizen-frontend/messages/MessageEditor.tsx
Labels: bug

#5783 Estetään `org.opensaml`-riipuvuuden asentaminen servicessä
  service/build.gradle.kts
  service/src/main/kotlin/fi/espoo/evaka/sficlient/SfiMessagesSoapClient.kt
  service/src/main/kotlin/fi/espoo/evaka/vtjclient/config/XroadSoapClientConfig.kt
Labels: dependencies

#5761 Aktivoi valintojen poisto backspace ja delete näppäimillä monivalintakomponentissa
  frontend/src/lib-components/atoms/form/MultiSelect.tsx
Labels: enhancement

#5763 Viestinäkymän kohdennuksen palautus
  frontend/src/citizen-frontend/calendar/CalendarPage.tsx
  frontend/src/citizen-frontend/messages/MessagesPage.tsx
  frontend/src/citizen-frontend/messages/ThreadList.tsx
  frontend/src/citizen-frontend/utils/focus.ts
  frontend/src/e2e-test/pages/citizen/citizen-messages.ts
  frontend/src/e2e-test/specs/7_messaging/messaging.spec.ts
  frontend/src/e2e-test/utils/page.ts
  frontend/src/lib-components/atoms/buttons/LegacyButton.tsx
Labels: enhancement

#5784 Parannetaan joidenkin sijoitus- ja varahoitokyselyiden suorituskykyä
  frontend/src/employee-frontend/generated/api-clients/placement.ts
  frontend/src/employee-frontend/state/child.tsx
  service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/VoucherValueDecisionIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/placement/PlacementControllerCitizenIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/placement/PlacementControllerIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/placement/PlacementServiceIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/serviceneed/ServiceNeedIntegrationTest.kt
  service/src/main/kotlin/fi/espoo/evaka/backupcare/BackupCareQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/daycare/controllers/DaycareController.kt
  service/src/main/kotlin/fi/espoo/evaka/placement/PlacementController.kt
  service/src/main/kotlin/fi/espoo/evaka/placement/PlacementQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/placement/PlacementService.kt
Labels: tech

#5792 OWASP: ohita CVE-2024-9329
  service/owasp-suppressions.xml
Labels: no-changelog

#5760 Kuntalaisen vastatessa viestiin viestikenttä avautuu ruudulle näkyviin kokonaisuudessaan
  frontend/src/citizen-frontend/messages/ThreadView.tsx
  frontend/src/lib-common/utils/scrolling.ts
  frontend/src/lib-components/atoms/form/TextArea.tsx
  frontend/src/lib-components/messages/MessageReplyEditor.tsx
Labels: bug

#5796 Parannetaan `days_in_range` SQL-funktiota, korjataan samalla regressio
  service/src/integrationTest/kotlin/fi/espoo/evaka/shared/db/DaysInRangeSqlTest.kt
  service/src/main/resources/db/migration/V444__better_days_in_range.sql
  service/src/main/resources/migrations.txt
Labels: bug

#5759 Parannetaan RangeBasedSet-tietorakenteiden suorituskykyä binäärihaulla
  service/build.gradle.kts
  service/evaka-bom/build.gradle.kts
  service/src/main/kotlin/fi/espoo/evaka/shared/data/DateSet.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/data/DateTimeSet.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/data/RangeBasedSet.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/data/TimeSet.kt
  service/src/test/kotlin/fi/espoo/evaka/shared/ArbExtensions.kt
  service/src/test/kotlin/fi/espoo/evaka/shared/data/DateSetPropertyTest.kt
  service/src/test/kotlin/fi/espoo/evaka/shared/data/DateTimeSetPropertyTest.kt
  service/src/test/kotlin/fi/espoo/evaka/shared/data/RangeBasedSetPropertyTest.kt
Labels: tech

#5788 Yksikkökalenterissa henkilökunnan ei-reaaliaikaiset läsnäolot voi merkitä vain toimintapäiville
  frontend/src/employee-frontend/components/absences/StaffAttendance.tsx
Labels: enhancement

#5786 Ei näytetä hetua hakemuslistauksessa
  frontend/src/employee-frontend/components/applications/ApplicationsList.tsx
  frontend/src/lib-common/generated/api-types/application.ts
  service/src/main/kotlin/fi/espoo/evaka/application/Application.kt
  service/src/main/kotlin/fi/espoo/evaka/application/ApplicationQueries.kt
Labels: enhancement

#5787 Espoo: päivityksiä maksu- ja arvopäätösten teksteihin
  service/src/main/resources/WEB-INF/templates/fee-decision/decision.properties
  service/src/main/resources/WEB-INF/templates/fee-decision/decision_sv.properties
  service/src/main/resources/WEB-INF/templates/fee-decision/voucher-value-decision.properties
  service/src/main/resources/WEB-INF/templates/fee-decision/voucher-value-decision_sv.properties
Labels: no-changelog

#5769 Palveluntarpeen muutoshakemuksen infotekstit
  frontend/src/citizen-frontend/children/sections/service-need-and-daily-service-time/NewServiceApplicationPage.tsx
  frontend/src/citizen-frontend/children/sections/service-need-and-daily-service-time/ServiceApplications.tsx
  frontend/src/lib-customizations/defaults/citizen/i18n/en.tsx
  frontend/src/lib-customizations/defaults/citizen/i18n/fi.tsx
  frontend/src/lib-customizations/defaults/citizen/i18n/sv.tsx
Labels: enhancement

#5726 Viimeinen muokkaaja ja viimeisen muutoksen aika lisätty palvelusetelikertoimeen ja tukikertoimeen
  frontend/src/e2e-test/dev-api/fixtures.ts
  frontend/src/e2e-test/generated/api-types.ts
  frontend/src/e2e-test/pages/employee/child-information.ts
  frontend/src/e2e-test/specs/0_citizen/citizen-reservations.spec.ts
  frontend/src/e2e-test/specs/5_employee/child-information-assistance.spec.ts
  frontend/src/employee-frontend/components/child-information/AssistanceNeedVoucherCoefficientSection.tsx
  frontend/src/employee-frontend/components/child-information/assistance-need/voucher-coefficient/AssistanceNeedVoucherCoefficientRow.tsx
  frontend/src/employee-frontend/components/child-information/assistance/AssistanceFactorRow.tsx
  frontend/src/employee-frontend/components/child-information/assistance/AssistanceFactorSection.tsx
  frontend/src/lib-common/generated/api-types/assistance.ts
  frontend/src/lib-common/generated/api-types/assistanceneed.ts
  frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
  service/src/integrationTest/kotlin/fi/espoo/evaka/TestFixtures.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/assistanceneed/AssistanceNeedVoucherCoefficientEndOutdatedTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/espoo/bi/EspooBiTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/service/VoucherValueDecisionGeneratorIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/koski/KoskiIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/reports/AttendanceReservationReportTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/shared/db/SchemaConventionsTest.kt
  service/src/main/kotlin/fi/espoo/evaka/assistance/Assistance.kt
  service/src/main/kotlin/fi/espoo/evaka/assistance/AssistanceQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/assistanceneed/vouchercoefficient/AssistanceNeedVoucherCoefficient.kt
  service/src/main/kotlin/fi/espoo/evaka/assistanceneed/vouchercoefficient/AssistanceNeedVoucherCoefficientController.kt
  service/src/main/kotlin/fi/espoo/evaka/assistanceneed/vouchercoefficient/AssistanceNeedVoucherCoefficientQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/dev/DataInitializers.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/dev/DevApi.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/job/ScheduledJobs.kt
  service/src/main/resources/db/migration/V445__assistance_need_voucher_coefficient_modified_by.sql
  service/src/main/resources/migrations.txt
Labels: enhancement

#5799 Tiedotteita ei lähetetä suljettuihin ryhmiin
  service/src/integrationTest/kotlin/fi/espoo/evaka/messaging/MessageQueriesTest.kt
  service/src/main/kotlin/fi/espoo/evaka/messaging/MessageQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/messaging/MessageService.kt
Labels: bug

#5785 Viestin uudelleenvalinta kohdistaa sen samoin kuin ensimmäisellä kerralla
  frontend/src/citizen-frontend/messages/MessagesPage.tsx
  frontend/src/citizen-frontend/messages/ThreadView.tsx
Labels: enhancement

#5794 Näytetään ryhmän tapahtumakalenterissa myös vuorohoidon toimintapäivät
  frontend/src/employee-frontend/components/unit/TabCalendar.tsx
Labels: bug

#5798 Lokitetaan X-Amzn-Trace-Id (AWS trace ID) proxy:ssä
  frontend/proxy/files/etc/nginx/conf.d/nginx.conf.template
Labels: tech

#5797 Yhdistetään kaksi huoltajien tietojen hakuendpointtia ja korjataan samalla flaky E2E-testi
  frontend/src/employee-frontend/components/child-information/Guardians.tsx
  frontend/src/employee-frontend/generated/api-clients/pis.ts
  frontend/src/employee-frontend/state/child.tsx
  frontend/src/lib-common/generated/api-types/pis.ts
  service/src/integrationTest/kotlin/fi/espoo/evaka/pis/controller/PersonControllerIntegrationTest.kt
  service/src/main/kotlin/fi/espoo/evaka/pis/controllers/PersonController.kt
Labels: tech

#5793 Viestiketjun poistamisesta indikaatio ruudunlukijalle
  frontend/src/citizen-frontend/messages/MessagesPage.tsx
  frontend/src/citizen-frontend/messages/ThreadList.tsx
  frontend/src/e2e-test/pages/citizen/citizen-messages.ts
  frontend/src/e2e-test/specs/7_messaging/messaging.spec.ts
  frontend/src/lib-customizations/defaults/citizen/i18n/en.tsx
  frontend/src/lib-customizations/defaults/citizen/i18n/fi.tsx
  frontend/src/lib-customizations/defaults/citizen/i18n/sv.tsx
Labels: enhancement

#5762 Läsnäolomodaalin saavutettavuusparannuksia
  frontend/src/citizen-frontend/calendar/TimeRangeInput.tsx
  frontend/src/citizen-frontend/calendar/reservation-modal/TimeInputs.tsx
  frontend/src/lib-components/atoms/buttons/icon-only-button-visuals.tsx
  frontend/src/lib-components/atoms/form/InputField.tsx
  frontend/src/lib-components/atoms/form/TimeInput.tsx
  frontend/src/lib-customizations/defaults/citizen/i18n/en.tsx
  frontend/src/lib-customizations/defaults/citizen/i18n/fi.tsx
  frontend/src/lib-customizations/defaults/citizen/i18n/sv.tsx
Labels: enhancement

#5803 Vahvistusdialogi jamix-uudelleenlähetykseen
  frontend/src/employee-frontend/components/reports/MealReport.tsx
  frontend/src/employee-frontend/components/reports/queries.ts
  frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
Labels: enhancement

#5804 Keskustelun aihe ja lapsen nimi poistettu keskusteluajan sähköposteista
  service/src/integrationTest/kotlin/fi/espoo/evaka/calendarevent/CalendarEventServiceIntegrationTest.kt
  service/src/main/kotlin/fi/espoo/evaka/calendarevent/CalendarEventNotificationService.kt
  service/src/main/kotlin/fi/espoo/evaka/calendarevent/CalendarEventQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/emailclient/EvakaEmailMessageProvider.kt
  service/src/main/kotlin/fi/espoo/evaka/emailclient/IEmailMessageProvider.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/dev/DevApi.kt
Labels: enhancement

#5790 Lisätty "Tallennus onnistui" poissaolo- ja läsnäolovarausmodaaleihin
  frontend/src/citizen-frontend/calendar/AbsenceModal.tsx
  frontend/src/citizen-frontend/calendar/CalendarPage.tsx
  frontend/src/citizen-frontend/calendar/DayView.tsx
  frontend/src/e2e-test/pages/citizen/citizen-calendar.ts
  frontend/src/e2e-test/specs/0_citizen/citizen-reservations.spec.ts
  frontend/src/lib-customizations/defaults/citizen/i18n/en.tsx
  frontend/src/lib-customizations/defaults/citizen/i18n/fi.tsx
  frontend/src/lib-customizations/defaults/citizen/i18n/sv.tsx
Labels: enhancement

#5816 Lisätty optimointityökaluun mahdollisuus viedä hakemus päätöksen valmisteluun asti
  service/src/integrationTest/kotlin/fi/espoo/evaka/FullApplicationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/application/PlacementToolServiceIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/reports/AssistanceNeedsAndActionsReportControllerTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/reservations/ReservationControllerCitizenIntegrationTest.kt
  service/src/main/kotlin/fi/espoo/evaka/application/ApplicationStateService.kt
  service/src/main/kotlin/fi/espoo/evaka/application/PlacementToolService.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/FeatureConfig.kt
Labels: enhancement

#5817 Lisätty optimointityökaluun tuki hetuille
  service/src/integrationTest/kotlin/fi/espoo/evaka/application/PlacementToolServiceIntegrationTest.kt
  service/src/main/kotlin/fi/espoo/evaka/application/PlacementToolService.kt
  service/src/main/kotlin/fi/espoo/evaka/pis/service/FridgeFamilyService.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/async/AsyncJob.kt
Labels: enhancement

#5820 Korjaa testin
  service/src/integrationTest/kotlin/fi/espoo/evaka/application/PlacementToolServiceIntegrationTest.kt
Labels: no-changelog

#5826 Korjaus pelkkään esiopetukseen sijoitettujen lasten toteumalaskentaan
  service/src/integrationTest/kotlin/fi/espoo/evaka/absence/AbsenceServiceIntegrationTest.kt
  service/src/main/kotlin/fi/espoo/evaka/absence/AbsenceQueries.kt
Labels: bug

#5829 Lisätään tietokantaskeematesti `daterange`:n ja `datemultirange`:n raja-arvoille
  service/src/integrationTest/kotlin/fi/espoo/evaka/shared/db/SchemaConventionsTest.kt
  service/src/main/resources/db/migration/V446__consistent_daterange_checks.sql
  service/src/main/resources/migrations.txt
Labels: tech

#5823 Estetään tyhjät kyselyt Digitransit API:in
  frontend/src/citizen-frontend/map/api.ts
Labels: bug

#5815 Ei huomioida päätösluonnoksia hakemusprosessin metatiedoissa
  service/src/main/kotlin/fi/espoo/evaka/process/ProcessMetadataController.kt
Labels: bug

#5831 Lisätty näkyvä validaatiovirhe keskusteluajoille uuden kyselyn luonnissa
  frontend/src/employee-frontend/components/unit/tab-calendar/discussion-surveys/times-calendar/CalendarEventTimeInput.tsx
Labels: enhancement

#5819 Korjattu piilotetun hakemuksen päätökset-laskuri
  service/src/integrationTest/kotlin/fi/espoo/evaka/decision/DecisionCreationIntegrationTest.kt
  service/src/main/kotlin/fi/espoo/evaka/application/ApplicationQueries.kt
Labels: bug

#5818 Lasten tiedot: Pedagoginen dokumentointi: kuka muokanut viimeksi ja milloin
  frontend/src/citizen-frontend/children/sections/pedagogical-documents/PedagogicalDocumentsSection.tsx
  frontend/src/e2e-test/dev-api/fixtures.ts
  frontend/src/e2e-test/generated/api-types.ts
  frontend/src/employee-frontend/components/child-information/PedagogicalDocumentRow.tsx
  frontend/src/employee-frontend/components/child-information/PedagogicalDocuments.tsx
  frontend/src/lib-common/generated/api-types/pedagogicaldocument.ts
  frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
  service/src/integrationTest/kotlin/fi/espoo/evaka/pedagogicaldocument/PedagogicalDocumentIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/shared/db/SchemaConventionsTest.kt
  service/src/main/kotlin/fi/espoo/evaka/espoo/bi/EspooBi.kt
  service/src/main/kotlin/fi/espoo/evaka/espoo/bi/EspooBiModels.kt
  service/src/main/kotlin/fi/espoo/evaka/pedagogicaldocument/PedagogicalDocumentController.kt
  service/src/main/kotlin/fi/espoo/evaka/pedagogicaldocument/PedagogicalDocumentQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/dev/DataInitializers.kt
  service/src/main/resources/db/migration/V449__pedagogical_document_modified_by.sql
  service/src/main/resources/migrations.txt
Labels: enhancement

#5855 CVE-2024-38816: Päivitetään springframework
  service/evaka-bom/build.gradle.kts
Labels: dependencies

#5834 Parannuksia keskusteluaikojen kasvattajan käyttöliittymän muokkaustyökalujen indikointiin
  frontend/src/employee-frontend/components/unit/tab-calendar/discussion-surveys/times-calendar/CalendarEventTimeReservation.tsx
  frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
Labels: enhancement

#5838 Validoi Titanian lähettämät työvuorot ja koosta konfliktoivista vuoroista raportti
  frontend/src/employee-frontend/App.tsx
  frontend/src/employee-frontend/components/Reports.tsx
  frontend/src/employee-frontend/components/reports/TitaniaErrors.tsx
  frontend/src/employee-frontend/components/reports/queries.ts
  frontend/src/employee-frontend/generated/api-clients/reports.ts
  frontend/src/lib-common/generated/action.d.ts
  frontend/src/lib-common/generated/api-types/reports.ts
  frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
  frontend/src/lib-customizations/types.d.ts
  service/src/integrationTest/kotlin/fi/espoo/evaka/titania/TitaniaControllerTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/titania/TitaniaQueriesTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/titania/TitaniaServiceTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/titania/TitaniaTestData.kt
  service/src/main/kotlin/fi/espoo/evaka/Audit.kt
  service/src/main/kotlin/fi/espoo/evaka/reports/ReportPermissions.kt
  service/src/main/kotlin/fi/espoo/evaka/reports/TitaniaErrorsReport.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/job/ScheduledJobs.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/security/Action.kt
  service/src/main/kotlin/fi/espoo/evaka/titania/Titania.kt
  service/src/main/kotlin/fi/espoo/evaka/titania/TitaniaController.kt
  service/src/main/kotlin/fi/espoo/evaka/titania/TitaniaQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/titania/TitaniaService.kt
  service/src/main/resources/db/migration/V450__titania_errors.sql
  service/src/main/resources/migrations.txt
Labels: enhancement

#5854 Lapsen vaihtaminen kuntalaisen näkymässä ei päivittänyt pedagogisia asiakirjoja
  frontend/src/citizen-frontend/child-documents/queries.ts
  frontend/src/citizen-frontend/children/sections/ChildDocumentsSection.tsx
Labels: bug

#5857 Tietoturvakorjaus mobiilin pin-kirjautumiseen
  apigw/src/internal/mobile-device-session.ts
Labels: bug

#5731 Laskukorjausten kohdistuminen tiettyyn kuukauteen
  frontend/src/citizen-frontend/children/sections/service-need-and-daily-service-time/AttendanceSummaryTable.tsx
  frontend/src/citizen-frontend/children/sections/service-need-and-daily-service-time/queries.ts
  frontend/src/citizen-frontend/generated/api-clients/children.ts
  frontend/src/e2e-test/pages/employee/guardian-information.ts
  frontend/src/e2e-test/specs/5_employee/guardian-information-page.spec.ts
  frontend/src/employee-frontend/components/person-profile/PersonInvoiceCorrections.tsx
  frontend/src/employee-frontend/components/person-profile/queries.ts
  frontend/src/employee-frontend/generated/api-clients/invoicing.ts
  frontend/src/lib-common/date-range.ts
  frontend/src/lib-common/finite-date-range.ts
  frontend/src/lib-common/generated/api-types/invoicing.ts
  frontend/src/lib-common/json.d.ts
  frontend/src/lib-common/local-date.ts
  frontend/src/lib-common/year-month.ts
  frontend/src/lib-components/atoms/dropdowns/Select.tsx
  frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
  service/codegen/src/main/kotlin/evaka/codegen/api/Config.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/service/InvoiceCorrectionsIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/service/InvoiceGeneratorIntegrationTest.kt
  service/src/main/kotlin/fi/espoo/evaka/invoicing/controller/InvoiceController.kt
  service/src/main/kotlin/fi/espoo/evaka/invoicing/controller/InvoiceCorrectionsController.kt
  service/src/main/kotlin/fi/espoo/evaka/invoicing/data/InvoiceQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/invoicing/domain/Invoices.kt
  service/src/main/kotlin/fi/espoo/evaka/invoicing/service/InvoiceCorrection.kt
  service/src/main/kotlin/fi/espoo/evaka/invoicing/service/InvoiceCorrectionQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/invoicing/service/InvoiceGenerator.kt
  service/src/main/kotlin/fi/espoo/evaka/invoicing/service/InvoiceService.kt
  service/src/main/kotlin/fi/espoo/evaka/pis/InactivePeopleCleanup.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/async/AsyncJob.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/db/Db.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/db/JdbiExtensions.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/dev/DataInitializers.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/domain/Time.kt
  service/src/main/resources/db/migration/V451__invoice_correction_target.sql
  service/src/main/resources/migrations.txt
Labels: enhancement

#5827 Asiakasmaksupäätöksillä on aina loppupäivä
  frontend/src/e2e-test/dev-api/fixtures.ts
  frontend/src/e2e-test/generated/api-types.ts
  frontend/src/e2e-test/specs/0_citizen/citizen-finance-decisions.spec.ts
  frontend/src/e2e-test/specs/4_finance/fee-decisions.spec.ts
  frontend/src/e2e-test/specs/4_finance/invoices.spec.ts
  frontend/src/e2e-test/specs/4_finance/person-finance-decisions.spec.ts
  frontend/src/employee-frontend/components/fee-decision-details/Heading.tsx
  frontend/src/lib-common/generated/api-types/invoicing.ts
  service/src/integrationTest/kotlin/fi/espoo/evaka/espoo/bi/EspooBiTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/FeeDecisionIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/InvoiceIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/PaymentsIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/controller/FinanceDecisionCitizenIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/data/FeeDecisionQueriesTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/data/FeeDecisionSearchTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/data/VoucherValueDecisionQueriesTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/service/FeeDecisionGenerationForDataChangesIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/service/FeeDecisionGeneratorIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/service/InvoiceGeneratorIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/service/VoucherValueDecisionGenerationForDataChangesIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/service/VoucherValueDecisionGeneratorIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/reports/ServiceVoucherValueAreaReportTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/reports/ServiceVoucherValueUnitReportTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/shared/db/SchemaConventionsTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/varda/VardaServiceIntegrationTest.kt
  service/src/main/kotlin/fi/espoo/evaka/invoicing/data/FeeDecisionQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/invoicing/data/VoucherValueDecisionQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/invoicing/domain/FeeDecisions.kt
  service/src/main/kotlin/fi/espoo/evaka/invoicing/domain/FinanceDecisions.kt
  service/src/main/kotlin/fi/espoo/evaka/invoicing/domain/VoucherValueDecisions.kt
  service/src/main/kotlin/fi/espoo/evaka/invoicing/service/DraftInvoiceGenerator.kt
  service/src/main/kotlin/fi/espoo/evaka/invoicing/service/InvoiceGenerator.kt
  service/src/main/kotlin/fi/espoo/evaka/invoicing/service/VoucherValueDecisionService.kt
  service/src/main/kotlin/fi/espoo/evaka/invoicing/service/generator/FeeDecisionGeneratorV2.kt
  service/src/main/kotlin/fi/espoo/evaka/invoicing/service/generator/SharedLogic.kt
  service/src/main/kotlin/fi/espoo/evaka/invoicing/service/generator/VoucherValueDecisionGeneratorV2.kt
  service/src/main/kotlin/fi/espoo/evaka/pdfgen/PdfGenerator.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/domain/Time.kt
  service/src/main/kotlin/fi/espoo/evaka/timeline/TimelineController.kt
  service/src/main/resources/db/migration/V452__finance_decision_date_nullability.sql
  service/src/main/resources/migrations.txt
  service/src/test/kotlin/fi/espoo/evaka/invoicing/TestFixtures.kt
  service/src/test/kotlin/fi/espoo/evaka/invoicing/service/PdfGenerationTest.kt
  service/src/test/kotlin/fi/espoo/evaka/invoicing/service/generator/FeeDecisionGeneratorV2Test.kt
  service/src/test/kotlin/fi/espoo/evaka/invoicing/service/generator/VoucherValueDecisionGeneratorV2Test.kt
  service/src/test/kotlin/fi/espoo/evaka/shared/domain/TimeTest.kt
Labels: tech

#5868 Lisätään Koski-integraation PlantUML-kaavio
  docs/diagrams/src/koski-integration.puml
Labels: no-changelog

#5805 Parannetaan RangeBasedMap-tietorakenteiden suorituskykyä binäärihaulla
  service/src/main/kotlin/fi/espoo/evaka/shared/data/DateMap.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/data/DateTimeMap.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/data/DateTimeSet.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/data/RangeBasedMap.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/data/RangeBasedSet.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/domain/HelsinkiDateTime.kt
  service/src/test/kotlin/fi/espoo/evaka/shared/ArbExtensions.kt
  service/src/test/kotlin/fi/espoo/evaka/shared/data/DateMapPropertyTest.kt
  service/src/test/kotlin/fi/espoo/evaka/shared/data/DateSetPropertyTest.kt
  service/src/test/kotlin/fi/espoo/evaka/shared/data/DateTimeMapPropertyTest.kt
  service/src/test/kotlin/fi/espoo/evaka/shared/data/DateTimeSetPropertyTest.kt
  service/src/test/kotlin/fi/espoo/evaka/shared/data/RangeBasedMapPropertyTest.kt
  service/src/test/kotlin/fi/espoo/evaka/shared/data/RangeBasedSetPropertyTest.kt
Labels: tech

#5836 Espoo: Kerhopäätöksen tekstimuutos
  service/src/main/resources/WEB-INF/templates/club/decision.properties
Labels: no-changelog

#5835 Korjauksia ja parannuksia sähköpostinotifikaatioiden blokkaukseen
  frontend/src/citizen-frontend/generated/api-clients/pis.ts
  frontend/src/citizen-frontend/personal-details/NotificationSettingsSection.tsx
  frontend/src/e2e-test/dev-api/fixtures.ts
  frontend/src/e2e-test/generated/api-types.ts
  frontend/src/e2e-test/pages/citizen/citizen-personal-details.ts
  frontend/src/e2e-test/specs/0_citizen/citizen-personal-details.spec.ts
  frontend/src/lib-common/generated/api-types/pis.ts
  frontend/src/lib-customizations/defaults/citizen/i18n/en.tsx
  frontend/src/lib-customizations/defaults/citizen/i18n/fi.tsx
  frontend/src/lib-customizations/defaults/citizen/i18n/sv.tsx
  service/src/integrationTest/kotlin/fi/espoo/evaka/emailclient/EmailTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/FeeDecisionIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/VoucherValueDecisionIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/pis/controller/PersonalDataControllerCitizenIntegrationTest.kt
  service/src/main/kotlin/fi/espoo/evaka/calendarevent/CalendarEventNotificationService.kt
  service/src/main/kotlin/fi/espoo/evaka/emailclient/EmailClient.kt
  service/src/main/kotlin/fi/espoo/evaka/invoicing/service/NewCustomerIncomeNotification.kt
  service/src/main/kotlin/fi/espoo/evaka/invoicing/service/OutdatedIncomeNotifications.kt
  service/src/main/kotlin/fi/espoo/evaka/messaging/MessageNotificationEmailService.kt
  service/src/main/kotlin/fi/espoo/evaka/pis/PersonalData.kt
  service/src/main/kotlin/fi/espoo/evaka/pis/PersonalDataQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/pis/controllers/PersonalDataControllerCitizen.kt
  service/src/main/kotlin/fi/espoo/evaka/reservations/MissingHolidayReservationsReminders.kt
  service/src/main/kotlin/fi/espoo/evaka/reservations/MissingReservationsReminders.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/dev/DataInitializers.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/dev/DevApi.kt
  service/src/main/resources/db/migration/V453__email_message_type.sql
  service/src/main/resources/migrations.txt
Labels: enhancement

#5866 Poistettu henkilötunnuksen näkyminen Varhaiskasvatuksessa aloittavat/lopettavat raporteilta
  frontend/src/e2e-test/pages/employee/reports.ts
  frontend/src/e2e-test/specs/5_employee/ended-placements-report.spec.ts
  frontend/src/e2e-test/specs/5_employee/starting-placements-report.spec.ts
  frontend/src/employee-frontend/components/Reports.tsx
  frontend/src/employee-frontend/components/reports/EndedPlacements.tsx
  frontend/src/employee-frontend/components/reports/StartingPlacements.tsx
  frontend/src/lib-common/generated/api-types/reports.ts
  service/src/integrationTest/kotlin/fi/espoo/evaka/reports/StartingPlacementsReportTest.kt
  service/src/main/kotlin/fi/espoo/evaka/reports/EndedPlacementsReport.kt
  service/src/main/kotlin/fi/espoo/evaka/reports/StartingPlacementsReport.kt
Labels: enhancement

#5837 Näytetään ryhmitystä odottavat lapset vain jos sijoitus on seuraavan kuuden kuukauden aikana
  service/src/main/kotlin/fi/espoo/evaka/daycare/controllers/DaycareController.kt
  service/src/main/kotlin/fi/espoo/evaka/placement/PlacementService.kt
Labels: enhancement

#5860 Lisätään raakaraportille palveluntarve
  frontend/src/employee-frontend/components/reports/Raw.tsx
  frontend/src/lib-common/generated/api-types/reports.ts
  service/src/integrationTest/kotlin/fi/espoo/evaka/reports/RawReportControllerTest.kt
  service/src/main/kotlin/fi/espoo/evaka/reports/RawReport.kt
Labels: enhancement

#5858 Laskujen muodostuksen tekniset parannukset
  service/src/main/kotlin/fi/espoo/evaka/invoicing/domain/FeeThresholds.kt
  service/src/main/kotlin/fi/espoo/evaka/invoicing/service/DraftInvoiceGenerator.kt
  service/src/main/kotlin/fi/espoo/evaka/invoicing/service/InvoiceGenerator.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/data/DateSet.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/db/JdbiExtensions.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/domain/Time.kt
  service/src/test/kotlin/fi/espoo/evaka/shared/domain/TimeTest.kt
Labels: tech

#5881 Käsitellään edellisten Varda-lähdejärjestelmien maksutiedot oikein
  service/src/integrationTest/kotlin/fi/espoo/evaka/varda/new/VardaUpdaterIntegrationTest.kt
  service/src/main/kotlin/fi/espoo/evaka/varda/new/VardaUpdateServiceNew.kt
Labels: bug

#5839 Muutoksia viestien näkyvyyteen ja sallittuihin vastaanottajiin
  frontend/src/citizen-frontend/messages/MessageEditor.tsx
  frontend/src/citizen-frontend/messages/MessagesPage.tsx
  frontend/src/citizen-frontend/messages/ThreadView.tsx
  frontend/src/e2e-test/specs/7_messaging/messaging.spec.ts
  service/src/integrationTest/kotlin/fi/espoo/evaka/messaging/MessageIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/messaging/MessageQueriesTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/pis/SystemControllerCitizenTest.kt
  service/src/main/kotlin/fi/espoo/evaka/messaging/MessageQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/messaging/MessageService.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/security/AccessControlCitizen.kt
Labels: enhancement

#5884 Parannetaan `InvoiceGenerationLogicChooser`-rajapintaa
  service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/service/InvoiceCorrectionsIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/service/InvoiceGeneratorIntegrationTest.kt
  service/src/main/kotlin/fi/espoo/evaka/invoicing/service/DraftInvoiceGenerator.kt
  service/src/main/kotlin/fi/espoo/evaka/invoicing/service/InvoiceGenerator.kt
Labels: tech
