Repository espoon-voltti/evaka, pull requests merged in 2024-11, with the labels that each got.

#5891 Refaktoroidaan employee-frontendin routet
  frontend/src/employee-mobile-frontend/App.tsx
  frontend/src/employee-mobile-frontend/child-attendance/AttendanceList.tsx
  frontend/src/employee-mobile-frontend/child-attendance/AttendancePageWrapper.tsx
  frontend/src/employee-mobile-frontend/child-attendance/ChildList.tsx
  frontend/src/employee-mobile-frontend/child-attendance/ChildListItem.tsx
  frontend/src/employee-mobile-frontend/child-attendance/actions/MarkAbsent.tsx
  frontend/src/employee-mobile-frontend/child-attendance/actions/MarkAbsentBeforehand.tsx
  frontend/src/employee-mobile-frontend/child-attendance/actions/MarkDeparted.tsx
  frontend/src/employee-mobile-frontend/child-attendance/actions/MarkPresent.tsx
  frontend/src/employee-mobile-frontend/child-attendance/actions/MarkReservations.tsx
  frontend/src/employee-mobile-frontend/child-info/AttendanceChildPage.tsx
  frontend/src/employee-mobile-frontend/child-info/ChildButtons.tsx
  frontend/src/employee-mobile-frontend/child-info/ChildInfoPage.tsx
  frontend/src/employee-mobile-frontend/child-info/child-state-pages/AttendanceChildComing.tsx
  frontend/src/employee-mobile-frontend/child-info/child-state-pages/AttendanceChildDeparted.tsx
  frontend/src/employee-mobile-frontend/child-info/child-state-pages/AttendanceChildPresent.tsx
  frontend/src/employee-mobile-frontend/child-notes/ChildNotes.tsx
  frontend/src/employee-mobile-frontend/messages/NewChildMessagePage.tsx
Labels: tech

#5904 Lisätään tuloselvitykset-listaan yksikön mukaan suodatus
  frontend/src/employee-frontend/components/common/Filters.tsx
  frontend/src/employee-frontend/components/fee-decisions/FeeDecisionFilters.tsx
  frontend/src/employee-frontend/components/income-statements/IncomeStatementFilters.tsx
  frontend/src/employee-frontend/components/income-statements/IncomeStatementsPage.tsx
  frontend/src/employee-frontend/components/invoices/InvoiceFilters.tsx
  frontend/src/employee-frontend/components/payments/PaymentFilters.tsx
  frontend/src/employee-frontend/components/unit/queries.ts
  frontend/src/employee-frontend/components/voucher-value-decisions/VoucherValueDecisionFilters.tsx
  frontend/src/employee-frontend/state/invoicing-ui.tsx
  frontend/src/lib-common/generated/api-types/incomestatement.ts
  service/src/integrationTest/kotlin/fi/espoo/evaka/incomestatement/IncomeStatementControllerIntegrationTest.kt
  service/src/main/kotlin/fi/espoo/evaka/incomestatement/IncomeStatementController.kt
  service/src/main/kotlin/fi/espoo/evaka/incomestatement/IncomeStatementQueries.kt
Labels: enhancement

#5905 Korjaa testin
  service/src/integrationTest/kotlin/fi/espoo/evaka/occupancy/OccupancyControllerIntegrationTest.kt
Labels: no-changelog

#5882 Parempi S3-rajapinta evaka-servicessä
  service/src/integrationTest/kotlin/fi/espoo/evaka/attachments/AttachmentServiceTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/pis/service/MergeServiceIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/s3/S3DocumentServiceIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/sficlient/SoapStackIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/sficlient/rest/SfiMessagesRestClientIntegrationTest.kt
  service/src/main/kotlin/fi/espoo/evaka/assistanceneed/decision/AssistanceNeedDecisionService.kt
  service/src/main/kotlin/fi/espoo/evaka/assistanceneed/preschooldecision/AssistanceNeedPreschoolDecisionService.kt
  service/src/main/kotlin/fi/espoo/evaka/attachment/AttachmentService.kt
  service/src/main/kotlin/fi/espoo/evaka/attachment/AttachmentsController.kt
  service/src/main/kotlin/fi/espoo/evaka/childimages/ChildImage.kt
  service/src/main/kotlin/fi/espoo/evaka/childimages/ChildImageController.kt
  service/src/main/kotlin/fi/espoo/evaka/decision/DecisionService.kt
  service/src/main/kotlin/fi/espoo/evaka/document/childdocument/ChildDocumentService.kt
  service/src/main/kotlin/fi/espoo/evaka/invoicing/service/FeeDecisionService.kt
  service/src/main/kotlin/fi/espoo/evaka/invoicing/service/VoucherValueDecisionService.kt
  service/src/main/kotlin/fi/espoo/evaka/pis/service/MergeService.kt
  service/src/main/kotlin/fi/espoo/evaka/s3/DocumentKey.kt
  service/src/main/kotlin/fi/espoo/evaka/s3/DocumentService.kt
  service/src/main/kotlin/fi/espoo/evaka/s3/S3DocumentService.kt
  service/src/main/kotlin/fi/espoo/evaka/sficlient/SfiMessagesSoapClient.kt
  service/src/main/kotlin/fi/espoo/evaka/sficlient/rest/SfiMessagesRestClient.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/dev/DevApi.kt
Labels: tech

#5880 Poistetaan vanhat käyttämättömät tuen tarpeen tietokantataulut
  service/src/integrationTest/kotlin/fi/espoo/evaka/pis/PersonIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/shared/db/SchemaConventionsTest.kt
  service/src/main/resources/db/migration/R__application_view.sql
  service/src/main/resources/db/migration/V456__legacy_assistance_need_tables.sql
  service/src/main/resources/migrations.txt
Labels: tech

#5908 Korjataan rikkinäinen migraatio
  service/src/main/resources/db/migration/V456__legacy_assistance_need_tables.sql
Labels: no-changelog

#5909 Lisätään query-parametrien tuki uri-builderiin
  frontend/src/lib-common/uri.spec.ts
  frontend/src/lib-common/uri.ts
Labels: tech

#5907 Mahdollistettu varhaiskasvatuksen tuen päätöksen toimivalta-tekstin muotoilu
  frontend/src/employee-frontend/components/child-information/assistance-need/decision/AssistanceNeededDecisionForm.tsx
  frontend/src/lib-components/assistance-need-decision/AssistanceNeedDecisionReadOnly.tsx
  frontend/src/lib-customizations/defaults/citizen/i18n/fi.tsx
  frontend/src/lib-customizations/defaults/citizen/i18n/sv.tsx
  frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
  frontend/src/lib-customizations/defaults/employee/i18n/sv.tsx
Labels: tech, breaking

#5911 Validate pull request labels
  .github/workflows/validate-labels.yml
  bin/validate-labels.js
Labels: no-changelog

#5883 Poistetaan deprekoitu sarake person.enabled_email_types
  service/src/main/resources/db/migration/V457__drop_enabled_email_types.sql
  service/src/main/resources/migrations.txt
Labels: tech

#5862 Kasvattajalle mahdollisuus poistaa lapsen kaikki yhden kyselyn keskusteluaikavaraukset kerralla
  frontend/src/e2e-test/pages/employee/units/unit-discussion-survey-page.ts
  frontend/src/e2e-test/specs/5_employee/unit-calendar-events.spec.ts
  frontend/src/employee-frontend/components/unit/tab-calendar/discussion-surveys/DiscussionSurveyView.tsx
  frontend/src/employee-frontend/components/unit/tab-calendar/discussion-surveys/InviteeSection.tsx
  frontend/src/employee-frontend/components/unit/tab-calendar/queries.ts
  frontend/src/employee-frontend/generated/api-clients/calendarevent.ts
  frontend/src/lib-common/generated/api-types/calendarevent.ts
  frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
  service/src/integrationTest/kotlin/fi/espoo/evaka/calendarevent/CalendarEventServiceIntegrationTest.kt
  service/src/main/kotlin/fi/espoo/evaka/Audit.kt
  service/src/main/kotlin/fi/espoo/evaka/calendarevent/CalendarEvent.kt
  service/src/main/kotlin/fi/espoo/evaka/calendarevent/CalendarEventController.kt
  service/src/main/kotlin/fi/espoo/evaka/calendarevent/CalendarEventQueries.kt
Labels: enhancement

#5885 Rajoitetaan uuden työntekijän näkemiä ryhmäpostilaatikon viestejä
  frontend/src/e2e-test/dev-api/fixtures.ts
  frontend/src/e2e-test/generated/api-types.ts
  frontend/src/e2e-test/specs/6_mobile/messages.spec.ts
  frontend/src/e2e-test/specs/7_messaging/messaging-by-staff.spec.ts
  frontend/src/e2e-test/specs/7_messaging/municipal-messaging.spec.ts
  service/src/integrationTest/kotlin/fi/espoo/evaka/attendance/MobileRealtimeStaffAttendanceControllerIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/attendance/RealtimeStaffAttendanceControllerIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/messaging/MessageAccountQueriesTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/messaging/MessageIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/pis/InactiveEmployeesRoleResetIntegrationTest.kt
  service/src/main/kotlin/fi/espoo/evaka/daycare/controllers/UnitAclController.kt
  service/src/main/kotlin/fi/espoo/evaka/messaging/DraftQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/messaging/MessageController.kt
  service/src/main/kotlin/fi/espoo/evaka/messaging/MessageQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/auth/AclQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/dev/DataInitializers.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/dev/DevApi.kt
Labels: enhancement

#5917 Korjataan väärinymmärrys Suomi.fi REST salasanan vaihdossa
  service/src/integrationTest/kotlin/fi/espoo/evaka/sficlient/rest/MockSfiMessagesRestEndpoint.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/sficlient/rest/SfiMessagesRestClientIntegrationTest.kt
  service/src/main/kotlin/fi/espoo/evaka/sficlient/rest/SfiMessagesRestClient.kt
Labels: bug

#5915 Palveluntarpeen muutoshakemuksessa lisätiedot vaaditaan jos ei kuun ensimmäinen päivä
  frontend/src/citizen-frontend/children/sections/service-need-and-daily-service-time/NewServiceApplicationPage.tsx
  frontend/src/lib-customizations/defaults/citizen/i18n/en.tsx
  frontend/src/lib-customizations/defaults/citizen/i18n/fi.tsx
  frontend/src/lib-customizations/defaults/citizen/i18n/sv.tsx
Labels: enhancement

#5912 Nostetaan "käsittelyä odottavat palveluntarpeen muutoshakemukset" osio ylimmäiseksi
  frontend/src/employee-frontend/components/unit/TabApplicationProcess.tsx
Labels: enhancement

#5922 Korjaus Jamix-synkronoinnin aikatauluun
  service/src/main/kotlin/fi/espoo/evaka/shared/job/ScheduledJobs.kt
Labels: enhancement

#5921 Korjataan frontend docker copy -komento
  frontend/Dockerfile
Labels: tech

#5919 Lisätään maksatukseen eräpäivän konfigurointi
  frontend/src/employee-frontend/components/payments/PaymentsPage.tsx
  frontend/src/lib-customizations/employee.tsx
  frontend/src/lib-customizations/types.d.ts
Labels: enhancement

#5892 Lisätään Aromi-csv poc
  frontend/src/employee-frontend/components/reports/AttendanceReservationByChild.tsx
  frontend/src/employee-frontend/components/reports/ReportDownload.tsx
  frontend/src/lib-common/generated/action.d.ts
  frontend/src/lib-common/generated/api-types/reports.ts
  frontend/src/lib-customizations/types.d.ts
  service/.gitattributes
  service/src/integrationTest/kotlin/fi/espoo/evaka/aromi/AromiControllerTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/reports/AttendanceReservationReportByChildTest.kt
  service/src/main/kotlin/fi/espoo/evaka/aromi/AromiController.kt
  service/src/main/kotlin/fi/espoo/evaka/aromi/AromiService.kt
  service/src/main/kotlin/fi/espoo/evaka/reports/AttendanceReservationReportController.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/security/Action.kt
  service/src/test/resources/aromi/ok-admin.csv
  service/src/test/resources/aromi/ok-admin.csv.license
Labels: enhancement

#5923 Sähköpostinotifikaatio käsitellystä palveluntarpeen muutoshakemuksesta
  service/src/integrationTest/kotlin/fi/espoo/evaka/serviceneed/application/ServiceApplicationIntegrationTest.kt
  service/src/main/kotlin/fi/espoo/evaka/emailclient/EvakaEmailMessageProvider.kt
  service/src/main/kotlin/fi/espoo/evaka/emailclient/IEmailMessageProvider.kt
  service/src/main/kotlin/fi/espoo/evaka/serviceneed/application/ServiceApplicationController.kt
  service/src/main/kotlin/fi/espoo/evaka/serviceneed/application/ServiceApplicationService.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/async/AsyncJob.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/dev/DevApi.kt
Labels: enhancement

#5910 Lasten tiedot: Tulotiedot/alennukset vapautukset ja korotukset: kuka muokannut ja milloin
  frontend/src/e2e-test/dev-api/fixtures.ts
  frontend/src/e2e-test/generated/api-types.ts
  frontend/src/e2e-test/specs/0_citizen/citizen-income.spec.ts
  frontend/src/e2e-test/specs/5_employee/fridge-head-information.spec.ts
  frontend/src/e2e-test/specs/5_employee/income.spec.ts
  frontend/src/employee-frontend/components/child-information/FeeAlteration.tsx
  frontend/src/employee-frontend/components/child-information/fee-alteration/FeeAlterationList.tsx
  frontend/src/employee-frontend/components/person-profile/income/IncomeItemBody.tsx
  frontend/src/employee-frontend/components/person-profile/income/IncomeItemEditor.tsx
  frontend/src/employee-frontend/components/person-profile/income/IncomeItemHeader.tsx
  frontend/src/employee-frontend/components/person-profile/income/IncomeList.tsx
  frontend/src/employee-frontend/types/fee-alteration.ts
  frontend/src/lib-common/generated/api-types/invoicing.ts
  frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
  service/src/integrationTest/kotlin/fi/espoo/evaka/TestFixtures.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/attachments/AttachmentQueriesTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/attachments/AttachmentServiceTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/incomestatement/IncomeStatementControllerIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/FeeAlterationIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/IncomeIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/controller/IncomeControllerCitizenIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/data/FeeAlterationQueriesTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/service/FeeDecisionGenerationForDataChangesIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/service/FeeDecisionGeneratorIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/service/OutdatedIncomeNotificationsIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/service/VoucherValueDecisionGenerationForDataChangesIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/service/VoucherValueDecisionGeneratorIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/pis/controller/FamilyOverviewTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/pis/service/MergeServiceIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/shared/db/SchemaConventionsTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/timeline/TimelineControllerIntegrationTest.kt
  service/src/main/kotlin/fi/espoo/evaka/invoicing/controller/FeeAlterationController.kt
  service/src/main/kotlin/fi/espoo/evaka/invoicing/controller/IncomeController.kt
  service/src/main/kotlin/fi/espoo/evaka/invoicing/data/FeeAlterationQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/invoicing/data/IncomeQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/invoicing/domain/FeeAlterations.kt
  service/src/main/kotlin/fi/espoo/evaka/invoicing/domain/Incomes.kt
  service/src/main/kotlin/fi/espoo/evaka/invoicing/service/OutdatedIncomeNotifications.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/dev/DataInitializers.kt
  service/src/main/resources/db/migration/V458__income_adjustments_modified_metadata.sql
  service/src/main/resources/migrations.txt
Labels: enhancement

#5888 Usean lapsen sisäänkirjaaminen mobiilissa yhtä aikaa
  frontend/src/e2e-test/pages/mobile/list-page.ts
  frontend/src/e2e-test/specs/6_mobile/child-attendances.spec.ts
  frontend/src/employee-mobile-frontend/App.tsx
  frontend/src/employee-mobile-frontend/child-attendance/AttendanceList.tsx
  frontend/src/employee-mobile-frontend/child-attendance/AttendancePageWrapper.tsx
  frontend/src/employee-mobile-frontend/child-attendance/ChildList.tsx
  frontend/src/employee-mobile-frontend/child-attendance/ChildListItem.tsx
  frontend/src/employee-mobile-frontend/child-attendance/ChildNotesSummary.tsx
  frontend/src/employee-mobile-frontend/child-attendance/actions/MarkAbsent.tsx
  frontend/src/employee-mobile-frontend/child-attendance/actions/MarkDeparted.tsx
  frontend/src/employee-mobile-frontend/child-attendance/actions/MarkPresent.tsx
  frontend/src/employee-mobile-frontend/child-attendance/queries.ts
  frontend/src/employee-mobile-frontend/child-info/child-state-pages/AttendanceChildComing.tsx
  frontend/src/employee-mobile-frontend/child-info/child-state-pages/AttendanceChildDeparted.tsx
  frontend/src/employee-mobile-frontend/generated/api-clients/attendance.ts
  frontend/src/lib-common/generated/api-types/attendance.ts
  frontend/src/lib-customizations/defaults/employee-mobile-frontend/i18n/fi.ts
  service/src/integrationTest/kotlin/fi/espoo/evaka/attendance/AttendanceTransitionsIntegrationTest.kt
  service/src/main/kotlin/fi/espoo/evaka/attendance/ChildAttendanceController.kt
Labels: enhancement

#5931 Piilotetaan arkistoitavat metatiedot lomakkeiden tulosteista
  frontend/src/employee-frontend/components/archive-metadata/MetadataSection.tsx
Labels: bug

#5934 Palautetaan lapset oikein laskuhaussa
  service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/InvoiceIntegrationTest.kt
  service/src/main/kotlin/fi/espoo/evaka/invoicing/data/InvoiceQueries.kt
Labels: bug

#5861 Lasten tiedot: Sijoitusehdotustiedot: kuka hyväksynyt ja milloin/ hakemukselle tieto sijoitusehdotukesta
  frontend/src/employee-frontend/components/applications/ApplicationsList.tsx
  frontend/src/lib-common/generated/api-types/application.ts
  frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
  service/src/main/kotlin/fi/espoo/evaka/application/Application.kt
  service/src/main/kotlin/fi/espoo/evaka/application/ApplicationQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/application/ApplicationStateService.kt
  service/src/main/kotlin/fi/espoo/evaka/placement/PlacementControllerCitizen.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/job/ScheduledJobs.kt
  service/src/main/resources/db/migration/V460__modification_metadata.sql
  service/src/main/resources/migrations.txt
Labels: enhancement

#5920 Puuttuvat tulotiedot - raportti
  frontend/src/employee-frontend/App.tsx
  frontend/src/employee-frontend/components/Reports.tsx
  frontend/src/employee-frontend/components/reports/IncompleteIncomeReport.tsx
  frontend/src/employee-frontend/components/reports/queries.ts
  frontend/src/employee-frontend/generated/api-clients/reports.ts
  frontend/src/lib-common/generated/action.d.ts
  frontend/src/lib-common/generated/api-types/reports.ts
  frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
  service/src/integrationTest/kotlin/fi/espoo/evaka/reports/IncompleteIncomeReportTest.kt
  service/src/main/kotlin/fi/espoo/evaka/Audit.kt
  service/src/main/kotlin/fi/espoo/evaka/reports/IncompleteIncomeReport.kt
  service/src/main/kotlin/fi/espoo/evaka/reports/ReportPermissions.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/security/Action.kt
Labels: enhancement

#5887 Korjataan päivän valinta enterillä
  frontend/src/lib-components/molecules/date-picker/DatePickerLowLevel.tsx
Labels: bug

#5928 Tekstimuutoksia Espoon tuloselvitykselle
  frontend/src/lib-customizations/espoo/citizen.tsx
Labels: no-changelog

#5925 Oikaisulaskut, osa 1: Laskujen yöllinen generointi (ei vielä käytössä)
  frontend/src/e2e-test/dev-api/fixtures.ts
  frontend/src/e2e-test/generated/api-types.ts
  frontend/src/lib-common/generated/api-types/invoicing.ts
  frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
  service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/InvoiceIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/data/InvoiceQueriesTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/service/InvoiceCorrectionsIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/service/InvoiceGeneratorIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/service/ReplacementInvoicesIntegrationTest.kt
  service/src/main/kotlin/fi/espoo/evaka/EvakaEnv.kt
  service/src/main/kotlin/fi/espoo/evaka/invoicing/controller/InvoiceController.kt
  service/src/main/kotlin/fi/espoo/evaka/invoicing/data/InvoiceQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/invoicing/domain/Invoices.kt
  service/src/main/kotlin/fi/espoo/evaka/invoicing/service/InvoiceCorrectionQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/invoicing/service/InvoiceGenerator.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/dev/DataInitializers.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/dev/DevApi.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/job/ScheduledJobs.kt
  service/src/main/resources/db/migration/V461__replacement_invoices.sql
  service/src/main/resources/migrations.txt
  service/src/test/kotlin/fi/espoo/evaka/invoicing/integration/EspooInvoiceIntegrationClientTest.kt
Labels: enhancement

#5955 Korjaus laskuhakun tuloksiin, kun löydetyissä laskuissa ei ole yhtään riviä
  service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/InvoiceIntegrationTest.kt
  service/src/main/kotlin/fi/espoo/evaka/invoicing/data/InvoiceQueries.kt
Labels: bug

#5938 Salli vastaaminen erityisopettajan ja muun päiväkotihenkilöstön viesteihin
  frontend/src/citizen-frontend/messages/MessageEditor.tsx
  frontend/src/citizen-frontend/messages/MessagesPage.tsx
  frontend/src/citizen-frontend/messages/ThreadView.tsx
  frontend/src/lib-common/generated/api-types/messaging.ts
  service/src/integrationTest/kotlin/fi/espoo/evaka/messaging/MessageQueriesTest.kt
  service/src/main/kotlin/fi/espoo/evaka/messaging/MessageControllerCitizen.kt
  service/src/main/kotlin/fi/espoo/evaka/messaging/MessageQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/messaging/MessageService.kt
Labels: bug

#5894 Lisätään esiopetushakemukselle "sisaruksen koulu" lisätieto
  frontend/src/citizen-frontend/applications/editor/unit-preference/SiblingBasisSubSection.tsx
  frontend/src/citizen-frontend/applications/editor/validations.ts
  frontend/src/citizen-frontend/applications/editor/verification/UnitPreferenceSection.tsx
  frontend/src/e2e-test/utils/application-forms.ts
  frontend/src/employee-frontend/components/application-page/ApplicationEditView.tsx
  frontend/src/employee-frontend/components/application-page/ApplicationReadView.tsx
  frontend/src/lib-common/api-types/application/ApplicationFormData.ts
  frontend/src/lib-common/generated/api-types/application.ts
  frontend/src/lib-customizations/defaults/citizen/i18n/en.tsx
  frontend/src/lib-customizations/defaults/citizen/i18n/fi.tsx
  frontend/src/lib-customizations/defaults/citizen/i18n/sv.tsx
  frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
  service/src/integrationTest/kotlin/fi/espoo/evaka/application/GetApplicationIntegrationTests.kt
  service/src/main/kotlin/fi/espoo/evaka/application/ApplicationControllerCitizen.kt
  service/src/main/kotlin/fi/espoo/evaka/application/ApplicationForm.kt
  service/src/main/kotlin/fi/espoo/evaka/application/persistence/club/ClubFormV0.kt
  service/src/main/kotlin/fi/espoo/evaka/application/persistence/daycare/DaycareFormV0.kt
Labels: enhancement

#5937 Yhteystietosähköpostien päivitys
  README.md
Labels: no-changelog

#5886 Yksikön johtajien käyttöoikeus ja yksikön mukaan suodatus varhaiskasvatuksessa aloittavien raportille
  frontend/src/e2e-test/pages/employee/reports.ts
  frontend/src/e2e-test/specs/5_employee/starting-placements-report.spec.ts
  frontend/src/employee-frontend/components/reports/StartingPlacements.tsx
  frontend/src/employee-frontend/components/reports/queries.ts
  frontend/src/lib-common/generated/action.d.ts
  frontend/src/lib-common/generated/api-types/reports.ts
  frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
  service/src/integrationTest/kotlin/fi/espoo/evaka/reports/StartingPlacementsReportTest.kt
  service/src/main/kotlin/fi/espoo/evaka/reports/ReportPermissions.kt
  service/src/main/kotlin/fi/espoo/evaka/reports/StartingPlacementsReport.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/security/Action.kt
Labels: enhancement

#5918 Poistetaan vanhentuneet Suomi.fi SAML 2022 -sertifikaatit
  apigw/config/certificates/saml-signing-testi.apro.tunnistus.fi.2022.pem
  apigw/config/certificates/saml-signing.idp.tunnistautuminen.suomi.fi.2022.pem
  apigw/src/shared/certificates.ts
  apigw/src/shared/config.ts
Labels: tech

#5957 Tuen tarpeen päätöksen validointikorjaus
  service/src/main/kotlin/fi/espoo/evaka/assistanceneed/decision/AssistanceNeedDecisionController.kt
Labels: bug

#5935 Päätöstulosteiden tekstisisällön päivityksiä
  service/src/main/resources/WEB-INF/templates/daycare/decision.properties
  service/src/main/resources/WEB-INF/templates/daycare/decision_sv.properties
  service/src/main/resources/WEB-INF/templates/daycare/transfer/decision.properties
  service/src/main/resources/WEB-INF/templates/daycare/transfer/decision_sv.properties
  service/src/main/resources/WEB-INF/templates/daycare/voucher/decision.properties
  service/src/main/resources/WEB-INF/templates/daycare/voucher/decision_sv.properties
  service/src/main/resources/WEB-INF/templates/preparatory/decision.properties
Labels: enhancement

#5933 Lisätään pelkän täydentävän varhaiskasvatuksen sijoitustyyppi Vardaan vietävien listalle
  service/src/main/kotlin/fi/espoo/evaka/varda/new/VardaQueries.kt
Labels: bug

#5932 Näytetään päivälapset mobiilissa poissaolevina viikonloppuisin
  frontend/src/e2e-test/specs/6_mobile/child-attendances.spec.ts
  frontend/src/e2e-test/specs/6_mobile/messages.spec.ts
  frontend/src/employee-mobile-frontend/child-attendance/utils.ts
  frontend/src/employee-mobile-frontend/child-info/AttendanceChildPage.tsx
  frontend/src/lib-common/generated/api-types/attendance.ts
  service/src/main/kotlin/fi/espoo/evaka/attendance/ChildAttendance.kt
  service/src/main/kotlin/fi/espoo/evaka/attendance/ChildAttendanceController.kt
Labels: enhancement

#5929 Poistetaan deprekoitu endpoint
  frontend/src/employee-mobile-frontend/generated/api-clients/attendance.ts
  frontend/src/lib-common/generated/api-types/attendance.ts
  service/src/main/kotlin/fi/espoo/evaka/attendance/ChildAttendanceController.kt
Labels: tech

#5913 Lisätään tuloselvitykset-listaan uusia järjestämismahdollisuuksia
  frontend/src/employee-frontend/components/income-statements/IncomeStatementsPage.tsx
  frontend/src/lib-common/generated/api-types/incomestatement.ts
  service/src/integrationTest/kotlin/fi/espoo/evaka/incomestatement/IncomeStatementControllerIntegrationTest.kt
  service/src/main/kotlin/fi/espoo/evaka/incomestatement/IncomeStatementController.kt
  service/src/main/kotlin/fi/espoo/evaka/incomestatement/IncomeStatementQueries.kt
Labels: enhancement

#5962 Ehdottavan esiopetusken raportin parannuksia
  frontend/src/employee-frontend/components/reports/PreschoolApplicationReport.tsx
  frontend/src/lib-components/layout/Table.tsx
  frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
Labels: enhancement

#5956 Kopiot tiedotteista muille johtajille ja veoille
  frontend/src/e2e-test/pages/employee/messages/messages-page.ts
  frontend/src/e2e-test/specs/7_messaging/messaging-by-staff.spec.ts
  frontend/src/employee-frontend/components/messages/SingleThreadView.tsx
  frontend/src/employee-frontend/components/messages/ThreadListContainer.tsx
  frontend/src/employee-frontend/components/messages/types-view.ts
  service/src/integrationTest/kotlin/fi/espoo/evaka/messaging/MessageIntegrationTest.kt
  service/src/main/kotlin/fi/espoo/evaka/messaging/MessageQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/messaging/MessageService.kt
Labels: enhancement

#5936 Kuntalainen voi merkitä poissaoloja vain toimintapäiville
  service/src/integrationTest/kotlin/fi/espoo/evaka/absence/AbsencePushNotificationsTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/reservations/ReservationControllerCitizenIntegrationTest.kt
  service/src/main/kotlin/fi/espoo/evaka/reservations/ReservationControllerCitizen.kt
Labels: enhancement

#5963 Lähettämättömän päätöksen tila näkyy hakemuksella väärin
  frontend/src/employee-frontend/components/application-page/ApplicationDecisionsSection.tsx
  frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
Labels: bug

#5965 Dokumenttinäkymä ei lataa uudelleen vaan säilyttää scroll-position välilehteä vaihtaessa
  frontend/src/employee-frontend/components/child-information/queries.ts
  frontend/src/lib-common/query.ts
Labels: bug

#5961 Ei tehdä tilauksia Jamixiin suljetuista yksiköistä/ryhmistä
  service/src/integrationTest/kotlin/fi/espoo/evaka/jamix/JamixIntegrationTest.kt
  service/src/main/kotlin/fi/espoo/evaka/jamix/JamixQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/jamix/JamixService.kt
Labels: bug

#5959 Kalenteri: Tieto jos työntekijä muokannut omaa/mahdollisesti toisen kalenterimerkintää
  frontend/src/e2e-test/dev-api/fixtures.ts
  frontend/src/e2e-test/generated/api-types.ts
  frontend/src/employee-frontend/components/unit/tab-calendar/CalendarEventsSection.tsx
  frontend/src/lib-common/generated/api-types/calendarevent.ts
  frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
  service/src/integrationTest/kotlin/fi/espoo/evaka/calendarevent/CalendarEventNotificationQueriesTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/calendarevent/CalendarEventServiceIntegrationTest.kt
  service/src/main/kotlin/fi/espoo/evaka/calendarevent/CalendarEvent.kt
  service/src/main/kotlin/fi/espoo/evaka/calendarevent/CalendarEventController.kt
  service/src/main/kotlin/fi/espoo/evaka/calendarevent/CalendarEventQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/dev/DataInitializers.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/dev/DevApi.kt
  service/src/main/resources/db/migration/V463__calendar_event_modified_by.sql
  service/src/main/resources/migrations.txt
Labels: enhancement

#5966 Oikaisulaskut, osa 2: Oikaisulaskujen näyttäminen (ei vielä käytössä)
  frontend/src/e2e-test/dev-api/fixtures.ts
  frontend/src/e2e-test/generated/api-clients.ts
  frontend/src/e2e-test/pages/employee/finance/finance-page.ts
  frontend/src/e2e-test/pages/employee/finance/invoice-details-page.ts
  frontend/src/e2e-test/pages/employee/guardian-information.ts
  frontend/src/e2e-test/specs/4_finance/invoices.spec.ts
  frontend/src/e2e-test/specs/5_employee/guardian-information-page.spec.ts
  frontend/src/employee-frontend/components/common/Filters.tsx
  frontend/src/employee-frontend/components/invoice/Actions.tsx
  frontend/src/employee-frontend/components/invoice/InvoiceDetailsSection.tsx
  frontend/src/employee-frontend/components/invoice/InvoiceHeadOfFamilySection.tsx
  frontend/src/employee-frontend/components/invoice/InvoicePage.tsx
  frontend/src/employee-frontend/components/invoice/InvoiceRowsSection.tsx
  frontend/src/employee-frontend/components/invoice/InvoiceRowsSectionRow.tsx
  frontend/src/employee-frontend/components/invoice/Sum.tsx
  frontend/src/employee-frontend/components/invoice/utils.ts
  frontend/src/employee-frontend/components/invoices/Invoices.tsx
  frontend/src/employee-frontend/components/invoices/InvoicesPage.tsx
  frontend/src/employee-frontend/components/person-profile/PersonInvoices.tsx
  frontend/src/lib-common/finite-date-range.ts
  frontend/src/lib-common/generated/api-types/invoicing.ts
  frontend/src/lib-common/generated/api-types/shared.ts
  frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
  service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/InvoiceIntegrationTest.kt
  service/src/main/kotlin/fi/espoo/evaka/invoicing/controller/InvoiceController.kt
  service/src/main/kotlin/fi/espoo/evaka/invoicing/data/InvoiceQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/pis/SystemController.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/dev/DataInitializers.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/dev/DevApi.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/security/EmployeeFeatures.kt
  service/src/main/resources/application-local.yaml
Labels: enhancement

#5969 Lisätään vuorohoidon info siirtopäätökseen
  service/evaka-bom/build.gradle.kts
  service/src/main/resources/WEB-INF/templates/daycare/transfer/decision.properties
  service/src/main/resources/WEB-INF/templates/daycare/transfer/decision_sv.properties
Labels: enhancement

#5863 Loma-ajan läsnäoloraportin opetustauolla olevien lasten suodatus
  service/src/integrationTest/kotlin/fi/espoo/evaka/reports/HolidayPeriodAttendanceReportTest.kt
  service/src/main/kotlin/fi/espoo/evaka/reports/HolidayPeriodAttendanceReport.kt
Labels: enhancement

#5968 Poistetaan curl IP-osoitteen hakemisesta
  apigw/Dockerfile
  apigw/entrypoint.sh
Labels: tech

#5967 Käyttämättömän proxy moduulin poisto
  frontend/Dockerfile
Labels: tech

#5987 db-scheduler-kirjaston päivityksen vaatima tietokantamuutos
  service/src/main/resources/db/migration/V464__scheduled_tasks_priority.sql
  service/src/main/resources/migrations.txt
Labels: dependencies

#5988 Ohitetaan CVE joka koskee vain vanhoja Spring-versioita
  service/owasp-suppressions.xml
Labels: no-changelog

#5958 Korjaus pedagogisen lomakkeen pdf-generointiin
  service/src/main/kotlin/fi/espoo/evaka/document/childdocument/DocumentHtmlGenerator.kt
Labels: breaking

#5994 Tarkistus seuraavan esiopetuskauden olemassaolosta ehdottavan EO:n työkaluun
  frontend/src/employee-frontend/components/placement-tool/PlacementToolPage.tsx
  frontend/src/employee-frontend/components/placement-tool/queries.ts
  frontend/src/employee-frontend/generated/api-clients/application.ts
  frontend/src/employee-frontend/query.ts
  frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
  service/src/integrationTest/kotlin/fi/espoo/evaka/application/PlacementToolServiceIntegrationTest.kt
  service/src/main/kotlin/fi/espoo/evaka/application/PlacementToolController.kt
Labels: enhancement

#5999 Korjattu regressio SAML-kirjautumisen RelayState-validaatiossa
  apigw/src/shared/routes/saml.ts
  apigw/src/shared/saml/index.ts
Labels: bug

#5992 Muutetaan ryhmät-välilehden yhteystietokooste-linkki tukemaan käyttöoikeussääntöjä
  frontend/src/employee-frontend/components/Reports.tsx
  frontend/src/employee-frontend/components/reports/AssistanceNeedsAndActions.tsx
  frontend/src/employee-frontend/components/reports/queries.ts
  frontend/src/employee-frontend/components/unit/tab-groups/Groups.tsx
  frontend/src/lib-common/generated/api-types/reports.ts
  service/src/main/kotlin/fi/espoo/evaka/reports/ReportPermissions.kt
Labels: enhancement

#6005 Korjattu yksikön hakemuksien haun käyttöoikeustarkastus
  service/src/main/kotlin/fi/espoo/evaka/application/ApplicationControllerV2.kt
Labels: bug

#6002 Korjaus riittämättömään käyttöoikeustarkistukseen kuntalaisen keskusteluaikojen perumisessa
  frontend/src/lib-common/generated/action.d.ts
  service/src/integrationTest/kotlin/fi/espoo/evaka/calendarevent/CalendarEventServiceIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/children/ChildControllerCitizenTest.kt
  service/src/main/kotlin/fi/espoo/evaka/calendarevent/CalendarEventController.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/security/Action.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/security/actionrule/IsCitizen.kt
Labels: bug

#5998 Asetetaan kuukausinäkymä kalenteriin oletukseksi
  frontend/src/citizen-frontend/calendar/CalendarGridView.tsx
  frontend/src/citizen-frontend/calendar/CalendarMonthView.tsx
  frontend/src/citizen-frontend/calendar/CalendarPage.tsx
  frontend/src/citizen-frontend/calendar/DayElem.tsx
  frontend/src/citizen-frontend/calendar/hooks.ts
  frontend/src/e2e-test/pages/citizen/citizen-calendar.ts
  frontend/src/e2e-test/specs/0_citizen/citizen-reservations.spec.ts
  frontend/src/e2e-test/specs/0_citizen/citizen-show-service-usage.spec.ts
  frontend/src/e2e-test/specs/0_citizen/citizen-start-after-holiday-deadline.spec.ts
  frontend/src/lib-customizations/espoo/featureFlags.tsx
  frontend/src/lib-customizations/types.d.ts
Labels: enhancement

#5995 Kevennetään CSRF-tarkistusta OWASP-suositusten mukaisesti
  apigw/src/shared/middleware/csrf.ts
  frontend/src/citizen-frontend/api-client.ts
  frontend/src/citizen-frontend/messages/utils.ts
  frontend/src/employee-frontend/api/client.ts
  frontend/src/employee-frontend/components/messages/utils.ts
  frontend/src/employee-mobile-frontend/client.ts
Labels: tech

#6007 Poistetaan käyttämättömiä nginx moduuleita
  frontend/Dockerfile
Labels: tech

#5972 Lomakyselyraportti tarkastelee lapsen tuen tasoa tukitoimellisten näyttämiseksi
  frontend/src/e2e-test/specs/5_employee/holiday-period-attendance-report.spec.ts
  service/src/integrationTest/kotlin/fi/espoo/evaka/reports/HolidayPeriodAttendanceReportTest.kt
  service/src/main/kotlin/fi/espoo/evaka/reports/HolidayPeriodAttendanceReport.kt
Labels: enhancement

#6011 Titania työvuorosuunnitelmien tarkistuksen korjaus
  service/src/integrationTest/kotlin/fi/espoo/evaka/titania/TitaniaServiceTest.kt
  service/src/main/kotlin/fi/espoo/evaka/titania/TitaniaService.kt
Labels: bug

#5997 Laskujen generoinnin suorituskykyparannuksia
  service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/service/InvoiceGeneratorIntegrationTest.kt
  service/src/main/kotlin/fi/espoo/evaka/children/ChildrenQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/invoicing/FinanceDecisionUtils.kt
  service/src/main/kotlin/fi/espoo/evaka/invoicing/data/FeeDecisionQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/invoicing/data/VoucherValueDecisionQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/invoicing/service/DraftInvoiceGenerator.kt
  service/src/main/kotlin/fi/espoo/evaka/invoicing/service/FeeDecisionService.kt
  service/src/main/kotlin/fi/espoo/evaka/invoicing/service/InvoiceGenerator.kt
  service/src/main/kotlin/fi/espoo/evaka/invoicing/service/VoucherValueDecisionService.kt
Labels: tech

#5970 Päiväeditorin tallennuksen indikointi ilman notifikaatiota
  frontend/src/citizen-frontend/calendar/AbsenceModal.tsx
  frontend/src/citizen-frontend/calendar/CalendarPage.tsx
  frontend/src/citizen-frontend/calendar/DayView.tsx
  frontend/src/citizen-frontend/calendar/ReservationModal.tsx
  frontend/src/lib-components/atoms/buttons/AsyncButton.tsx
  frontend/src/lib-components/atoms/buttons/async-button-behavior.ts
Labels: enhancement

#5991 Ehdottavan esiopetushakemuksen hyväksymisen esto johtajalta
  frontend/src/employee-frontend/components/unit/tab-placement-proposals/PlacementProposalRow.tsx
  frontend/src/lib-common/generated/api-types/placement.ts
  service/src/integrationTest/kotlin/fi/espoo/evaka/placement/PlacementPlanIntegrationTest.kt
  service/src/main/kotlin/fi/espoo/evaka/placement/PlacementPlan.kt
  service/src/main/kotlin/fi/espoo/evaka/placement/PlacementPlanQueries.kt
Labels: enhancement

#5971 Mobiilinotifikaatio varatusta/perutusta keskusteluajasta
  frontend/src/employee-mobile-frontend/settings/NotificationSettings.tsx
  frontend/src/lib-common/generated/api-types/webpush.ts
  frontend/src/lib-customizations/defaults/employee-mobile-frontend/i18n/fi.ts
  service/src/integrationTest/kotlin/fi/espoo/evaka/calendarevent/CalendarEventPushNotificationsTest.kt
  service/src/main/kotlin/fi/espoo/evaka/calendarevent/CalendarEventController.kt
  service/src/main/kotlin/fi/espoo/evaka/calendarevent/CalendarEventPushNotifications.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/async/AsyncJob.kt
  service/src/main/kotlin/fi/espoo/evaka/webpush/PushNotificationCategory.kt
  service/src/main/resources/db/migration/V466__push_notification_calendar_event_reservation.sql
  service/src/main/resources/db/migration/V467__push_notification_calendar_event_reservation_defaults.sql
  service/src/main/resources/migrations.txt
Labels: enhancement

#5996 Lähetetään tulotietomuistutus vasta tulotiedon loppumisen jälkeisenä päivänä
  service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/service/OutdatedIncomeNotificationsIntegrationTest.kt
  service/src/main/kotlin/fi/espoo/evaka/invoicing/service/OutdatedIncomeNotifications.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/async/AsyncJob.kt
Labels: enhancement

#6009 Poistetaan curl frontend-imagesta
  compose/e2e/playwright.Dockerfile
  compose/e2e/playwright/bin/run-tests.sh
  compose/e2e/playwright/bin/wait-for-url.sh
  frontend/Dockerfile
Labels: tech

#6016 Käytetään mock clockia e2e testeissä
  frontend/src/e2e-test/specs/6_mobile/absences.spec.ts
  frontend/src/e2e-test/specs/6_mobile/notes.spec.ts
  frontend/src/e2e-test/specs/6_mobile/pin-login.spec.ts
Labels: tech

#6012 Ei deaktivoida valmiiksi epäaktiivisia työntekijöitä uudelleen
  service/src/integrationTest/kotlin/fi/espoo/evaka/pis/InactiveEmployeesRoleResetIntegrationTest.kt
  service/src/main/kotlin/fi/espoo/evaka/pis/EmployeeQueries.kt
Labels: bug

#6008 Kevennetään SAML-virhelokitusta
  apigw/src/shared/logging.ts
  apigw/src/shared/middleware/error-handler.ts
  apigw/src/shared/routes/saml.ts
  apigw/tsconfig.json
Labels: tech

#6018 Poistetaan dollarimerkki esiopetuksen tuenpäätökseltä
  frontend/src/lib-components/assistance-need-decision/AssistanceNeedPreschoolDecisionReadOnly.tsx
Labels: bug

#6033 Johtajan hyväksyntä näkyy hakemushaussa kaikissa tiloissa
  service/src/main/kotlin/fi/espoo/evaka/application/ApplicationQueries.kt
Labels: bug

#6017 Usean lapsen lähteneeksi merkitseminen
  frontend/src/e2e-test/pages/mobile/list-page.ts
  frontend/src/e2e-test/specs/6_mobile/child-attendances.spec.ts
  frontend/src/employee-mobile-frontend/App.tsx
  frontend/src/employee-mobile-frontend/child-attendance/ChildList.tsx
  frontend/src/employee-mobile-frontend/child-attendance/ChildListItem.tsx
  frontend/src/employee-mobile-frontend/child-attendance/actions/MarkDeparted.tsx
  frontend/src/employee-mobile-frontend/child-attendance/queries.ts
  frontend/src/employee-mobile-frontend/child-info/child-state-pages/AttendanceChildPresent.tsx
  frontend/src/employee-mobile-frontend/generated/api-clients/attendance.ts
  frontend/src/lib-common/generated/api-types/attendance.ts
  frontend/src/lib-customizations/defaults/employee-mobile-frontend/i18n/fi.ts
  frontend/src/lib-customizations/espoo/featureFlags.tsx
  frontend/src/lib-customizations/types.d.ts
  service/codegen/src/main/kotlin/evaka/codegen/api/Config.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/attendance/AttendanceTransitionsIntegrationTest.kt
  service/src/main/kotlin/fi/espoo/evaka/attendance/ChildAttendanceController.kt
  service/src/main/kotlin/fi/espoo/evaka/attendance/ChildAttendanceQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/placement/PlacementQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/reservations/AbsenceCalculator.kt
Labels: enhancement

#6036 Korjataan päänavigaation sijainti Firefox mobiiliselaimella
  frontend/src/citizen-frontend/navigation/MobileNav.tsx
Labels: bug

#6037 Korjataan asiakasmaksuperusteet-linkki tulotiedot-sivulla (vain Espoo)
  frontend/src/lib-customizations/espoo/citizen.tsx
Labels: bug

#6032 Oikaisulaskut, osa 4: Oikaisulaskujen muodostus yksittäiselle päämiehelle (ei vielä käytössä)
  frontend/src/employee-frontend/components/person-profile/PersonInvoices.tsx
  frontend/src/employee-frontend/components/person-profile/queries.ts
  frontend/src/employee-frontend/generated/api-clients/invoicing.ts
  frontend/src/lib-common/generated/action.d.ts
  frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
  frontend/src/lib-icons/fontawesome.d.ts
  frontend/src/lib-icons/free-icons.ts
  frontend/src/lib-icons/pro-icons.ts
  service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/service/ReplacementInvoicesIntegrationTest.kt
  service/src/main/kotlin/fi/espoo/evaka/Audit.kt
  service/src/main/kotlin/fi/espoo/evaka/invoicing/controller/InvoiceController.kt
  service/src/main/kotlin/fi/espoo/evaka/invoicing/data/InvoiceQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/invoicing/service/DraftInvoiceGenerator.kt
  service/src/main/kotlin/fi/espoo/evaka/invoicing/service/InvoiceGenerator.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/security/Action.kt
Labels: enhancement

#6040 Päivitetään yarn versioon 4.5.3
  apigw/.yarn/releases/yarn-4.5.0.cjs
  apigw/.yarn/releases/yarn-4.5.3.cjs
  apigw/.yarnrc.yml
  apigw/package.json
  apigw/yarn.lock
  frontend/.yarn/releases/yarn-4.5.0.cjs
  frontend/.yarn/releases/yarn-4.5.3.cjs
  frontend/.yarnrc.yml
  frontend/package.json
  frontend/yarn.lock
Labels: dependencies

#5926 Alustava uusi kevytkirjautuminen kuntalaisille (ei vielä tuotantokäytössä)
  apigw/src/enduser/app.ts
  apigw/src/enduser/routes/auth-weak-login.ts
  apigw/src/index.ts
  apigw/src/shared/__tests__/parse-url-with-origin.ts
  apigw/src/shared/auth/dev-auth.ts
  apigw/src/shared/config.ts
  apigw/src/shared/parse-url-with-origin.ts
  apigw/src/shared/redis-client.ts
  apigw/src/shared/routes/saml.ts
  apigw/src/shared/saml/index.ts
  apigw/src/shared/service-client.ts
  apigw/src/shared/test/mock-redis-client.ts
  frontend/src/citizen-frontend/auth/api.ts
  frontend/src/citizen-frontend/generated/api-clients/pis.ts
  frontend/src/citizen-frontend/login/LoginPage.tsx
  frontend/src/citizen-frontend/navigation/const.ts
  frontend/src/citizen-frontend/personal-details/LoginDetailsSection.tsx
  frontend/src/citizen-frontend/personal-details/PersonalDetails.tsx
  frontend/src/citizen-frontend/personal-details/queries.ts
  frontend/src/lib-common/generated/api-types/pis.ts
  frontend/src/lib-common/utils/parse-url-with-origin.spec.ts
  frontend/src/lib-common/utils/parse-url-with-origin.ts
  frontend/src/lib-components/atoms/form/InputField.tsx
  frontend/src/lib-customizations/defaults/citizen/i18n/en.tsx
  frontend/src/lib-customizations/defaults/citizen/i18n/fi.tsx
  frontend/src/lib-customizations/defaults/citizen/i18n/sv.tsx
  frontend/src/lib-customizations/espoo/featureFlags.tsx
  frontend/src/lib-customizations/types.d.ts
  service/build.gradle.kts
  service/codegen/src/main/kotlin/evaka/codegen/api/Config.kt
  service/codegen/src/main/kotlin/evaka/codegen/api/TsCodeGenerator.kt
  service/codegen/src/main/kotlin/evaka/codegen/api/TsRepresentation.kt
  service/codegen/src/main/kotlin/evaka/codegen/api/TypeMetadata.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/pis/PersonIntegrationTest.kt
  service/src/main/kotlin/fi/espoo/evaka/Audit.kt
  service/src/main/kotlin/fi/espoo/evaka/EvakaEnv.kt
  service/src/main/kotlin/fi/espoo/evaka/pis/PersonQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/pis/SystemController.kt
  service/src/main/kotlin/fi/espoo/evaka/pis/controllers/PersonalDataControllerCitizen.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/auth/Password.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/auth/PasswordService.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/controllers/ExceptionHandler.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/domain/Errors.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/security/Action.kt
  service/src/main/kotlin/fi/espoo/evaka/user/CitizenUserQueries.kt
  service/src/main/resources/application-local.yaml
  service/src/main/resources/db/migration/V468__citizen_user.sql
  service/src/main/resources/migrations.txt
  service/src/test/kotlin/fi/espoo/evaka/shared/auth/PasswordHasherCli.kt
  service/src/test/kotlin/fi/espoo/evaka/shared/auth/PasswordTest.kt
Labels: enhancement

#6047 Korjataan viimeisen laskutetun kuukauden päättely
  service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/service/ReplacementInvoicesIntegrationTest.kt
  service/src/main/kotlin/fi/espoo/evaka/invoicing/data/InvoiceQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/invoicing/service/InvoiceGenerator.kt
Labels: bug

#6043 Maksupäätöksien hakuun uusi hakuehto: ei avoimia tuloselvityksiä
  frontend/src/lib-common/generated/api-types/invoicing.ts
  frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
  service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/FeeDecisionIntegrationTest.kt
  service/src/main/kotlin/fi/espoo/evaka/invoicing/controller/FeeDecisionController.kt
  service/src/main/kotlin/fi/espoo/evaka/invoicing/data/FeeDecisionQueries.kt
Labels: enhancement

#6041 Poistetaan deprekoituja endpointteja
  service/codegen/src/main/kotlin/evaka/codegen/api/Config.kt
  service/src/main/kotlin/fi/espoo/evaka/attendance/ChildAttendanceController.kt
Labels: tech

#6049 Tekstimuutoksia varhaiskasvatuspäätösten tulosteisiin
  service/src/main/resources/WEB-INF/templates/daycare/decision.properties
  service/src/main/resources/WEB-INF/templates/daycare/decision_sv.properties
  service/src/main/resources/WEB-INF/templates/daycare/transfer/decision.properties
  service/src/main/resources/WEB-INF/templates/daycare/transfer/decision_sv.properties
Labels: enhancement

#6042 Tulotietojen sivun ulkonäön bugikorjaus
  frontend/src/employee-frontend/components/child-information/fee-alteration/FeeAlterationList.tsx
  frontend/src/employee-frontend/components/person-profile/income/IncomeItemHeader.tsx
Labels: bug

#6050 Korjataan lapsen dokumentin muokkausnäkymän tallennuskäyttäytyminen virhetilanteissa
  frontend/src/employee-frontend/components/child-documents/ChildDocumentEditor.tsx
  frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
Labels: bug

#6054 Poistetaan vanhat Varda-integraatiot
  frontend/src/e2e-test/generated/api-clients.ts
  frontend/src/e2e-test/generated/api-types.ts
  frontend/src/e2e-test/specs/5_employee/varda_error_report.spec.ts
  frontend/src/employee-frontend/components/reports/VardaChildErrors.tsx
  frontend/src/employee-frontend/components/reports/queries.ts
  frontend/src/employee-frontend/generated/api-clients/varda.ts
  frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
  service/src/integrationTest/kotlin/fi/espoo/evaka/pis/controller/PersonControllerIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/varda/VardaIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/varda/VardaOrganizerChildrenIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/varda/VardaPlacementsIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/varda/VardaServiceIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/varda/VardaUnitIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/varda/new/VardaUpdateServiceIntegrationTest.kt
  service/src/main/kotlin/fi/espoo/evaka/EvakaEnv.kt
  service/src/main/kotlin/fi/espoo/evaka/pis/controllers/PersonController.kt
  service/src/main/kotlin/fi/espoo/evaka/reports/VardaErrorsReport.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/async/AsyncJob.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/dev/DataInitializers.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/dev/DevApi.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/job/ScheduledJobs.kt
  service/src/main/kotlin/fi/espoo/evaka/varda/Varda.kt
  service/src/main/kotlin/fi/espoo/evaka/varda/VardaController.kt
  service/src/main/kotlin/fi/espoo/evaka/varda/VardaOrganizerChild.kt
  service/src/main/kotlin/fi/espoo/evaka/varda/VardaQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/varda/VardaService.kt
  service/src/main/kotlin/fi/espoo/evaka/varda/integration/MockVardaIntegrationEndpoint.kt
  service/src/main/kotlin/fi/espoo/evaka/varda/integration/VardaClient.kt
  service/src/main/kotlin/fi/espoo/evaka/varda/integration/VardaTokenProvider.kt
  service/src/main/kotlin/fi/espoo/evaka/varda/new/VardaQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/varda/new/VardaUpdateServiceNew.kt
  service/src/main/kotlin/fi/espoo/evaka/varda/old/VardaResetService.kt
  service/src/main/kotlin/fi/espoo/evaka/varda/old/VardaUpdateService.kt
Labels: tech

#6051 Sijoitusehdotuksen hylkäämisestä luotava muistilappu siirtyy palveluohjauksen muistilapuksi
  service/src/integrationTest/kotlin/fi/espoo/evaka/application/ApplicationStateServiceIntegrationTests.kt
  service/src/main/kotlin/fi/espoo/evaka/application/ApplicationStateService.kt
  service/src/main/kotlin/fi/espoo/evaka/application/notes/ApplicationNoteQueries.kt
Labels: enhancement
