Repository espoon-voltti/evaka, pull requests merged in 2024-06, with the labels that each got.

#5205 Mahdollista palse-arvojen päivittäminen
  frontend/src/employee-frontend/components/finance-basics/ServiceNeedItem.tsx
  frontend/src/employee-frontend/components/finance-basics/VoucherValueEditor.tsx
  frontend/src/employee-frontend/components/finance-basics/queries.ts
  frontend/src/employee-frontend/generated/api-clients/invoicing.ts
  frontend/src/lib-common/generated/action.d.ts
  service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/VoucherValueIntegrationTest.kt
  service/src/main/kotlin/fi/espoo/evaka/Audit.kt
  service/src/main/kotlin/fi/espoo/evaka/invoicing/controller/FinanceBasicsController.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/security/Action.kt
Labels: enhancement

#5218 Asiakasmaksut raportti
  frontend/src/employee-frontend/App.tsx
  frontend/src/employee-frontend/components/Reports.tsx
  frontend/src/employee-frontend/components/reports/CustomerFees.tsx
  frontend/src/employee-frontend/components/reports/queries.ts
  frontend/src/employee-frontend/generated/api-clients/reports.ts
  frontend/src/lib-common/generated/action.d.ts
  frontend/src/lib-common/generated/api-types/invoicing.ts
  frontend/src/lib-common/generated/api-types/reports.ts
  frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
  service/src/integrationTest/kotlin/fi/espoo/evaka/reports/CustomerFeesReportTest.kt
  service/src/main/kotlin/fi/espoo/evaka/Audit.kt
  service/src/main/kotlin/fi/espoo/evaka/invoicing/domain/FinanceDecisions.kt
  service/src/main/kotlin/fi/espoo/evaka/reports/CustomerFeesReport.kt
  service/src/main/kotlin/fi/espoo/evaka/reports/ReportPermissions.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/security/Action.kt
Labels: enhancement

#5226 Lisätty keycloak admin-konsolin piilottaminen
  frontend/proxy/files/etc/nginx/conf.d/nginx.conf.template
  frontend/proxy/files/etc/nginx/keycloak-proxy.conf.template
Labels: enhancement

#5216 Tarkastettu-tila palvelusetelien maksuaineistojen maksatukselle eVakasta
  frontend/src/e2e-test/pages/employee/finance/finance-page.ts
  frontend/src/e2e-test/specs/4_finance/payments.spec.ts
  frontend/src/employee-frontend/components/payments/Actions.tsx
  frontend/src/employee-frontend/components/payments/PaymentFilters.tsx
  frontend/src/employee-frontend/components/payments/PaymentsPage.tsx
  frontend/src/employee-frontend/generated/api-clients/invoicing.ts
  frontend/src/lib-common/generated/action.d.ts
  frontend/src/lib-common/generated/api-types/invoicing.ts
  frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
  service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/PaymentsIntegrationTest.kt
  service/src/main/kotlin/fi/espoo/evaka/Audit.kt
  service/src/main/kotlin/fi/espoo/evaka/invoicing/controller/PaymentController.kt
  service/src/main/kotlin/fi/espoo/evaka/invoicing/data/PaymentQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/invoicing/domain/Payments.kt
  service/src/main/kotlin/fi/espoo/evaka/invoicing/service/PaymentService.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/security/Action.kt
  service/src/main/resources/db/migration/V419__payment_confirmed_state.sql
  service/src/main/resources/db/migration/V420__payment_constraint_change.sql
  service/src/main/resources/migrations.txt
Labels: enhancement

#5240 Ei huomioida Kotlin-kääntäjän sessiokansiota git-versioinnissa
  service/.gitignore
Labels: no-changelog

#5238 Satunnaisen vuorohoidon varasijoitustarpeessa huomioidaan sijoitusyksikön vuorohoidon aukioloajat
  frontend/src/employee-frontend/components/absences/MonthCalendarTable.tsx
  frontend/src/lib-common/generated/api-types/absence.ts
  service/src/integrationTest/kotlin/fi/espoo/evaka/absence/AbsenceServiceIntegrationTest.kt
  service/src/main/kotlin/fi/espoo/evaka/absence/AbsenceService.kt
Labels: bug

#5239 Varoitetaan mobiilissakin jos viestillä on yli 2 vastaanottajaa
  frontend/src/e2e-test/pages/mobile/message-editor.ts
  frontend/src/e2e-test/specs/6_mobile/messages.spec.ts
  frontend/src/employee-mobile-frontend/messages/MessageEditor.tsx
  frontend/src/employee-mobile-frontend/messages/queries.ts
  frontend/src/lib-components/molecules/ConfirmedMutation.tsx
  frontend/src/lib-customizations/defaults/employee-mobile-frontend/i18n/fi.ts
Labels: enhancement

#5244 Tulevien esikoululaisten raportin parannus
  frontend/src/employee-frontend/components/reports/FuturePreschoolersReport.tsx
  frontend/src/employee-frontend/components/reports/queries.ts
  frontend/src/employee-frontend/components/unit/unit-details/UnitEditor.tsx
  frontend/src/employee-frontend/generated/api-clients/reports.ts
  frontend/src/lib-common/generated/api-types/daycare.ts
  frontend/src/lib-common/generated/api-types/reports.ts
  frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
  service/src/integrationTest/kotlin/fi/espoo/evaka/daycare/DaycareEditIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/reports/FuturePreschoolersReportTest.kt
  service/src/main/kotlin/fi/espoo/evaka/daycare/CareArea.kt
  service/src/main/kotlin/fi/espoo/evaka/daycare/DaycareQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/reports/FuturePreschoolersReport.kt
  service/src/main/resources/db/migration/V422__daycare_with_school.sql
  service/src/main/resources/migrations.txt
Labels: enhancement

#5228 Parempi HTTP-clientin konfigurointi
  service/src/integrationTest/kotlin/fi/espoo/evaka/FullApplicationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/dvv/DvvModificationsServiceIntegrationTestBase.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/espoo/bi/EspooBiJobTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/koski/KoskiIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/koski/KoskiPayloadIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/varda/VardaIntegrationTest.kt
  service/src/main/kotlin/fi/espoo/evaka/EspooConfig.kt
  service/src/main/kotlin/fi/espoo/evaka/EvakaEnv.kt
  service/src/main/kotlin/fi/espoo/evaka/dvv/DvvModificationsServiceClient.kt
  service/src/main/kotlin/fi/espoo/evaka/espoo/bi/EspooBiHttpClient.kt
  service/src/main/kotlin/fi/espoo/evaka/invoicing/integration/EspooInvoiceIntegrationClient.kt
  service/src/main/kotlin/fi/espoo/evaka/jamix/JamixService.kt
  service/src/main/kotlin/fi/espoo/evaka/koski/KoskiClient.kt
  service/src/main/kotlin/fi/espoo/evaka/reports/patu/EspooPatuIntegrationClient.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/Fuel.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/config/FuelManagerConfig.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/config/KoskiConfig.kt
  service/src/main/kotlin/fi/espoo/evaka/varda/VardaService.kt
  service/src/main/kotlin/fi/espoo/evaka/varda/integration/VardaClient.kt
  service/src/main/kotlin/fi/espoo/evaka/varda/integration/VardaTokenProvider.kt
  service/src/main/kotlin/fi/espoo/evaka/varda/old/VardaResetService.kt
  service/src/main/kotlin/fi/espoo/evaka/varda/old/VardaUpdateService.kt
  service/src/test/kotlin/fi/espoo/evaka/varda/integration/VardaClientTest.kt
Labels: tech

#5246 Espoo: muutetaan organisaation nimi metadatassa
  service/src/integrationTest/kotlin/fi/espoo/evaka/document/childdocument/ChildDocumentControllerIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/process/ArchivedProcessQueriesTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/shared/config/SharedIntegrationTestConfig.kt
  service/src/main/kotlin/fi/espoo/evaka/EspooConfig.kt
Labels: no-changelog

#5243 Espoo: Tekstikorjauksia
  frontend/src/lib-customizations/defaults/citizen/i18n/en.tsx
  frontend/src/lib-customizations/defaults/citizen/i18n/fi.tsx
  frontend/src/lib-customizations/defaults/citizen/i18n/sv.tsx
  service/src/main/resources/WEB-INF/templates/daycare/voucher/decision_sv.properties
  service/src/main/resources/WEB-INF/templates/fee-decision/voucher-value-decision.html
  service/src/main/resources/WEB-INF/templates/shared/common.html
  service/src/main/resources/WEB-INF/templates/shared/common.properties
  service/src/main/resources/WEB-INF/templates/shared/common_sv.properties
Labels: enhancement

#5258 Tulevien esikoululaisten raportin bugikorjaus
  frontend/src/employee-frontend/components/reports/FuturePreschoolersReport.tsx
  frontend/src/employee-frontend/components/reports/queries.ts
  frontend/src/lib-common/generated/api-types/reports.ts
  service/src/integrationTest/kotlin/fi/espoo/evaka/reports/FuturePreschoolersReportTest.kt
  service/src/main/kotlin/fi/espoo/evaka/reports/FuturePreschoolersReport.kt
Labels: bug

#5259 Lisätty validointeja palse-arvojen ylläpito-UI:hin
  frontend/src/employee-frontend/components/finance-basics/ServiceNeedItem.tsx
  frontend/src/employee-frontend/components/finance-basics/VoucherValueEditor.tsx
  frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
Labels: enhancement

#5245 Tilapäiset ilmoitukset kuten häiriötiedotteet kuntalaiselle ja työntekijän mobiiliin
  frontend/src/citizen-frontend/App.tsx
  frontend/src/citizen-frontend/generated/api-clients/systemnotifications.ts
  frontend/src/citizen-frontend/login/LoginPage.tsx
  frontend/src/citizen-frontend/login/queries.ts
  frontend/src/citizen-frontend/query.ts
  frontend/src/e2e-test/pages/employee/SystemNotificationsPage.ts
  frontend/src/e2e-test/pages/employee/employee-nav.ts
  frontend/src/e2e-test/pages/mobile/top-nav.ts
  frontend/src/e2e-test/specs/5_employee/system-notifications.spec.ts
  frontend/src/employee-frontend/App.tsx
  frontend/src/employee-frontend/components/Header.tsx
  frontend/src/employee-frontend/components/system-notifications/SystemNotificationsPage.tsx
  frontend/src/employee-frontend/components/system-notifications/queries.ts
  frontend/src/employee-frontend/generated/api-clients/systemnotifications.ts
  frontend/src/employee-frontend/query.ts
  frontend/src/employee-mobile-frontend/common/TopBar.tsx
  frontend/src/employee-mobile-frontend/common/top-bar/queries.ts
  frontend/src/employee-mobile-frontend/generated/api-clients/systemnotifications.ts
  frontend/src/employee-mobile-frontend/query.ts
  frontend/src/lib-common/generated/action.d.ts
  frontend/src/lib-common/generated/api-types/shared.ts
  frontend/src/lib-common/generated/api-types/systemnotifications.ts
  frontend/src/lib-customizations/defaults/citizen/i18n/en.tsx
  frontend/src/lib-customizations/defaults/citizen/i18n/fi.tsx
  frontend/src/lib-customizations/defaults/citizen/i18n/sv.tsx
  frontend/src/lib-customizations/defaults/employee-mobile-frontend/i18n/fi.ts
  frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
  frontend/src/lib-icons/fontawesome.d.ts
  frontend/src/lib-icons/free-icons.ts
  frontend/src/lib-icons/pro-icons.ts
  service/src/integrationTest/kotlin/fi/espoo/evaka/systemnotifications/SystemNotificationsControllerIntegrationTest.kt
  service/src/main/kotlin/fi/espoo/evaka/Audit.kt
  service/src/main/kotlin/fi/espoo/evaka/pis/SystemController.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/security/Action.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/security/EmployeeFeatures.kt
  service/src/main/kotlin/fi/espoo/evaka/systemnotifications/SystemNotificationsController.kt
  service/src/main/resources/db/migration/V423__system_notifications.sql
  service/src/main/resources/migrations.txt
Labels: enhancement

#5262 Tuen päätösten raportille lisätty päätösnumero ja onko kyseessä varhaiskasvatus vai esiopetus
  frontend/src/employee-frontend/components/reports/AssistanceNeedDecisionsReport.tsx
  frontend/src/lib-common/generated/api-types/reports.ts
  frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
  service/src/main/kotlin/fi/espoo/evaka/reports/AssistanceNeedDecisionsReport.kt
Labels: enhancement

#5264 Pääkäyttäjä voi testiympäristössä peruuttaa lomakepohjan julkaisun
  frontend/src/employee-frontend/components/document-templates/queries.ts
  frontend/src/employee-frontend/components/document-templates/template-editor/TemplateContentEditor.tsx
  frontend/src/employee-frontend/generated/api-clients/document.ts
  frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
  frontend/src/lib-customizations/espoo/featureFlags.tsx
  frontend/src/lib-customizations/types.d.ts
  service/codegen/src/main/kotlin/evaka/codegen/api/Config.kt
  service/codegen/src/main/kotlin/evaka/codegen/api/Controllers.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/document/childdocument/ChildDocumentControllerIntegrationTest.kt
  service/src/integrationTest/resources/application-integration-test.yaml
  service/src/main/kotlin/fi/espoo/evaka/Audit.kt
  service/src/main/kotlin/fi/espoo/evaka/EvakaEnv.kt
  service/src/main/kotlin/fi/espoo/evaka/document/DocumentTemplateController.kt
  service/src/main/kotlin/fi/espoo/evaka/document/DocumentTemplateQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/security/Action.kt
  service/src/main/resources/application-local.yaml
Labels: enhancement

#5265 Ei yritetä poistaa henkilöä jolla on tuen tarpeen päätös
  service/src/integrationTest/kotlin/fi/espoo/evaka/pis/InactivePeopleCleanupIntegrationTest.kt
  service/src/main/kotlin/fi/espoo/evaka/pis/InactivePeopleCleanup.kt
Labels: bug

#5267 Lisää päättyvän sijoituksen yksikkö ja alue varhaiskasvatuksessa lopettavien lasten raportille
  frontend/src/employee-frontend/components/reports/EndedPlacements.tsx
  frontend/src/lib-common/generated/api-types/reports.ts
  frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
  service/src/main/kotlin/fi/espoo/evaka/reports/EndedPlacementsReport.kt
Labels: enhancement

#5270 Lisätty lapsen syntymäaika ja kieli tulevat esikoululaiset raportille
  frontend/src/employee-frontend/components/reports/FuturePreschoolersReport.tsx
  frontend/src/employee-frontend/generated/api-clients/reports.ts
  frontend/src/lib-common/generated/api-types/reports.ts
  service/src/main/kotlin/fi/espoo/evaka/reports/FuturePreschoolersReport.kt
Labels: enhancement

#5266 Päivitetään Keycloak versioon 24.0.5 (vain ydin)
  keycloak/Dockerfile
  keycloak/evaka-logging/pom.xml
  keycloak/evaka-review-profile/pom.xml
  keycloak/evaka-review-profile/src/main/java/com/espoo/keycloak/authenticator/EvakaReviewProfileAuthenticator.java.diff
  keycloak/evaka-review-profile/src/main/java/com/espoo/keycloak/authenticator/EvakaReviewProfileAuthenticatorFactory.java.diff
Labels: dependencies

#5276 Vuorohoito näytetään hakemuksen tooltipissä jos se on valittu hakemukselle
  frontend/src/employee-frontend/components/unit/TabApplications.tsx
  frontend/src/lib-common/generated/api-types/application.ts
  frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
  service/src/main/kotlin/fi/espoo/evaka/application/Application.kt
  service/src/main/kotlin/fi/espoo/evaka/application/ApplicationQueries.kt
Labels: enhancement

#5242 Lähetetään varoitus yksikönjohtajille ERV nollaantumisesta
  service/src/integrationTest/kotlin/fi/espoo/evaka/jamix/JamixIntegrationTest.kt
  service/src/main/kotlin/fi/espoo/evaka/children/ChildrenQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/emailclient/EmailClient.kt
  service/src/main/kotlin/fi/espoo/evaka/jamix/JamixService.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/auth/AclQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/specialdiet/SpecialDietQueries.kt
Labels: enhancement

#5278 Korjattu vuorohoidon näyttäminen yksikön johtajalle hakemuslistan tooltipissä
  service/src/main/kotlin/fi/espoo/evaka/application/ApplicationQueries.kt
Labels: bug

#5271 Tuen päätösten metadataprosessit
  frontend/src/employee-frontend/components/archive-metadata/MetadataSection.tsx
  frontend/src/employee-frontend/components/child-documents/ChildDocumentEditor.tsx
  frontend/src/employee-frontend/components/child-information/assistance-need/decision/AssistanceNeedDecisionPage.tsx
  frontend/src/employee-frontend/components/child-information/assistance-need/decision/AssistanceNeedPreschoolDecisionReadPage.tsx
  frontend/src/employee-frontend/components/child-information/queries.ts
  frontend/src/employee-frontend/generated/api-clients/process.ts
  frontend/src/lib-common/generated/action.d.ts
  frontend/src/lib-common/generated/api-types/process.ts
  frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
  service/src/integrationTest/kotlin/fi/espoo/evaka/assistanceneed/decision/AssistanceNeedDecisionIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/assistanceneed/decision/AssistanceNeedPreschoolDecisionIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/document/childdocument/ChildDocumentControllerIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/process/ArchivedProcessQueriesTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/shared/config/SharedIntegrationTestConfig.kt
  service/src/main/kotlin/fi/espoo/evaka/Audit.kt
  service/src/main/kotlin/fi/espoo/evaka/EspooConfig.kt
  service/src/main/kotlin/fi/espoo/evaka/assistanceneed/decision/AssistanceNeedDecisionController.kt
  service/src/main/kotlin/fi/espoo/evaka/assistanceneed/decision/AssistanceNeedDecisionQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/assistanceneed/decision/AssistanceNeedDecisionService.kt
  service/src/main/kotlin/fi/espoo/evaka/assistanceneed/preschooldecision/AssistanceNeedPreschoolDecisionController.kt
  service/src/main/kotlin/fi/espoo/evaka/assistanceneed/preschooldecision/AssistanceNeedPreschoolDecisionQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/assistanceneed/preschooldecision/AssistanceNeedPreschoolDecisionService.kt
  service/src/main/kotlin/fi/espoo/evaka/document/childdocument/ChildDocumentController.kt
  service/src/main/kotlin/fi/espoo/evaka/process/ArchivedProcesses.kt
  service/src/main/kotlin/fi/espoo/evaka/process/ProcessMetadataController.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/FeatureConfig.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/security/Action.kt
  service/src/main/resources/db/migration/V424__assistance_need_decision_archive_metadata.sql
  service/src/main/resources/migrations.txt
Labels: breaking

#5274 Korjataan linkki kuntalaisen tulotietojen ilmoituksessa (Espoo)
  frontend/src/lib-customizations/espoo/citizen.tsx
Labels: enhancement

#5290 Päivitetään suurin osa lint-paketeista
  frontend/package.json
  frontend/yarn.lock
Labels: dependencies, javascript

#5293 Korjaus Varda-tietueiden voimassaoloajan päättämiseen
  service/src/integrationTest/kotlin/fi/espoo/evaka/varda/new/VardaUpdaterIntegrationTest.kt
  service/src/main/kotlin/fi/espoo/evaka/varda/new/VardaClient.kt
  service/src/main/kotlin/fi/espoo/evaka/varda/new/VardaUpdateServiceNew.kt
Labels: bug

#5296 Ei näytetä suljettuja yksiköitä tuen päätöksen lomakkeilla
  frontend/src/employee-frontend/components/child-information/assistance-need/decision/AssistanceNeedPreschoolDecisionEditPage.tsx
  frontend/src/employee-frontend/components/child-information/assistance-need/decision/AssistanceNeededDecisionForm.tsx
Labels: enhancement

#5268 Kerätään access logeja vain API-poluista ja Keycloakin realms-poluista
  frontend/proxy/files/etc/nginx/conf.d/nginx.conf.template
Labels: tech

#5301 Ruokailijaraportin viikonpäivän näytön korjaus
  frontend/src/employee-frontend/components/reports/MealReport.tsx
Labels: bug

#5298 Suurempi tekstikenttä kuntalaisen uusi viesti dialogiin
  frontend/src/citizen-frontend/messages/MessageEditor.tsx
Labels: enhancement

#5299 Vaka- tuen päätöksiin automaattinen päättymispäivä jos tulevaisuudessa on jo toinen päätös
  frontend/src/employee-frontend/components/reports/AssistanceNeedDecisionsReportDecision.tsx
  frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
  service/src/integrationTest/kotlin/fi/espoo/evaka/assistanceneed/decision/AssistanceNeedDecisionIntegrationTest.kt
  service/src/main/kotlin/fi/espoo/evaka/assistanceneed/decision/AssistanceNeedDecisionController.kt
  service/src/main/kotlin/fi/espoo/evaka/assistanceneed/decision/AssistanceNeedDecisionQueries.kt
Labels: enhancement

#5309 Korjaus lasten läsnäolojen automaattikatkaisuun
  service/src/main/kotlin/fi/espoo/evaka/shared/job/ScheduledJobs.kt
Labels: bug

#5312 apigw:n ESLint-sääntöjen ja koodin parannuksia
  apigw/eslint.config.js
  apigw/package.json
  apigw/src/enduser/__tests__/csrf.ts
  apigw/src/enduser/app.ts
  apigw/src/enduser/dev-sfi-auth.ts
  apigw/src/enduser/keycloak-citizen-saml.ts
  apigw/src/enduser/mapRoutes.ts
  apigw/src/enduser/publicRoutes.ts
  apigw/src/enduser/routes.ts
  apigw/src/enduser/routes/auth-status.ts
  apigw/src/enduser/suomi-fi-saml.ts
  apigw/src/index.ts
  apigw/src/internal/__tests__/csrf.ts
  apigw/src/internal/__tests__/mobile-device-session.ts
  apigw/src/internal/ad-saml.ts
  apigw/src/internal/app.ts
  apigw/src/internal/dev-ad-auth.ts
  apigw/src/internal/keycloak-employee-saml.ts
  apigw/src/internal/mobile-device-session.ts
  apigw/src/internal/routes/auth-status.ts
  apigw/src/pino-cli/__tests__/cli/bin.ts
  apigw/src/pino-cli/cli/bin.ts
  apigw/src/pino-cli/cli/index.ts
  apigw/src/pino-cli/test-utils/fixtures/log-messages.ts
  apigw/src/shared/__tests__/logging.ts
  apigw/src/shared/__tests__/passport-saml-cache-redis.ts
  apigw/src/shared/__tests__/saml-certificates-test.ts
  apigw/src/shared/__tests__/saml-slo.ts
  apigw/src/shared/auth/dev-auth.ts
  apigw/src/shared/auth/index.ts
  apigw/src/shared/auth/jwt.ts
  apigw/src/shared/certificates.ts
  apigw/src/shared/config.ts
  apigw/src/shared/dev-api.ts
  apigw/src/shared/express.ts
  apigw/src/shared/logging.ts
  apigw/src/shared/middleware/error-handler.ts
  apigw/src/shared/proxy-utils.ts
  apigw/src/shared/routes/csp.ts
  apigw/src/shared/routes/saml.ts
  apigw/src/shared/saml/error-utils.ts
  apigw/src/shared/saml/index.ts
  apigw/src/shared/saml/passport-saml-cache-redis.ts
  apigw/src/shared/service-client.ts
  apigw/src/shared/session.ts
  apigw/src/shared/test/gateway-tester.ts
  apigw/src/tracer.ts
  apigw/yarn.lock
Labels: tech

#5316 Lyhennetään vanhempainvapaa -teksti mahtumaan yksikön viikkonäkymässä
  frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
Labels: enhancement

#5315 Käytetään uusinta core-js:ää
  frontend/webpack.config.js
Labels: tech

#5300 Automaattinen poissaolojen luonti varausten luonnin yhteydessä
  frontend/src/citizen-frontend/calendar/DayView.tsx
  frontend/src/citizen-frontend/calendar/calendar-elements.tsx
  frontend/src/citizen-frontend/calendar/queries.ts
  frontend/src/citizen-frontend/calendar/reservation-modal/form.spec.ts
  frontend/src/citizen-frontend/calendar/reservation-modal/form.ts
  frontend/src/citizen-frontend/generated/api-clients/reservations.ts
  frontend/src/e2e-test/generated/api-clients.ts
  frontend/src/e2e-test/pages/citizen/citizen-calendar.ts
  frontend/src/e2e-test/specs/0_citizen/citizen-reservations.spec.ts
  frontend/src/employee-frontend/components/unit/queries.ts
  frontend/src/employee-frontend/generated/api-clients/reservations.ts
  frontend/src/lib-customizations/espoo/featureFlags.tsx
  frontend/src/lib-customizations/types.d.ts
  service/src/integrationTest/kotlin/fi/espoo/evaka/reservations/CreateReservationsAndAbsencesTest.kt
  service/src/main/kotlin/fi/espoo/evaka/reservations/AttendanceReservationController.kt
  service/src/main/kotlin/fi/espoo/evaka/reservations/ReservationControllerCitizen.kt
  service/src/main/kotlin/fi/espoo/evaka/reservations/ReservationQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/reservations/Reservations.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/dev/DevApi.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/domain/Time.kt
Labels: enhancement

#5313 Espoo: päivityksiä päätösten ja sähköpostien teksteihin
  service/src/main/kotlin/fi/espoo/evaka/emailclient/EvakaEmailMessageProvider.kt
  service/src/main/resources/WEB-INF/templates/assistance-need-preschool/decision.properties
  service/src/main/resources/WEB-INF/templates/assistance-need-preschool/decision_sv.properties
  service/src/main/resources/WEB-INF/templates/assistance-need/decision.properties
  service/src/main/resources/WEB-INF/templates/assistance-need/decision_sv.properties
  service/src/main/resources/WEB-INF/templates/preparatory/decision.properties
  service/src/main/resources/WEB-INF/templates/preparatory/decision_sv.properties
  service/src/main/resources/WEB-INF/templates/preschool/decision.properties
  service/src/main/resources/WEB-INF/templates/preschool/decision_sv.properties
  service/src/main/resources/WEB-INF/templates/shared/daycare-correction.html
  service/src/main/resources/WEB-INF/templates/shared/daycare-correction_sv.properties
Labels: no-changelog

#5279 Suomi.fi viestit REST-pilottitoteutus
  service/src/integrationTest/kotlin/fi/espoo/evaka/sficlient/SoapStackIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/sficlient/rest/MockSfiMessagesRestEndpoint.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/sficlient/rest/SfiMessagesRestClientIntegrationTest.kt
  service/src/main/kotlin/fi/espoo/evaka/EvakaEnv.kt
  service/src/main/kotlin/fi/espoo/evaka/sficlient/rest/InMemoryStore.kt
  service/src/main/kotlin/fi/espoo/evaka/sficlient/rest/RestSchema.kt
  service/src/main/kotlin/fi/espoo/evaka/sficlient/rest/SfiMessagesRestClient.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/config/SfiConfig.kt
Labels: enhancement

#5317 Ei näytetä suljettuja yksiköitä toimintojen avauksissa
  service/src/main/kotlin/fi/espoo/evaka/daycare/DaycareQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/daycare/controllers/DaycareController.kt
Labels: enhancement

#5311 Vahvistetaan hakemuksen poistaminen käsittelystä
  frontend/src/employee-frontend/components/applications/ApplicationActions.tsx
  frontend/src/lib-components/molecules/modals/InfoModal.tsx
  frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
Labels: enhancement

#5314 Järjestetään talouspäätökset päämiehen sivulla voimassaoloajan mukaan
  frontend/src/employee-frontend/components/person-profile/PersonFeeDecisions.tsx
  frontend/src/employee-frontend/components/person-profile/PersonVoucherValueDecisions.tsx
Labels: enhancement

#5318 isPermittedForSomeTarget-käyttöoikeustarkastus ei ole enää liian salliva
  service/src/integrationTest/kotlin/fi/espoo/evaka/shared/security/IsCitizenTest.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/security/AccessControl.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/security/actionrule/ActionRule.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/security/actionrule/HasGlobalRole.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/security/actionrule/HasGroupRole.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/security/actionrule/HasUnitRole.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/security/actionrule/IsCitizen.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/security/actionrule/IsEmployee.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/security/actionrule/IsMobile.kt
Labels: bug

#5320 Raportit aakkosjärjestykseen
  frontend/src/employee-frontend/components/Reports.tsx
Labels: enhancement

#5323 Ei sallita kuntalaisen tehdä varauksia aikojen kanssa avoimille loma-ajoille
  service/src/integrationTest/kotlin/fi/espoo/evaka/reservations/CreateReservationsAndAbsencesTest.kt
  service/src/main/kotlin/fi/espoo/evaka/reservations/Reservations.kt
Labels: bug

#5324 Käytetään uutta SQL query API:a, osa 4
  service/src/integrationTest/kotlin/fi/espoo/evaka/TestFixtures.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/absence/AbsenceControllerIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/absence/AbsenceGenerationIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/application/ApplicationStateServiceIntegrationTests.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/application/ApplicationUpdateIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/application/GetApplicationIntegrationTests.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/assistanceneed/AssistanceNeedVoucherCoefficientIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/attendance/AttendanceUpkeepIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/attendance/MobileRealtimeStaffAttendanceControllerIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/dailyservicetimes/DailyServiceTimesIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/daycare/controllers/UnitAclControllerIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/daycare/service/StaffAttendanceServiceIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/decision/DecisionCreationIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/holidayperiod/HolidayPeriodControllerCitizenIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/incomestatement/IncomeStatementControllerCitizenIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/incomestatement/IncomeStatementControllerIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/FeeDecisionIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/InvoiceIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/PaymentsIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/VoucherValueDecisionIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/data/FeeDecisionSearchTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/data/VoucherValueDecisionQueriesTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/service/FeeDecisionGeneratorIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/service/FinanceDecisionGeneratorIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/service/InvoiceCorrectionsIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/service/InvoiceGeneratorIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/service/OutdatedIncomeNotificationsIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/service/VoucherValueDecisionGeneratorIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/koski/KoskiIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/koski/KoskiIntegrationTestHelpers.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/koski/KoskiPayloadIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/messaging/DraftQueriesTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/messaging/MessageAccountQueriesTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/messaging/MessageIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/messaging/MessageNotificationEmailServiceIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/messaging/MessageQueriesTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/pairing/PairingIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/pedagogicaldocument/PedagogicalDocumentNotificationServiceIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/pis/InactiveEmployeesRoleResetIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/pis/PersonIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/pis/controller/PersonControllerIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/pis/service/MergeServiceIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/placement/PlacementServiceIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/reports/InvoicingReportTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/reports/MissingHeadOfFamilyReportTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/reservations/AttendanceReservationsControllerIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/reservations/MissingReservationsRemindersTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/reservations/ReservationUpkeepIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/shared/async/AsyncJobQueriesTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/shared/async/AsyncJobRunnerTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/shared/db/DatabaseTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/shared/job/ScheduledJobsTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/shared/security/AssistanceNeedDecisionAccessControlTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/test/TestQueries.kt
Labels: tech
