Repository espoon-voltti/evaka, pull requests merged in 2024-09, with the labels that each got.

#5599 Laskuluonnoksen rivejä ei voi enää muokata manuaalisesti
  frontend/src/e2e-test/pages/employee/finance/finance-page.ts
  frontend/src/e2e-test/specs/4_finance/invoices.spec.ts
  frontend/src/employee-frontend/components/invoice/Actions.tsx
  frontend/src/employee-frontend/components/invoice/InvoicePage.tsx
  frontend/src/employee-frontend/components/invoice/InvoiceRowsSection.tsx
  frontend/src/employee-frontend/components/invoice/InvoiceRowsSectionRow.tsx
  frontend/src/employee-frontend/components/person-profile/PersonInvoiceCorrections.tsx
  frontend/src/employee-frontend/generated/api-clients/invoicing.ts
  frontend/src/lib-common/generated/action.d.ts
  frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
  service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/InvoiceIntegrationTest.kt
  service/src/main/kotlin/fi/espoo/evaka/invoicing/controller/InvoiceController.kt
  service/src/main/kotlin/fi/espoo/evaka/invoicing/data/InvoiceQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/invoicing/service/InvoiceService.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/security/Action.kt
Labels: breaking

#5600 Suorituskykyparannus lasten läsnäolohakuun (käytössä mobiilissa)
  service/src/main/kotlin/fi/espoo/evaka/attendance/ChildAttendanceQueries.kt
Labels: tech

#5602 Suorituskykyparannus yksikön kuukausikalenteriin
  service/src/main/kotlin/fi/espoo/evaka/absence/AbsenceQueries.kt
Labels: tech

#5590 Lisää korjauksia sähköpostien lähetykseen
  service/src/integrationTest/kotlin/fi/espoo/evaka/jamix/JamixIntegrationTest.kt
  service/src/main/kotlin/fi/espoo/evaka/emailclient/EmailClient.kt
  service/src/main/kotlin/fi/espoo/evaka/jamix/JamixService.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/async/AsyncJob.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/dev/DevApi.kt
  service/src/main/kotlin/fi/espoo/evaka/specialdiet/SpecialDietController.kt
  service/src/main/kotlin/fi/espoo/evaka/specialdiet/SpecialDietQueries.kt
Labels: tech

#5601 Tulotietomuistutuksen lähetyslogiikan muutos
  service/src/main/kotlin/fi/espoo/evaka/invoicing/service/IncomeQueries.kt
Labels: enhancement

#5591 Usean kyselyn aikaisen sijoituksen aiheuttamien keskusteluaikaongelmien korjaus kuntalaiselle
  frontend/src/citizen-frontend/calendar/discussion-reservation-modal/DiscussionReservationModal.tsx
  frontend/src/e2e-test/pages/citizen/citizen-discussion-surveys.ts
  frontend/src/e2e-test/specs/0_citizen/citizen-discussion-surveys.spec.ts
  service/src/main/kotlin/fi/espoo/evaka/calendarevent/CalendarEvent.kt
  service/src/main/kotlin/fi/espoo/evaka/calendarevent/CalendarEventController.kt
  service/src/main/kotlin/fi/espoo/evaka/calendarevent/CalendarEventQueries.kt
Labels: bug

#5544 Lasten läsnäoloraporttiin tuntifiltteri
  frontend/src/e2e-test/pages/employee/reports.ts
  frontend/src/e2e-test/specs/5_employee/child-attendance-reservation-report.spec.ts
  frontend/src/employee-frontend/components/reports/AttendanceReservationByChild.tsx
  frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
Labels: enhancement

#5609 Bugikorjaus käyttöastekyselyyn
  service/src/main/kotlin/fi/espoo/evaka/daycare/CaretakerQueries.kt
Labels: bug

#5608 Ei heitetä virhettä jos pyynnössä ei ole Accept-headeria
  service/src/main/kotlin/fi/espoo/evaka/shared/config/SpringMvcConfig.kt
Labels: tech

#5603 Korjaa monta sijoitusta omaavien lasten näyttäminen kasvattajille keskustelukyselyissä
  frontend/src/e2e-test/pages/employee/units/unit.ts
  frontend/src/e2e-test/specs/5_employee/unit-calendar-events.spec.ts
  frontend/src/employee-frontend/components/unit/tab-calendar/CalendarEventsSection.tsx
  frontend/src/employee-frontend/components/unit/tab-calendar/discussion-surveys/DiscussionSurveyView.tsx
  frontend/src/employee-frontend/components/unit/tab-calendar/discussion-surveys/survey-editor/form.tsx
Labels: bug

#5612 Espoo: keskusteluvaraukset tuotantoon
  frontend/src/lib-customizations/espoo/featureFlags.tsx
Labels: no-changelog

#5581 Pääkäyttäjä voi uudelleenlähettää yksikön Jamix-ruokatilaukset tietylle päivälle
  frontend/src/employee-frontend/components/reports/MealReport.tsx
  frontend/src/employee-frontend/components/reports/ReportDownload.tsx
  frontend/src/employee-frontend/generated/api-clients/jamix.ts
  frontend/src/lib-common/generated/action.d.ts
  frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
  service/src/integrationTest/kotlin/fi/espoo/evaka/jamix/JamixIntegrationTest.kt
  service/src/main/kotlin/fi/espoo/evaka/Audit.kt
  service/src/main/kotlin/fi/espoo/evaka/jamix/JamixController.kt
  service/src/main/kotlin/fi/espoo/evaka/jamix/JamixService.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/security/Action.kt
Labels: enhancement

#5607 Laskutus-frontendin refaktorointi
  frontend/src/employee-frontend/components/invoice/Actions.tsx
  frontend/src/employee-frontend/components/invoice/InvoicePage.tsx
  frontend/src/employee-frontend/components/invoices/Actions.tsx
  frontend/src/employee-frontend/components/invoices/Invoices.tsx
  frontend/src/employee-frontend/components/invoices/InvoicesPage.tsx
  frontend/src/employee-frontend/components/invoices/invoices-state.ts
  frontend/src/employee-frontend/components/invoices/queries.ts
  frontend/src/employee-frontend/query.ts
Labels: tech

#5606 Siivotaan fronttikomponentteja aikaisempien löydösten perusteella
  frontend/src/citizen-frontend/calendar/AbsenceModal.tsx
  frontend/src/citizen-frontend/calendar/DayView.tsx
  frontend/src/citizen-frontend/calendar/ReservationModal.tsx
  frontend/src/citizen-frontend/children/sections/service-need-and-daily-service-time/ServiceNeedAndDailyServiceTimeSection.tsx
  frontend/src/citizen-frontend/login/LoginPage.tsx
  frontend/src/employee-frontend/components/holiday-term-periods/FixedPeriodQuestionnaireForm.tsx
  frontend/src/employee-frontend/components/placement-draft/PlacementDraft.tsx
  frontend/src/employee-frontend/components/placement-draft/UnitCard.tsx
  frontend/src/employee-frontend/components/unit/TabCalendar.tsx
  frontend/src/employee-frontend/components/unit/tab-groups/notes/ChildDailyNoteForm.tsx
  frontend/src/employee-mobile-frontend/child-attendance/actions/AbsenceSelector.tsx
  frontend/src/employee-mobile-frontend/child-notes/DailyNotesTab.tsx
  frontend/src/employee-mobile-frontend/staff-attendance/components/StaffAttendanceTypeSelection.tsx
  frontend/src/lib-components/async-rendering.tsx
  frontend/src/lib-components/atoms/Chip.tsx
  frontend/src/lib-components/atoms/HorizontalLine.tsx
  frontend/src/lib-components/atoms/InternalLink.tsx
  frontend/src/lib-components/atoms/LinkWrapperInlineBlock.tsx
  frontend/src/lib-components/atoms/state/ErrorSegment.tsx
  frontend/src/lib-components/atoms/state/Spinner.tsx
Labels: tech

#5611 Paremmat tyypitykset queryille + `queryOrDefault` pois
  frontend/src/citizen-frontend/applications/editor/ApplicationFormDaycare.tsx
  frontend/src/citizen-frontend/applications/editor/ApplicationFormPreschool.tsx
  frontend/src/citizen-frontend/income-statements/ChildIncomeStatementEditor.tsx
  frontend/src/citizen-frontend/income-statements/IncomeStatementEditor.tsx
  frontend/src/employee-frontend/components/invoices/InvoicesPage.tsx
  frontend/src/employee-frontend/components/reports/AttendanceReservation.tsx
  frontend/src/employee-frontend/components/reports/AttendanceReservationByChild.tsx
  frontend/src/employee-frontend/components/reports/ChildAttendanceReport.tsx
  frontend/src/employee-frontend/components/reports/CustomerFees.tsx
  frontend/src/employee-frontend/components/reports/ExceededServiceNeeds.tsx
  frontend/src/employee-frontend/components/reports/FamilyContacts.tsx
  frontend/src/employee-frontend/components/reports/MissingHeadOfFamily.tsx
  frontend/src/employee-frontend/components/reports/PreschoolAbsenceReport.tsx
  frontend/src/employee-frontend/components/unit/unit-reservations/ChildDateModal.tsx
  frontend/src/employee-mobile-frontend/child-attendance/ChildListItem.tsx
  frontend/src/employee-mobile-frontend/child-attendance/actions/MarkAbsent.tsx
  frontend/src/employee-mobile-frontend/child-attendance/actions/MarkDeparted.tsx
  frontend/src/employee-mobile-frontend/child-attendance/actions/MarkPresent.tsx
  frontend/src/employee-mobile-frontend/common/top-bar/LoggedInUser.tsx
  frontend/src/employee-mobile-frontend/messages/ThreadView.tsx
  frontend/src/employee-mobile-frontend/messages/state.tsx
  frontend/src/lib-common/query.ts
Labels: tech

#5615 Muut kuntakohtaiset lomakkeet ja lomakepohjien sijoitustyyppirajaus
  frontend/src/e2e-test/dev-api/fixtures.ts
  frontend/src/e2e-test/generated/api-types.ts
  frontend/src/e2e-test/pages/employee/documents/document-templates.ts
  frontend/src/e2e-test/specs/5_employee/child-documents.spec.ts
  frontend/src/employee-frontend/components/child-documents/statuses.ts
  frontend/src/employee-frontend/components/document-templates/template-editor/TemplateContentEditor.tsx
  frontend/src/employee-frontend/components/document-templates/template-editor/TemplateModal.tsx
  frontend/src/lib-common/generated/api-types/document.ts
  frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
  service/src/integrationTest/kotlin/fi/espoo/evaka/document/DocumentTemplateIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/document/childdocument/ChildDocumentControllerIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/pdfgen/PdfGeneratorTest.kt
  service/src/main/kotlin/fi/espoo/evaka/document/DocumentTemplate.kt
  service/src/main/kotlin/fi/espoo/evaka/document/DocumentTemplateController.kt
  service/src/main/kotlin/fi/espoo/evaka/document/DocumentTemplateQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/document/childdocument/ChildDocumentQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/document/childdocument/ChildDocumentQueriesCitizen.kt
  service/src/main/kotlin/fi/espoo/evaka/placement/PlacementQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/dev/DataInitializers.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/dev/DevApi.kt
  service/src/main/kotlin/fi/espoo/evaka/vasu/DocumentMigrator.kt
  service/src/main/resources/db/migration/V432__document_template_placement_types.sql
  service/src/main/resources/migrations.txt
Labels: enhancement

#5617 Yksikön kuukausikalenterissa voi valita rivin kaikki päivät yhdellä klikkauksella
  frontend/src/employee-frontend/components/absences/MonthCalendarCell.tsx
  frontend/src/employee-frontend/components/absences/MonthCalendarTable.tsx
  frontend/src/lib-components/layout/Table.tsx
  frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
Labels: enhancement

#5619 Parannuksia päivämodaalin yhteensopivuuteen selaimen käännöstoiminnon kanssa
  frontend/src/citizen-frontend/calendar/AttendanceInfo.tsx
  frontend/src/citizen-frontend/calendar/MonthlyHoursSummary.tsx
Labels: enhancement

#5638 Korjataan liitetiedostojen maksimikoon rajoitus
  frontend/proxy/files/etc/nginx/conf.d/nginx.conf.template
Labels: bug

#5620 Korjataan osapäivän poissaolojen käsittely raportilla ja yksikön käyttöastegraafissa
  service/src/integrationTest/kotlin/fi/espoo/evaka/reports/AttendanceReservationReportTest.kt
  service/src/main/kotlin/fi/espoo/evaka/absence/AbsenceQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/occupancy/OccupancyController.kt
  service/src/main/kotlin/fi/espoo/evaka/reports/AttendanceReservationReportController.kt
Labels: bug

#5621 Suorituskykyparannus lapsen tiedot -sivulle
  service/src/main/resources/db/migration/V433__child_document_template_index.sql
  service/src/main/resources/migrations.txt
Labels: tech

#5465 Vasumigraation yliheitto
  frontend/src/citizen-frontend/App.tsx
  frontend/src/citizen-frontend/child-documents/ChildDocumentPage.tsx
  frontend/src/citizen-frontend/children/ChildPage.tsx
  frontend/src/citizen-frontend/children/sections/ChildDocumentsSection.tsx
  frontend/src/citizen-frontend/children/sections/vasu-and-leops/VasuAndLeopsSection.tsx
  frontend/src/citizen-frontend/children/sections/vasu-and-leops/queries.ts
  frontend/src/citizen-frontend/children/sections/vasu-and-leops/vasu/VasuPage.tsx
  frontend/src/citizen-frontend/children/sections/vasu-and-leops/vasu/components/CheckboxQuestion.tsx
  frontend/src/citizen-frontend/children/sections/vasu-and-leops/vasu/components/DateQuestion.tsx
  frontend/src/citizen-frontend/children/sections/vasu-and-leops/vasu/components/FollowupQuestion.tsx
  frontend/src/citizen-frontend/children/sections/vasu-and-leops/vasu/components/MultiFieldListQuestion.tsx
  frontend/src/citizen-frontend/children/sections/vasu-and-leops/vasu/components/MultiFieldQuestion.tsx
  frontend/src/citizen-frontend/children/sections/vasu-and-leops/vasu/components/MultiSelectQuestion.tsx
  frontend/src/citizen-frontend/children/sections/vasu-and-leops/vasu/components/Paragraph.tsx
  frontend/src/citizen-frontend/children/sections/vasu-and-leops/vasu/components/RadioGroupQuestion.tsx
  frontend/src/citizen-frontend/children/sections/vasu-and-leops/vasu/components/ReadOnlyValue.tsx
  frontend/src/citizen-frontend/children/sections/vasu-and-leops/vasu/components/StaticInfoSubsection.tsx
  frontend/src/citizen-frontend/children/sections/vasu-and-leops/vasu/components/TextQuestion.tsx
  frontend/src/citizen-frontend/children/sections/vasu-and-leops/vasu/components/ValueOrNoRecord.tsx
  frontend/src/citizen-frontend/children/sections/vasu-and-leops/vasu/components/VasuContainer.tsx
  frontend/src/citizen-frontend/children/sections/vasu-and-leops/vasu/components/VasuStateChip.tsx
  frontend/src/citizen-frontend/children/sections/vasu-and-leops/vasu/components/question-props.ts
  frontend/src/citizen-frontend/children/sections/vasu-and-leops/vasu/sections/CitizenBasicsSection.tsx
  frontend/src/citizen-frontend/children/sections/vasu-and-leops/vasu/sections/CitizenDynamicSections.tsx
  frontend/src/citizen-frontend/children/sections/vasu-and-leops/vasu/sections/CitizenVasuEvents.tsx
  frontend/src/citizen-frontend/children/sections/vasu-and-leops/vasu/sections/CitizenVasuHeader.tsx
  frontend/src/citizen-frontend/children/sections/vasu-and-leops/vasu/vasu-content.ts
  frontend/src/citizen-frontend/children/sections/vasu-and-leops/vasu/vasu-events.ts
  frontend/src/citizen-frontend/navigation/utils.ts
  frontend/src/e2e-test/pages/citizen/citizen-children.ts
  frontend/src/e2e-test/pages/employee/child-information.ts
  frontend/src/e2e-test/pages/employee/vasu/pageSections.ts
  frontend/src/e2e-test/pages/employee/vasu/vasu-template-edit.ts
  frontend/src/e2e-test/pages/employee/vasu/vasu-templates-list.ts
  frontend/src/e2e-test/pages/employee/vasu/vasu.ts
  frontend/src/e2e-test/specs/0_citizen/citizen-child-documents.spec.ts
  frontend/src/e2e-test/specs/0_citizen/citizen-vasu.spec.ts
  frontend/src/e2e-test/specs/0_citizen/foster-parents.spec.ts
  frontend/src/e2e-test/specs/5_employee/curriculum-document.spec.ts
  frontend/src/e2e-test/specs/5_employee/leops.spec.ts
  frontend/src/e2e-test/specs/5_employee/vasu.spec.ts
  frontend/src/employee-frontend/components/child-information/ChildDocuments.tsx
  frontend/src/employee-frontend/components/child-information/ChildDocumentsSection.tsx
  frontend/src/lib-customizations/defaults/citizen/i18n/en.tsx
  frontend/src/lib-customizations/defaults/citizen/i18n/fi.tsx
  frontend/src/lib-customizations/defaults/citizen/i18n/sv.tsx
  service/src/main/kotlin/fi/espoo/evaka/document/childdocument/ChildDocumentController.kt
  service/src/main/kotlin/fi/espoo/evaka/document/childdocument/ChildDocumentQueriesCitizen.kt
Labels: breaking

#5616 Viestin lähetyksestä indikaatio ruudunlukijalle
  frontend/src/citizen-frontend/messages/MessagesPage.tsx
  frontend/src/e2e-test/pages/citizen/citizen-messages.ts
  frontend/src/e2e-test/specs/7_messaging/messaging.spec.ts
  frontend/src/lib-components/Notifications.tsx
  frontend/src/lib-components/molecules/TimedToast.tsx
  frontend/src/lib-customizations/defaults/citizen/i18n/en.tsx
  frontend/src/lib-customizations/defaults/citizen/i18n/fi.tsx
  frontend/src/lib-customizations/defaults/citizen/i18n/sv.tsx
Labels: enhancement

#5622 Suorituskykyparannus läsnäolotietojen hakuun
  service/src/main/kotlin/fi/espoo/evaka/reports/AttendanceReservationReportController.kt
Labels: tech

#5624 Keycloak-teeman tekninen siivous
  keycloak/theme/evaka/account/account.ftl
  keycloak/theme/evaka/account/messages/messages_en.properties
  keycloak/theme/evaka/account/messages/messages_fi.properties
  keycloak/theme/evaka/account/messages/messages_sv.properties
  keycloak/theme/evaka/account/password.ftl
  keycloak/theme/evaka/account/resources/js/fakeSignOutPage.js
  keycloak/theme/evaka/account/template.ftl
  keycloak/theme/evaka/account/theme.properties
  keycloak/theme/evaka/email/messages/messages_en.properties
  keycloak/theme/evaka/email/messages/messages_fi.properties
  keycloak/theme/evaka/email/messages/messages_sv.properties
  keycloak/theme/evaka/login/messages/messages_en.properties
  keycloak/theme/evaka/login/messages/messages_fi.properties
  keycloak/theme/evaka/login/messages/messages_sv.properties
  keycloak/theme/package-lock.json
  keycloak/theme/package.json
  keycloak/theme/scripts/.eslintrc
  keycloak/theme/scripts/config.js
  keycloak/theme/scripts/export-translations.js
  keycloak/theme/scripts/pack-theme.js
  keycloak/theme/scripts/update-translations/convertTranslationData.js
  keycloak/theme/scripts/update-translations/getTranslationDataFromSources.js
  keycloak/theme/scripts/update-translations/getTranslationSources.js
  keycloak/theme/scripts/update-translations/index.js
  keycloak/theme/scripts/update-translations/writeTranslations.js
Labels: tech

#5645 MultiSelect-komponentin yhteensopivuus selaimen automaattikäännöksen kanssa
  frontend/src/lib-components/atoms/form/MultiSelect.tsx
Labels: enhancement

#5643 Korjauksia lapsikohtaiset läsnäoloajat -raporttiin
  frontend/src/e2e-test/pages/employee/reports.ts
  frontend/src/e2e-test/specs/5_employee/child-attendance-reservation-report.spec.ts
  frontend/src/employee-frontend/components/reports/AttendanceReservationByChild.tsx
  frontend/src/employee-frontend/components/reports/queries.ts
  frontend/src/employee-frontend/generated/api-clients/reports.ts
  frontend/src/lib-common/generated/api-types/reports.ts
  frontend/src/lib-common/time-range-endpoint.ts
  frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
  service/src/integrationTest/kotlin/fi/espoo/evaka/reports/AttendanceReservationReportByChildTest.kt
  service/src/main/kotlin/fi/espoo/evaka/reports/AttendanceReservationReportController.kt
Labels: enhancement

#5613 Kuntalaisen tuloselvityksen parannuksia
  frontend/src/citizen-frontend/income-statements/IncomeStatementForm.tsx
  frontend/src/citizen-frontend/income-statements/types/form.ts
  frontend/src/e2e-test/pages/citizen/citizen-income.ts
  frontend/src/e2e-test/specs/0_citizen/citizen-income-statement.spec.ts
  frontend/src/lib-customizations/defaults/citizen/i18n/en.tsx
  frontend/src/lib-customizations/defaults/citizen/i18n/fi.tsx
  frontend/src/lib-customizations/defaults/citizen/i18n/sv.tsx
Labels: enhancement

#5652 Yhden API-polun korjaus
  apigw/src/shared/service-client.ts
Labels: tech

#5648 Päivitetään Keycloak versioon 25.0.5
  keycloak/Dockerfile
  keycloak/dummy-suomifi/gradle/libs.versions.toml
  keycloak/evaka-logging/pom.xml
Labels: tech

#5653 Lähetetään hetuttomat lapset Vardaan eri tavalla
  service/src/integrationTest/kotlin/fi/espoo/evaka/varda/new/VardaUpdaterIntegrationTest.kt
  service/src/main/kotlin/fi/espoo/evaka/varda/new/VardaClient.kt
  service/src/main/kotlin/fi/espoo/evaka/varda/new/VardaUpdateServiceNew.kt
Labels: bug

#5646 Talouden päätöksen lakitekstin muutos
  service/src/main/resources/WEB-INF/templates/fee-decision/decision.properties
  service/src/main/resources/WEB-INF/templates/fee-decision/decision_sv.properties
Labels: enhancement

#5642 Lisätään uusi tuotantosertifikaatti Suomi.fi kirjautumiselle + helpotetaan konfiguraatiota
  apigw/config/certificates/saml-signing.idp.tunnistautuminen.suomi.fi.2024.pem
  apigw/src/shared/certificates.ts
  apigw/src/shared/config.ts
Labels: tech

#5641 Poistetaan sivukoon määritys API-requesteista
  frontend/src/citizen-frontend/generated/api-clients/incomestatement.ts
  frontend/src/citizen-frontend/generated/api-clients/messaging.ts
  frontend/src/citizen-frontend/income-statements/ChildrenIncomeStatements.tsx
  frontend/src/citizen-frontend/income-statements/IncomeStatements.tsx
  frontend/src/citizen-frontend/income-statements/queries.ts
  frontend/src/citizen-frontend/messages/queries.ts
  frontend/src/citizen-frontend/messages/state.tsx
  frontend/src/employee-frontend/components/applications/ApplicationsPage.tsx
  frontend/src/employee-frontend/components/employees/EmployeesPage.tsx
  frontend/src/employee-frontend/components/employees/queries.ts
  frontend/src/employee-frontend/components/fee-decisions/FeeDecisionsPage.tsx
  frontend/src/employee-frontend/components/income-statements/IncomeStatementsPage.tsx
  frontend/src/employee-frontend/components/invoices/InvoicesPage.tsx
  frontend/src/employee-frontend/components/messages/MessageContext.tsx
  frontend/src/employee-frontend/components/payments/payments-state.ts
  frontend/src/employee-frontend/components/person-profile/PersonIncome.tsx
  frontend/src/employee-frontend/components/voucher-value-decisions/VoucherValueDecisionsPage.tsx
  frontend/src/employee-frontend/generated/api-clients/incomestatement.ts
  frontend/src/employee-frontend/generated/api-clients/messaging.ts
  frontend/src/employee-mobile-frontend/generated/api-clients/messaging.ts
  frontend/src/employee-mobile-frontend/messages/queries.ts
  frontend/src/lib-common/generated/api-types/application.ts
  frontend/src/lib-common/generated/api-types/incomestatement.ts
  frontend/src/lib-common/generated/api-types/invoicing.ts
  frontend/src/lib-common/generated/api-types/pis.ts
  service/src/integrationTest/kotlin/fi/espoo/evaka/application/ApplicationQueriesSmokeTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/application/ApplicationSearchIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/incomestatement/IncomeStatementControllerCitizenIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/incomestatement/IncomeStatementControllerIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/FeeDecisionIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/InvoiceIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/PaymentsIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/messaging/MessageIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/pis/controller/EmployeeControllerSearchIntegrationTest.kt
  service/src/main/kotlin/fi/espoo/evaka/application/ApplicationControllerV2.kt
  service/src/main/kotlin/fi/espoo/evaka/application/ApplicationQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/incomestatement/IncomeStatementController.kt
  service/src/main/kotlin/fi/espoo/evaka/incomestatement/IncomeStatementControllerCitizen.kt
  service/src/main/kotlin/fi/espoo/evaka/invoicing/controller/FeeDecisionController.kt
  service/src/main/kotlin/fi/espoo/evaka/invoicing/controller/InvoiceController.kt
  service/src/main/kotlin/fi/espoo/evaka/invoicing/controller/PaymentController.kt
  service/src/main/kotlin/fi/espoo/evaka/invoicing/controller/VoucherValueDecisionController.kt
  service/src/main/kotlin/fi/espoo/evaka/invoicing/data/PaymentQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/messaging/MessageController.kt
  service/src/main/kotlin/fi/espoo/evaka/messaging/MessageControllerCitizen.kt
  service/src/main/kotlin/fi/espoo/evaka/pis/controllers/EmployeeController.kt
Labels: tech

#5655 Ei yritetä poistaa inaktiivista huoltajaa tai lasta jolla on pedadoc tai tuen päätös
  service/src/integrationTest/kotlin/fi/espoo/evaka/pis/InactivePeopleCleanupIntegrationTest.kt
  service/src/main/kotlin/fi/espoo/evaka/pis/InactivePeopleCleanup.kt
Labels: bug

#5670 Poistaa esiopetuksen poissaoloraportilta tulevaisuuden poissaolot
  frontend/src/e2e-test/specs/5_employee/preschool-absence-report.spec.ts
  frontend/src/employee-frontend/components/reports/PreschoolAbsenceReport.tsx
Labels: enhancement

#5671 Poistetaan käyttämättömiä metodeita
  service/src/main/kotlin/fi/espoo/evaka/shared/security/actionrule/HasUnitRole.kt
Labels: tech

#5673 Automaattinen poissolojen luonti varausten luonnin yhteydessä päälle Espoon tuotannossa
  frontend/src/lib-customizations/espoo/featureFlags.tsx
Labels: no-changelog

#5677 Käytetään oikeaa triggeriä `archived_process`-taulussa
  service/src/main/resources/db/migration/V435__archived_process_fix_trigger.sql
  service/src/main/resources/migrations.txt
Labels: tech

#5675 Varhaiskasvatussihteeri voi nähdä ryhmien kalenterin menneisyyteen
  frontend/src/employee-frontend/components/unit/tab-groups/Groups.tsx
Labels: enhancement

#5680 Parannuksia erityisruokavalion valintaan
  frontend/src/e2e-test/specs/5_employee/child-information.spec.ts
  frontend/src/employee-frontend/components/child-information/person-details/AdditionalInformation.tsx
Labels: enhancement

#5674 Tekstikorjauksia
  frontend/src/lib-customizations/defaults/employee-mobile-frontend/i18n/fi.ts
  frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
  service/src/main/resources/application-espoo_evaka.yaml
Labels: bug

#5605 Esiopetuspaikan osoituksen aineiston luku ja hakemusten luonti
  frontend/src/employee-frontend/App.tsx
  frontend/src/employee-frontend/components/Header.tsx
  frontend/src/employee-frontend/components/placement-tool/PlacementToolPage.tsx
  frontend/src/employee-frontend/components/placement-tool/api.ts
  frontend/src/lib-common/generated/action.d.ts
  frontend/src/lib-common/generated/api-types/shared.ts
  frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
  service/build.gradle.kts
  service/evaka-bom/build.gradle.kts
  service/src/integrationTest/kotlin/fi/espoo/evaka/application/PlacementToolServiceIntegrationTest.kt
  service/src/main/kotlin/fi/espoo/evaka/Audit.kt
  service/src/main/kotlin/fi/espoo/evaka/application/Application.kt
  service/src/main/kotlin/fi/espoo/evaka/application/ApplicationControllerV2.kt
  service/src/main/kotlin/fi/espoo/evaka/application/ApplicationStateService.kt
  service/src/main/kotlin/fi/espoo/evaka/application/PlacementToolController.kt
  service/src/main/kotlin/fi/espoo/evaka/application/PlacementToolService.kt
  service/src/main/kotlin/fi/espoo/evaka/pis/SystemController.kt
  service/src/main/kotlin/fi/espoo/evaka/s3/ContentTypeUtils.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/async/AsyncJob.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/message/EvakaMessageProvider.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/message/MessageProvider.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/security/Action.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/security/EmployeeFeatures.kt
Labels: enhancement

#5678 lisätään toimintayksikön id ladattavalle tulevat esikoululaiset raportille
  frontend/src/employee-frontend/components/reports/FuturePreschoolersReport.tsx
Labels: bug

#5672 Näytetään tulotiedon päättymispäivä tuloselvitykset-listassa, versio 2
  frontend/src/e2e-test/pages/employee/finance/finance-page.ts
  frontend/src/e2e-test/specs/4_finance/income-staments.spec.ts
  frontend/src/employee-frontend/components/common/Filters.tsx
  frontend/src/employee-frontend/components/income-statements/IncomeStatementFilters.tsx
  frontend/src/employee-frontend/components/income-statements/IncomeStatementsPage.tsx
  frontend/src/employee-frontend/components/income-statements/queries.ts
  frontend/src/employee-frontend/query.ts
  frontend/src/lib-common/generated/api-types/incomestatement.ts
  frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
  service/src/integrationTest/kotlin/fi/espoo/evaka/incomestatement/IncomeStatementControllerIntegrationTest.kt
  service/src/main/kotlin/fi/espoo/evaka/calendarevent/CalendarEventQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/incomestatement/IncomeStatementController.kt
  service/src/main/kotlin/fi/espoo/evaka/incomestatement/IncomeStatementQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/reservations/ReservationQueries.kt
  service/src/main/resources/db/migration/V436_income_statement_and_income_indexes.sql
  service/src/main/resources/migrations.txt
Labels: enhancement

#5682 Viestiketjuun vastaamisesta indikaatio ruudunlukijalle
  frontend/src/citizen-frontend/messages/ThreadView.tsx
  frontend/src/e2e-test/specs/7_messaging/messaging.spec.ts
Labels: enhancement

#5684 Lisätään mahdollisuus konfiguroida varhaiskasvatuksen oletuspäättymispäivämäärä
  service/src/main/kotlin/fi/espoo/evaka/placement/PlacementPlanService.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/FeatureConfig.kt
Labels: enhancement

#5683 Poistetaan asiakasmaksutiimi osoite tulotietomuistutukselta
  service/src/main/kotlin/fi/espoo/evaka/emailclient/EvakaEmailMessageProvider.kt
Labels: enhancement

#5685 Muutetaan pin-login endpoint system-tyyppiseksi
  apigw/src/shared/service-client.ts
  frontend/src/employee-mobile-frontend/auth/api.ts
  frontend/src/employee-mobile-frontend/generated/api-clients/pairing.ts
  frontend/src/lib-common/generated/api-types/pairing.ts
  frontend/src/lib-common/generated/api-types/pis.ts
  service/codegen/src/main/kotlin/evaka/codegen/api/Config.kt
  service/src/main/kotlin/fi/espoo/evaka/pairing/MobileDevicesController.kt
  service/src/main/kotlin/fi/espoo/evaka/pis/SystemController.kt
Labels: tech

#5687 Korjataan yksikön kuukausikalenterin "Henkilökuntaa paikalla"-kenttien sijainti
  frontend/src/employee-frontend/components/absences/StaffAttendance.tsx
Labels: bug

#5686 apigw:n testeihin liittyviä korjauksia
  apigw/.dockerignore
  apigw/Dockerfile
  apigw/jest.config.js
  apigw/package.json
  apigw/src/shared/__tests__/logging.ts
  apigw/src/shared/__tests__/saml-certificates-test.ts
Labels: tech

#5676 Parannuksia päivämäärien ja aikojen käsittelyyn
  frontend/package.json
  frontend/src/employee-frontend/components/applications/ApplicationsList.tsx
  frontend/src/employee-frontend/components/child-documents/ChildDocumentEditor.tsx
  frontend/src/employee-frontend/components/child-information/assistance-need/decision/AssistanceNeedPreschoolDecisionEditPage.tsx
  frontend/src/employee-frontend/components/common/AutosaveStatusIndicator.tsx
  frontend/src/employee-frontend/components/reports/Occupancies.tsx
  frontend/src/employee-frontend/components/unit/tab-unit-information/occupancy/OccupancyDayGraphPlanned.tsx
  frontend/src/employee-frontend/components/unit/tab-unit-information/occupancy/OccupancyDayGraphRealized.tsx
  frontend/src/employee-frontend/components/unit/tab-unit-information/occupancy/OccupancyGraph.tsx
  frontend/src/employee-frontend/utils/use-autosave.ts
  frontend/src/employee-mobile-frontend/child-attendance/actions/MarkPresent.tsx
  frontend/src/employee-mobile-frontend/staff-attendance/StaffMarkArrivedPage.tsx
  frontend/src/lib-common/date.spec.ts
  frontend/src/lib-common/date.ts
  frontend/src/lib-common/helsinki-date-time.spec.ts
  frontend/src/lib-common/helsinki-date-time.ts
  frontend/yarn.lock
Labels: tech

#5658 Kuntalainen voi tehdä palveluntarpeen muutoshakemuksen
  frontend/src/citizen-frontend/App.tsx
  frontend/src/citizen-frontend/children/queries.ts
  frontend/src/citizen-frontend/children/sections/service-need-and-daily-service-time/NewServiceApplicationPage.tsx
  frontend/src/citizen-frontend/children/sections/service-need-and-daily-service-time/ServiceApplications.tsx
  frontend/src/citizen-frontend/children/sections/service-need-and-daily-service-time/ServiceNeedAndDailyServiceTimeSection.tsx
  frontend/src/citizen-frontend/generated/api-clients/serviceneed.ts
  frontend/src/lib-common/generated/action.d.ts
  frontend/src/lib-common/generated/api-types/serviceneed.ts
  frontend/src/lib-customizations/defaults/citizen/i18n/en.tsx
  frontend/src/lib-customizations/defaults/citizen/i18n/fi.tsx
  frontend/src/lib-customizations/defaults/citizen/i18n/sv.tsx
  frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
  frontend/src/lib-customizations/espoo/featureFlags.tsx
  frontend/src/lib-customizations/types.d.ts
  service/codegen/src/main/kotlin/evaka/codegen/actionenum/Definitions.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/children/ChildControllerCitizenTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/pis/PersonIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/serviceneed/application/ServiceApplicationIntegrationTest.kt
  service/src/main/kotlin/fi/espoo/evaka/Audit.kt
  service/src/main/kotlin/fi/espoo/evaka/children/ChildControllerCitizen.kt
  service/src/main/kotlin/fi/espoo/evaka/serviceneed/application/ServiceApplication.kt
  service/src/main/kotlin/fi/espoo/evaka/serviceneed/application/ServiceApplicationControllerCitizen.kt
  service/src/main/kotlin/fi/espoo/evaka/serviceneed/application/ServiceApplicationQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/Id.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/security/Action.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/security/actionrule/IsCitizen.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/utils/Kotlin.kt
  service/src/main/resources/db/migration/V437__service_application.sql
  service/src/main/resources/migrations.txt
Labels: enhancement

#5644 Aiempien päivien kirjausten muokkaus mobiilissa
  frontend/src/e2e-test/pages/mobile/staff-page.ts
  frontend/src/e2e-test/specs/6_mobile/realtime-staff-attendances.spec.ts
  frontend/src/employee-mobile-frontend/App.tsx
  frontend/src/employee-mobile-frontend/generated/api-clients/attendance.ts
  frontend/src/employee-mobile-frontend/staff-attendance/StaffAttendanceEditPage.tsx
  frontend/src/employee-mobile-frontend/staff-attendance/StaffMemberPage.tsx
  frontend/src/employee-mobile-frontend/staff-attendance/StaffPreviousAttendancesPage.tsx
  frontend/src/employee-mobile-frontend/staff-attendance/queries.ts
  frontend/src/lib-components/layout/ListGrid.tsx
  frontend/src/lib-customizations/defaults/employee-mobile-frontend/i18n/fi.ts
  service/src/integrationTest/kotlin/fi/espoo/evaka/attendance/MobileRealtimeStaffAttendanceControllerIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/attendance/RealtimeStaffAttendanceQueriesTest.kt
  service/src/main/kotlin/fi/espoo/evaka/attendance/MobileRealtimeStaffAttendanceController.kt
  service/src/main/kotlin/fi/espoo/evaka/attendance/StaffAttendanceQueries.kt
Labels: enhancement

#5656 Parempi apigw:n konfiguraatiomekanismi ja dokumentaatio
  apigw/src/enduser/mapRoutes.ts
  apigw/src/index.ts
  apigw/src/shared/auth/jwt.ts
  apigw/src/shared/config.ts
  apigw/src/shared/middleware/error-handler.ts
Labels: tech

#5688 Parannuksia RangeBasedSet/RangeBasedMap -datarakenteisiin
  service/src/main/kotlin/fi/espoo/evaka/absence/AbsenceService.kt
  service/src/main/kotlin/fi/espoo/evaka/invoicing/service/DraftInvoiceGenerator.kt
  service/src/main/kotlin/fi/espoo/evaka/koski/KoskiData.kt
  service/src/main/kotlin/fi/espoo/evaka/occupancy/Occupancy.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/data/RangeBasedMap.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/data/RangeBasedSet.kt
  service/src/test/kotlin/fi/espoo/evaka/shared/data/DateMapTest.kt
  service/src/test/kotlin/fi/espoo/evaka/shared/data/DateSetTest.kt
  service/src/test/kotlin/fi/espoo/evaka/shared/data/DateTimeMapTest.kt
  service/src/test/kotlin/fi/espoo/evaka/shared/data/DateTimeSetTest.kt
Labels: tech

#5679 Poistetaan esiopetuksen kerhon laskutus
  service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/service/InvoiceGeneratorIntegrationTest.kt
  service/src/main/kotlin/fi/espoo/evaka/invoicing/service/DraftInvoiceGenerator.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/domain/Time.kt
Labels: enhancement

#5657 Siivotaan suurin osa deprekoiduista asioista evaka-servicessä
  apigw/src/enduser/keycloak-citizen-saml.ts
  apigw/src/internal/mobile-device-session.ts
  apigw/src/internal/routes/auth-status.ts
  service/src/main/kotlin/fi/espoo/evaka/EvakaEnv.kt
  service/src/main/kotlin/fi/espoo/evaka/assistanceneed/decision/AssistanceNeedDecision.kt
  service/src/main/kotlin/fi/espoo/evaka/invoicing/service/PdfGeneration.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/db/Database.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/dev/DataInitializers.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/message/IMessageProvider.kt
  service/src/main/kotlin/fi/espoo/evaka/vasu/Vasu.kt
Labels: tech

#5695 HOTFIX: Vaihdetaan takaisin `date-fns-tz`-kirjastoon
  frontend/package.json
  frontend/src/lib-common/helsinki-date-time.ts
  frontend/yarn.lock
Labels: no-changelog

#5692 Varoitetaan toisessa yksikössä olevista avoimista kirjauksista mobiilissa
  frontend/src/e2e-test/pages/mobile/staff-page.ts
  frontend/src/e2e-test/specs/6_mobile/realtime-staff-attendances.spec.ts
  frontend/src/employee-frontend/components/unit/unit-reservations/StaffAttendanceDetailsModal.tsx
  frontend/src/employee-frontend/components/unit/unit-reservations/StaffAttendanceTable.tsx
  frontend/src/employee-frontend/generated/api-clients/attendance.ts
  frontend/src/employee-mobile-frontend/generated/api-clients/attendance.ts
  frontend/src/employee-mobile-frontend/staff-attendance/StaffMemberPage.tsx
  frontend/src/employee-mobile-frontend/staff-attendance/queries.ts
  frontend/src/lib-customizations/defaults/employee-mobile-frontend/i18n/fi.ts
  service/src/main/kotlin/fi/espoo/evaka/attendance/MobileRealtimeStaffAttendanceController.kt
  service/src/main/kotlin/fi/espoo/evaka/attendance/RealtimeStaffAttendanceController.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/security/Action.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/security/actionrule/IsEmployee.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/security/actionrule/IsMobile.kt
Labels: enhancement

#5698 Korjataan esiopetuksen poissaoloraportti opetustauoilla
  service/src/integrationTest/kotlin/fi/espoo/evaka/reports/PreschoolAbsenceReportTest.kt
  service/src/main/kotlin/fi/espoo/evaka/reports/PreschoolAbsenceReport.kt
Labels: bug

#5706 Korjataan `yarn.lock`
  frontend/yarn.lock
Labels: no-changelog

#5708 Päivitetään Keycloak versioon 25.0.6
  keycloak/Dockerfile
  keycloak/dummy-suomifi/gradle/libs.versions.toml
  keycloak/evaka-logging/pom.xml
Labels: dependencies

#5707 Päivitetään yarn versioon 4.5.0
  apigw/.yarn/releases/yarn-4.3.1.cjs
  apigw/.yarn/releases/yarn-4.5.0.cjs
  apigw/.yarnrc.yml
  apigw/package.json
  apigw/yarn.lock
  frontend/.yarn/releases/yarn-4.3.1.cjs
  frontend/.yarn/releases/yarn-4.5.0.cjs
  frontend/.yarnrc.yml
  frontend/package.json
  frontend/yarn.lock
Labels: dependencies

#5709 Update frontend/.gitignore
  frontend/.gitignore
Labels: no-changelog

#5710 Lisätään palveluntarpeen muutoshakemukset toimintojen avauksiin
  frontend/src/citizen-frontend/children/sections/service-need-and-daily-service-time/NewServiceApplicationPage.tsx
  frontend/src/citizen-frontend/children/sections/service-need-and-daily-service-time/ServiceApplications.tsx
  frontend/src/citizen-frontend/children/sections/service-need-and-daily-service-time/ServiceNeedAndDailyServiceTimeSection.tsx
  frontend/src/lib-common/generated/api-types/shared.ts
  frontend/src/lib-customizations/defaults/citizen/i18n/en.tsx
  frontend/src/lib-customizations/defaults/citizen/i18n/fi.tsx
  frontend/src/lib-customizations/defaults/citizen/i18n/sv.tsx
  frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
  service/src/integrationTest/kotlin/fi/espoo/evaka/serviceneed/application/ServiceApplicationIntegrationTest.kt
  service/src/main/kotlin/fi/espoo/evaka/children/ChildControllerCitizen.kt
  service/src/main/kotlin/fi/espoo/evaka/serviceneed/application/ServiceApplicationControllerCitizen.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/security/Action.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/security/PilotFeature.kt
  service/src/main/resources/db/migration/V438__service_applications_unit_feature.sql
  service/src/main/resources/migrations.txt
Labels: enhancement

#5697 Focus-tyylien palauttaminen
  frontend/src/citizen-frontend/calendar/CalendarGridView.tsx
  frontend/src/citizen-frontend/calendar/DayElem.tsx
  frontend/src/employee-frontend/components/Header.tsx
  frontend/src/lib-components/atoms/buttons/LinkButton.tsx
  frontend/src/lib-components/layout/Container.tsx
  frontend/src/lib-components/molecules/DatePickerDeprecated.tsx
  frontend/src/lib-components/molecules/Tabs.tsx
Labels: bug

#5696 Yksikön täyttö- ja käyttöastegraafin parannuksia
  frontend/src/e2e-test/pages/employee/units/unit-calendar-page-base.ts
  frontend/src/e2e-test/specs/5_employee/realtime-attendances.spec.ts
  frontend/src/employee-frontend/components/unit/queries.ts
  frontend/src/employee-frontend/components/unit/tab-unit-information/Occupancy.tsx
  frontend/src/employee-frontend/components/unit/tab-unit-information/occupancy/OccupanciesForSingleDay.tsx
  frontend/src/employee-frontend/generated/api-clients/occupancy.ts
  frontend/src/lib-common/generated/api-types/occupancy.ts
  frontend/src/lib-components/atoms/dropdowns/TreeDropdown.tsx
  service/src/integrationTest/kotlin/fi/espoo/evaka/occupancy/OccupancyControllerIntegrationTest.kt
  service/src/main/kotlin/fi/espoo/evaka/occupancy/OccupancyController.kt
  service/src/main/kotlin/fi/espoo/evaka/occupancy/RealtimeOccupancy.kt
Labels: enhancement

#5712 Tekinen: Poistetaan `automaticFixedScheduleAbsences` feature flag
  frontend/src/citizen-frontend/calendar/queries.ts
  frontend/src/citizen-frontend/generated/api-clients/reservations.ts
  frontend/src/employee-frontend/components/unit/queries.ts
  frontend/src/employee-frontend/generated/api-clients/reservations.ts
  frontend/src/lib-customizations/espoo/featureFlags.tsx
  frontend/src/lib-customizations/types.d.ts
  service/src/integrationTest/kotlin/fi/espoo/evaka/reservations/CreateReservationsAndAbsencesTest.kt
  service/src/main/kotlin/fi/espoo/evaka/reservations/AttendanceReservationController.kt
  service/src/main/kotlin/fi/espoo/evaka/reservations/ReservationControllerCitizen.kt
  service/src/main/kotlin/fi/espoo/evaka/reservations/Reservations.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/dev/DevApi.kt
Labels: tech

#5717 Muutetaan asiakasmaksut csv raportti käyttämään euroja senttien sijaan
  frontend/src/employee-frontend/components/reports/CustomerFees.tsx
Labels: bug

#5715 Yksikön hakuprosessi-välilehdellä näytetään käsittelyä odottavat palveluntarpeen muutoshakemukset
  frontend/src/e2e-test/pages/employee/units/unit.ts
  frontend/src/employee-frontend/components/UnitPage.tsx
  frontend/src/employee-frontend/components/unit/TabApplicationProcess.tsx
  frontend/src/employee-frontend/components/unit/TabServiceApplications.tsx
  frontend/src/employee-frontend/components/unit/queries.ts
  frontend/src/employee-frontend/generated/api-clients/serviceneed.ts
  frontend/src/lib-common/generated/action.d.ts
  frontend/src/lib-common/generated/api-types/serviceneed.ts
  frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
  service/src/integrationTest/kotlin/fi/espoo/evaka/serviceneed/application/ServiceApplicationIntegrationTest.kt
  service/src/main/kotlin/fi/espoo/evaka/Audit.kt
  service/src/main/kotlin/fi/espoo/evaka/daycare/controllers/DaycareController.kt
  service/src/main/kotlin/fi/espoo/evaka/serviceneed/application/ServiceApplication.kt
  service/src/main/kotlin/fi/espoo/evaka/serviceneed/application/ServiceApplicationController.kt
  service/src/main/kotlin/fi/espoo/evaka/serviceneed/application/ServiceApplicationQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/security/Action.kt
Labels: enhancement

#5720 Näytetään tuloselvityksen luontipäivä kuntalaiselle
  frontend/src/citizen-frontend/income-statements/ChildrenIncomeStatements.tsx
  frontend/src/citizen-frontend/income-statements/IncomeStatements.tsx
  frontend/src/lib-customizations/defaults/citizen/i18n/en.tsx
  frontend/src/lib-customizations/defaults/citizen/i18n/fi.tsx
  frontend/src/lib-customizations/defaults/citizen/i18n/sv.tsx
Labels: enhancement

#5721 Varoitetaan avoimista kirjauksista vain jos ne ovat toisessa yksikössä
  frontend/src/employee-frontend/components/unit/unit-reservations/StaffAttendanceDetailsModal.tsx
  frontend/src/employee-frontend/components/unit/unit-reservations/StaffAttendanceTable.tsx
  frontend/src/employee-frontend/generated/api-clients/attendance.ts
  service/src/main/kotlin/fi/espoo/evaka/attendance/RealtimeStaffAttendanceController.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/security/Action.kt
Labels: bug

#5716 E2E-testit palveluntarpeen muutoshakemuksille
  frontend/src/citizen-frontend/children/sections/service-need-and-daily-service-time/NewServiceApplicationPage.tsx
  frontend/src/citizen-frontend/children/sections/service-need-and-daily-service-time/ServiceApplications.tsx
  frontend/src/e2e-test/dev-api/fixtures.ts
  frontend/src/e2e-test/pages/citizen/citizen-children.ts
  frontend/src/e2e-test/pages/citizen/citizen-new-service-application.ts
  frontend/src/e2e-test/pages/employee/child-information.ts
  frontend/src/e2e-test/pages/employee/units/unit.ts
  frontend/src/e2e-test/specs/5_employee/service-applications.spec.ts
  frontend/src/e2e-test/specs/8_access/access.spec.ts
  frontend/src/employee-frontend/components/child-information/ServiceApplicationsSection.tsx
  frontend/src/employee-frontend/components/unit/TabServiceApplications.tsx
Labels: tech

#5718 Palveluntarpeen muutoshakemuksen hyväksyntä luo uuden palveluntarpeen
  frontend/src/e2e-test/pages/employee/child-information.ts
  frontend/src/e2e-test/specs/5_employee/service-applications.spec.ts
  frontend/src/employee-frontend/components/child-information/ServiceApplicationsSection.tsx
  frontend/src/employee-frontend/components/child-information/placements/service-needs/ServiceNeedReadRow.tsx
  frontend/src/employee-frontend/generated/api-clients/serviceneed.ts
  frontend/src/lib-common/generated/api-types/serviceneed.ts
  frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
  service/src/integrationTest/kotlin/fi/espoo/evaka/serviceneed/application/ServiceApplicationIntegrationTest.kt
  service/src/main/kotlin/fi/espoo/evaka/serviceneed/application/ServiceApplication.kt
  service/src/main/kotlin/fi/espoo/evaka/serviceneed/application/ServiceApplicationController.kt
  service/src/main/kotlin/fi/espoo/evaka/serviceneed/application/ServiceApplicationQueries.kt
Labels: enhancement

#5728 Korjataan viallinen migraatio ja validoidaan migraatioiden nimet
  service/src/main/kotlin/fi/espoo/evaka/shared/config/DatabaseConfig.kt
  service/src/main/resources/db/migration/V439__income_statement_and_income_indexes.sql
  service/src/main/resources/migrations.txt
Labels: tech

#5723 Palveluntarpeen muutoshakemus sallii vaihdon osapäiväisen/kokopäiväisen sijoituksen välillä
  frontend/src/employee-frontend/components/child-information/ServiceApplicationsSection.tsx
  frontend/src/lib-common/generated/api-types/serviceneed.ts
  frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
  service/src/integrationTest/kotlin/fi/espoo/evaka/serviceneed/application/ServiceApplicationIntegrationTest.kt
  service/src/main/kotlin/fi/espoo/evaka/serviceneed/application/ServiceApplication.kt
  service/src/main/kotlin/fi/espoo/evaka/serviceneed/application/ServiceApplicationController.kt
  service/src/main/kotlin/fi/espoo/evaka/serviceneed/application/ServiceApplicationControllerCitizen.kt
  service/src/main/kotlin/fi/espoo/evaka/serviceneed/application/ServiceApplicationQueries.kt
Labels: enhancement

#5724 Ei lasketa huoltajalla vahvistettavana olevia hakemuksia yksikön hakuprosessi-välilehden huomio-lukumäärään
  service/src/main/kotlin/fi/espoo/evaka/application/Application.kt
  service/src/main/kotlin/fi/espoo/evaka/daycare/controllers/DaycareController.kt
  service/src/main/kotlin/fi/espoo/evaka/placement/PlacementPlanQueries.kt
Labels: enhancement

#5729 Lisätään modaalien sulkeminen esc-näppäimellä
  frontend/package.json
  frontend/src/citizen-frontend/calendar/AbsenceModal.tsx
  frontend/src/citizen-frontend/calendar/DayView.tsx
  frontend/src/citizen-frontend/calendar/ReservationModal.tsx
  frontend/src/citizen-frontend/calendar/discussion-reservation-modal/DiscussionReservationModal.tsx
  frontend/src/citizen-frontend/calendar/discussion-reservation-modal/DiscussionSurveyModal.tsx
  frontend/src/citizen-frontend/children/sections/service-need-and-daily-service-time/ServiceApplications.tsx
  frontend/src/employee-frontend/components/unit/tab-groups/notes/NotesModal.tsx
  frontend/src/employee-frontend/components/unit/tab-unit-information/DaycareAclAdditionModal.tsx
  frontend/src/employee-frontend/components/unit/tab-unit-information/EmployeeAclRowEditModal.tsx
  frontend/src/employee-frontend/components/unit/unit-reservations/StaffAttendanceDetailsModal.tsx
  frontend/src/employee-frontend/components/unit/unit-reservations/StaffAttendanceExternalPersonModal.tsx
  frontend/src/lib-components/molecules/date-picker/DatePickerLowLevel.tsx
  frontend/src/lib-components/molecules/modals/BaseModal.tsx
  frontend/src/lib-components/molecules/modals/ModalBackground.tsx
  frontend/yarn.lock
Labels: enhancement

#5732 Päiväeditorin sulkeminen kohdistaa kalenteripäivään
  frontend/src/citizen-frontend/calendar/CalendarGridView.tsx
  frontend/src/citizen-frontend/calendar/CalendarPage.tsx
  frontend/src/citizen-frontend/calendar/DayElem.tsx
  frontend/src/e2e-test/pages/citizen/citizen-calendar.ts
  frontend/src/e2e-test/specs/0_citizen/citizen-calendar.spec.ts
Labels: enhancement

#5735 Näytetään kaikki työaikakirjaukset kun kalenterin ryhmävalintana on henkilökunta
  frontend/src/e2e-test/specs/5_employee/realtime-attendances.spec.ts
  frontend/src/employee-frontend/components/unit/unit-reservations/StaffAttendanceTable.tsx
  frontend/src/employee-frontend/components/unit/unit-reservations/UnitAttendanceReservationsView.tsx
Labels: bug

#5736 Näytetään pedagogisen arvion toimintopainikkeet tulosteessa lomakkeen lopussa eikä sisällön päällä
  frontend/src/employee-frontend/components/child-documents/ChildDocumentEditor.tsx
Labels: bug

#5750 Korjataan `bootRunTest` käyttämään testikantaa
  service/build.gradle.kts
Labels: tech

#5730 Korjataan työntekijän mobiilin navigaatiopalkki asetukset sivulla
  frontend/src/employee-mobile-frontend/settings/SettingsPage.tsx
Labels: bug
