Repository espoon-voltti/evaka, pull requests merged in 2025-02, with the labels that each got.

#6333 Palvelutuottajien uusi kirjautuminen Espoon tuotantoon päälle
  frontend/src/lib-customizations/espoo/featureFlags.tsx
Labels: no-changelog

#6318 Yksikön luvitus-sivun refaktorointi ja uudistus (osa 1)
  frontend/src/e2e-test/pages/employee/units/unit.ts
  frontend/src/e2e-test/specs/5_employee/unit-acl.spec.ts
  frontend/src/e2e-test/specs/5_employee/unit-editor.spec.ts
  frontend/src/employee-frontend/components/UnitPage.tsx
  frontend/src/employee-frontend/components/unit/TabApplicationProcess.tsx
  frontend/src/employee-frontend/components/unit/TabCalendar.tsx
  frontend/src/employee-frontend/components/unit/TabGroups.tsx
  frontend/src/employee-frontend/components/unit/TabUnitInformation.tsx
  frontend/src/employee-frontend/components/unit/queries.ts
  frontend/src/employee-frontend/components/unit/tab-calendar/CalendarEventsSection.tsx
  frontend/src/employee-frontend/components/unit/tab-unit-information/DaycareAclAdditionModal.tsx
  frontend/src/employee-frontend/components/unit/tab-unit-information/EmployeeAclRowEditModal.tsx
  frontend/src/employee-frontend/components/unit/tab-unit-information/UnitAccessControl.tsx
  frontend/src/employee-frontend/components/unit/tab-unit-information/UnitMobileDevices.tsx
  frontend/src/employee-frontend/components/unit/tab-unit-information/acl-modals/AddAclModal.tsx
  frontend/src/employee-frontend/components/unit/tab-unit-information/acl-modals/AddTemporaryEmployeeModal.tsx
  frontend/src/employee-frontend/components/unit/tab-unit-information/acl-modals/EditAclModal.tsx
  frontend/src/employee-frontend/components/unit/tab-unit-information/acl-modals/EditTemporaryEmployeeModal.tsx
  frontend/src/employee-frontend/components/unit/tab-unit-information/acl-modals/common.ts
  frontend/src/employee-frontend/generated/api-clients/daycare.ts
  frontend/src/employee-frontend/state/StateProvider.tsx
  frontend/src/employee-frontend/state/unit.tsx
  frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
  service/src/main/kotlin/fi/espoo/evaka/daycare/controllers/UnitAclController.kt
Labels: enhancement

#6340 Kuntalaisen kevytkirjautumisen pikkukorjauksia
  frontend/src/citizen-frontend/personal-details/LoginDetailsSection.tsx
  frontend/src/citizen-frontend/personal-details/PersonalDetails.tsx
  frontend/src/lib-customizations/defaults/citizen/i18n/en.tsx
  frontend/src/lib-customizations/defaults/citizen/i18n/fi.tsx
  frontend/src/lib-customizations/defaults/citizen/i18n/sv.tsx
  service/src/integrationTest/kotlin/fi/espoo/evaka/pis/controller/WeakCredentialsIntegrationTest.kt
  service/src/main/kotlin/fi/espoo/evaka/pis/SystemController.kt
  service/src/main/kotlin/fi/espoo/evaka/pis/controllers/PersonalDataControllerCitizen.kt
Labels: enhancement

#6334 Kuntalaisten uusi kevytkirjautuminen Espoon tuotantoon päälle
  frontend/src/lib-customizations/espoo/featureFlags.tsx
Labels: no-changelog

#6338 Poistetaan käyttämätön tietokantanäkymä
  service/src/main/resources/db/migration/R__message_account_access_view.sql
Labels: tech

#6316 Talouden muistiinpano aikuisen tietoihin
  frontend/src/e2e-test/generated/api-clients.ts
  frontend/src/e2e-test/generated/api-types.ts
  frontend/src/e2e-test/pages/employee/guardian-information.ts
  frontend/src/e2e-test/specs/4_finance/person-finance-notes-and-messages.spec.ts
  frontend/src/employee-frontend/components/PersonProfile.tsx
  frontend/src/employee-frontend/components/person-profile/PersonFinanceNotesAndMessages.tsx
  frontend/src/employee-frontend/components/person-profile/queries.ts
  frontend/src/employee-frontend/generated/api-clients/finance.ts
  frontend/src/lib-common/generated/action.d.ts
  frontend/src/lib-common/generated/api-types/finance.ts
  frontend/src/lib-common/generated/api-types/shared.ts
  frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
  service/codegen/src/main/kotlin/evaka/codegen/actionenum/Definitions.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/pis/PersonIntegrationTest.kt
  service/src/main/kotlin/fi/espoo/evaka/Audit.kt
  service/src/main/kotlin/fi/espoo/evaka/finance/notes/FinanceNote.kt
  service/src/main/kotlin/fi/espoo/evaka/finance/notes/FinanceNoteController.kt
  service/src/main/kotlin/fi/espoo/evaka/finance/notes/FinanceNoteQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/Id.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/dev/DevApi.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/security/Action.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/security/actionrule/IsEmployee.kt
  service/src/main/resources/db/migration/V492__finance_note.sql
  service/src/main/resources/migrations.txt
Labels: enhancement

#6347 Näytetään selkeämpi virhe jos oikeudet puuttuvat
  frontend/src/citizen-frontend/async-rendering.tsx
  frontend/src/employee-frontend/components/async-rendering.tsx
  frontend/src/employee-mobile-frontend/async-rendering.tsx
  frontend/src/lib-components/async-rendering.tsx
  frontend/src/lib-customizations/defaults/citizen/i18n/en.tsx
  frontend/src/lib-customizations/defaults/citizen/i18n/fi.tsx
  frontend/src/lib-customizations/defaults/citizen/i18n/sv.tsx
  frontend/src/lib-customizations/defaults/employee-mobile-frontend/i18n/fi.ts
  frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
Labels: enhancement

#6346 Johtaja saa poistaa henkilökunnan luvituksia
  frontend/src/employee-frontend/components/unit/tab-unit-information/UnitAccessControl.tsx
Labels: bug

#6345 Korjataan yksikön viikkokalenterin näkyvyystarkistus
  frontend/src/employee-frontend/components/unit/TabCalendar.tsx
Labels: bug

#6341 Poistetaan huoltajuussuhteet joissa lapsi on jo täysi-ikäinen
  service/src/integrationTest/kotlin/fi/espoo/evaka/shared/job/ScheduledJobsTest.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/job/ScheduledJobs.kt
Labels: enhancement

#6344 Merkitään hakemus salassapidettäväksi jos siinä on liite
  service/src/main/kotlin/fi/espoo/evaka/application/ApplicationQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/application/ApplicationStateService.kt
Labels: enhancement

#6336 Luvituksen ennalta asetettu loppupäivä
  frontend/src/employee-frontend/components/employees/DaycareRolesModal.tsx
  frontend/src/employee-frontend/components/employees/EmployeePage.tsx
  frontend/src/employee-frontend/components/unit/tab-unit-information/UnitAccessControl.tsx
  frontend/src/employee-frontend/components/unit/tab-unit-information/acl-modals/AddAclModal.tsx
  frontend/src/employee-frontend/components/unit/tab-unit-information/acl-modals/EditAclModal.tsx
  frontend/src/employee-frontend/generated/api-clients/daycare.ts
  frontend/src/lib-common/generated/api-types/daycare.ts
  frontend/src/lib-common/generated/api-types/pis.ts
  frontend/src/lib-common/generated/api-types/shared.ts
  frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
  service/src/integrationTest/kotlin/fi/espoo/evaka/daycare/controllers/UnitAclControllerIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/pis/controller/EmployeeControllerIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/pis/controller/EmployeeControllerSearchIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/shared/job/ScheduledJobsTest.kt
  service/src/main/kotlin/fi/espoo/evaka/daycare/controllers/UnitAclController.kt
  service/src/main/kotlin/fi/espoo/evaka/pis/EmployeeQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/pis/controllers/EmployeeController.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/auth/AclQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/dev/DataInitializers.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/job/ScheduledJobs.kt
  service/src/main/resources/db/migration/V493__acl_end_date.sql
  service/src/main/resources/migrations.txt
Labels: enhancement

#6348 Kirjautumisen pikkukorjauksia, osa 3
  apigw/src/enduser/routes/auth-weak-login.ts
  frontend/src/citizen-frontend/personal-details/LoginDetailsSection.tsx
  frontend/src/citizen-frontend/personal-details/PersonalDetailsSection.tsx
  frontend/src/lib-customizations/defaults/citizen/i18n/en.tsx
  frontend/src/lib-customizations/defaults/citizen/i18n/fi.tsx
  frontend/src/lib-customizations/defaults/citizen/i18n/sv.tsx
  service/src/main/kotlin/fi/espoo/evaka/pis/SystemController.kt
  service/src/main/kotlin/fi/espoo/evaka/pis/controllers/PersonalDataControllerCitizen.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/job/ScheduledJobs.kt
Labels: enhancement

#6339 Pääkäyttäjä voi ajastaa tulevia luvituksia etukäteen
  frontend/src/employee-frontend/components/employees/DaycareRolesModal.tsx
  frontend/src/employee-frontend/components/employees/EmployeePage.tsx
  frontend/src/employee-frontend/components/employees/queries.ts
  frontend/src/employee-frontend/components/unit/queries.ts
  frontend/src/employee-frontend/components/unit/tab-unit-information/UnitAccessControl.tsx
  frontend/src/employee-frontend/generated/api-clients/daycare.ts
  frontend/src/employee-frontend/generated/api-clients/pis.ts
  frontend/src/lib-common/generated/api-types/pis.ts
  frontend/src/lib-common/generated/api-types/shared.ts
  frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
  service/src/integrationTest/kotlin/fi/espoo/evaka/pis/controller/EmployeeControllerIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/shared/job/ScheduledJobsTest.kt
  service/src/main/kotlin/fi/espoo/evaka/Audit.kt
  service/src/main/kotlin/fi/espoo/evaka/daycare/controllers/UnitAclController.kt
  service/src/main/kotlin/fi/espoo/evaka/pis/EmployeeQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/pis/controllers/EmployeeController.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/auth/AclQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/job/ScheduledJobs.kt
  service/src/main/resources/db/migration/V494__daycare_acl_schedule.sql
  service/src/main/resources/migrations.txt
Labels: enhancement

#6309 Henkilökunnan viestintä aloittaville lapsille
  frontend/src/citizen-frontend/messages/ThreadView.tsx
  frontend/src/e2e-test/pages/citizen/citizen-messages.ts
  frontend/src/e2e-test/pages/employee/messages/messages-page.ts
  frontend/src/e2e-test/specs/6_mobile/messages.spec.ts
  frontend/src/e2e-test/specs/7_messaging/messaging-by-staff.spec.ts
  frontend/src/e2e-test/specs/7_messaging/messaging.spec.ts
  frontend/src/e2e-test/specs/7_messaging/municipal-messaging.spec.ts
  frontend/src/e2e-test/specs/7_messaging/out-of-office.spec.ts
  frontend/src/e2e-test/utils/page.ts
  frontend/src/employee-frontend/components/messages/MessageEditor.tsx
  frontend/src/employee-frontend/generated/api-clients/messaging.ts
  frontend/src/employee-mobile-frontend/generated/api-clients/messaging.ts
  frontend/src/employee-mobile-frontend/messages/MessageEditor.tsx
  frontend/src/lib-common/api-types/messaging.ts
  frontend/src/lib-common/generated/api-types/messaging.ts
  frontend/src/lib-components/messages/SelectorNode.ts
  frontend/src/lib-customizations/defaults/employee-mobile-frontend/i18n/fi.ts
  frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
  service/codegen/src/main/kotlin/evaka/codegen/api/Config.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/messaging/DraftQueriesTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/messaging/MessageIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/messaging/MessageQueriesTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/messaging/MessageReceiversIntegrationTest.kt
  service/src/main/kotlin/fi/espoo/evaka/messaging/DraftContent.kt
  service/src/main/kotlin/fi/espoo/evaka/messaging/DraftQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/messaging/Message.kt
  service/src/main/kotlin/fi/espoo/evaka/messaging/MessageQueries.kt
  service/src/main/resources/db/migration/V495__draft_message_recipients.sql
  service/src/main/resources/migrations.txt
Labels: enhancement

#6354 Päivitys s3-mock versiolle
  compose/docker-compose.yml
Labels: bug

#6343 Lisätään muokkaa useampaa päivää -linkki kuntalaisen kalenterin päivämodaaliin
  frontend/src/citizen-frontend/calendar/DayView.tsx
  frontend/src/lib-customizations/defaults/citizen/i18n/en.tsx
  frontend/src/lib-customizations/defaults/citizen/i18n/fi.tsx
  frontend/src/lib-customizations/defaults/citizen/i18n/sv.tsx
Labels: enhancement

#6355 Näytetään kuntalaisen kalenterissa ilmoittamattomat poissaolot
  frontend/src/citizen-frontend/calendar/calendar-elements.tsx
  frontend/src/lib-customizations/defaults/citizen/i18n/en.tsx
  frontend/src/lib-customizations/defaults/citizen/i18n/fi.tsx
  frontend/src/lib-customizations/defaults/citizen/i18n/sv.tsx
Labels: enhancement

#6357 Kotikunta-tieto raakaraportille
  frontend/src/employee-frontend/components/reports/Raw.tsx
  frontend/src/lib-common/generated/api-types/reports.ts
  service/src/integrationTest/kotlin/fi/espoo/evaka/reports/RawReportControllerTest.kt
  service/src/main/kotlin/fi/espoo/evaka/reports/RawReport.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/dev/DataInitializers.kt
Labels: enhancement

#6372 Näytä aloittavien ryhmä viimeisenä mobiilin vastaanottajavalinnassa
  frontend/src/e2e-test/specs/7_messaging/messaging-by-staff.spec.ts
  frontend/src/employee-mobile-frontend/messages/MessageEditor.tsx
  frontend/src/lib-customizations/defaults/employee-mobile-frontend/i18n/fi.ts
  frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
Labels: bug

#6360 Lisätään mahdollisuus konfiguroida hakemuksen liitteet pakollisiksi
  frontend/src/citizen-frontend/applications/editor/service-need/PreferredStartSubSection.tsx
  frontend/src/citizen-frontend/applications/editor/service-need/ServiceTimeSubSectionDaycare.tsx
  frontend/src/citizen-frontend/applications/editor/validations.ts
  frontend/src/citizen-frontend/applications/editor/verification/ApplicationVerificationView.tsx
  frontend/src/lib-customizations/types.d.ts
Labels: enhancement

#6374 Upgrade netty to fix a CVE
  service/evaka-bom/build.gradle.kts
Labels: dependencies

#6319 Tuloselvitysten liitteet yksitellen
  frontend/src/citizen-frontend/attachments.ts
  frontend/src/citizen-frontend/generated/api-clients/incomestatement.ts
  frontend/src/citizen-frontend/income-statements/ChildIncomeStatementAttachments.tsx
  frontend/src/citizen-frontend/income-statements/ChildIncomeStatementEditor.tsx
  frontend/src/citizen-frontend/income-statements/ChildIncomeStatementForm.tsx
  frontend/src/citizen-frontend/income-statements/ChildIncomeStatementView.tsx
  frontend/src/citizen-frontend/income-statements/ChildrenIncomeStatements.tsx
  frontend/src/citizen-frontend/income-statements/IncomeStatementAttachments.tsx
  frontend/src/citizen-frontend/income-statements/IncomeStatementComponents.tsx
  frontend/src/citizen-frontend/income-statements/IncomeStatementEditor.tsx
  frontend/src/citizen-frontend/income-statements/IncomeStatementForm.tsx
  frontend/src/citizen-frontend/income-statements/IncomeStatementView.tsx
  frontend/src/citizen-frontend/income-statements/IncomeStatements.tsx
  frontend/src/citizen-frontend/income-statements/queries.ts
  frontend/src/citizen-frontend/income-statements/types/body.ts
  frontend/src/citizen-frontend/income-statements/types/common.ts
  frontend/src/citizen-frontend/income-statements/types/form.ts
  frontend/src/e2e-test/generated/api-clients.ts
  frontend/src/e2e-test/generated/api-types.ts
  frontend/src/e2e-test/pages/citizen/citizen-child-income.ts
  frontend/src/e2e-test/pages/citizen/citizen-income.ts
  frontend/src/e2e-test/specs/0_citizen/citizen-child-income-statement.spec.ts
  frontend/src/e2e-test/specs/0_citizen/citizen-income-statement.spec.ts
  frontend/src/e2e-test/utils/page.ts
  frontend/src/employee-frontend/api/attachments.ts
  frontend/src/employee-frontend/components/IncomeStatementPage.tsx
  frontend/src/employee-frontend/components/application-page/ApplicationEditView.tsx
  frontend/src/employee-frontend/generated/api-clients/incomestatement.ts
  frontend/src/lib-common/generated/api-types/application.ts
  frontend/src/lib-common/generated/api-types/attachment.ts
  frontend/src/lib-common/generated/api-types/incomestatement.ts
  frontend/src/lib-common/income-statements.ts
  frontend/src/lib-common/utils/scrolling.ts
  frontend/src/lib-components/atoms/buttons/button-visuals.tsx
  frontend/src/lib-components/molecules/FileUpload.tsx
  frontend/src/lib-customizations/defaults/citizen/i18n/en.tsx
  frontend/src/lib-customizations/defaults/citizen/i18n/fi.tsx
  frontend/src/lib-customizations/defaults/citizen/i18n/sv.tsx
  frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
  service/src/integrationTest/kotlin/fi/espoo/evaka/FullApplicationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/application/ApplicationStateServiceIntegrationTests.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/application/ApplicationUpdateIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/application/GetApplicationIntegrationTests.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/attachments/AttachmentQueriesTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/attachments/AttachmentsControllerIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/incomestatement/IncomeStatementControllerCitizenIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/incomestatement/IncomeStatementControllerIntegrationTest.kt
  service/src/main/kotlin/fi/espoo/evaka/Audit.kt
  service/src/main/kotlin/fi/espoo/evaka/application/Application.kt
  service/src/main/kotlin/fi/espoo/evaka/application/ApplicationStateService.kt
  service/src/main/kotlin/fi/espoo/evaka/attachment/Attachment.kt
  service/src/main/kotlin/fi/espoo/evaka/attachment/AttachmentQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/attachment/AttachmentService.kt
  service/src/main/kotlin/fi/espoo/evaka/attachment/AttachmentsController.kt
  service/src/main/kotlin/fi/espoo/evaka/incomestatement/IncomeStatement.kt
  service/src/main/kotlin/fi/espoo/evaka/incomestatement/IncomeStatementController.kt
  service/src/main/kotlin/fi/espoo/evaka/incomestatement/IncomeStatementControllerCitizen.kt
  service/src/main/kotlin/fi/espoo/evaka/incomestatement/IncomeStatementQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/dev/DevApi.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/security/Action.kt
Labels: enhancement

#6376 Korjaus virheeseen siirrettäessä hakemusta sijoitettaviin
  service/src/main/kotlin/fi/espoo/evaka/application/ApplicationStateService.kt
Labels: bug

#6350 Lisätään filttereitä tuen päätökset raporttiin
  frontend/src/employee-frontend/components/reports/AssistanceNeedDecisionsReport.tsx
  frontend/src/lib-common/generated/api-types/assistanceneed.ts
  frontend/src/lib-common/generated/api-types/reports.ts
  frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
  service/src/main/kotlin/fi/espoo/evaka/assistanceneed/decision/AssistanceNeedDecision.kt
  service/src/main/kotlin/fi/espoo/evaka/reports/AssistanceNeedDecisionsReport.kt
Labels: enhancement

#6352 Korjataan pitkän linkin rivitys viesteissä työntekijäpuolella
  frontend/src/employee-frontend/components/messages/SingleThreadView.tsx
  frontend/src/employee-mobile-frontend/messages/ThreadView.tsx
Labels: bug

#6353 Hakemus on tarkistettava jos huoltajat eivät ole sopineet hakemisesta yhdessä
  frontend/src/e2e-test/specs/5_employee/application-details.spec.ts
  frontend/src/e2e-test/specs/5_employee/application-transitions.spec.ts
  service/src/main/kotlin/fi/espoo/evaka/application/ApplicationQueries.kt
Labels: enhancement

#6377 Tuloselvityksen tekstikorjauksia
  frontend/src/lib-customizations/defaults/citizen/i18n/en.tsx
  frontend/src/lib-customizations/defaults/citizen/i18n/fi.tsx
  frontend/src/lib-customizations/defaults/citizen/i18n/sv.tsx
Labels: enhancement

#6379 Lisätään Espoon tulevaa työvuorosuunnitteluintegraatiota varten toimintojen avaus
  frontend/src/lib-common/generated/api-types/shared.ts
  frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
  service/src/main/kotlin/fi/espoo/evaka/shared/security/PilotFeature.kt
  service/src/main/resources/db/migration/V496__staff_attendance_integration_feature.sql
  service/src/main/resources/migrations.txt
Labels: enhancement

#6381 Päivitetään Postgres versioon 17 composessa
  compose/db/Dockerfile
Labels: tech

#6378 Vanhojen Varda-integraatioiden poiston viimeistely
  service/src/integrationTest/kotlin/fi/espoo/evaka/reports/NonSsnChildrenReportTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/varda/new/VardaUpdateServiceIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/varda/new/VardaUpdaterIntegrationTest.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/job/ScheduledJobs.kt
  service/src/main/kotlin/fi/espoo/evaka/varda/UriUtils.kt
  service/src/main/kotlin/fi/espoo/evaka/varda/Varda.kt
  service/src/main/kotlin/fi/espoo/evaka/varda/VardaClient.kt
  service/src/main/kotlin/fi/espoo/evaka/varda/VardaQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/varda/VardaUnits.kt
  service/src/main/kotlin/fi/espoo/evaka/varda/VardaUpdateService.kt
Labels: tech

#6337 Lisätään generated-sarake ja foreign key constraint hakemuksen ykkösyksikölle
  service/gradle.properties
  service/src/integrationTest/kotlin/fi/espoo/evaka/attachments/AttachmentQueriesTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/attachments/AttachmentsControllerIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/occupancy/OccupancyTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/pdfgen/PdfGeneratorTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/reports/ManualDuplicationReportTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/shared/auth/AclIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/shared/security/AttachmentAccessControlTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/test/TestData.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/varda/new/VardaUpdaterIntegrationTest.kt
  service/src/main/resources/db/migration/V497__application_primary_preferred_unit.sql
  service/src/main/resources/migrations.txt
Labels: tech

#6351 Käytetään minimaalista dummy-idp -toteutusta testeissä oikean Suomi.fi-tunnistautumisen korvikkeena
  REUSE.toml
  apigw/config/test-cert/dummy-idp.pem
  apigw/src/shared/config.ts
  compose/docker-compose.e2e-tests.yml
  compose/docker-compose.e2e.yml
  compose/docker-compose.yml
  compose/e2e/playwright/bin/run-tests.sh
  dummy-idp/.dockerignore
  dummy-idp/.gitignore
  dummy-idp/Dockerfile
  dummy-idp/README.md
  dummy-idp/nodemon.json
  dummy-idp/nodemon.json.license
  dummy-idp/package-lock.json
  dummy-idp/package.json
  dummy-idp/src/config.ts
  dummy-idp/src/html.ts
  dummy-idp/src/index.ts
  dummy-idp/src/model.ts
  dummy-idp/src/routes.ts
  dummy-idp/src/saml.ts
  dummy-idp/src/tsconfig.json
  dummy-idp/test-cert/dummy-idp.key
  dummy-idp/test-cert/dummy-idp.pem
  dummy-idp/test-cert/sp-public-cert.pem
  dummy-idp/tsconfig.json
  frontend/src/e2e-test/dev-api/fixtures.ts
  frontend/src/e2e-test/pages/citizen/citizen-dummy-suomifi.ts
  frontend/src/e2e-test/pages/citizen/citizen-messages.ts
  frontend/src/e2e-test/utils/dummy-idp.ts
  frontend/src/e2e-test/utils/dummy-suomifi.ts
  frontend/src/e2e-test/utils/user.ts
Labels: tech

#6380 Korjauksia kevytkirjautumisen käyttäjätunnuksen käsittelyyn
  frontend/src/citizen-frontend/personal-details/PersonalDetailsSection.tsx
  service/src/main/kotlin/fi/espoo/evaka/pis/EmailVerificationQueries.kt
Labels: bug

#6382 Vähennetään apigw:stä tulevia turhia virhehälyjä
  apigw/src/app.ts
  apigw/src/shared/middleware/error-handler.ts
  apigw/src/shared/routes/saml.ts
Labels: tech

#6342 Korjataan poissaolokyselyn valittavat jaksot
  frontend/src/citizen-frontend/calendar/CalendarNotifications.tsx
  frontend/src/citizen-frontend/calendar/holiday-modal/FixedPeriodSelectionModal.tsx
  frontend/src/citizen-frontend/calendar/holiday-modal/OpenRangesSelectionModal.tsx
  frontend/src/e2e-test/pages/citizen/citizen-calendar.ts
  frontend/src/e2e-test/specs/0_citizen/citizen-holiday-reservations.spec.ts
  frontend/src/lib-common/generated/api-types/holidayperiod.ts
  service/src/integrationTest/kotlin/fi/espoo/evaka/holidayperiod/HolidayPeriodControllerCitizenIntegrationTest.kt
  service/src/main/kotlin/fi/espoo/evaka/holidayperiod/HolidayPeriodControllerCitizen.kt
  service/src/main/kotlin/fi/espoo/evaka/placement/PlacementQueries.kt
Labels: enhancement

#6384 Tuloselvityksen saavutettavuus- ja UI-parannuksia
  frontend/src/citizen-frontend/income-statements/ChildIncomeStatementAttachments.tsx
  frontend/src/citizen-frontend/income-statements/ChildIncomeStatementEditor.tsx
  frontend/src/citizen-frontend/income-statements/ChildIncomeStatementForm.tsx
  frontend/src/citizen-frontend/income-statements/ChildIncomeStatementView.tsx
  frontend/src/citizen-frontend/income-statements/IncomeStatementAttachments.tsx
  frontend/src/citizen-frontend/income-statements/IncomeStatementEditor.tsx
  frontend/src/citizen-frontend/income-statements/IncomeStatementForm.tsx
  frontend/src/citizen-frontend/income-statements/IncomeStatementView.tsx
  frontend/src/e2e-test/pages/citizen/citizen-child-income.ts
  frontend/src/e2e-test/pages/citizen/citizen-income.ts
  frontend/src/employee-frontend/components/IncomeStatementPage.tsx
  frontend/src/lib-common/income-statements/attachments.ts
  frontend/src/lib-common/income-statements/body.ts
  frontend/src/lib-common/income-statements/form.ts
  frontend/src/lib-components/molecules/FileUpload.tsx
  frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
Labels: enhancement

#6373 Palveluohjauksen viestien kansiointi
  frontend/src/e2e-test/pages/employee/messages/messages-page.ts
  frontend/src/e2e-test/specs/7_messaging/service-worker-messaging.spec.ts
  frontend/src/employee-frontend/components/Header.tsx
  frontend/src/employee-frontend/components/messages/GroupMessageAccountList.tsx
  frontend/src/employee-frontend/components/messages/MessageBox.tsx
  frontend/src/employee-frontend/components/messages/MessageContext.tsx
  frontend/src/employee-frontend/components/messages/MessageEditor.tsx
  frontend/src/employee-frontend/components/messages/MessagesPage.tsx
  frontend/src/employee-frontend/components/messages/Sidebar.tsx
  frontend/src/employee-frontend/components/messages/SingleThreadView.tsx
  frontend/src/employee-frontend/components/messages/ThreadList.tsx
  frontend/src/employee-frontend/components/messages/ThreadListContainer.tsx
  frontend/src/employee-frontend/components/messages/types-view.ts
  frontend/src/employee-frontend/generated/api-clients/messaging.ts
  frontend/src/lib-common/generated/api-types/messaging.ts
  frontend/src/lib-common/generated/api-types/shared.ts
  frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
  service/src/integrationTest/kotlin/fi/espoo/evaka/messaging/MessageIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/messaging/MessageNotificationEmailServiceIntegrationTest.kt
  service/src/main/kotlin/fi/espoo/evaka/Audit.kt
  service/src/main/kotlin/fi/espoo/evaka/messaging/MessageController.kt
  service/src/main/kotlin/fi/espoo/evaka/messaging/MessageQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/messaging/MessageService.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/dev/DataInitializers.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/dev/DevApi.kt
Labels: enhancement

#6359 Pedagogisten dokumenttien arkistointegraation 1. osa
  frontend/src/e2e-test/pages/employee/documents/child-document.ts
  frontend/src/e2e-test/pages/employee/documents/document-templates.ts
  frontend/src/e2e-test/specs/5_employee/child-documents.spec.ts
  frontend/src/employee-frontend/components/child-documents/ChildDocumentEditor.tsx
  frontend/src/employee-frontend/components/child-information/queries.ts
  frontend/src/employee-frontend/components/document-templates/template-editor/TemplateContentEditor.tsx
  frontend/src/employee-frontend/components/document-templates/template-editor/TemplateModal.tsx
  frontend/src/employee-frontend/generated/api-clients/document.ts
  frontend/src/lib-common/generated/action.d.ts
  frontend/src/lib-common/generated/api-types/document.ts
  frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
  frontend/src/lib-customizations/espoo/featureFlags.tsx
  frontend/src/lib-customizations/types.d.ts
  service/src/integrationTest/kotlin/fi/espoo/evaka/document/childdocument/ChildDocumentControllerIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/pdfgen/PdfGeneratorTest.kt
  service/src/main/kotlin/fi/espoo/evaka/Audit.kt
  service/src/main/kotlin/fi/espoo/evaka/EvakaEnv.kt
  service/src/main/kotlin/fi/espoo/evaka/document/archival/ArchiveChildDocumentService.kt
  service/src/main/kotlin/fi/espoo/evaka/document/archival/SärmäClientConfig.kt
  service/src/main/kotlin/fi/espoo/evaka/document/archival/SärmäClientInterface.kt
  service/src/main/kotlin/fi/espoo/evaka/document/archival/SärmäHttpClient.kt
  service/src/main/kotlin/fi/espoo/evaka/document/archival/SärmäMockClient.kt
  service/src/main/kotlin/fi/espoo/evaka/document/childdocument/ChildDocument.kt
  service/src/main/kotlin/fi/espoo/evaka/document/childdocument/ChildDocumentController.kt
  service/src/main/kotlin/fi/espoo/evaka/document/childdocument/ChildDocumentQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/async/AsyncJob.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/config/EnvConfig.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/security/Action.kt
  service/src/main/resources/application-local.yaml
  service/src/main/resources/db/migration/V498__child_document_archived_at.sql
  service/src/main/resources/migrations.txt
Labels: enhancement

#6399 Kuntalainen voi lähettää useaa lasta koskevan viestin vaikka lapset olisivat saman yksikön eri ryhmissä
  frontend/src/citizen-frontend/messages/MessageEditor.tsx
  frontend/src/e2e-test/specs/7_messaging/messaging.spec.ts
  service/src/main/kotlin/fi/espoo/evaka/messaging/MessageControllerCitizen.kt
Labels: enhancement

#6403 Korjataan import
  frontend/src/employee-frontend/components/child-documents/ChildDocumentEditor.tsx
Labels: no-changelog

#6402 Keycloak-siivousta
  apigw/config/test-cert/keycloak-local.pem
  apigw/src/app.ts
  apigw/src/shared/config.ts
  compose/README.md
  compose/db/entry/create-keycloak.sh
  compose/docker-compose.e2e-tests.yml
  compose/docker-compose.e2e.yml
  compose/docker-compose.yml
  keycloak/docker-compose.yml
  keycloak/dummy-suomifi/.dockerignore
  keycloak/dummy-suomifi/.gitignore
  keycloak/dummy-suomifi/Dockerfile
  keycloak/dummy-suomifi/build.gradle.kts
  keycloak/dummy-suomifi/gradle.properties
  keycloak/dummy-suomifi/gradle/libs.versions.toml
  keycloak/dummy-suomifi/gradle/wrapper/gradle-wrapper.jar
  keycloak/dummy-suomifi/gradle/wrapper/gradle-wrapper.properties
  keycloak/dummy-suomifi/gradlew
  keycloak/dummy-suomifi/gradlew.bat
  keycloak/dummy-suomifi/settings.gradle.kts
  keycloak/dummy-suomifi/src/main/kotlin/dummy_suomifi/App.kt
  keycloak/dummy-suomifi/src/main/kotlin/dummy_suomifi/Config.kt
  keycloak/dummy-suomifi/src/main/kotlin/dummy_suomifi/Saml.kt
  keycloak/dummy-suomifi/src/main/kotlin/dummy_suomifi/User.kt
  keycloak/dummy-suomifi/src/main/kotlin/dummy_suomifi/Utils.kt
Labels: tech

#6383 Ajastettujen luvitusten UX-parannuksia
  frontend/src/employee-frontend/components/employees/DaycareRolesModal.tsx
  frontend/src/employee-frontend/components/employees/EmployeePage.tsx
  frontend/src/employee-frontend/components/unit/queries.ts
  frontend/src/employee-frontend/components/unit/tab-unit-information/UnitAccessControl.tsx
  frontend/src/employee-frontend/components/unit/tab-unit-information/acl-modals/AddAclModal.tsx
  frontend/src/employee-frontend/generated/api-clients/daycare.ts
  frontend/src/lib-common/generated/action.d.ts
  frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
  service/src/main/kotlin/fi/espoo/evaka/Audit.kt
  service/src/main/kotlin/fi/espoo/evaka/daycare/controllers/UnitAclController.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/security/Action.kt
Labels: enhancement

#6406 Käytetään hakemusten generoitua saraketta SQL-kyselyissä
  service/src/main/kotlin/fi/espoo/evaka/application/ApplicationQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/incomestatement/IncomeStatementQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/reports/PreschoolApplicationReport.kt
  service/src/main/resources/db/migration/R__application_view.sql
Labels: tech

#6407 Lisätään metatietoihin asiakirjan id ja (hakemuksen) saapumistapa
  frontend/src/employee-frontend/components/archive-metadata/MetadataSection.tsx
  frontend/src/lib-common/generated/api-types/process.ts
  frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
  service/src/main/kotlin/fi/espoo/evaka/process/ProcessMetadataController.kt
Labels: enhancement

#6409 Korjataan virhe 0-oikaisulaskujen generoinnissa
  service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/service/ReplacementInvoicesIntegrationTest.kt
  service/src/main/kotlin/fi/espoo/evaka/invoicing/service/InvoiceGenerator.kt
Labels: bug

#6412 Kuusikkoraportin suorituskykykorjaus
  service/src/main/kotlin/fi/espoo/evaka/reports/SextetReport.kt
Labels: tech

#6405 Poistetaan Suomi.fi-viestit SOAP client
  service/Dockerfile
  service/build.gradle.kts
  service/certificates/integraatiopalvelu.sh
  service/certificates/pr0.integraatiopalvelu.fi_2024/Intermediate.pem
  service/certificates/pr0.integraatiopalvelu.fi_2024/Root.pem
  service/certificates/pr0.integraatiopalvelu.fi_2024/ServerCertificate.pem
  service/certificates/pr0.integraatiopalvelu.fi_entrust_2023/Intermediate.pem
  service/certificates/pr0.integraatiopalvelu.fi_entrust_2023/Root.pem
  service/certificates/pr0.integraatiopalvelu.fi_entrust_2023/ServerCertificate.pem
  service/certificates/qat.integraatiopalvelu.fi_2024/Intermediate.pem
  service/certificates/qat.integraatiopalvelu.fi_2024/Root.pem
  service/certificates/qat.integraatiopalvelu.fi_2024/ServerCertificate.pem
  service/certificates/qat.integraatiopalvelu.fi_entrust_2023/Intermediate.pem
  service/certificates/qat.integraatiopalvelu.fi_entrust_2023/Root.pem
  service/certificates/qat.integraatiopalvelu.fi_entrust_2023/ServerCertificate.pem
  service/evaka-bom/build.gradle.kts
  service/sficlient/README.md
  service/sficlient/build.gradle.kts
  service/sficlient/src/main/resources/wsdl/Viranomaispalvelut.wsdl
  service/sficlient/src/main/resources/wsdl/Viranomaispalvelut.xsd
  service/src/integrationTest/kotlin/fi/espoo/evaka/sficlient/SoapStackIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/sficlient/rest/SfiMessagesRestClientIntegrationTest.kt
  service/src/main/kotlin/fi/espoo/evaka/EvakaEnv.kt
  service/src/main/kotlin/fi/espoo/evaka/sficlient/SfiMessagesSoapClient.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/config/SfiConfig.kt
Labels: breaking

#6410 Propagoidaan `traceId` servicelle kaikissa `/system`-requesteissa
  apigw/src/enduser/dev-sfi-auth.ts
  apigw/src/enduser/keycloak-citizen-saml.ts
  apigw/src/enduser/routes/auth-weak-login.ts
  apigw/src/enduser/suomi-fi-saml.ts
  apigw/src/internal/ad-saml.ts
  apigw/src/internal/dev-ad-auth.ts
  apigw/src/internal/dev-sfi-auth.ts
  apigw/src/internal/keycloak-employee-saml.ts
  apigw/src/shared/routes/saml.ts
  apigw/src/shared/saml/index.ts
  apigw/src/shared/service-client.ts
Labels: bug

#6398 Uusi tulotieto aiheuttaa aina uuden maksu/arvopäätöksen
  frontend/src/e2e-test/dev-api/fixtures.ts
  frontend/src/lib-common/generated/api-types/invoicing.ts
  service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/data/FeeDecisionQueriesTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/data/VoucherValueDecisionQueriesTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/service/FeeDecisionGeneratorIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/service/VoucherValueDecisionGeneratorIntegrationTest.kt
  service/src/main/kotlin/fi/espoo/evaka/invoicing/FinanceDecisionUtils.kt
  service/src/main/kotlin/fi/espoo/evaka/invoicing/domain/FeeDecisions.kt
  service/src/main/kotlin/fi/espoo/evaka/invoicing/domain/Incomes.kt
  service/src/main/kotlin/fi/espoo/evaka/invoicing/domain/VoucherValueDecisions.kt
Labels: enhancement

#6401 Estetään sopimuspoissaolojen muuttaminen suljetulta ajalta
  service/src/integrationTest/kotlin/fi/espoo/evaka/reservations/ReservationControllerCitizenIntegrationTest.kt
  service/src/main/kotlin/fi/espoo/evaka/absence/AbsenceQueries.kt
Labels: enhancement

#6408 Korjataan päivälapset käyttö- ja täyttöasteet raportilla
  service/src/integrationTest/kotlin/fi/espoo/evaka/occupancy/OccupancyTest.kt
  service/src/main/kotlin/fi/espoo/evaka/occupancy/Occupancy.kt
Labels: bug

#6429 Korjataan bugi jonka takia salasanassa ei voinut olla välilyöntejä alussa tai lopussa
  frontend/src/citizen-frontend/login/WeakLoginFormPage.tsx
  frontend/src/citizen-frontend/personal-details/LoginDetailsSection.tsx
Labels: bug

#6415 Metadataprosessien nimet
  frontend/src/employee-frontend/components/archive-metadata/MetadataSection.tsx
  frontend/src/lib-common/generated/api-types/process.ts
  frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
  service/src/main/kotlin/fi/espoo/evaka/process/ProcessMetadataController.kt
Labels: enhancement

#6431 Ei lasketa arkistoituja viestejä lukemattomien viestien määrään
  service/src/integrationTest/kotlin/fi/espoo/evaka/messaging/MessageQueriesTest.kt
  service/src/main/kotlin/fi/espoo/evaka/messaging/MessageQueries.kt
Labels: enhancement

#6335 Tampereen Seutuselvitysraportti osa 3: vuosittaisten arvojen CSV
  frontend/src/employee-frontend/components/reports/TampereRegionalSurvey.tsx
  frontend/src/employee-frontend/components/reports/queries.ts
  frontend/src/employee-frontend/generated/api-clients/reports.ts
  frontend/src/lib-common/generated/api-types/reports.ts
  frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
  service/src/integrationTest/kotlin/fi/espoo/evaka/reports/TampereRegionalSurveyTest.kt
  service/src/main/kotlin/fi/espoo/evaka/Audit.kt
  service/src/main/kotlin/fi/espoo/evaka/reports/TampereRegionalSurvey.kt
Labels: enhancement

#6434 Kansioituun viestiin voi vastata
  frontend/src/e2e-test/pages/employee/messages/messages-page.ts
  frontend/src/e2e-test/specs/7_messaging/service-worker-messaging.spec.ts
  frontend/src/employee-frontend/components/messages/MessageContext.tsx
  frontend/src/employee-frontend/components/messages/SingleThreadView.tsx
  service/src/main/resources/dev-data/dev-data.sql
Labels: bug

#6435 Piilotetaan tuen päätökset huoltajalta jos lapsen asiakkuus on päättynyt
  frontend/src/e2e-test/specs/0_citizen/citizen-decisions.spec.ts
  frontend/src/e2e-test/specs/0_citizen/foster-parents.spec.ts
  service/src/main/kotlin/fi/espoo/evaka/assistanceneed/decision/AssistanceNeedDecisionQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/assistanceneed/preschooldecision/AssistanceNeedPreschoolDecisionQueries.kt
Labels: enhancement

#6433 Tietokannan skeemapäivityksiä
  service/src/integrationTest/kotlin/fi/espoo/evaka/pis/PersonIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/shared/db/SchemaConventionsTest.kt
  service/src/main/resources/db/migration/V499__drop_unused_tables.sql
  service/src/main/resources/db/migration/V500__create_trigger.sql
  service/src/main/resources/migrations.txt
Labels: tech

#6436 Korjaus laskun muodostukseen sopimuspäiväläisen aloittaessa kesken kuun
  service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/service/InvoiceGeneratorIntegrationTest.kt
  service/src/main/kotlin/fi/espoo/evaka/invoicing/service/DraftInvoiceGenerator.kt
Labels: bug

#6411 Korjattu lainausmerkkien käsittely raportti-CSV:n muodostuksessa
  frontend/src/employee-frontend/components/reports/CsvFormation.spec.ts
  frontend/src/employee-frontend/components/reports/ExceededServiceNeeds.tsx
  frontend/src/employee-frontend/components/reports/Occupancies.tsx
  frontend/src/employee-frontend/components/reports/ReportDownload.tsx
Labels: bug

#6437 Satunnaisessa vuorohoidossa jokainen päivä on toimintapäivä
  service/src/integrationTest/kotlin/fi/espoo/evaka/reservations/AttendanceReservationsControllerIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/shared/domain/OperationalDaysIntegrationTest.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/domain/OperationalDays.kt
Labels: enhancement

#6439 Järjestetään kuntalaisen talouspäätökset ensisijaisesti voimassaoloajan mukaan
  frontend/src/citizen-frontend/decisions/decisions-page/Decisions.tsx
Labels: enhancement

#6442 UI-viilauksia yksikkösivun notifikaatiopalloihin
  frontend/src/employee-frontend/components/unit/TabApplications.tsx
  frontend/src/employee-frontend/components/unit/TabWaitingConfirmation.tsx
  frontend/src/employee-frontend/components/unit/tab-groups/MissingGroupPlacements.tsx
Labels: enhancement

#6443 Piilotetaan toimimaton mahdollisuus siirtää lähetetty viesti kansioon
  frontend/src/employee-frontend/components/messages/ThreadListContainer.tsx
Labels: bug
