Repository espoon-voltti/evaka, pull requests merged in 2025-01, with the labels that each got.

#6202 Lisätään MA003-suodatin Varda-lapsivirheet -raportille
  frontend/src/e2e-test/pages/employee/reports.ts
  frontend/src/employee-frontend/components/reports/VardaChildErrors.tsx
  frontend/src/lib-common/generated/api-types/reports.ts
  frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
  service/src/main/kotlin/fi/espoo/evaka/reports/VardaErrorsReport.kt
Labels: enhancement

#6206 Lisätään esiopetuksen tuen päätökselle vastuuvapauslauseke
  frontend/src/employee-frontend/components/child-information/assistance-need/decision/AssistanceNeedPreschoolDecisionEditPage.tsx
  frontend/src/lib-components/assistance-need-decision/AssistanceNeedPreschoolDecisionReadOnly.tsx
  frontend/src/lib-customizations/defaults/citizen/i18n/fi.tsx
  frontend/src/lib-customizations/defaults/citizen/i18n/sv.tsx
  frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
Labels: enhancement

#6122 Kalenteri: Tieto jos muokattu lapsen tulo/lähtöaikaa henkilökunnan toimesta
  frontend/src/citizen-frontend/calendar/reservation-modal/form.spec.ts
  frontend/src/e2e-test/dev-api/fixtures.ts
  frontend/src/e2e-test/generated/api-types.ts
  frontend/src/e2e-test/specs/5_employee/month-calendar.spec.ts
  frontend/src/e2e-test/specs/5_employee/reservation-calendar.spec.ts
  frontend/src/employee-frontend/components/unit/unit-reservations/ChildDateModal.tsx
  frontend/src/employee-frontend/components/unit/unit-reservations/ChildDayAttendance.tsx
  frontend/src/employee-frontend/components/unit/unit-reservations/ChildDayReservation.tsx
  frontend/src/lib-common/generated/api-types/attendance.ts
  frontend/src/lib-common/generated/api-types/reservations.ts
  frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
  service/src/integrationTest/kotlin/fi/espoo/evaka/TestFixtures.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/absence/AbsenceServiceIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/attendance/AttendanceQueriesTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/attendance/GetAttendancesIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/attendance/MobileUnitControllerIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/reservations/AttendanceReservationsControllerIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/reservations/ReservationControllerCitizenIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/shared/db/SchemaConventionsTest.kt
  service/src/main/kotlin/fi/espoo/evaka/absence/AbsenceQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/attendance/ChildAttendance.kt
  service/src/main/kotlin/fi/espoo/evaka/attendance/ChildAttendanceController.kt
  service/src/main/kotlin/fi/espoo/evaka/attendance/ChildAttendanceQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/reservations/AttendanceReservationController.kt
  service/src/main/kotlin/fi/espoo/evaka/reservations/ReservationQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/reservations/Reservations.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/dev/DataInitializers.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/dev/DevApi.kt
  service/src/main/resources/db/migration/V481__attendance_reservation_modification_metadata.sql
  service/src/main/resources/migrations.txt
  service/src/test/kotlin/fi/espoo/evaka/reports/MealReportTests.kt
Labels: enhancement

#6213 Korjauksia esiopetussijoitusten tuontiin
  service/src/integrationTest/kotlin/fi/espoo/evaka/application/PlacementToolServiceIntegrationTest.kt
  service/src/main/kotlin/fi/espoo/evaka/application/PlacementToolService.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/async/AsyncJob.kt
Labels: enhancement

#6203 Lisätään yrityksen nimi ja Y-tunnus tuloselvityslomakkeelle
  frontend/src/citizen-frontend/income-statements/IncomeStatementForm.tsx
  frontend/src/citizen-frontend/income-statements/IncomeStatementView.tsx
  frontend/src/citizen-frontend/income-statements/types/body.ts
  frontend/src/citizen-frontend/income-statements/types/form.ts
  frontend/src/employee-frontend/components/IncomeStatementPage.tsx
  frontend/src/lib-common/generated/api-types/incomestatement.ts
  frontend/src/lib-customizations/defaults/citizen/i18n/en.tsx
  frontend/src/lib-customizations/defaults/citizen/i18n/fi.tsx
  frontend/src/lib-customizations/defaults/citizen/i18n/sv.tsx
  frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
  service/src/integrationTest/kotlin/fi/espoo/evaka/incomestatement/IncomeStatementControllerCitizenIntegrationTest.kt
  service/src/main/kotlin/fi/espoo/evaka/incomestatement/IncomeStatement.kt
  service/src/main/kotlin/fi/espoo/evaka/incomestatement/IncomeStatementQueries.kt
  service/src/main/resources/db/migration/V482__income_statement_company.sql
  service/src/main/resources/migrations.txt
Labels: enhancement

#6178 Pedagogiset asiakirjat-raportti
  frontend/src/e2e-test/pages/citizen/citizen-messages.ts
  frontend/src/e2e-test/pages/employee/reports.ts
  frontend/src/e2e-test/specs/5_employee/child-documents.spec.ts
  frontend/src/e2e-test/utils/page.ts
  frontend/src/employee-frontend/App.tsx
  frontend/src/employee-frontend/components/Reports.tsx
  frontend/src/employee-frontend/components/reports/ChildDocumentsReport.tsx
  frontend/src/employee-frontend/components/reports/queries.ts
  frontend/src/employee-frontend/generated/api-clients/reports.ts
  frontend/src/lib-common/generated/action.d.ts
  frontend/src/lib-common/generated/api-types/reports.ts
  frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
  service/src/main/kotlin/fi/espoo/evaka/Audit.kt
  service/src/main/kotlin/fi/espoo/evaka/reports/ChildDocumentsReport.kt
  service/src/main/kotlin/fi/espoo/evaka/reports/ReportPermissions.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/security/Action.kt
Labels: enhancement

#6199 Espoo: talousprosessien TOS-numerot konfiguraatioon
  service/src/main/kotlin/fi/espoo/evaka/EspooConfig.kt
Labels: no-changelog

#6215 Uusi viesti -dialogin pakolliset kentät
  frontend/src/citizen-frontend/messages/MessageEditor.tsx
  frontend/src/lib-components/atoms/form/MultiSelect.tsx
Labels: enhancement

#6216 Tulotiedot: poimitaan viimeksi muokattu päivämäärä oikeasta tietueesta
  service/src/main/kotlin/fi/espoo/evaka/invoicing/data/IncomeQueries.kt
Labels: bug

#6219 Päivitys tuentarpeen päätökset raportin käyttöoikeuksiin
  service/src/main/kotlin/fi/espoo/evaka/shared/security/Action.kt
Labels: enhancement

#6220 Ei enää poisteta tulevia sijoituksia kun luodaan kerhosijoitus
  service/src/integrationTest/kotlin/fi/espoo/evaka/placement/PlacementServiceIntegrationTest.kt
  service/src/main/kotlin/fi/espoo/evaka/placement/PlacementPlanService.kt
  service/src/main/kotlin/fi/espoo/evaka/placement/PlacementService.kt
Labels: enhancement

#6194 Johtajan poissaolojaksojen näkyminen viestin lähettäjille
  frontend/src/citizen-frontend/generated/api-clients/messaging.ts
  frontend/src/citizen-frontend/messages/MessageEditor.tsx
  frontend/src/citizen-frontend/messages/MessagesPage.tsx
  frontend/src/citizen-frontend/messages/ThreadView.tsx
  frontend/src/e2e-test/pages/citizen/citizen-messages.ts
  frontend/src/e2e-test/pages/employee/messages/out-of-office-page.ts
  frontend/src/e2e-test/specs/7_messaging/out-of-office.spec.ts
  frontend/src/employee-frontend/App.tsx
  frontend/src/employee-frontend/components/Header.tsx
  frontend/src/employee-frontend/components/messages/SingleThreadView.tsx
  frontend/src/employee-frontend/components/out-of-office/OutOfOfficeEditor.tsx
  frontend/src/employee-frontend/components/out-of-office/OutOfOfficePage.tsx
  frontend/src/employee-frontend/components/out-of-office/queries.ts
  frontend/src/employee-frontend/generated/api-clients/outofoffice.ts
  frontend/src/employee-mobile-frontend/messages/ThreadView.tsx
  frontend/src/lib-common/generated/action.d.ts
  frontend/src/lib-common/generated/api-types/messaging.ts
  frontend/src/lib-common/generated/api-types/outofoffice.ts
  frontend/src/lib-common/generated/api-types/shared.ts
  frontend/src/lib-components/i18n.tsx
  frontend/src/lib-components/messages/MessageReplyEditor.tsx
  frontend/src/lib-components/messages/OutOfOfficeInfo.tsx
  frontend/src/lib-components/utils/TestContextProvider.tsx
  frontend/src/lib-components/utils/useReplyRecipients.ts
  frontend/src/lib-customizations/defaults/components/i18n/en.tsx
  frontend/src/lib-customizations/defaults/components/i18n/fi.tsx
  frontend/src/lib-customizations/defaults/components/i18n/sv.tsx
  frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
  service/src/integrationTest/kotlin/fi/espoo/evaka/messaging/MessageIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/messaging/MessageQueriesTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/outofoffice/OutOfOfficeIntegrationTest.kt
  service/src/main/kotlin/fi/espoo/evaka/Audit.kt
  service/src/main/kotlin/fi/espoo/evaka/messaging/Message.kt
  service/src/main/kotlin/fi/espoo/evaka/messaging/MessageControllerCitizen.kt
  service/src/main/kotlin/fi/espoo/evaka/messaging/MessageQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/messaging/MessageService.kt
  service/src/main/kotlin/fi/espoo/evaka/outofoffice/OutOfOffice.kt
  service/src/main/kotlin/fi/espoo/evaka/outofoffice/OutOfOfficeController.kt
  service/src/main/kotlin/fi/espoo/evaka/pis/SystemController.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/Id.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/security/Action.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/security/EmployeeFeatures.kt
  service/src/main/resources/db/migration/V483__out_of_office.sql
  service/src/main/resources/migrations.txt
Labels: enhancement

#6222 Korjaus poissaolojaksojen oikeuksiin
  service/src/integrationTest/kotlin/fi/espoo/evaka/outofoffice/OutOfOfficeIntegrationTest.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/security/Action.kt
Labels: no-changelog

#6239 `voucherValueSeparation` päälle Espoon tuotantoon
  frontend/src/lib-customizations/espoo/featureFlags.tsx
Labels: no-changelog

#6238 Päivitys suomenkielisiin poissaoloviesteihin
  frontend/src/lib-customizations/defaults/components/i18n/fi.tsx
Labels: enhancement

#6240 Korjaus tuen päätösten näkyvyyteen
  frontend/src/e2e-test/specs/5_employee/assistance-need-decisions-report.spec.ts
  frontend/src/e2e-test/specs/5_employee/assistance-need-preschool-decision.spec.ts
  service/src/main/kotlin/fi/espoo/evaka/shared/security/Action.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/security/actionrule/HasGlobalRole.kt
Labels: bug

#6201 Lisätään hae-nappi talousnäkymän hakuihin
  frontend/src/e2e-test/pages/employee/finance/finance-page.ts
  frontend/src/e2e-test/specs/4_finance/fee-decisions.spec.ts
  frontend/src/e2e-test/specs/4_finance/invoices.spec.ts
  frontend/src/e2e-test/specs/4_finance/payments.spec.ts
  frontend/src/e2e-test/specs/4_finance/value-decisions.spec.ts
  frontend/src/employee-frontend/components/fee-decisions/Actions.tsx
  frontend/src/employee-frontend/components/fee-decisions/FeeDecisionFilters.tsx
  frontend/src/employee-frontend/components/fee-decisions/FeeDecisions.tsx
  frontend/src/employee-frontend/components/fee-decisions/FeeDecisionsPage.tsx
  frontend/src/employee-frontend/components/fee-decisions/fee-decision-queries.ts
  frontend/src/employee-frontend/components/finance-decisions/IgnoreDraftModal.tsx
  frontend/src/employee-frontend/components/income-statements/IncomeStatementFilters.tsx
  frontend/src/employee-frontend/components/income-statements/IncomeStatementsPage.tsx
  frontend/src/employee-frontend/components/invoices/InvoiceFilters.tsx
  frontend/src/employee-frontend/components/invoices/Invoices.tsx
  frontend/src/employee-frontend/components/invoices/InvoicesPage.tsx
  frontend/src/employee-frontend/components/payments/Actions.tsx
  frontend/src/employee-frontend/components/payments/PaymentFilters.tsx
  frontend/src/employee-frontend/components/payments/Payments.tsx
  frontend/src/employee-frontend/components/payments/PaymentsPage.tsx
  frontend/src/employee-frontend/components/payments/payments-state.ts
  frontend/src/employee-frontend/components/payments/queries.ts
  frontend/src/employee-frontend/components/voucher-value-decisions/VoucherValueDecisionActions.tsx
  frontend/src/employee-frontend/components/voucher-value-decisions/VoucherValueDecisionFilters.tsx
  frontend/src/employee-frontend/components/voucher-value-decisions/VoucherValueDecisions.tsx
  frontend/src/employee-frontend/components/voucher-value-decisions/VoucherValueDecisionsPage.tsx
  frontend/src/employee-frontend/components/voucher-value-decisions/voucher-value-decision-queries.ts
  frontend/src/employee-frontend/query.ts
  frontend/src/employee-frontend/state/invoicing-ui.tsx
Labels: enhancement

#6244 Salli johtajan poissaolojaksojen alkaminen menneisyydessä
  frontend/src/employee-frontend/components/out-of-office/OutOfOfficeEditor.tsx
  frontend/src/lib-components/molecules/date-picker/DatePickerLowLevel.tsx
  frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
  service/src/main/kotlin/fi/espoo/evaka/outofoffice/OutOfOfficeController.kt
Labels: enhancement

#6221 Kuntalainen: Viestieditorin responsiivisuusparannus
  frontend/src/citizen-frontend/messages/MessageEditor.tsx
Labels: enhancement

#6246 Päivitetään ryhmittämättömien lasten lista sisältämään sijoitukset 7kk asti
  service/src/main/kotlin/fi/espoo/evaka/daycare/controllers/DaycareController.kt
Labels: enhancement

#6245 Eslint-sääntö: vaaditaan triple equals käyttö
  frontend/eslint.config.mjs
  frontend/src/citizen-frontend/api-client.ts
  frontend/src/citizen-frontend/applications/ChildApplicationsBlock.tsx
  frontend/src/citizen-frontend/applications/read-view/ApplicationReadViewContents.tsx
  frontend/src/citizen-frontend/calendar/AbsenceModal.tsx
  frontend/src/citizen-frontend/calendar/AttendanceInfo.tsx
  frontend/src/citizen-frontend/calendar/MonthlyHoursSummary.tsx
  frontend/src/citizen-frontend/decisions/decisions-page/AssistanceDecision.tsx
  frontend/src/citizen-frontend/income-statements/types/body.ts
  frontend/src/citizen-frontend/map/MapView.tsx
  frontend/src/e2e-test/dev-api/fixtures.ts
  frontend/src/e2e-test/pages/citizen/citizen-header.ts
  frontend/src/employee-frontend/api/client.ts
  frontend/src/employee-frontend/components/UnitPage.tsx
  frontend/src/employee-frontend/components/application-page/ApplicationEditView.tsx
  frontend/src/employee-frontend/components/applications/ApplicationsFilters.tsx
  frontend/src/employee-frontend/components/child-information/PedagogicalDocuments.tsx
  frontend/src/employee-frontend/components/child-information/assistance-need/decision/AssistanceNeedPreschoolDecisionEditPage.tsx
  frontend/src/employee-frontend/components/child-information/assistance/AssistanceActionForm.tsx
  frontend/src/employee-frontend/components/child-information/assistance/AssistanceActionSection.tsx
  frontend/src/employee-frontend/components/child-information/backup-care/BackupCareForm.tsx
  frontend/src/employee-frontend/components/child-information/person-details/AdditionalInformation.tsx
  frontend/src/employee-frontend/components/common/CreatePersonInput.tsx
  frontend/src/employee-frontend/components/common/Filters.tsx
  frontend/src/employee-frontend/components/employee/EmployeePreferredFirstNamePage.tsx
  frontend/src/employee-frontend/components/finance-basics/PlacementTypeItem.tsx
  frontend/src/employee-frontend/components/finance-basics/ServiceNeedItem.tsx
  frontend/src/employee-frontend/components/finance-basics/VoucherValueEditor.tsx
  frontend/src/employee-frontend/components/invoice/InvoiceRowsSection.tsx
  frontend/src/employee-frontend/components/messages/MessageBox.tsx
  frontend/src/employee-frontend/components/messages/MessageEditor.tsx
  frontend/src/employee-frontend/components/messages/ThreadListContainer.tsx
  frontend/src/employee-frontend/components/placement-tool/api.ts
  frontend/src/employee-frontend/components/reports/AttendanceReservation.tsx
  frontend/src/employee-frontend/components/reports/DuplicatePeople.tsx
  frontend/src/employee-frontend/components/reports/Occupancies.tsx
  frontend/src/employee-frontend/components/reports/TitaniaErrors.tsx
  frontend/src/employee-frontend/components/unit/tab-groups/Groups.tsx
  frontend/src/employee-frontend/components/unit/tab-groups/MissingGroupPlacements.tsx
  frontend/src/employee-frontend/components/unit/tab-groups/groups/Group.tsx
  frontend/src/employee-frontend/components/unit/tab-groups/missing-group-placements/GroupPlacementModal.tsx
  frontend/src/employee-frontend/components/unit/tab-groups/notes/ChildDailyNoteForm.tsx
  frontend/src/employee-frontend/components/unit/tab-unit-information/occupancy/OccupancyCard.tsx
  frontend/src/employee-frontend/components/unit/unit-details/UnitEditor.tsx
  frontend/src/employee-frontend/components/unit/unit-reservations/ChildReservationsTable.tsx
  frontend/src/employee-frontend/utils/html-utils.tsx
  frontend/src/employee-mobile-frontend/child-info/AttendanceChildPage.tsx
  frontend/src/employee-mobile-frontend/child-info/ImageEditor.tsx
  frontend/src/employee-mobile-frontend/client.ts
  frontend/src/lib-common/api-types/application/ApplicationFormData.ts
  frontend/src/lib-common/helsinki-date-time.spec.ts
  frontend/src/lib-common/local-date.spec.ts
  frontend/src/lib-common/local-time.spec.ts
  frontend/src/lib-common/local-time.ts
  frontend/src/lib-common/utils/number.ts
  frontend/src/lib-components/atoms/buttons/Button.tsx
Labels: tech

#6249 Katkaistaan myös määräaikainen päällekkäinen tulotieto automaattisesti uutta luotaessa
  frontend/src/e2e-test/specs/5_employee/income.spec.ts
  service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/IncomeIntegrationTest.kt
  service/src/main/kotlin/fi/espoo/evaka/invoicing/controller/IncomeController.kt
  service/src/main/kotlin/fi/espoo/evaka/invoicing/data/IncomeQueries.kt
Labels: enhancement

#6250 Korjataan maksuluonnosten tuplaantuminen
  service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/PaymentsIntegrationTest.kt
  service/src/main/kotlin/fi/espoo/evaka/invoicing/data/PaymentQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/invoicing/domain/Payments.kt
Labels: enhancement

#6251 Kuntalainen: Kaikkien viestin vastaanottajien pitää olla sallittuja kaikille valituille lapsille
  frontend/src/citizen-frontend/messages/MessageEditor.tsx
  frontend/src/e2e-test/pages/citizen/citizen-messages.ts
  frontend/src/e2e-test/specs/7_messaging/messaging.spec.ts
  frontend/src/e2e-test/utils/page.ts
Labels: bug

#6247 Oikaisulaskujen liitteet
  frontend/src/citizen-frontend/children/sections/pedagogical-documents/PedagogicalDocumentsSection.tsx
  frontend/src/citizen-frontend/income-statements/ChildIncomeStatementAttachments.tsx
  frontend/src/citizen-frontend/income-statements/ChildIncomeStatementForm.tsx
  frontend/src/citizen-frontend/income-statements/ChildIncomeStatementView.tsx
  frontend/src/citizen-frontend/income-statements/IncomeStatementAttachments.tsx
  frontend/src/citizen-frontend/income-statements/IncomeStatementForm.tsx
  frontend/src/citizen-frontend/income-statements/IncomeStatementView.tsx
  frontend/src/citizen-frontend/income-statements/types/form.ts
  frontend/src/citizen-frontend/messages/MessageEditor.tsx
  frontend/src/e2e-test/pages/employee/finance/invoice-details-page.ts
  frontend/src/e2e-test/specs/4_finance/invoices.spec.ts
  frontend/src/e2e-test/utils/page.ts
  frontend/src/employee-frontend/api/attachments.ts
  frontend/src/employee-frontend/components/IncomeStatementPage.tsx
  frontend/src/employee-frontend/components/child-information/PedagogicalDocumentRow.tsx
  frontend/src/employee-frontend/components/child-information/fee-alteration/FeeAlterationEditor.tsx
  frontend/src/employee-frontend/components/child-information/fee-alteration/FeeAlterationList.tsx
  frontend/src/employee-frontend/components/invoice/ReplacementDraftInfo.tsx
  frontend/src/employee-frontend/components/messages/MessageEditor.tsx
  frontend/src/employee-frontend/components/person-profile/income/IncomeItemBody.tsx
  frontend/src/employee-frontend/components/person-profile/income/IncomeItemEditor.tsx
  frontend/src/lib-common/api-types/attachment.ts
  frontend/src/lib-common/generated/action.d.ts
  frontend/src/lib-common/generated/api-types/attachment.ts
  frontend/src/lib-common/generated/api-types/invoicing.ts
  frontend/src/lib-common/generated/api-types/messaging.ts
  frontend/src/lib-common/generated/api-types/pedagogicaldocument.ts
  frontend/src/lib-components/molecules/FileDownloadButton.tsx
  frontend/src/lib-components/molecules/FileUpload.tsx
  frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
  service/src/integrationTest/kotlin/fi/espoo/evaka/attachments/AttachmentQueriesTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/attachments/AttachmentServiceTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/FeeAlterationIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/InvoiceIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/service/InvoiceGeneratorIntegrationTest.kt
  service/src/main/kotlin/fi/espoo/evaka/Audit.kt
  service/src/main/kotlin/fi/espoo/evaka/attachment/Attachment.kt
  service/src/main/kotlin/fi/espoo/evaka/attachment/AttachmentQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/attachment/AttachmentsController.kt
  service/src/main/kotlin/fi/espoo/evaka/invoicing/data/InvoiceQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/invoicing/domain/FeeAlterations.kt
  service/src/main/kotlin/fi/espoo/evaka/invoicing/domain/Incomes.kt
  service/src/main/kotlin/fi/espoo/evaka/invoicing/domain/Invoices.kt
  service/src/main/kotlin/fi/espoo/evaka/messaging/DraftContent.kt
  service/src/main/kotlin/fi/espoo/evaka/messaging/Message.kt
  service/src/main/kotlin/fi/espoo/evaka/messaging/MessageQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/pedagogicaldocument/PedagogicalDocumentController.kt
  service/src/main/kotlin/fi/espoo/evaka/pedagogicaldocument/PedagogicalDocumentQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/security/Action.kt
  service/src/main/resources/db/migration/V484__invoice_attachment.sql
  service/src/main/resources/migrations.txt
  service/src/test/kotlin/fi/espoo/evaka/invoicing/integration/EspooInvoiceIntegrationClientTest.kt
Labels: enhancement

#6179 Tampereen Seutuselvitysraportti osa 1: kuukausittaisten arvojen CSV
  frontend/src/employee-frontend/App.tsx
  frontend/src/employee-frontend/components/Reports.tsx
  frontend/src/employee-frontend/components/reports/TampereRegionalSurvey.tsx
  frontend/src/employee-frontend/components/reports/queries.ts
  frontend/src/employee-frontend/generated/api-clients/reports.ts
  frontend/src/lib-common/generated/action.d.ts
  frontend/src/lib-common/generated/api-types/reports.ts
  frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
  service/src/integrationTest/kotlin/fi/espoo/evaka/reports/TampereRegionalSurveyTest.kt
  service/src/main/kotlin/fi/espoo/evaka/Audit.kt
  service/src/main/kotlin/fi/espoo/evaka/espoo/EspooActionRuleMapping.kt
  service/src/main/kotlin/fi/espoo/evaka/reports/ReportPermissions.kt
  service/src/main/kotlin/fi/espoo/evaka/reports/TampereRegionalSurvey.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/security/Action.kt
Labels: enhancement

#6253 Esiopetuksen johtajan tiedot
  frontend/src/employee-frontend/components/unit/unit-details/UnitEditor.tsx
  frontend/src/lib-common/generated/api-types/daycare.ts
  frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
  service/src/integrationTest/kotlin/fi/espoo/evaka/daycare/DaycareEditIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/daycare/controllers/DaycareControllerIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/pdfgen/PdfGeneratorTest.kt
  service/src/main/kotlin/fi/espoo/evaka/daycare/CareArea.kt
  service/src/main/kotlin/fi/espoo/evaka/daycare/DaycareQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/daycare/controllers/DaycareController.kt
  service/src/main/kotlin/fi/espoo/evaka/daycare/service/DaycareService.kt
  service/src/main/kotlin/fi/espoo/evaka/decision/DecisionService.kt
  service/src/main/resources/db/migration/V485__preschool_manager.sql
  service/src/main/resources/migrations.txt
Labels: enhancement

#6217 Hakemushaun hae-nappi
  frontend/src/e2e-test/pages/admin/application-details-page.ts
  frontend/src/e2e-test/pages/admin/application-workbench-page.ts
  frontend/src/e2e-test/pages/employee/applications.ts
  frontend/src/e2e-test/pages/employee/applications/application-list-view.ts
  frontend/src/e2e-test/pages/employee/applications/application-read-view.ts
  frontend/src/e2e-test/specs/5_employee/application-attachments.spec.ts
  frontend/src/e2e-test/specs/5_employee/application-details.spec.ts
  frontend/src/e2e-test/specs/5_employee/application-search.spec.ts
  frontend/src/e2e-test/specs/5_employee/application-transitions.spec.ts
  frontend/src/e2e-test/specs/5_employee/applications.spec.ts
  frontend/src/e2e-test/specs/5_employee/feature-flag-decision-draft-multiple-units.spec.ts
  frontend/src/e2e-test/specs/7_messaging/service-worker-messaging.spec.ts
  frontend/src/employee-frontend/components/ApplicationPage.tsx
  frontend/src/employee-frontend/components/application-page/ApplicationNoteBox.tsx
  frontend/src/employee-frontend/components/application-page/ApplicationNotes.tsx
  frontend/src/employee-frontend/components/application-page/queries.ts
  frontend/src/employee-frontend/components/applications/ActionBar.tsx
  frontend/src/employee-frontend/components/applications/ActionCheckbox.tsx
  frontend/src/employee-frontend/components/applications/ApplicationActions.tsx
  frontend/src/employee-frontend/components/applications/ApplicationsFilters.tsx
  frontend/src/employee-frontend/components/applications/ApplicationsList.tsx
  frontend/src/employee-frontend/components/applications/ApplicationsPage.tsx
  frontend/src/employee-frontend/components/applications/PrimaryAction.tsx
  frontend/src/employee-frontend/components/applications/queries.ts
  frontend/src/employee-frontend/components/common/EllipsisMenu.tsx
  frontend/src/employee-frontend/components/common/Filters.tsx
  frontend/src/employee-frontend/components/common/StickyActionBar.tsx
  frontend/src/employee-frontend/state/application-ui.tsx
Labels: enhancement

#6255 Korjaus talouden hakufiltterien säilymiseen
  frontend/src/employee-frontend/components/fee-decisions/FeeDecisionFilters.tsx
  frontend/src/employee-frontend/components/income-statements/IncomeStatementFilters.tsx
  frontend/src/employee-frontend/components/invoices/InvoiceFilters.tsx
  frontend/src/employee-frontend/components/invoices/InvoicesPage.tsx
  frontend/src/employee-frontend/components/payments/PaymentFilters.tsx
  frontend/src/employee-frontend/components/voucher-value-decisions/VoucherValueDecisionFilters.tsx
  frontend/src/employee-frontend/state/invoicing-ui.tsx
Labels: bug

#6254 Korjaus hakemuksien salassapidettävyyden migraatioon
  frontend/src/e2e-test/specs/5_employee/application-transitions.spec.ts
  frontend/src/e2e-test/specs/5_employee/placement-sketching-report.spec.ts
  frontend/src/e2e-test/specs/5_employee/unit-application-process.spec.ts
  service/src/integrationTest/kotlin/fi/espoo/evaka/TestFixtures.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/application/DuplicateApplicationIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/application/PendingDecisionEmailServiceIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/daycare/controllers/DaycareControllerIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/decision/DecisionResolutionIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/occupancy/OccupancyTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/reports/PreschoolApplicationReportTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/shared/job/ScheduledJobsTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/shared/security/ApplicationAccessControlTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/varda/new/VardaUpdaterIntegrationTest.kt
  service/src/main/kotlin/fi/espoo/evaka/application/ApplicationQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/dev/DataInitializers.kt
  service/src/main/resources/db/migration/V486__fix_application_confidentiality.sql
  service/src/main/resources/migrations.txt
Labels: bug

#6256 Talous- ja hakemushaut voi käynnistää painamalla entteriä
  frontend/src/employee-frontend/components/common/Filters.tsx
Labels: enhancement

#6266 Korjaus pitkien linkkien/sanojen ruudun yli menemiseen kuntalaisen mobiilin viesteissä
  frontend/src/citizen-frontend/messages/ThreadView.tsx
Labels: bug

#6265 Nimetään Espoon BI-raportin sarakkeet takaisin alkuperäisiksi
  service/src/main/kotlin/fi/espoo/evaka/espoo/bi/EspooBi.kt
  service/src/main/kotlin/fi/espoo/evaka/espoo/bi/EspooBiModels.kt
Labels: bug

#6269 Laitetaan sentry webpack pluginiin tarkempi lokitus päälle
  frontend/webpack.config.js
Labels: no-changelog

#6270 suodatetaan kansalaisilta piilotetut palveluntarpeet muutoshakemukselta
  frontend/src/e2e-test/dev-api/fixtures.ts
  frontend/src/lib-common/generated/api-types/serviceneed.ts
  service/src/integrationTest/kotlin/fi/espoo/evaka/ServiceNeedTestFixtures.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/application/PlacementToolServiceIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/espoo/bi/EspooBiTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/reports/TampereRegionalSurveyTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/serviceneed/application/ServiceApplicationIntegrationTest.kt
  service/src/main/kotlin/fi/espoo/evaka/serviceneed/ServiceNeed.kt
  service/src/main/kotlin/fi/espoo/evaka/serviceneed/ServiceNeedQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/serviceneed/application/ServiceApplicationControllerCitizen.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/dev/DataInitializers.kt
  service/src/test/kotlin/fi/espoo/evaka/invoicing/service/generator/FeeDecisionGeneratorV2Test.kt
  service/src/test/kotlin/fi/espoo/evaka/invoicing/service/generator/VoucherValueDecisionGeneratorV2Test.kt
Labels: enhancement

#6248 Henkilökunta: Korjaus poissaolokoosteen tooltippiin
  frontend/src/employee-frontend/components/invoice/AbsencesModal.tsx
Labels: bug

#6274 Päätös erityisestä tuesta: Poistettu $-merkki Muu laillinen edustaja- tiedon edestä.
  frontend/src/lib-components/assistance-need-decision/AssistanceNeedPreschoolDecisionReadOnly.tsx
Labels: bug

#6275 Näytetään esiopetuksen johtajan tiedot vain esiopetuksen ja valmistavan opetuksen päätöksillä
  service/src/main/kotlin/fi/espoo/evaka/decision/DecisionService.kt
Labels: bug

#6200 Lisätään työaikakirjaukseen luonti/muokkaustiedot
  frontend/src/e2e-test/dev-api/fixtures.ts
  frontend/src/e2e-test/generated/api-types.ts
  frontend/src/e2e-test/pages/employee/units/unit-calendar-page-base.ts
  frontend/src/e2e-test/specs/5_employee/realtime-attendances.spec.ts
  frontend/src/e2e-test/specs/6_mobile/realtime-staff-attendances.spec.ts
  frontend/src/employee-frontend/components/unit/unit-reservations/StaffAttendanceTable.tsx
  frontend/src/lib-common/generated/api-types/attendance.ts
  frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
  service/src/integrationTest/kotlin/fi/espoo/evaka/attendance/MobileRealtimeStaffAttendanceControllerIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/attendance/MobileUnitControllerIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/attendance/RealtimeStaffAttendanceQueriesTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/occupancy/OccupancyControllerIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/occupancy/OccupancyTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/occupancy/RealtimeOccupancyTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/titania/TitaniaQueriesTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/titania/TitaniaServiceTest.kt
  service/src/main/kotlin/fi/espoo/evaka/attendance/MobileRealtimeStaffAttendanceController.kt
  service/src/main/kotlin/fi/espoo/evaka/attendance/RealtimeStaffAttendanceController.kt
  service/src/main/kotlin/fi/espoo/evaka/attendance/StaffAttendance.kt
  service/src/main/kotlin/fi/espoo/evaka/attendance/StaffAttendanceQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/dev/DataInitializers.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/dev/DevApi.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/job/ScheduledJobs.kt
  service/src/main/kotlin/fi/espoo/evaka/titania/TitaniaQueries.kt
  service/src/main/resources/db/migration/V487__staff_attendance_realtime_modified.sql
  service/src/main/resources/migrations.txt
  service/src/test/kotlin/fi/espoo/evaka/titania/TitaniaHelpersTest.kt
Labels: enhancement

#6243 Lisätään lasten laskennallinen määrä yksikön viikokalenteriin
  frontend/src/e2e-test/specs/5_employee/reservation-calendar.spec.ts
  frontend/src/employee-frontend/components/unit/unit-reservations/ChildReservationsTable.tsx
  frontend/src/lib-common/generated/api-types/reservations.ts
  service/src/integrationTest/kotlin/fi/espoo/evaka/absence/AbsenceServiceIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/reservations/AttendanceReservationsControllerIntegrationTest.kt
  service/src/main/kotlin/fi/espoo/evaka/absence/AbsenceService.kt
  service/src/main/kotlin/fi/espoo/evaka/reservations/AttendanceReservationController.kt
  service/src/main/kotlin/fi/espoo/evaka/serviceneed/ServiceNeedQueries.kt
  service/src/test/kotlin/fi/espoo/evaka/reports/MealReportTests.kt
Labels: enhancement

#6267 Korjataan hakutoiveiden validointi
  frontend/src/citizen-frontend/applications/editor/unit-preference/UnitPreferenceSection.tsx
  frontend/src/citizen-frontend/applications/editor/unit-preference/UnitsSubSection.tsx
  frontend/src/lib-customizations/defaults/citizen/i18n/en.tsx
  frontend/src/lib-customizations/defaults/citizen/i18n/fi.tsx
  frontend/src/lib-customizations/defaults/citizen/i18n/sv.tsx
Labels: bug

#6281 Poistetaan hakemukselta liittyvän aloituspäivä jos poistetaan liittyvä
  frontend/src/employee-frontend/components/application-page/ApplicationReadView.tsx
  frontend/src/lib-common/api-types/application/ApplicationFormData.ts
Labels: bug

#6282 Yksinkertaistetaan `FileUpload`-komponentin käyttöä
  frontend/src/citizen-frontend/applications/editor/service-need/PreferredStartSubSection.tsx
  frontend/src/citizen-frontend/applications/editor/service-need/ServiceTimeSubSectionDaycare.tsx
  frontend/src/citizen-frontend/applications/editor/service-need/ServiceTimeSubSectionPreschool.tsx
  frontend/src/citizen-frontend/attachments.ts
  frontend/src/citizen-frontend/income-statements/ChildIncomeStatementAttachments.tsx
  frontend/src/citizen-frontend/income-statements/IncomeStatementAttachments.tsx
  frontend/src/citizen-frontend/messages/MessageEditor.tsx
  frontend/src/employee-frontend/api/attachments.ts
  frontend/src/employee-frontend/components/IncomeStatementPage.tsx
  frontend/src/employee-frontend/components/application-page/ApplicationEditView.tsx
  frontend/src/employee-frontend/components/child-information/PedagogicalDocumentRow.tsx
  frontend/src/employee-frontend/components/child-information/fee-alteration/FeeAlterationEditor.tsx
  frontend/src/employee-frontend/components/invoice/ReplacementDraftInfo.tsx
  frontend/src/employee-frontend/components/messages/MessageEditor.tsx
  frontend/src/employee-frontend/components/messages/MessagesPage.tsx
  frontend/src/employee-frontend/components/person-profile/income/IncomeItemEditor.tsx
  frontend/src/employee-frontend/components/placement-tool/PlacementToolPage.tsx
  frontend/src/employee-frontend/components/placement-tool/api.ts
  frontend/src/lib-components/molecules/FileUpload.tsx
Labels: tech

#6273 Ehdottavan esiopetuksen hakemuksen sovittu yhdessä tiedon poisto
  frontend/src/citizen-frontend/applications/editor/contact-info/SecondGuardianSubSection.tsx
  frontend/src/employee-frontend/components/application-page/ApplicationEditView.tsx
  frontend/src/lib-common/api-types/application/ApplicationFormData.ts
  frontend/src/lib-common/generated/api-types/application.ts
  frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
  service/src/main/kotlin/fi/espoo/evaka/application/ApplicationForm.kt
  service/src/main/kotlin/fi/espoo/evaka/application/PlacementToolService.kt
Labels: enhancement

#6276 Päivitetään ikärajoja ja parannetaan validointeja
  frontend/src/e2e-test/specs/5_employee/paper-application.spec.ts
  frontend/src/employee-frontend/components/ChildInformation.tsx
  frontend/src/employee-frontend/components/PersonProfile.tsx
  frontend/src/employee-frontend/components/Search.tsx
  frontend/src/employee-frontend/components/child-information/CreateApplicationModal.tsx
  frontend/src/employee-frontend/components/common/PersonSearch.tsx
  frontend/src/employee-frontend/components/person-profile/FosterChildren.tsx
  frontend/src/employee-frontend/components/person-profile/person-fridge-child/FridgeChildModal.tsx
  frontend/src/employee-frontend/components/person-profile/person-fridge-partner/FridgePartnerModal.tsx
  frontend/src/employee-frontend/components/person-search/CreatePersonModal.tsx
  frontend/src/employee-frontend/components/reports/DuplicatePeople.tsx
  frontend/src/employee-frontend/constants.ts
  frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
  service/src/main/resources/db/migration/V488__no_head_of_self.sql
  service/src/main/resources/migrations.txt
Labels: enhancement

#6278 Piilotetaan käyttäjävalikosta mobiiliin/viestintään liittyvät toiminnot jos ne eivät ole käytössä yksikössä
  service/src/main/kotlin/fi/espoo/evaka/shared/security/Action.kt
Labels: bug

#6242 Kuntalaisen kevytkirjautumistunnuksien hallinta (ei vielä käytössä)
  apigw/src/app.ts
  frontend/src/citizen-frontend/generated/api-clients/pis.ts
  frontend/src/citizen-frontend/personal-details/LoginDetailsSection.tsx
  frontend/src/citizen-frontend/personal-details/PersonalDetails.tsx
  frontend/src/citizen-frontend/personal-details/PersonalDetailsSection.tsx
  frontend/src/citizen-frontend/personal-details/components.tsx
  frontend/src/citizen-frontend/personal-details/queries.ts
  frontend/src/e2e-test/dev-api/fixtures.ts
  frontend/src/e2e-test/generated/api-clients.ts
  frontend/src/e2e-test/generated/api-types.ts
  frontend/src/e2e-test/pages/citizen/citizen-personal-details.ts
  frontend/src/e2e-test/specs/0_citizen/citizen-email-verification.spec.ts
  frontend/src/e2e-test/specs/0_citizen/citizen-weak-credentials.spec.ts
  frontend/src/e2e-test/utils/email.ts
  frontend/src/lib-common/generated/api-types/pis.ts
  frontend/src/lib-common/generated/api-types/shared.ts
  frontend/src/lib-customizations/defaults/citizen/i18n/en.tsx
  frontend/src/lib-customizations/defaults/citizen/i18n/fi.tsx
  frontend/src/lib-customizations/defaults/citizen/i18n/sv.tsx
  service/src/integrationTest/kotlin/fi/espoo/evaka/pis/PersonIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/pis/controller/EmailVerificationIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/pis/controller/WeakCredentialsIntegrationTest.kt
  service/src/integrationTest/resources/application-integration-test.yaml
  service/src/main/kotlin/fi/espoo/evaka/Audit.kt
  service/src/main/kotlin/fi/espoo/evaka/emailclient/EmailClient.kt
  service/src/main/kotlin/fi/espoo/evaka/emailclient/EvakaEmailMessageProvider.kt
  service/src/main/kotlin/fi/espoo/evaka/emailclient/IEmailMessageProvider.kt
  service/src/main/kotlin/fi/espoo/evaka/pis/EmailVerification.kt
  service/src/main/kotlin/fi/espoo/evaka/pis/EmailVerificationJobs.kt
  service/src/main/kotlin/fi/espoo/evaka/pis/EmailVerificationQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/pis/PersonQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/pis/SystemController.kt
  service/src/main/kotlin/fi/espoo/evaka/pis/controllers/PersonalDataControllerCitizen.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/Id.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/async/AsyncJob.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/dev/DataInitializers.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/dev/DevApi.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/security/Action.kt
  service/src/main/kotlin/fi/espoo/evaka/user/CitizenUserQueries.kt
  service/src/main/resources/db/migration/V489__person_email_verification.sql
  service/src/main/resources/migrations.txt
Labels: enhancement

#6284 Palveluohjauksen mustiinpanot yksiköille
  frontend/src/e2e-test/pages/employee/units/unit.ts
  frontend/src/e2e-test/specs/5_employee/unit-service-worker-note.spec.ts
  frontend/src/employee-frontend/components/UnitPage.tsx
  frontend/src/employee-frontend/components/unit/UnitServiceWorkerNote.tsx
  frontend/src/employee-frontend/components/unit/queries.ts
  frontend/src/employee-frontend/generated/api-clients/daycare.ts
  frontend/src/lib-common/generated/action.d.ts
  frontend/src/lib-common/generated/api-types/daycare.ts
  frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
  service/src/main/kotlin/fi/espoo/evaka/Audit.kt
  service/src/main/kotlin/fi/espoo/evaka/daycare/controllers/DaycareController.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/security/Action.kt
  service/src/main/resources/db/migration/V490__daycare_service_worker_note.sql
  service/src/main/resources/migrations.txt
Labels: enhancement

#6288 Lisätään puuttuva mobiilisessioiden refresh-endpoint
  apigw/src/app.ts
Labels: tech

#6291 Korjaus foster-parents e2e testiin
  frontend/src/e2e-test/specs/0_citizen/foster-parents.spec.ts
Labels: no-changelog

#6280 Tampereen Seutuselvitysraportti osa 2: ikäjaotteluarvojen CSV
  frontend/src/employee-frontend/components/reports/TampereRegionalSurvey.tsx
  frontend/src/employee-frontend/components/reports/queries.ts
  frontend/src/employee-frontend/generated/api-clients/reports.ts
  frontend/src/lib-common/generated/api-types/reports.ts
  frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
  service/src/integrationTest/kotlin/fi/espoo/evaka/reports/TampereRegionalSurveyTest.kt
  service/src/main/kotlin/fi/espoo/evaka/Audit.kt
  service/src/main/kotlin/fi/espoo/evaka/reports/TampereRegionalSurvey.kt
Labels: enhancement

#6286 Viimeistellään kuntalaisen kevytkirjautussivu käyttöönottoa varten
  apigw/src/app.ts
  apigw/src/enduser/routes/auth-weak-login.ts
  apigw/src/shared/config.ts
  frontend/src/citizen-frontend/App.tsx
  frontend/src/citizen-frontend/login/LoginPage.tsx
  frontend/src/citizen-frontend/login/WeakLoginFormPage.tsx
  frontend/src/citizen-frontend/navigation/const.ts
  frontend/src/e2e-test/pages/citizen/citizen-keycloak.ts
  frontend/src/e2e-test/pages/citizen/citizen-personal-details.ts
  frontend/src/e2e-test/specs/0_citizen/citizen-auth.spec.ts
  frontend/src/e2e-test/specs/0_citizen/citizen-child-page.spec.ts
  frontend/src/e2e-test/specs/0_citizen/citizen-keycloak.spec.ts
  frontend/src/e2e-test/specs/0_citizen/citizen-personal-details.spec.ts
  frontend/src/e2e-test/specs/7_messaging/messaging-by-staff.spec.ts
  frontend/src/e2e-test/specs/7_messaging/messaging.spec.ts
  frontend/src/e2e-test/utils/keycloak.ts
  frontend/src/e2e-test/utils/user.ts
  frontend/src/lib-customizations/defaults/citizen/i18n/en.tsx
  frontend/src/lib-customizations/defaults/citizen/i18n/fi.tsx
  frontend/src/lib-customizations/defaults/citizen/i18n/sv.tsx
Labels: enhancement

#6285 Uuden palvelutuottajatyöntekijän luonti hetulla
  frontend/src/e2e-test/pages/employee/employees.ts
  frontend/src/e2e-test/specs/5_employee/employees.spec.ts
  frontend/src/employee-frontend/components/employees/EmployeesPage.tsx
  frontend/src/employee-frontend/components/employees/queries.ts
  frontend/src/employee-frontend/components/login-page/Login.tsx
  frontend/src/employee-frontend/generated/api-clients/pis.ts
  frontend/src/employee-frontend/utils/roles.tsx
  frontend/src/lib-common/generated/api-types/pis.ts
  frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
  service/src/integrationTest/kotlin/fi/espoo/evaka/pis/controller/EmployeeControllerIntegrationTest.kt
  service/src/main/kotlin/fi/espoo/evaka/pis/EmployeeQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/pis/SystemController.kt
  service/src/main/kotlin/fi/espoo/evaka/pis/controllers/EmployeeController.kt
Labels: enhancement

#6303 Lisätään monipuolisempi seuraavan laskunumeron valinta
  service/src/integrationTest/kotlin/fi/espoo/evaka/shared/config/SharedIntegrationTestConfig.kt
  service/src/main/kotlin/fi/espoo/evaka/EspooConfig.kt
  service/src/main/kotlin/fi/espoo/evaka/invoicing/service/InvoiceService.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/FeatureConfig.kt
Labels: breaking

#6307 Ei näytetä suljettuja yksiköitä yksiköt raportilta
  service/src/main/kotlin/fi/espoo/evaka/reports/UnitsReport.kt
Labels: enhancement

#6308 Näytetään pedagogiset asiakirjat raportilla vain yksiköt joissa toiminto on käytössä
  frontend/src/employee-frontend/components/reports/ChildDocumentsReport.tsx
  frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
Labels: enhancement

#6310 Päivitys tuloselvityksen tekstiin
  frontend/src/citizen-frontend/income-statements/IncomeStatementForm.tsx
  frontend/src/lib-customizations/defaults/citizen/i18n/en.tsx
  frontend/src/lib-customizations/defaults/citizen/i18n/fi.tsx
  frontend/src/lib-customizations/defaults/citizen/i18n/sv.tsx
Labels: enhancement

#6305 Korjataan kuntalaisen tuloselvitysten näkyminen mobiililla
  frontend/src/citizen-frontend/income-statements/ChildrenIncomeStatements.tsx
  frontend/src/citizen-frontend/income-statements/IncomeStatements.tsx
  frontend/src/e2e-test/pages/citizen/citizen-child-income.ts
  frontend/src/e2e-test/pages/citizen/citizen-children.ts
  frontend/src/e2e-test/pages/citizen/citizen-header.ts
  frontend/src/e2e-test/pages/citizen/citizen-income.ts
  frontend/src/e2e-test/specs/0_citizen/citizen-calendar.spec.ts
  frontend/src/e2e-test/specs/0_citizen/citizen-child-income-statement.spec.ts
  frontend/src/e2e-test/specs/0_citizen/citizen-child-page.spec.ts
  frontend/src/e2e-test/specs/0_citizen/citizen-discussion-surveys.spec.ts
  frontend/src/e2e-test/specs/0_citizen/citizen-income-statement.spec.ts
  frontend/src/e2e-test/specs/0_citizen/citizen-income.spec.ts
  frontend/src/e2e-test/specs/0_citizen/citizen-reservations.spec.ts
  frontend/src/e2e-test/specs/0_citizen/feature-flag-citizen-reservations-intermittent-shif-care.spec.ts
  frontend/src/e2e-test/utils/page.ts
  frontend/src/lib-customizations/defaults/citizen/i18n/en.tsx
  frontend/src/lib-customizations/defaults/citizen/i18n/fi.tsx
  frontend/src/lib-customizations/defaults/citizen/i18n/sv.tsx
Labels: bug

#6304 Muutetaan laskujen täsmäytysraportin hakuehto
  frontend/src/employee-frontend/components/reports/Invoices.tsx
  frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
  service/src/integrationTest/kotlin/fi/espoo/evaka/reports/InvoicingReportTest.kt
  service/src/main/kotlin/fi/espoo/evaka/invoicing/data/InvoiceQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/reports/InvoiceReport.kt
Labels: enhancement

#6312 Poistetaan turha ympäristömuuttuja
  service/src/integrationTest/resources/application-integration-test.yaml
  service/src/main/kotlin/fi/espoo/evaka/EvakaEnv.kt
  service/src/main/kotlin/fi/espoo/evaka/pis/SystemController.kt
  service/src/main/kotlin/fi/espoo/evaka/pis/controllers/PersonalDataControllerCitizen.kt
  service/src/main/resources/application-local.yaml
Labels: tech

#6311 Lisätään ehdottavan esiopetushakemuksen luontiin tarkistus olemassa olevista hakemuksista
  frontend/src/employee-frontend/components/placement-tool/PlacementToolPage.tsx
  frontend/src/employee-frontend/components/placement-tool/api.ts
  frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
  service/src/integrationTest/kotlin/fi/espoo/evaka/application/PlacementToolServiceIntegrationTest.kt
  service/src/main/kotlin/fi/espoo/evaka/application/PlacementToolController.kt
  service/src/main/kotlin/fi/espoo/evaka/application/PlacementToolService.kt
Labels: enhancement

#6315 Korjataan keskustelukyselyiden sähköpostimuistus jos lapsi on varahoidossa
  service/src/integrationTest/kotlin/fi/espoo/evaka/calendarevent/CalendarEventServiceIntegrationTest.kt
  service/src/main/kotlin/fi/espoo/evaka/calendarevent/CalendarEventQueries.kt
Labels: bug
