Repository espoon-voltti/evaka, pull requests merged in 2025-06, with the labels that each got.

#7021 Arkistointi metadata: Asian päättymispäivä logiikan parannus
  service/src/main/kotlin/fi/espoo/evaka/document/archival/DocumentMetadataUtils.kt
  service/src/test/kotlin/fi/espoo/evaka/document/archival/DocumentMetadataUtilsTest.kt
Labels: enhancement

#7066 Trimmaa Aromin vastuuyksikkökoodi ennen tallennusta
  frontend/src/employee-frontend/components/unit/tab-groups/groups/GroupModal.tsx
  frontend/src/employee-frontend/components/unit/tab-groups/groups/group/GroupUpdateModal.tsx
Labels: enhancement

#7112 Lisätään yksikön johtajalle oikeus listata poissaolokyselyt
  service/src/main/kotlin/fi/espoo/evaka/shared/security/Action.kt
Labels: bug

#7111 Lisää ohjeteksti lasten asiakirjan luonnospalautuksen vahvistusikkunaan
  frontend/src/employee-frontend/components/child-documents/ChildDocumentReadView.tsx
  frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
Labels: enhancement

#7113 Tekninen: korjataan Dockerfile-tiedostojen ENV lauseiden muodot
  apigw/Dockerfile
  service/Dockerfile
Labels: no-changelog

#7119 Korjataan Titania-integraatioon toteuman pyöristys jos leimaus on lähellä kahta suunnitelmaa
  service/src/integrationTest/kotlin/fi/espoo/evaka/titania/TitaniaServiceTest.kt
  service/src/main/kotlin/fi/espoo/evaka/titania/TitaniaService.kt
Labels: bug

#7120 Lisätään yksikön johtajalle ja ryhmän henkilökunnalle oikeus palauttaa lähetetty kuntalaisen lomake luonnokseksi
  frontend/src/e2e-test/pages/employee/documents/child-document.ts
  frontend/src/e2e-test/specs/5_employee/child-documents.spec.ts
  frontend/src/employee-frontend/components/child-documents/ChildDocumentReadView.tsx
  service/src/main/kotlin/fi/espoo/evaka/shared/security/Action.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/security/actionrule/HasGroupRole.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/security/actionrule/HasUnitRole.kt
Labels: enhancement

#7145 Parannetaan sijoituksen päivityksen logitusta
  service/src/main/kotlin/fi/espoo/evaka/placement/PlacementController.kt
Labels: enhancement

#7118 Korjataan esiopetuksen poissaolohakemuksen käsittelyn käyttöoikeudet
  frontend/src/employee-frontend/components/child-information/AbsenceApplicationsSection.tsx
  frontend/src/lib-common/generated/action.d.ts
  service/src/integrationTest/kotlin/fi/espoo/evaka/absence/AbsenceApplicationControllersTest.kt
  service/src/main/kotlin/fi/espoo/evaka/absence/application/AbsenceApplicationControllers.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/domain/OperationalDays.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/security/Action.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/security/actionrule/HasGroupRole.kt
Labels: enhancement

#7109 Talouden viestinnän kansiointi
  frontend/src/e2e-test/specs/4_finance/person-finance-notes-and-messages.spec.ts
  frontend/src/employee-frontend/components/messages/Sidebar.tsx
  frontend/src/employee-frontend/components/messages/queries.ts
  frontend/src/employee-frontend/components/person-profile/PersonFinanceNotesAndMessages.tsx
  frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
  service/src/integrationTest/kotlin/fi/espoo/evaka/messaging/MessageIntegrationTest.kt
  service/src/main/kotlin/fi/espoo/evaka/messaging/MessageController.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/dev/DevApi.kt
  service/src/main/resources/dev-data/dev-data.sql
Labels: enhancement

#7149 Korjataan yksikön karttakoordinaattien tyhjennys
  service/src/integrationTest/kotlin/fi/espoo/evaka/daycare/DaycareEditIntegrationTest.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/db/JdbiExtensions.kt
Labels: bug

#7101 Lisätään päätökset-raportille hakemuksen tyypin mukaan suodatus
  frontend/src/employee-frontend/components/reports/Decisions.tsx
  frontend/src/employee-frontend/generated/api-clients/reports.ts
  frontend/src/lib-common/generated/api-types/application.ts
  service/src/integrationTest/kotlin/fi/espoo/evaka/reports/ReportSmokeTests.kt
  service/src/main/kotlin/fi/espoo/evaka/application/Application.kt
  service/src/main/kotlin/fi/espoo/evaka/reports/DecisionsReport.kt
Labels: enhancement

#7153 Särmän metadata skeeman päivitys
  service/sarmamodel/src/main/schema/yleinen/yleinen-1.0.xsd
Labels: tech

#7064 Esiopetuksen tuen tason lakimuutokset
  frontend/src/employee-frontend/components/child-information/assistance/DaycareAssistanceForm.tsx
  frontend/src/employee-frontend/components/child-information/assistance/DaycareAssistanceRow.tsx
  frontend/src/employee-frontend/components/child-information/assistance/DaycareAssistanceSection.tsx
  frontend/src/employee-frontend/components/child-information/assistance/PreschoolAssistanceForm.tsx
  frontend/src/employee-frontend/components/child-information/assistance/PreschoolAssistanceRow.tsx
  frontend/src/employee-frontend/components/child-information/assistance/PreschoolAssistanceSection.tsx
  frontend/src/employee-frontend/components/reports/AssistanceNeedsAndActions.tsx
  frontend/src/lib-common/generated/api-types/assistance.ts
  frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
  service/src/integrationTest/kotlin/fi/espoo/evaka/koski/KoskiIntegrationTest.kt
  service/src/main/kotlin/fi/espoo/evaka/assistance/Assistance.kt
  service/src/main/kotlin/fi/espoo/evaka/assistance/AssistanceController.kt
  service/src/main/kotlin/fi/espoo/evaka/koski/KoskiData.kt
  service/src/main/kotlin/fi/espoo/evaka/koski/Oppija.kt
Labels: enhancement

#7156 Lisätään uusien asiakkaiden tulotietojen ja tulotietoselvitysten tarkistus
  service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/service/NewCustomerIncomeNotificationIntegrationTest.kt
  service/src/main/kotlin/fi/espoo/evaka/invoicing/service/IncomeQueries.kt
Labels: enhancement

#7157 org.postgresql:postgresql tietoturvapäivitys
  service/evaka-bom/build.gradle.kts
Labels: dependencies

#7006 Käytetään Viteä tuotantobuildiin
  frontend/.dockerignore
  frontend/.yarn/patches/unplugin-npm-1.0.1-70bc9bb0e2.patch
  frontend/Dockerfile
  frontend/package.json
  frontend/proxy/files/etc/nginx/conf.d/nginx.conf.template
  frontend/src/lib-customizations/espoo/appConfigs.ts
  frontend/src/lib-customizations/espoo/citizen.tsx
  frontend/src/lib-customizations/espoo/employee.tsx
  frontend/src/lib-customizations/espoo/employeeMobile.tsx
  frontend/vite.config.ts
  frontend/yarn.lock
Labels: tech

#7161 Korjataan Tänään-nappi kasvattajan mobiilin lapsilistassa
  frontend/src/employee-mobile-frontend/App.tsx
Labels: bug

#7163 Migratoidaan vanhat poissaolokyselyn vastaukset ja lisätään rajoituksia
  service/src/integrationTest/kotlin/fi/espoo/evaka/shared/db/SchemaConventionsTest.kt
  service/src/main/resources/db/migration/V541__holiday_questionnaire_constraints.sql
  service/src/main/resources/migrations.txt
Labels: bug

#7165 Korjauksia kasvattajan mobiilin linkkeihin
  frontend/src/employee-mobile-frontend/App.tsx
  frontend/src/employee-mobile-frontend/child-attendance/AttendanceList.tsx
  frontend/src/employee-mobile-frontend/child-attendance/AttendancePageWrapper.tsx
  frontend/src/employee-mobile-frontend/staff-attendance/StaffAttendancesPage.tsx
  frontend/src/lib-components/molecules/Tabs.tsx
Labels: bug

#7159 Korjataan nimettömän henkilön näyttäminen perheen tietojen koosteessa
  frontend/src/employee-frontend/components/person-profile/PersonFamilyOverview.tsx
Labels: bug

#7146 Korjataan viestit-sivun käyttö pienillä resoluutioilla
  frontend/src/employee-frontend/components/messages/SingleThreadView.tsx
Labels: enhancement

#7205 CVE-korjaus
  service/evaka-bom/build.gradle.kts
Labels: dependencies

#7151 Lisää kuntalaiselle mahdollisuus näyttää salasana sitä syötettäessä
  frontend/src/citizen-frontend/login/WeakLoginFormPage.tsx
  frontend/src/citizen-frontend/personal-details/LoginDetailsSection.tsx
  frontend/src/lib-components/atoms/form/InputField.tsx
  frontend/src/lib-components/i18n.tsx
  frontend/src/lib-components/molecules/PasswordInputF.tsx
  frontend/src/lib-components/utils/TestContextProvider.tsx
  frontend/src/lib-customizations/defaults/components/i18n/en.tsx
  frontend/src/lib-customizations/defaults/components/i18n/fi.tsx
  frontend/src/lib-customizations/defaults/components/i18n/sv.tsx
Labels: enhancement

#7210 Kerrotaan Sentrylle mikä frontin versio on ajossa
  frontend/src/citizen-frontend/index.tsx
  frontend/src/employee-frontend/index.tsx
  frontend/src/employee-mobile-frontend/index.tsx
Labels: tech

#7168 Muutetaan "Lapsen asiakirjat" käyttämään linkkejä nappuloiden sijaan
  frontend/src/employee-frontend/components/child-information/ChildDocuments.tsx
  frontend/src/employee-frontend/index.css
  frontend/src/lib-components/atoms/DisableableLink.tsx
Labels: bug

#7154 Korjauksia metadatamigraatioon
  service/src/integrationTest/kotlin/fi/espoo/evaka/process/MigrationTest.kt
  service/src/main/kotlin/fi/espoo/evaka/process/Migration.kt
Labels: tech

#7209 Lisätään esiopetusta järjestävät yksiköt varasijoituksiin
  frontend/src/employee-frontend/components/applications/ApplicationsFilters.tsx
  frontend/src/employee-frontend/components/child-information/assistance-need/decision/AssistanceNeedPreschoolDecisionEditPage.tsx
  frontend/src/employee-frontend/components/child-information/assistance-need/decision/AssistanceNeededDecisionForm.tsx
  frontend/src/employee-frontend/components/child-information/backup-care/BackupCareForm.tsx
  frontend/src/employee-frontend/generated/api-clients/daycare.ts
  frontend/src/employee-frontend/state/invoicing-ui.tsx
  frontend/src/lib-common/generated/api-types/daycare.ts
  service/src/main/kotlin/fi/espoo/evaka/daycare/controllers/LocationController.kt
Labels: enhancement

#7216 Retag evaka/service-builder after build success
  .github/workflows/build.yml
Labels: no-changelog

#7212 Palveluntuottajan sähköpostiosoitteen muokkaaminen pääkäyttäjänä
  frontend/src/employee-frontend/components/employees/EmployeePage.tsx
  frontend/src/employee-frontend/components/employees/queries.ts
  frontend/src/employee-frontend/generated/api-clients/pis.ts
  frontend/src/lib-common/generated/api-types/pis.ts
  service/src/integrationTest/kotlin/fi/espoo/evaka/pis/controller/EmployeeControllerIntegrationTest.kt
  service/src/main/kotlin/fi/espoo/evaka/Audit.kt
  service/src/main/kotlin/fi/espoo/evaka/pis/EmployeeQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/pis/controllers/EmployeeController.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/security/Action.kt
Labels: enhancement

#7206 Lisätään yksikköeditoriin integraatio-ikonit
  frontend/src/employee-frontend/components/unit/unit-details/UnitEditor.tsx
  frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
Labels: enhancement

#7215 Korjataan linkkien aktiivisuus kuntalaisen (mobiili+desktop) ja henkilökunnan (desktop) käyttöliittymissä
  frontend/src/citizen-frontend/navigation/DesktopNav.tsx
  frontend/src/citizen-frontend/navigation/MobileNav.tsx
  frontend/src/employee-frontend/components/Header.tsx
  frontend/src/employee-mobile-frontend/child-attendance/AttendancePageWrapper.tsx
  frontend/src/employee-mobile-frontend/staff-attendance/StaffAttendancesPage.tsx
  frontend/src/lib-components/atoms/NavLink.tsx
  frontend/src/lib-components/molecules/Tabs.tsx
Labels: bug

#7214 Lisätään arkistoitavan asiakirjan luontipäivämäärä
  service/src/main/kotlin/fi/espoo/evaka/document/archival/DocumentMetadataUtils.kt
Labels: enhancement

#7219 Poistetaan esiopetuspaikan osoituksesta oletus palveluntarve
  service/src/integrationTest/kotlin/fi/espoo/evaka/application/PlacementToolServiceIntegrationTest.kt
  service/src/main/kotlin/fi/espoo/evaka/application/PlacementToolService.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/async/AsyncJob.kt
Labels: breaking

#7221 Asianhallinnan tehtäväluokka osittain pakolliseksi
  frontend/src/e2e-test/specs/5_employee/child-documents.spec.ts
  frontend/src/employee-frontend/components/document-templates/forms.ts
Labels: enhancement

#7226 Poistetaan kalenterin puuttuvan poissaolokyselyvastauksen indikaattori ilmaisilta sijoituksilta
  service/src/main/kotlin/fi/espoo/evaka/absence/AbsenceService.kt
Labels: bug

#7167 Tuetaan tukitoimivaihtoehtojen muuttumista
  frontend/src/e2e-test/dev-api/fixtures.ts
  frontend/src/e2e-test/generated/api-types.ts
  frontend/src/employee-frontend/components/child-information/assistance/AssistanceActionForm.tsx
  frontend/src/employee-frontend/components/child-information/assistance/AssistanceActionRow.tsx
  frontend/src/employee-frontend/components/common/LabelValueList.tsx
  frontend/src/employee-frontend/generated/api-clients/assistance.ts
  frontend/src/employee-frontend/generated/api-clients/reports.ts
  frontend/src/lib-common/generated/api-types/assistanceaction.ts
  frontend/src/lib-common/generated/api-types/reports.ts
  frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
  service/src/integrationTest/kotlin/fi/espoo/evaka/TestFixtures.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/assistanceaction/AssistanceActionIntegrationTest.kt
  service/src/main/kotlin/fi/espoo/evaka/assistanceaction/AssistanceAction.kt
  service/src/main/kotlin/fi/espoo/evaka/assistanceaction/AssistanceActionQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/assistanceaction/AssistanceActionService.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/dev/DataInitializers.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/dev/DevApi.kt
  service/src/main/resources/db/migration/V542__assistance_action_option_validity.sql
  service/src/main/resources/dev-data/dev-data.sql
  service/src/main/resources/migrations.txt
Labels: breaking

#7169 Estetään tuen päätöksen automaattikatkaisu jos lapsi jatkaa edelleen samannimisessä yksikössä kuin päätöksen yksikkö
  service/src/integrationTest/kotlin/fi/espoo/evaka/assistanceneed/decision/AssistanceNeedDecisionIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/assistanceneed/decision/AssistanceNeedPreschoolDecisionIntegrationTest.kt
  service/src/main/kotlin/fi/espoo/evaka/assistanceneed/decision/AssistanceNeedDecisionQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/assistanceneed/preschooldecision/AssistanceNeedPreschoolDecisionQueries.kt
Labels: enhancement

#7218 Korjataan viestiketjun merkitseminen luetuksi
  frontend/src/employee-frontend/components/messages/MessageContext.tsx
  frontend/src/employee-frontend/components/messages/SingleThreadView.tsx
  frontend/src/employee-frontend/components/person-profile/PersonFinanceNotesAndMessages.tsx
  service/src/integrationTest/kotlin/fi/espoo/evaka/messaging/MessageIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/messaging/MessageQueriesTest.kt
  service/src/main/kotlin/fi/espoo/evaka/messaging/MessageController.kt
  service/src/main/kotlin/fi/espoo/evaka/messaging/MessageControllerCitizen.kt
  service/src/main/kotlin/fi/espoo/evaka/messaging/MessageQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/messaging/MessageService.kt
Labels: enhancement

#7230 Muutetaan tulotietojen muistutusviestit haitariin
  frontend/src/e2e-test/pages/employee/guardian-information.ts
  frontend/src/e2e-test/specs/5_employee/income.spec.ts
  frontend/src/employee-frontend/components/person-profile/PersonIncome.tsx
  frontend/src/employee-frontend/components/person-profile/income/IncomeNotifications.tsx
  frontend/src/employee-frontend/components/reports/HolidayPeriodAttendanceReport.tsx
  frontend/src/employee-frontend/components/reports/HolidayQuestionnaireReport.tsx
  frontend/src/employee-frontend/components/unit/tab-calendar/discussion-surveys/DiscussionSurveyView.tsx
  frontend/src/employee-frontend/components/unit/tab-calendar/discussion-surveys/survey-editor/DiscussionTimesForm.tsx
  frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
Labels: enhancement

#7262 Päivitetään lomakepohjien tyypit
  frontend/src/e2e-test/specs/5_employee/child-documents.spec.ts
  frontend/src/employee-frontend/components/document-templates/template-editor/TemplateContentEditor.tsx
  frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
  service/src/main/kotlin/fi/espoo/evaka/emailclient/EvakaEmailMessageProvider.kt
Labels: enhancement

#7227 Parannetaan integraatiotestien ajamista CI:ssä
  .github/workflows/build.yml
  bin/split-integration-tests.sh
Labels: no-changelog

#7225 Näytetään muokkaustiedot kaikissa tuen osioissa
  frontend/src/employee-frontend/components/child-information/AssistanceNeedVoucherCoefficientSection.tsx
  frontend/src/employee-frontend/components/child-information/assistance-need/voucher-coefficient/AssistanceNeedVoucherCoefficientForm.tsx
  frontend/src/employee-frontend/components/child-information/assistance-need/voucher-coefficient/AssistanceNeedVoucherCoefficientRow.tsx
  frontend/src/employee-frontend/components/child-information/assistance/AssistanceActionRow.tsx
  frontend/src/employee-frontend/components/child-information/assistance/AssistanceFactorForm.tsx
  frontend/src/employee-frontend/components/child-information/assistance/AssistanceFactorRow.tsx
  frontend/src/employee-frontend/components/child-information/assistance/AssistanceFactorSection.tsx
  frontend/src/employee-frontend/components/child-information/assistance/DaycareAssistanceForm.tsx
  frontend/src/employee-frontend/components/child-information/assistance/DaycareAssistanceRow.tsx
  frontend/src/employee-frontend/components/child-information/assistance/DaycareAssistanceSection.tsx
  frontend/src/employee-frontend/components/child-information/assistance/OtherAssistanceMeasureForm.tsx
  frontend/src/employee-frontend/components/child-information/assistance/OtherAssistanceMeasureRow.tsx
  frontend/src/employee-frontend/components/child-information/assistance/OtherAssistanceMeasureSection.tsx
  frontend/src/employee-frontend/components/child-information/assistance/PreschoolAssistanceForm.tsx
  frontend/src/employee-frontend/components/child-information/assistance/PreschoolAssistanceRow.tsx
  frontend/src/employee-frontend/components/child-information/assistance/PreschoolAssistanceSection.tsx
  frontend/src/lib-common/generated/api-types/assistanceaction.ts
  frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
  service/src/integrationTest/kotlin/fi/espoo/evaka/assistanceaction/AssistanceActionIntegrationTest.kt
  service/src/main/kotlin/fi/espoo/evaka/assistance/AssistanceController.kt
  service/src/main/kotlin/fi/espoo/evaka/assistance/AssistanceQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/assistanceaction/AssistanceAction.kt
  service/src/main/kotlin/fi/espoo/evaka/assistanceaction/AssistanceActionQueries.kt
Labels: enhancement

#7228 Kuntalaiselle hakemuksen metatietoja näkyviin
  frontend/src/citizen-frontend/applications/ChildApplicationsBlock.tsx
  frontend/src/citizen-frontend/applications/queries.ts
  frontend/src/citizen-frontend/generated/api-clients/process.ts
  frontend/src/citizen-frontend/metadata/MetadataSection.tsx
  frontend/src/e2e-test/pages/citizen/citizen-applications.ts
  frontend/src/e2e-test/specs/0_citizen/citizen-applications-list.spec.ts
  frontend/src/employee-frontend/components/archive-metadata/MetadataSection.tsx
  frontend/src/employee-frontend/components/child-information/assistance-need/voucher-coefficient/AssistanceNeedVoucherCoefficientForm.tsx
  frontend/src/employee-frontend/components/child-information/assistance/AssistanceActionForm.tsx
  frontend/src/employee-frontend/components/child-information/assistance/AssistanceActionRow.tsx
  frontend/src/employee-frontend/components/child-information/fee-alteration/FeeAlterationEditor.tsx
  frontend/src/employee-frontend/components/child-information/person-details/AdditionalInformation.tsx
  frontend/src/employee-frontend/components/decision-draft/DecisionDraft.tsx
  frontend/src/employee-frontend/components/document-templates/template-editor/TemplateContentEditor.tsx
  frontend/src/employee-frontend/components/fee-decision-details/ChildSection.tsx
  frontend/src/employee-frontend/components/fee-decision-details/Heading.tsx
  frontend/src/employee-frontend/components/fee-decision-details/IncomeSection.tsx
  frontend/src/employee-frontend/components/invoice/InvoiceDetailsSection.tsx
  frontend/src/employee-frontend/components/invoice/InvoiceHeadOfFamilySection.tsx
  frontend/src/employee-frontend/components/person-profile/PersonFamilyOverview.tsx
  frontend/src/employee-frontend/components/person-shared/PersonDetails.tsx
  frontend/src/employee-frontend/components/unit/unit-reservations/UnitAttendanceReservationsView.tsx
  frontend/src/employee-frontend/components/voucher-value-decision/VoucherValueDecisionChildSection.tsx
  frontend/src/employee-frontend/components/voucher-value-decision/VoucherValueDecisionHeading.tsx
  frontend/src/employee-frontend/components/voucher-value-decision/VoucherValueDecisionIncomeSection.tsx
  frontend/src/lib-common/generated/api-types/process.ts
  frontend/src/lib-components/i18n.tsx
  frontend/src/lib-components/molecules/LabelValueList.tsx
  frontend/src/lib-components/molecules/Metadatas.tsx
  frontend/src/lib-components/utils/TestContextProvider.tsx
  frontend/src/lib-customizations/defaults/components/i18n/en.tsx
  frontend/src/lib-customizations/defaults/components/i18n/fi.tsx
  frontend/src/lib-customizations/defaults/components/i18n/sv.tsx
  frontend/src/lib-customizations/espoo/featureFlags.tsx
  frontend/src/lib-customizations/types.d.ts
  service/src/main/kotlin/fi/espoo/evaka/process/ArchivedProcesses.kt
  service/src/main/kotlin/fi/espoo/evaka/process/ProcessMetadataController.kt
  service/src/main/kotlin/fi/espoo/evaka/process/ProcessMetadataControllerCitizen.kt
  service/src/main/kotlin/fi/espoo/evaka/process/ProcessMetadataQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/process/ProcessMetadataService.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/dev/DevApi.kt
Labels: enhancement

#7267 Yksikön viikkokalenterissa voi valita ryhmäksi lapset joilla on vuorohoitoa
  frontend/src/e2e-test/pages/employee/units/unit-calendar-page-base.ts
  frontend/src/e2e-test/specs/5_employee/reservation-calendar.spec.ts
  frontend/src/employee-frontend/components/unit/TabCalendar.tsx
  frontend/src/employee-frontend/components/unit/tab-calendar/AttendanceGroupFilterSelect.tsx
  frontend/src/employee-frontend/components/unit/unit-reservations/ChildReservationsTable.tsx
  frontend/src/lib-common/generated/api-types/reservations.ts
  frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
  service/src/integrationTest/kotlin/fi/espoo/evaka/reservations/AttendanceReservationsControllerIntegrationTest.kt
  service/src/main/kotlin/fi/espoo/evaka/reservations/AttendanceReservationController.kt
Labels: enhancement

#7231 Oletuspalveluntarpeen näyttämisen parannuksia
  frontend/src/citizen-frontend/children/sections/service-need-and-daily-service-time/ServiceNeedTable.tsx
  frontend/src/e2e-test/specs/0_citizen/citizen-child-page.spec.ts
  frontend/src/employee-frontend/components/child-information/placements/ServiceNeeds.tsx
  frontend/src/employee-frontend/components/child-information/placements/service-needs/MissingServiceNeedRow.tsx
  frontend/src/employee-frontend/components/reports/MissingServiceNeed.tsx
  frontend/src/employee-frontend/generated/api-clients/reports.ts
  frontend/src/employee-frontend/types/unit.ts
  frontend/src/lib-common/generated/api-types/placement.ts
  frontend/src/lib-common/generated/api-types/reports.ts
  frontend/src/lib-common/generated/api-types/serviceneed.ts
  frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
  service/src/integrationTest/kotlin/fi/espoo/evaka/placement/PlacementServiceIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/reports/MissingServiceNeedReportTest.kt
  service/src/main/kotlin/fi/espoo/evaka/application/ApplicationForm.kt
  service/src/main/kotlin/fi/espoo/evaka/children/ChildControllerCitizen.kt
  service/src/main/kotlin/fi/espoo/evaka/placement/PlacementService.kt
  service/src/main/kotlin/fi/espoo/evaka/reports/MissingServiceNeedReport.kt
  service/src/main/kotlin/fi/espoo/evaka/serviceneed/ServiceNeed.kt
  service/src/main/kotlin/fi/espoo/evaka/serviceneed/ServiceNeedQueries.kt
Labels: enhancement

#7160 Vastaamattomien päivien huomautus kuntalaisen kalenterin loma-aika vastauksiin
  frontend/src/citizen-frontend/calendar/ReservationModal.tsx
  frontend/src/citizen-frontend/calendar/reservation-modal/TimeInputs.tsx
  frontend/src/e2e-test/pages/citizen/citizen-calendar.ts
  frontend/src/e2e-test/specs/0_citizen/citizen-holiday-reservations.spec.ts
  frontend/src/lib-customizations/defaults/citizen/i18n/en.tsx
  frontend/src/lib-customizations/defaults/citizen/i18n/fi.tsx
  frontend/src/lib-customizations/defaults/citizen/i18n/sv.tsx
Labels: enhancement

#7269 Tallennetaan lomakepohjaisen päätöksen aloitushetken yksikkö kun päätös hyväksytään
  frontend/src/employee-frontend/components/child-information/ChildDocuments.tsx
  frontend/src/lib-common/generated/api-types/document.ts
  frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
  service/src/integrationTest/kotlin/fi/espoo/evaka/document/childdocument/ChildDocumentControllerIntegrationTest.kt
  service/src/main/kotlin/fi/espoo/evaka/document/childdocument/ChildDocument.kt
  service/src/main/kotlin/fi/espoo/evaka/document/childdocument/ChildDocumentController.kt
  service/src/main/kotlin/fi/espoo/evaka/document/childdocument/ChildDocumentQueries.kt
  service/src/main/resources/db/migration/V544__child_document_decision_unit.sql
  service/src/main/resources/migrations.txt
Labels: enhancement

#7272 Konfiguroidaan yöllinen metadatamigraatioajo päälle kaikissa kunnissa
  service/src/main/kotlin/fi/espoo/evaka/shared/job/ScheduledJobs.kt
Labels: enhancement

#7270 Vanhentuneiden päätösten katkaisu yöllisessä ajossa
  frontend/src/e2e-test/dev-api/fixtures.ts
  frontend/src/e2e-test/generated/api-types.ts
  service/src/integrationTest/kotlin/fi/espoo/evaka/document/childdocument/ChildDocumentDecisionExpirationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/reports/ChildDocumentDecisionsReportTest.kt
  service/src/main/kotlin/fi/espoo/evaka/document/childdocument/ChildDocumentQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/dev/DataInitializers.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/dev/DevApi.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/job/ScheduledJobs.kt
Labels: enhancement
