Repository espoon-voltti/evaka, pull requests merged in 2025-07, with the labels that each got.

#7303 Korjataan esiopetuksen poissaolohakemus
  frontend/src/citizen-frontend/children/sections/absence-applications/NewAbsenceApplicationForm.tsx
  frontend/src/citizen-frontend/children/sections/absence-applications/NewAbsenceApplicationPage.tsx
  frontend/src/citizen-frontend/children/sections/absence-applications/queries.ts
  frontend/src/citizen-frontend/generated/api-clients/absence.ts
  frontend/src/e2e-test/pages/citizen/citizen-new-absence-application.ts
  frontend/src/e2e-test/specs/absence-application/absence-application.spec.ts
  frontend/src/lib-components/molecules/date-picker/DateRangePicker.tsx
  frontend/src/lib-customizations/defaults/citizen/i18n/en.tsx
  frontend/src/lib-customizations/defaults/citizen/i18n/fi.tsx
  frontend/src/lib-customizations/defaults/citizen/i18n/sv.tsx
  service/src/integrationTest/kotlin/fi/espoo/evaka/absence/AbsenceApplicationControllersTest.kt
  service/src/main/kotlin/fi/espoo/evaka/Audit.kt
  service/src/main/kotlin/fi/espoo/evaka/absence/application/AbsenceApplicationControllers.kt
  service/src/main/kotlin/fi/espoo/evaka/absence/application/AbsenceApplicationQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/children/ChildControllerCitizen.kt
Labels: bug

#7309 Näytetään hakemuspäätöksen asianhallinnan metadata kuntalaiselle
  frontend/src/citizen-frontend/decisions/decisions-page/ApplicationDecision.tsx
  frontend/src/e2e-test/pages/citizen/citizen-decisions.ts
  frontend/src/e2e-test/specs/0_citizen/citizen-decisions.spec.ts
Labels: enhancement

#7310 Näytetään maksuihin liittyvien päätösten asianhallinnan metadata kuntalaiselle
  frontend/src/citizen-frontend/decisions/decisions-page/FinanceDecision.tsx
  frontend/src/citizen-frontend/decisions/queries.ts
  frontend/src/citizen-frontend/generated/api-clients/caseprocess.ts
  frontend/src/e2e-test/generated/api-clients.ts
  frontend/src/e2e-test/pages/citizen/citizen-decisions.ts
  frontend/src/e2e-test/specs/0_citizen/citizen-finance-decisions.spec.ts
  service/src/main/kotlin/fi/espoo/evaka/caseprocess/ProcessMetadataController.kt
  service/src/main/kotlin/fi/espoo/evaka/caseprocess/ProcessMetadataControllerCitizen.kt
  service/src/main/kotlin/fi/espoo/evaka/caseprocess/ProcessMetadataQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/dev/DevApi.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/security/Action.kt
Labels: enhancement

#7313 Refaktoroidaan henkilön nimen formatointia
  frontend/src/citizen-frontend/applications/editor/contact-info/ChildSubSection.tsx
  frontend/src/citizen-frontend/applications/editor/contact-info/GuardianSubSection.tsx
  frontend/src/citizen-frontend/applications/editor/verification/UnitPreferenceSection.tsx
  frontend/src/citizen-frontend/calendar/discussion-reservation-modal/DiscussionSurveyModal.tsx
  frontend/src/lib-common/names.ts
  frontend/src/lib-components/molecules/PersonNames.tsx
Labels: tech

#7315 Tekninen: Poistetaan jq apigw-imagesta
  apigw/Dockerfile
Labels: tech

#7352 Päivitetty evaka kontekstikuvaa lisäämällä ruokapalvelu
  docs/diagrams/src/evaka-context.puml
  docs/out/diagrams/src/evaka-context/eVakan kontekstikaavio.png
Labels: enhancement

#7318 Korjataan kuntalaisen kalenterin kuukauden tuntikoosteen päivitys
  frontend/src/citizen-frontend/calendar/CalendarMonthView.tsx
  frontend/src/citizen-frontend/calendar/CalendarPage.tsx
  frontend/src/citizen-frontend/calendar/hooks.ts
  frontend/src/e2e-test/pages/citizen/citizen-calendar.ts
  frontend/src/e2e-test/specs/0_citizen/citizen-show-service-usage.spec.ts
Labels: bug

#7351 Päätöspohjassa valitaan katkeaako päätös yksikön vaihtuessa
  frontend/src/e2e-test/dev-api/fixtures.ts
  frontend/src/e2e-test/generated/api-types.ts
  frontend/src/e2e-test/specs/0_citizen/citizen-child-documents.spec.ts
  frontend/src/e2e-test/specs/5_employee/child-documents.spec.ts
  frontend/src/employee-frontend/components/document-templates/forms.ts
  frontend/src/employee-frontend/components/document-templates/template-editor/TemplateContentEditor.tsx
  frontend/src/employee-frontend/components/document-templates/template-editor/TemplateModal.tsx
  frontend/src/lib-common/generated/api-types/document.ts
  frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
  service/src/integrationTest/kotlin/fi/espoo/evaka/document/DocumentTemplateIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/document/childdocument/ChildDocumentControllerIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/document/childdocument/ChildDocumentDecisionExpirationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/document/childdocument/ChildDocumentServiceIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/pdfgen/PdfGeneratorTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/reports/ChildDocumentDecisionsReportTest.kt
  service/src/main/kotlin/fi/espoo/evaka/document/DocumentTemplate.kt
  service/src/main/kotlin/fi/espoo/evaka/document/DocumentTemplateController.kt
  service/src/main/kotlin/fi/espoo/evaka/document/DocumentTemplateQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/document/childdocument/ChildDocumentQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/dev/DataInitializers.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/dev/DevApi.kt
  service/src/main/resources/db/migration/V546__end_decision_when_unit_changes_config.sql
  service/src/main/resources/migrations.txt
  service/src/test/kotlin/fi/espoo/evaka/document/archival/ArchiveChildDocumentServiceTest.kt
  service/src/test/kotlin/fi/espoo/evaka/document/archival/DocumentMetadataUtilsTest.kt
Labels: enhancement

#7356 Korjaus yöllisten ajojen metadatamigraation jumiutumisongelmaan
  service/src/main/kotlin/fi/espoo/evaka/caseprocess/Migration.kt
Labels: bug

#7353 Päivitetään päätöksen tila -tekstejä
  frontend/src/e2e-test/specs/5_employee/child-documents.spec.ts
  frontend/src/lib-components/atoms/Chip.tsx
  frontend/src/lib-components/document-templates/ChildDocumentStateChip.tsx
  frontend/src/lib-customizations/defaults/components/i18n/fi.tsx
Labels: enhancement

#7319 Päätöstyyppisen dokumentin muistutussähköpostin tekstimuutos
  service/src/main/kotlin/fi/espoo/evaka/document/childdocument/ChildDocumentController.kt
  service/src/main/kotlin/fi/espoo/evaka/emailclient/EvakaEmailMessageProvider.kt
Labels: enhancement

#7360 Poista lapsen toisintamisen toiminnallisuudet
  frontend/src/e2e-test/pages/employee/reports.ts
  frontend/src/e2e-test/specs/5_employee/manual-duplication-report.spec.ts
  frontend/src/e2e-test/specs/5_employee/missing-head-of-family-report.spec.ts
  frontend/src/e2e-test/specs/5_employee/non-ssn-children-report.spec.ts
  frontend/src/e2e-test/specs/5_employee/preschool-absence-report.spec.ts
  frontend/src/employee-frontend/components/Reports.tsx
  frontend/src/employee-frontend/components/person-profile/queries.ts
  frontend/src/employee-frontend/components/person-shared/PersonDetails.tsx
  frontend/src/employee-frontend/components/reports/DuplicatePeople.tsx
  frontend/src/employee-frontend/components/reports/ManualDuplicationReport.tsx
  frontend/src/employee-frontend/components/reports/MissingHeadOfFamily.tsx
  frontend/src/employee-frontend/components/reports/queries.ts
  frontend/src/employee-frontend/generated/api-clients/pis.ts
  frontend/src/employee-frontend/generated/api-clients/reports.ts
  frontend/src/employee-frontend/router.tsx
  frontend/src/lib-common/generated/action.d.ts
  frontend/src/lib-common/generated/api-types/reports.ts
  frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
  frontend/src/lib-customizations/espoo/featureFlags.tsx
  frontend/src/lib-customizations/types.d.ts
  service/src/integrationTest/kotlin/fi/espoo/evaka/pis/controller/PersonControllerIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/reports/ManualDuplicationReportTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/reports/MissingHeadOfFamilyReportTest.kt
  service/src/main/kotlin/fi/espoo/evaka/Audit.kt
  service/src/main/kotlin/fi/espoo/evaka/pis/controllers/PersonController.kt
  service/src/main/kotlin/fi/espoo/evaka/reports/DuplicatePeopleReport.kt
  service/src/main/kotlin/fi/espoo/evaka/reports/ManualDuplicationReportController.kt
  service/src/main/kotlin/fi/espoo/evaka/reports/MissingHeadOfFamilyReport.kt
  service/src/main/kotlin/fi/espoo/evaka/reports/ReportPermissions.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/security/Action.kt
Labels: enhancement

#7393 Lisätään linkki hakemukseen palveluohjauksen viestiketjuissa
  frontend/src/employee-frontend/components/messages/MessageContext.tsx
  frontend/src/employee-frontend/components/messages/SingleThreadView.tsx
  frontend/src/lib-common/generated/api-types/messaging.ts
  frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
  service/src/main/kotlin/fi/espoo/evaka/messaging/Message.kt
  service/src/main/kotlin/fi/espoo/evaka/messaging/MessageQueries.kt
Labels: enhancement

#7392 Korjataan ilmoita läsnäoloja -modaalin saavutettavuutta
  frontend/src/citizen-frontend/calendar/ReservationModal.tsx
  frontend/src/citizen-frontend/calendar/reservation-modal/TimeInputs.tsx
  frontend/src/lib-customizations/defaults/citizen/i18n/en.tsx
  frontend/src/lib-customizations/defaults/citizen/i18n/fi.tsx
  frontend/src/lib-customizations/defaults/citizen/i18n/sv.tsx
Labels: enhancement

#7427 Bump form-data from 4.0.0 to 4.0.4 in /frontend
  frontend/yarn.lock
Labels: dependencies

#7428 Bump form-data from 4.0.2 to 4.0.4 in /apigw
  apigw/yarn.lock
Labels: dependencies

#7419 Lisätään sivun title vastaamaan valittua pääsivua
  frontend/src/citizen-frontend/AccessibilityStatement.tsx
  frontend/src/citizen-frontend/applications/editor/ApplicationEditor.tsx
  frontend/src/citizen-frontend/applications/read-view/ApplicationReadView.tsx
  frontend/src/citizen-frontend/applications/read-view/ApplicationReadViewContents.tsx
  frontend/src/citizen-frontend/calendar/CalendarPage.tsx
  frontend/src/citizen-frontend/child-documents/ChildDocumentPage.tsx
  frontend/src/citizen-frontend/children/ChildHeader.tsx
  frontend/src/citizen-frontend/children/ChildPage.tsx
  frontend/src/citizen-frontend/children/sections/absence-applications/NewAbsenceApplicationPage.tsx
  frontend/src/citizen-frontend/children/sections/service-need-and-daily-service-time/NewServiceApplicationPage.tsx
  frontend/src/citizen-frontend/decisions/assistance-decision-page/AssistanceDecisionPage.tsx
  frontend/src/citizen-frontend/decisions/assistance-decision-page/AssistancePreschoolDecisionPage.tsx
  frontend/src/citizen-frontend/income-statements/ChildIncomeStatementForm.tsx
  frontend/src/citizen-frontend/income-statements/ChildIncomeStatementView.tsx
  frontend/src/citizen-frontend/income-statements/IncomeStatementForm.tsx
  frontend/src/citizen-frontend/income-statements/IncomeStatementView.tsx
  frontend/src/citizen-frontend/income-statements/IncomeStatements.tsx
  frontend/src/citizen-frontend/login/LoginPage.tsx
  frontend/src/citizen-frontend/login/WeakLoginFormPage.tsx
  frontend/src/citizen-frontend/messages/MessagesPage.tsx
  frontend/src/citizen-frontend/personal-details/PersonalDetails.tsx
Labels: enhancement

#7423 Korjataan omien tietojen muokkauksen kohdistus
  frontend/src/citizen-frontend/personal-details/PersonalDetailsSection.tsx
  frontend/src/lib-components/atoms/dropdowns/Select.tsx
Labels: enhancement

#7422 Näytetään hakemus yksikön sivulla kunnes kaikkiin päätöksiin on otettu kantaa
  frontend/src/e2e-test/specs/5_employee/unit-application-process.spec.ts
  service/src/integrationTest/kotlin/fi/espoo/evaka/decision/DecisionResolutionIntegrationTest.kt
  service/src/main/kotlin/fi/espoo/evaka/application/ApplicationStateService.kt
Labels: bug

#7395 Sijoituksen viimeiseen päivään irtisanominen ei näy huoltajan irtisanomana
  service/src/integrationTest/kotlin/fi/espoo/evaka/placement/PlacementControllerCitizenIntegrationTest.kt
  service/src/main/kotlin/fi/espoo/evaka/placement/PlacementControllerCitizen.kt
  service/src/main/kotlin/fi/espoo/evaka/placement/PlacementQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/placement/PlacementService.kt
  service/src/main/kotlin/fi/espoo/evaka/placement/PlacementTermination.kt
Labels: bug

#7429 Korjataan kohdistus kun viestiketju suljetaan
  frontend/src/citizen-frontend/messages/MessagesPage.tsx
  frontend/src/citizen-frontend/messages/ThreadList.tsx
  frontend/src/citizen-frontend/messages/ThreadListItem.tsx
Labels: enhancement

#7430 Näytetään mobiilin työvuorolistoissa vain päivät jona yksikkö on auki
  frontend/src/e2e-test/specs/6_mobile/realtime-staff-attendances.spec.ts
  frontend/src/employee-mobile-frontend/generated/api-clients/attendance.ts
  frontend/src/employee-mobile-frontend/staff-attendance/StaffAttendancesPage.tsx
  frontend/src/employee-mobile-frontend/staff-attendance/StaffMemberPlannedAttendancesPage.tsx
  frontend/src/employee-mobile-frontend/staff-attendance/StaffPreviousAttendancesPage.tsx
  frontend/src/lib-common/generated/api-types/attendance.ts
  service/src/main/kotlin/fi/espoo/evaka/attendance/MobileRealtimeStaffAttendanceController.kt
  service/src/main/kotlin/fi/espoo/evaka/attendance/StaffAttendance.kt
Labels: bug

#7451 Upgrade brace-expansion to fix vulnerability
  dummy-idp/package-lock.json
Labels: dependencies

#7435 Lisätään talouden päätöksien lataamiseen tiedostonimi
  service/src/main/kotlin/fi/espoo/evaka/invoicing/data/FeeDecisionQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/invoicing/data/VoucherValueDecisionQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/invoicing/service/FeeDecisionService.kt
  service/src/main/kotlin/fi/espoo/evaka/invoicing/service/VoucherValueDecisionService.kt
Labels: enhancement

#7450 Korjataan frontend docker-kontin konteksti
  frontend/.dockerignore
Labels: tech

#7487 Lisätään tarkistus yksikön aukiololle varasijoituksen luomiseen
  frontend/src/e2e-test/pages/employee/child-information.ts
  frontend/src/e2e-test/specs/5_employee/child-information.spec.ts
  frontend/src/employee-frontend/components/child-information/BackupCare.tsx
  frontend/src/employee-frontend/components/child-information/backup-care/BackupCareForm.tsx
  frontend/src/employee-frontend/generated/api-clients/daycare.ts
  frontend/src/employee-frontend/queries.ts
  frontend/src/lib-common/generated/api-types/daycare.ts
  frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
  service/src/integrationTest/kotlin/fi/espoo/evaka/backupcare/BackupCareIntegrationTest.kt
  service/src/main/kotlin/fi/espoo/evaka/Audit.kt
  service/src/main/kotlin/fi/espoo/evaka/backupcare/BackupCareController.kt
  service/src/main/kotlin/fi/espoo/evaka/daycare/CareArea.kt
  service/src/main/kotlin/fi/espoo/evaka/daycare/DaycareQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/daycare/controllers/DaycareController.kt
Labels: bug

#7490 Muutetaan sijoituksen tyypin käyttöliittymäteksti
  frontend/src/employee-frontend/components/reports/ServiceNeeds.tsx
  frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
Labels: enhancement

#7488 Korjataan kuntalaisen tuloselvitys lomakkeen napit näkymään kokonaan pienillä ruuduilla
  frontend/src/citizen-frontend/income-statements/IncomeStatementForm.tsx
Labels: bug

#7489 Lisätään muokattu viimeksi päivämäärä ryhmämuistiinpanoihin
  frontend/src/employee-frontend/components/unit/tab-groups/notes/NotesModal.tsx
  frontend/src/employee-mobile-frontend/child-notes/GroupNotesTab.tsx
  frontend/src/lib-common/generated/api-types/note.ts
  frontend/src/lib-components/employee/notes/StaticStickyNote.tsx
  frontend/src/lib-components/employee/notes/notes.d.ts
  frontend/src/lib-customizations/defaults/employee-mobile-frontend/i18n/fi.ts
  frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
  service/src/main/kotlin/fi/espoo/evaka/note/group/GroupNote.kt
  service/src/main/kotlin/fi/espoo/evaka/note/group/GroupNoteQueries.kt
Labels: enhancement

#7491 Esiopetukseen ilmoittautuessa kalenterin rajaaminen
  frontend/src/citizen-frontend/applications/editor/ApplicationEditor.tsx
  frontend/src/citizen-frontend/applications/editor/ApplicationFormClub.tsx
  frontend/src/citizen-frontend/applications/editor/ApplicationFormDaycare.tsx
  frontend/src/citizen-frontend/applications/editor/ApplicationFormPreschool.tsx
  frontend/src/citizen-frontend/applications/editor/service-need/PreferredStartSubSection.tsx
  frontend/src/citizen-frontend/applications/editor/service-need/ServiceNeedSection.tsx
  frontend/src/citizen-frontend/applications/editor/service-need/ServiceTimeSubSectionPreschool.tsx
  frontend/src/e2e-test/dev-api/fixtures.ts
  frontend/src/e2e-test/specs/0_citizen/citizen-club-application.spec.ts
  frontend/src/e2e-test/specs/0_citizen/citizen-preschool-application.spec.ts
  frontend/src/lib-components/molecules/date-picker/DatePicker.spec.tsx
  frontend/src/lib-components/molecules/date-picker/DatePicker.tsx
  frontend/src/lib-components/molecules/date-picker/DatePickerDay.tsx
  frontend/src/lib-components/molecules/date-picker/DatePickerLowLevel.tsx
  frontend/src/lib-components/molecules/date-picker/DateRangePicker.spec.tsx
  frontend/src/lib-components/molecules/date-picker/DateRangePicker.tsx
  service/src/integrationTest/kotlin/fi/espoo/evaka/application/ApplicationUpdateIntegrationTest.kt
  service/src/main/kotlin/fi/espoo/evaka/application/ApplicationStateService.kt
Labels: enhancement

#7493 Piiloitetaan pedagogiset dokumentit huoltajalta lapsen sijoituksen loputtua
  frontend/src/citizen-frontend/navigation/utils.ts
  frontend/src/lib-common/generated/api-types/children.ts
  service/src/integrationTest/kotlin/fi/espoo/evaka/children/ChildControllerCitizenTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/document/childdocument/ChildDocumentControllerCitizenIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/pedagogicaldocument/PedagogicalDocumentIntegrationTest.kt
  service/src/main/kotlin/fi/espoo/evaka/children/Children.kt
  service/src/main/kotlin/fi/espoo/evaka/children/ChildrenQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/security/Action.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/security/actionrule/IsCitizen.kt
Labels: bug
