Repository espoon-voltti/evaka, pull requests merged in 2025-10, with the labels that each got.

#7805 Korjataan esiopetuksen poissaoloraportin laskenta
  service/src/integrationTest/kotlin/fi/espoo/evaka/reports/PreschoolAbsenceReportTest.kt
  service/src/main/kotlin/fi/espoo/evaka/reports/PreschoolAbsenceReport.kt
Labels: bug

#7851 Aromi front-end vipu päälle Espoo stagingissa
  frontend/src/lib-customizations/espoo/featureFlags.tsx
Labels: enhancement

#7355 Tuen päätösten migraatio - part 1
  REUSE.toml
  frontend/src/employee-frontend/components/child-documents/statuses.ts
  frontend/src/employee-frontend/components/document-templates/forms.ts
  frontend/src/employee-frontend/components/document-templates/template-editor/TemplateContentEditor.tsx
  frontend/src/employee-frontend/components/document-templates/template-editor/TemplateModal.tsx
  frontend/src/lib-common/generated/api-types/assistanceneed.ts
  frontend/src/lib-common/generated/api-types/document.ts
  frontend/src/lib-components/document-templates/documents.tsx
  frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
  service/src/integrationTest/kotlin/fi/espoo/evaka/assistanceneed/decision/AssistanceNeedDecisionIntegrationTest.kt
  service/src/main/kotlin/fi/espoo/evaka/assistanceneed/decision/AssistanceNeedDecision.kt
  service/src/main/kotlin/fi/espoo/evaka/assistanceneed/decision/AssistanceNeedDecisionQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/assistanceneed/preschooldecision/AssistanceNeedPreschoolDecision.kt
  service/src/main/kotlin/fi/espoo/evaka/assistanceneed/preschooldecision/AssistanceNeedPreschoolDecisionQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/caseprocess/ProcessMetadataQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/document/DocumentTemplate.kt
  service/src/main/kotlin/fi/espoo/evaka/document/DocumentTemplateQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/document/childdocument/AssistanceDecisionMigrationService.kt
  service/src/main/kotlin/fi/espoo/evaka/document/childdocument/ChildDocumentController.kt
  service/src/main/kotlin/fi/espoo/evaka/document/childdocument/ChildDocumentControllerCitizen.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/async/AsyncJob.kt
  service/src/main/resources/db/migration/V557__migrated_assistance_decision_document_types_part_1.sql
  service/src/main/resources/db/migration/V558__migrated_assistance_decision_document_types_part_2.sql
  service/src/main/resources/db/scripts/migrate_assistance_decision_counts.sql
  service/src/main/resources/db/scripts/migrate_daycare_assistance_decisions.sql
  service/src/main/resources/db/scripts/migrate_preschool_assistance_decisions.sql
  service/src/main/resources/document-templates/migrated_daycare_assistance_decision_fi_espoo.template.json
  service/src/main/resources/document-templates/migrated_daycare_assistance_decision_sv_espoo.template.json
  service/src/main/resources/document-templates/migrated_preschool_assistance_decision_fi_espoo.template.json
  service/src/main/resources/document-templates/migrated_preschool_assistance_decision_sv_espoo.template.json
  service/src/main/resources/migrations.txt
Labels: tech

#7846 Uudelleennimetään tuen raportit
  frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
Labels: enhancement

#7852 Titania syykoodien lisäys
  frontend/src/employee-frontend/components/unit/unit-reservations/StaffAttendanceDetailsModal.tsx
  frontend/src/employee-mobile-frontend/staff-attendance/StaffAttendanceEditPage.tsx
  frontend/src/employee-mobile-frontend/staff-attendance/utils.ts
  frontend/src/lib-common/generated/api-types/attendance.ts
  frontend/src/lib-customizations/defaults/employee-mobile-frontend/i18n/fi.ts
  frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
  frontend/src/lib-customizations/espoo/featureFlags.tsx
  frontend/src/lib-customizations/types.d.ts
  service/src/integrationTest/kotlin/fi/espoo/evaka/occupancy/OccupancyTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/titania/TitaniaServiceTest.kt
  service/src/main/kotlin/fi/espoo/evaka/attendance/MobileRealtimeStaffAttendanceController.kt
  service/src/main/kotlin/fi/espoo/evaka/attendance/StaffAttendance.kt
  service/src/main/kotlin/fi/espoo/evaka/linkity/LinkityService.kt
  service/src/main/kotlin/fi/espoo/evaka/titania/TitaniaService.kt
  service/src/main/resources/db/migration/V560__new_staff_attendance_types.sql
  service/src/main/resources/migrations.txt
Labels: enhancement

#7812 Lisätään tuen tarpeet ja tukitoimet raportille näytettävien tukitoimien valitsin
  frontend/src/e2e-test/pages/employee/reports.ts
  frontend/src/e2e-test/specs/5_employee/assistance-need-and-actions-report.spec.ts
  frontend/src/employee-frontend/components/reports/AssistanceNeedsAndActions.tsx
  frontend/src/employee-frontend/generated/api-clients/reports.ts
  frontend/src/lib-common/generated/api-types/reports.ts
  service/src/main/kotlin/fi/espoo/evaka/reports/AssistanceNeedsAndActionsReportController.kt
Labels: enhancement

#7876 Päivitetään logback versioon 1.5.19
  service/evaka-bom/build.gradle.kts
Labels: enhancement

#7803 Lisätään yöllinen ajo poistuneen vuorohoidon tarpeen jälkeiseen varausten siivoamiseen tulevaisuudesta
  service/src/integrationTest/kotlin/fi/espoo/evaka/shared/job/ScheduledJobsTest.kt
  service/src/main/kotlin/fi/espoo/evaka/reservations/ReservationQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/job/ScheduledJobs.kt
Labels: enhancement

#7874 Hetuttomat lapset raportti: lisätään sarake "Viety Koskeen viimeeksi"
  frontend/src/employee-frontend/components/reports/NonSsnChildren.tsx
  frontend/src/lib-common/generated/api-types/reports.ts
  frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
  service/src/integrationTest/kotlin/fi/espoo/evaka/reports/NonSsnChildrenReportTest.kt
  service/src/main/kotlin/fi/espoo/evaka/reports/NonSsnChildrenReportController.kt
Labels: enhancement

#7856 Lisätty kalenteritapahtumiin mahdollisuus Nekku-aterioiden tilausvähennykseen
  frontend/src/e2e-test/dev-api/fixtures.ts
  frontend/src/e2e-test/generated/api-types.ts
  frontend/src/employee-frontend/components/unit/tab-calendar/CalendarEventsSection.tsx
  frontend/src/employee-frontend/components/unit/tab-calendar/discussion-surveys/survey-editor/DiscussionSurveyForm.tsx
  frontend/src/lib-common/generated/api-types/calendarevent.ts
  frontend/src/lib-common/generated/api-types/nekku.ts
  frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
  service/src/integrationTest/kotlin/fi/espoo/evaka/calendarevent/CalendarEventServiceIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/nekku/NekkuIntegrationTestData.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/nekku/NekkuIntegrationTestUtils.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/nekku/NekkuOrderIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/nekku/NekkuQueryIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/nekku/NekkuSyncIntegrationTest.kt
  service/src/main/kotlin/fi/espoo/evaka/calendarevent/CalendarEvent.kt
  service/src/main/kotlin/fi/espoo/evaka/calendarevent/CalendarEventQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/nekku/NekkuClient.kt
  service/src/main/kotlin/fi/espoo/evaka/nekku/NekkuQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/nekku/NekkuService.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/dev/DataInitializers.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/dev/DevApi.kt
  service/src/main/resources/db/migration/V562__calendar_event_nekku_unordered_meals.sql
  service/src/main/resources/migrations.txt
Labels: enhancement
