Repository espoon-voltti/evaka, pull requests merged in 2025-08, with the labels that each got.

#7524 Muutetaan esiopetushakemus hyväksymään opetustauot aloituspäivämääräksi
  frontend/src/citizen-frontend/applications/editor/ApplicationEditor.tsx
  frontend/src/e2e-test/specs/0_citizen/citizen-club-application.spec.ts
  frontend/src/e2e-test/specs/0_citizen/citizen-preschool-application.spec.ts
  service/src/integrationTest/kotlin/fi/espoo/evaka/application/ApplicationUpdateIntegrationTest.kt
  service/src/main/kotlin/fi/espoo/evaka/application/ApplicationStateService.kt
Labels: enhancement

#7523 Korjataan palvelusetelikertoimen automaattikatkaisu
  service/src/integrationTest/kotlin/fi/espoo/evaka/assistanceneed/AssistanceNeedVoucherCoefficientEndOutdatedTest.kt
  service/src/main/kotlin/fi/espoo/evaka/assistanceneed/vouchercoefficient/AssistanceNeedVoucherCoefficientQueries.kt
Labels: bug

#7531 Lisätään tarkistus lapsen asiakirjoille ei-aktiivisten henkilöiden poistamiseen
  service/src/integrationTest/kotlin/fi/espoo/evaka/pis/InactivePeopleCleanupIntegrationTest.kt
  service/src/main/kotlin/fi/espoo/evaka/pis/InactivePeopleCleanup.kt
Labels: bug

#7535 Keep Font Awesome icons at version 6.x
  .github/renovate.json5
  frontend/package.json
  frontend/yarn.lock
Labels: dependencies

#7527 Näytetään englanninkieliset asiakirjapohjat yksikön kielestä riippumatta
  frontend/src/e2e-test/specs/5_employee/child-documents.spec.ts
  service/src/main/kotlin/fi/espoo/evaka/document/DocumentTemplateController.kt
Labels: enhancement

#7536 Muutetaan kuntalaisen 'täytä asiakirja' linkki avaamaan asiakirja muokkaustilassa
  frontend/src/citizen-frontend/calendar/CalendarNotifications.tsx
  frontend/src/citizen-frontend/child-documents/ChildDocumentPage.tsx
  frontend/src/e2e-test/specs/0_citizen/citizen-child-documents.spec.ts
Labels: enhancement

#7541 Muutetaan tuntiperusteisten varausten päivittäiskeskiarvolaskenta pyöristämään alaspäin
  service/src/integrationTest/kotlin/fi/espoo/evaka/reservations/ReservationControllerCitizenIntegrationTest.kt
  service/src/main/kotlin/fi/espoo/evaka/reservations/Reservations.kt
  service/src/test/kotlin/fi/espoo/evaka/reservations/UsedServiceTests.kt
Labels: bug

#7537 Mahdollistetaan käyttäjän kevytkirjautumisen deaktivointi kannan tasolla
  service/src/main/resources/db/migration/V547__relax_weak_credentials_check.sql
  service/src/main/resources/migrations.txt
Labels: tech

#7573 Otetaan yksittäisen asiakirjan arkistointi käyttöön myös tuotannossa
  frontend/src/lib-customizations/espoo/featureFlags.tsx
Labels: enhancement

#7530 Ajetaan apigw ilman TypeScript-käännöstä
  apigw/.gitignore
  apigw/Dockerfile
  apigw/entrypoint.sh
  apigw/eslint.config.js
  apigw/package.json
  apigw/src/app.ts
  apigw/src/enduser/__tests__/csrf.ts
  apigw/src/enduser/dev-sfi-auth.ts
  apigw/src/enduser/mapRoutes.ts
  apigw/src/enduser/routes/auth-status.ts
  apigw/src/enduser/routes/auth-weak-login.ts
  apigw/src/enduser/suomi-fi-saml.ts
  apigw/src/index.ts
  apigw/src/internal/__tests__/csrf.ts
  apigw/src/internal/__tests__/mobile-device-session.ts
  apigw/src/internal/ad-saml.ts
  apigw/src/internal/dev-ad-auth.ts
  apigw/src/internal/dev-sfi-auth.ts
  apigw/src/internal/mobile-device-session.ts
  apigw/src/internal/routes/auth-status.ts
  apigw/src/pino-cli/__tests__/cli/bin.ts
  apigw/src/pino-cli/cli/bin.ts
  apigw/src/pino-cli/cli/index.ts
  apigw/src/pino-cli/test-utils/fixtures/log-messages.ts
  apigw/src/pino-cli/tsconfig.json
  apigw/src/shared/__tests__/logging.ts
  apigw/src/shared/__tests__/node-saml-cache-redis.ts
  apigw/src/shared/__tests__/parse-url-with-origin.ts
  apigw/src/shared/__tests__/saml-certificates-test.ts
  apigw/src/shared/__tests__/saml-slo.ts
  apigw/src/shared/auth/dev-auth.ts
  apigw/src/shared/auth/index.ts
  apigw/src/shared/auth/jwt.ts
  apigw/src/shared/config.ts
  apigw/src/shared/dev-api.ts
  apigw/src/shared/express.ts
  apigw/src/shared/logging.ts
  apigw/src/shared/middleware/cache-control.ts
  apigw/src/shared/middleware/csrf.ts
  apigw/src/shared/middleware/error-handler.ts
  apigw/src/shared/middleware/tracing.ts
  apigw/src/shared/proxy-utils.ts
  apigw/src/shared/routes/csp.ts
  apigw/src/shared/routes/saml.ts
  apigw/src/shared/saml/error-utils.ts
  apigw/src/shared/saml/index.ts
  apigw/src/shared/saml/node-saml-cache-redis.ts
  apigw/src/shared/service-client.ts
  apigw/src/shared/session.ts
  apigw/src/shared/test/gateway-tester.ts
  apigw/src/shared/test/mock-redis-client.ts
  apigw/src/shared/types.d.ts
  apigw/src/tracer.ts
  apigw/src/tsconfig.json
  apigw/tsconfig.json
  apigw/yarn.lock
Labels: tech

#7570 Kiinnitetään kuntalaisen lomakkeiden napit sivun alareunaan scrollatessa
  frontend/src/citizen-frontend/applications/editor/ApplicationEditor.tsx
  frontend/src/citizen-frontend/child-documents/ChildDocumentPage.tsx
  frontend/src/citizen-frontend/income-statements/ChildIncomeStatementForm.tsx
  frontend/src/citizen-frontend/income-statements/IncomeStatementForm.tsx
  frontend/src/e2e-test/pages/citizen/citizen-applications.ts
  frontend/src/e2e-test/pages/citizen/citizen-income.ts
  frontend/src/e2e-test/specs/0_citizen/citizen-child-income-statement.spec.ts
  frontend/src/lib-customizations/espoo/citizen.tsx
Labels: enhancement

#7578 Pedagogiset asiakirjat raportille ei kuulu valita mm. kuntalaisen täytettäviä asiakirjoja
  service/src/main/kotlin/fi/espoo/evaka/reports/ChildDocumentsReport.kt
Labels: enhancement

#7581 Poistetaan mahdollisesti arkaluontoiset tiedot eskarin poissaolohakemuksen ilmoitussähköpostista
  service/src/integrationTest/kotlin/fi/espoo/evaka/absence/AbsenceApplicationControllersTest.kt
  service/src/main/kotlin/fi/espoo/evaka/emailclient/EvakaEmailMessageProvider.kt
Labels: enhancement

#7582 Poistetaan väärä tieto ServiceApplication feature flagista
  frontend/src/lib-customizations/types.d.ts
Labels: bug

#7609 Paremmat dokumenttipohjan otsikot
  apigw/README.md
  apigw/package.json
  frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
  service/evaka-bom/build.gradle.kts
Labels: enhancement

#7607 Tallennetaan sijoituksen lisääjä ja sekä lisäämisen syy
  frontend/src/e2e-test/dev-api/fixtures.ts
  frontend/src/e2e-test/generated/api-types.ts
  frontend/src/e2e-test/specs/0_citizen/citizen-child-page.spec.ts
  frontend/src/e2e-test/specs/0_citizen/citizen-daycare-application.spec.ts
  service/src/integrationTest/kotlin/fi/espoo/evaka/application/ApplicationStateServiceIntegrationTests.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/holidayperiod/HolidayPeriodControllerCitizenIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/FeeDecisionIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/placement/FiveYearOldDaycarePlacementsIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/placement/PlacementControllerCitizenIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/placement/PlacementControllerIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/placement/PlacementServiceIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/serviceneed/application/ServiceApplicationIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/shared/db/SchemaConventionsTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/shared/job/ScheduledJobsTest.kt
  service/src/main/kotlin/fi/espoo/evaka/espoo/bi/EspooBi.kt
  service/src/main/kotlin/fi/espoo/evaka/occupancy/Occupancy.kt
  service/src/main/kotlin/fi/espoo/evaka/occupancy/OccupancyController.kt
  service/src/main/kotlin/fi/espoo/evaka/placement/Placement.kt
  service/src/main/kotlin/fi/espoo/evaka/placement/PlacementController.kt
  service/src/main/kotlin/fi/espoo/evaka/placement/PlacementPlan.kt
  service/src/main/kotlin/fi/espoo/evaka/placement/PlacementPlanService.kt
  service/src/main/kotlin/fi/espoo/evaka/placement/PlacementQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/placement/PlacementService.kt
  service/src/main/kotlin/fi/espoo/evaka/placement/PlacementTermination.kt
  service/src/main/kotlin/fi/espoo/evaka/reservations/ReservationQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/serviceneed/application/ServiceApplicationController.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/dev/DataInitializers.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/dev/DevApi.kt
  service/src/main/resources/db/migration/V548__placement_created_by_source_etc.sql
  service/src/main/resources/db/migration/V549__placement_indexes.sql
  service/src/main/resources/migrations.txt
Labels: tech

#7610 Esiopetuksen tuen taso: Lapsikohtainen tuki ja pidennetty oppivelvollisuus
  frontend/src/employee-frontend/components/child-information/assistance/PreschoolAssistanceForm.tsx
  frontend/src/employee-frontend/components/reports/AssistanceNeedsAndActions.tsx
  frontend/src/lib-common/generated/api-types/assistance.ts
  frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
  service/src/main/kotlin/fi/espoo/evaka/assistance/Assistance.kt
  service/src/main/kotlin/fi/espoo/evaka/koski/KoskiData.kt
  service/src/main/resources/db/migration/R__koski_views.sql
  service/src/main/resources/db/migration/V550__new_preschool_assistance_levels_v2.sql
  service/src/main/resources/migrations.txt
Labels: enhancement

#7616 Huoltajan täytettävät asiakirjat päälle Espoon tuotannossa
  frontend/src/lib-customizations/espoo/featureFlags.tsx
Labels: no-changelog

#7576 Ilmoita läsnäolo -modaalin saavutettavuusparannuksia
  frontend/src/citizen-frontend/applications/editor/unit-preference/UnitsSubSection.tsx
  frontend/src/citizen-frontend/calendar/hooks.ts
  frontend/src/citizen-frontend/calendar/reservation-modal/TimeInputs.tsx
  frontend/src/lib-customizations/defaults/citizen/i18n/en.tsx
  frontend/src/lib-customizations/defaults/citizen/i18n/fi.tsx
  frontend/src/lib-customizations/defaults/citizen/i18n/sv.tsx
Labels: enhancement

#7617 Lisätään animaatio kuntalaisen mobiilin "Uusi viesti" nappiin
  frontend/src/citizen-frontend/calendar/CalendarListView.tsx
  frontend/src/citizen-frontend/messages/ThreadList.tsx
  frontend/src/lib-components/atoms/buttons/button-commons.tsx
Labels: enhancement

#7612 Lisätään yksikkökohtainen Nekun tilausvähennysprosentti
  frontend/src/e2e-test/dev-api/fixtures.ts
  frontend/src/e2e-test/generated/api-types.ts
  frontend/src/employee-frontend/components/unit/unit-details/UnitEditor.tsx
  frontend/src/lib-common/generated/api-types/daycare.ts
  frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
  service/src/integrationTest/kotlin/fi/espoo/evaka/daycare/DaycareEditIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/daycare/controllers/DaycareControllerIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/nekku/NekkuOrderIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/nekku/NekkuQueryIntegrationTest.kt
  service/src/main/kotlin/fi/espoo/evaka/daycare/CareArea.kt
  service/src/main/kotlin/fi/espoo/evaka/daycare/DaycareQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/nekku/NekkuQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/nekku/NekkuService.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/FeatureConfig.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/dev/DataInitializers.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/dev/DevApi.kt
  service/src/main/resources/db/migration/V551__daycare_nekku_order_reduction_percentage.sql
  service/src/main/resources/migrations.txt
Labels: enhancement

#7608 Asiakirjojen arkistoon vienti erillisessä async job bulk-poolissa
  service/src/main/kotlin/fi/espoo/evaka/shared/async/AsyncJob.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/config/AsyncJobConfig.kt
  service/src/main/resources/db/scripts/archive_closed_child_documents.sql
  service/src/main/resources/db/scripts/archive_closed_child_documents_simple.sql
Labels: tech

#7584 Estetään vanhan mallisten tuen päätösten avaaminen
  frontend/src/employee-frontend/components/child-information/AssistanceNeedDecisionSection.tsx
  frontend/src/employee-frontend/components/child-information/AssistanceNeedPreschoolDecisionSection.tsx
  frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
Labels: breaking

#7650 Poistetaan ylimääräiset versiomääritykset
  service/evaka-bom/build.gradle.kts
Labels: dependencies

#7529 Lisää ruudunlukijan automaattinen kohdistus sivusisältöön kuntalaisen välilehdille
  frontend/src/citizen-frontend/calendar/CalendarMonthView.tsx
  frontend/src/citizen-frontend/calendar/MonthElem.tsx
  frontend/src/citizen-frontend/children/ChildHeader.tsx
  frontend/src/citizen-frontend/messages/ThreadList.tsx
  frontend/src/e2e-test/pages/citizen/citizen-children.ts
  frontend/src/e2e-test/specs/0_citizen/citizen-child-page.spec.ts
Labels: enhancement

#7583 Henkilökunta: Lukemattomien viestien lukumäärä huomioi viestien näkyvyyssäännöt
  service/src/integrationTest/kotlin/fi/espoo/evaka/messaging/MessageIntegrationTest.kt
  service/src/main/kotlin/fi/espoo/evaka/messaging/MessageController.kt
  service/src/main/kotlin/fi/espoo/evaka/messaging/MessageQueries.kt
Labels: bug

#7620 Korjataan puuttuvien poissaolokyselyn vastauksien huomautuset
  frontend/src/e2e-test/specs/5_employee/month-calendar.spec.ts
  service/src/main/kotlin/fi/espoo/evaka/absence/AbsenceService.kt
Labels: bug

#7621 Parannetaan ilmoitusten sijoittamista kuntalaisen käyttöliittymissä
  frontend/src/citizen-frontend/App.tsx
  frontend/src/e2e-test/specs/0_citizen/citizen-discussion-surveys.spec.ts
  frontend/src/lib-components/Notifications.tsx
Labels: enhancement

#7658 Rate limit to max 2 varda requests per second
  service/src/main/kotlin/fi/espoo/evaka/varda/VardaClient.kt
Labels: enhancement

#7659 Päätöksentekopäivämäärä muiden päätösten pdf-tiedostoihin
  service/src/main/kotlin/fi/espoo/evaka/document/childdocument/DocumentHtmlGenerator.kt
Labels: enhancement

#7662 Decrease varda api rate limit and log rate wait
  service/src/main/kotlin/fi/espoo/evaka/EvakaEnv.kt
  service/src/main/kotlin/fi/espoo/evaka/varda/VardaClient.kt
  service/src/main/kotlin/fi/espoo/evaka/varda/VardaUpdateService.kt
  service/src/main/resources/application-local.yaml
Labels: enhancement

#7664 Korjataan lapsen asiakirjan integraatiotestit
  service/src/integrationTest/kotlin/fi/espoo/evaka/document/childdocument/ChildDocumentServiceIntegrationTest.kt
Labels: no-changelog
