Repository espoon-voltti/evaka, pull requests merged in 2025-04, with the labels that each got.

#6595 Modernisoidaan koodia - osa 3
  frontend/src/employee-frontend/components/UnitPage.tsx
  frontend/src/employee-frontend/components/Units.tsx
  frontend/src/employee-frontend/components/applications/ApplicationsFilters.tsx
  frontend/src/employee-frontend/components/child-information/assistance-need/decision/AssistanceNeedPreschoolDecisionEditPage.tsx
  frontend/src/employee-frontend/components/child-information/assistance-need/decision/AssistanceNeededDecisionForm.tsx
  frontend/src/employee-frontend/components/child-information/backup-care/BackupCareForm.tsx
  frontend/src/employee-frontend/components/child-information/placements/CreatePlacementModal.tsx
  frontend/src/employee-frontend/components/child-information/queries.ts
  frontend/src/employee-frontend/components/common/PersonSearch.tsx
  frontend/src/employee-frontend/components/employees/EmployeePage.tsx
  frontend/src/employee-frontend/components/fee-decisions/FeeDecisionFilters.tsx
  frontend/src/employee-frontend/components/income-statements/IncomeStatementFilters.tsx
  frontend/src/employee-frontend/components/invoices/InvoiceFilters.tsx
  frontend/src/employee-frontend/components/payments/PaymentFilters.tsx
  frontend/src/employee-frontend/components/person-profile/PersonDependants.tsx
  frontend/src/employee-frontend/components/person-search/Search.tsx
  frontend/src/employee-frontend/components/person-search/queries.ts
  frontend/src/employee-frontend/components/reports/AssistanceNeedsAndActions.tsx
  frontend/src/employee-frontend/components/reports/AttendanceReservation.tsx
  frontend/src/employee-frontend/components/reports/AttendanceReservationByChild.tsx
  frontend/src/employee-frontend/components/reports/ChildDocumentsReport.tsx
  frontend/src/employee-frontend/components/reports/CustomerFees.tsx
  frontend/src/employee-frontend/components/reports/FamilyContacts.tsx
  frontend/src/employee-frontend/components/reports/HolidayPeriodAttendanceReport.tsx
  frontend/src/employee-frontend/components/reports/MealReport.tsx
  frontend/src/employee-frontend/components/reports/Occupancies.tsx
  frontend/src/employee-frontend/components/reports/PlacementGuarantee.tsx
  frontend/src/employee-frontend/components/reports/PreschoolAbsenceReport.tsx
  frontend/src/employee-frontend/components/reports/VoucherServiceProviders.tsx
  frontend/src/employee-frontend/components/unit/queries.ts
  frontend/src/employee-frontend/components/unit/tab-calendar/CalendarEventsSection.tsx
  frontend/src/employee-frontend/components/unit/tab-calendar/discussion-surveys/DiscussionSurveysPage.tsx
  frontend/src/employee-frontend/components/unit/unit-details/CreateUnitPage.tsx
  frontend/src/employee-frontend/components/unit/unit-details/UnitDetailsPage.tsx
  frontend/src/employee-frontend/components/voucher-value-decisions/VoucherValueDecisionFilters.tsx
  frontend/src/employee-frontend/queries.ts
  frontend/src/employee-frontend/state/application-ui.tsx
  frontend/src/employee-frontend/state/invoicing-ui.tsx
Labels: tech

#6612 Korjaus regressioon talouden kyselyissä
  frontend/src/employee-frontend/state/invoicing-ui.tsx
Labels: bug

#6611 Lisätään kuntalaisen täytettävä lomake
  frontend/src/citizen-frontend/App.tsx
  frontend/src/citizen-frontend/child-documents/ChildDocumentEditPage.tsx
  frontend/src/citizen-frontend/child-documents/ChildDocumentPage.tsx
  frontend/src/citizen-frontend/child-documents/queries.ts
  frontend/src/citizen-frontend/children/sections/ChildDocumentsSection.tsx
  frontend/src/citizen-frontend/generated/api-clients/document.ts
  frontend/src/e2e-test/pages/employee/documents/child-document.ts
  frontend/src/e2e-test/specs/0_citizen/citizen-child-documents.spec.ts
  frontend/src/employee-frontend/components/child-information/ChildDocuments.tsx
  frontend/src/lib-common/generated/api-types/document.ts
  frontend/src/lib-components/document-templates/documents.tsx
  frontend/src/lib-components/document-templates/question-descriptors/TextQuestionDescriptor.tsx
  frontend/src/lib-components/layout/flex-helpers.ts
  frontend/src/lib-customizations/defaults/citizen/i18n/en.tsx
  frontend/src/lib-customizations/defaults/citizen/i18n/fi.tsx
  frontend/src/lib-customizations/defaults/citizen/i18n/sv.tsx
  frontend/src/lib-customizations/espoo/featureFlags.tsx
  service/src/integrationTest/kotlin/fi/espoo/evaka/document/childdocument/ChildDocumentControllerCitizenIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/document/childdocument/ChildDocumentControllerIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/shared/db/SchemaConventionsTest.kt
  service/src/main/kotlin/fi/espoo/evaka/Audit.kt
  service/src/main/kotlin/fi/espoo/evaka/document/childdocument/ChildDocument.kt
  service/src/main/kotlin/fi/espoo/evaka/document/childdocument/ChildDocumentCitizen.kt
  service/src/main/kotlin/fi/espoo/evaka/document/childdocument/ChildDocumentController.kt
  service/src/main/kotlin/fi/espoo/evaka/document/childdocument/ChildDocumentControllerCitizen.kt
  service/src/main/kotlin/fi/espoo/evaka/document/childdocument/ChildDocumentQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/document/childdocument/ChildDocumentQueriesCitizen.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/security/Action.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/security/actionrule/HasGroupRole.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/security/actionrule/HasUnitRole.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/security/actionrule/IsCitizen.kt
  service/src/main/resources/db/migration/V514__child_document_references_evaka_user.sql
  service/src/main/resources/migrations.txt
Labels: enhancement

#6613 Lisätään testi että täytettävästä lomakkeesta lähtee sähköpostiviesti
  frontend/src/e2e-test/specs/5_employee/child-documents.spec.ts
Labels: tech

#6617 Muutetaan Aromin asiakastunnuksen nimi vastuuyksikkökoodiksi
  frontend/src/employee-frontend/components/reports/Raw.tsx
  frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
Labels: enhancement

#6620 Fix precommit when modifying generated files
  lefthook.yml
Labels: no-changelog

#6604 Konfiguroitava minimilasku
  service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/service/InvoiceGeneratorIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/service/ReplacementInvoicesIntegrationTest.kt
  service/src/main/kotlin/fi/espoo/evaka/invoicing/service/DraftInvoiceGenerator.kt
  service/src/main/kotlin/fi/espoo/evaka/invoicing/service/InvoiceGenerator.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/FeatureConfig.kt
Labels: enhancement

#6584 Codegen kieltää JsonValue-annotoitujen enumien käytön API:n enum-tyypeissä
  service/codegen/src/main/kotlin/evaka/codegen/api/TsRepresentation.kt
  service/codegen/src/test/kotlin/evaka/codegen/api/TsRepresentationTest.kt
Labels: tech

#6586 Tekninen: Linkity-rajapinnan muutosten huomioiminen
  service/src/integrationTest/kotlin/fi/espoo/evaka/linkity/LinkityServiceTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/linkity/MockLinkityClient.kt
  service/src/main/kotlin/fi/espoo/evaka/EspooConfig.kt
  service/src/main/kotlin/fi/espoo/evaka/linkity/Linkity.kt
  service/src/main/kotlin/fi/espoo/evaka/linkity/LinkityClient.kt
  service/src/main/kotlin/fi/espoo/evaka/linkity/LinkityQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/linkity/LinkityService.kt
Labels: tech

#6593 Mahdollistetaan esikoulupäätösten hyväksyntä ilman huoltajan vahvistusta
  frontend/src/citizen-frontend/applications/ChildApplicationsBlock.tsx
  service/src/integrationTest/kotlin/fi/espoo/evaka/application/ApplicationStateServiceIntegrationTests.kt
  service/src/main/kotlin/fi/espoo/evaka/application/ApplicationStateService.kt
  service/src/main/kotlin/fi/espoo/evaka/application/DecisionMessageProcessor.kt
  service/src/main/kotlin/fi/espoo/evaka/decision/DecisionService.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/FeatureConfig.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/async/AsyncJob.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/message/EvakaMessageProvider.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/message/IMessageProvider.kt
Labels: enhancement

#6623 Korjataan hakemuksen ja muistiinpanojen resetoituminen palveluohjaajan vaihtaessa selaimen välilehteä
  frontend/src/employee-frontend/components/application-page/ApplicationNoteBox.tsx
  frontend/src/employee-frontend/components/application-page/ApplicationPage.tsx
Labels: bug

#6626 Lisää tyhjän ennusteen lähettämisen eston ja aikaisimman aloituspäivän rajoitteen Aromi-integraatiolle
  service/src/integrationTest/kotlin/fi/espoo/evaka/aromi/AromiControllerTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/aromi/AromiServiceTest.kt
  service/src/main/kotlin/fi/espoo/evaka/aromi/AromiService.kt
  service/src/test/resources/aromi/simple_case_full.csv
  service/src/test/resources/aromi/simple_case_full.csv.license
  service/src/test/resources/aromi/simple_case_partial.csv
  service/src/test/resources/aromi/simple_case_partial.csv.license
Labels: enhancement

#6624 Estetään loma-ajan kyselyn turha näkyminen kuntalaiselle
  frontend/src/e2e-test/specs/0_citizen/citizen-holiday-reservations.spec.ts
  service/src/integrationTest/kotlin/fi/espoo/evaka/holidayperiod/HolidayPeriodControllerCitizenIntegrationTest.kt
  service/src/main/kotlin/fi/espoo/evaka/holidayperiod/HolidayPeriodControllerCitizen.kt
Labels: bug

#6610 Käytetään enemmän generoituja tyyppejä viestintäkoodissa ja yhtenäistetään nimeämistä
  frontend/src/citizen-frontend/generated/api-clients/messaging.ts
  frontend/src/citizen-frontend/messages/MessageEditor.tsx
  frontend/src/citizen-frontend/messages/MessagesPage.tsx
  frontend/src/citizen-frontend/messages/queries.ts
  frontend/src/e2e-test/pages/employee/messages/messages-page.ts
  frontend/src/e2e-test/pages/mobile/message-editor-page.ts
  frontend/src/e2e-test/specs/6_mobile/messages.spec.ts
  frontend/src/e2e-test/specs/7_messaging/messaging-by-staff.spec.ts
  frontend/src/e2e-test/specs/7_messaging/messaging.spec.ts
  frontend/src/e2e-test/specs/7_messaging/municipal-messaging.spec.ts
  frontend/src/e2e-test/specs/7_messaging/service-worker-messaging.spec.ts
  frontend/src/e2e-test/utils/page.ts
  frontend/src/employee-frontend/components/messages/MessageEditor.tsx
  frontend/src/employee-frontend/components/messages/MessagesPage.tsx
  frontend/src/employee-frontend/components/messages/Sidebar.tsx
  frontend/src/employee-frontend/components/person-profile/PersonFinanceNotesAndMessages.tsx
  frontend/src/employee-frontend/generated/api-clients/messaging.ts
  frontend/src/employee-mobile-frontend/generated/api-clients/messaging.ts
  frontend/src/employee-mobile-frontend/messages/MessageEditor.tsx
  frontend/src/employee-mobile-frontend/messages/MessagesPage.tsx
  frontend/src/employee-mobile-frontend/messages/NewChildMessagePage.tsx
  frontend/src/employee-mobile-frontend/messages/NewMessagePage.tsx
  frontend/src/employee-mobile-frontend/messages/queries.ts
  frontend/src/lib-common/api-types/messaging.ts
  frontend/src/lib-common/generated/api-types/messaging.ts
  frontend/src/lib-components/messages/SelectorNode.ts
  frontend/src/lib-customizations/defaults/employee-mobile-frontend/i18n/fi.ts
  frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
  service/codegen/src/main/kotlin/evaka/codegen/api/Config.kt
  service/codegen/src/main/kotlin/evaka/codegen/api/TsCodeGenerator.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/messaging/DraftQueriesTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/messaging/MessageIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/messaging/MessageNotificationEmailServiceIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/messaging/MessagePushNotificationsTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/messaging/MessageQueriesTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/messaging/MessageRecipientsIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/pis/service/MergeServiceIntegrationTest.kt
  service/src/main/kotlin/fi/espoo/evaka/application/ApplicationStateService.kt
  service/src/main/kotlin/fi/espoo/evaka/messaging/DraftContent.kt
  service/src/main/kotlin/fi/espoo/evaka/messaging/DraftQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/messaging/Message.kt
  service/src/main/kotlin/fi/espoo/evaka/messaging/MessageController.kt
  service/src/main/kotlin/fi/espoo/evaka/messaging/MessageControllerCitizen.kt
  service/src/main/kotlin/fi/espoo/evaka/messaging/MessageQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/messaging/MessageService.kt
Labels: tech

#6616 Lisätään lomakepohjille englannin kielen tuki
  frontend/src/e2e-test/generated/api-types.ts
  frontend/src/employee-frontend/components/document-templates/template-editor/TemplateContentEditor.tsx
  frontend/src/employee-frontend/components/document-templates/template-editor/TemplateModal.tsx
  frontend/src/lib-common/generated/api-types/document.ts
  frontend/src/lib-common/generated/api-types/shared.ts
  frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
  service/src/integrationTest/kotlin/fi/espoo/evaka/document/DocumentTemplateIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/pdfgen/PdfGeneratorTest.kt
  service/src/main/kotlin/fi/espoo/evaka/document/DocumentTemplate.kt
  service/src/main/kotlin/fi/espoo/evaka/document/childdocument/DocumentHtmlGenerator.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/dev/DevApi.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/domain/Languages.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/domain/UiLanguage.kt
  service/src/main/resources/db/migration/V515__document_template_language_en.sql
  service/src/main/resources/migrations.txt
  service/src/test/kotlin/fi/espoo/evaka/document/archival/ArchiveChildDocumentServiceTest.kt
Labels: enhancement

#6633 Tekninen: Estetään Linkity-jobien retryt testausvaiheen ajaksi
  service/src/main/kotlin/fi/espoo/evaka/espoo/EspooScheduledJobs.kt
Labels: tech

#6635 Lisätään lokitusta Aromi-integraatioon
  service/src/main/kotlin/fi/espoo/evaka/aromi/AromiService.kt
Labels: enhancement

#6606 Palveluohjaaja voi siirtää aloitusta ottaessa esiopetuspaikan vastaan huoltajan puolesta
  service/src/main/kotlin/fi/espoo/evaka/application/ApplicationControllerCitizen.kt
  service/src/main/kotlin/fi/espoo/evaka/application/ApplicationStateService.kt
  service/src/main/kotlin/fi/espoo/evaka/decision/Decision.kt
Labels: enhancement

#6619 Modernisoidaan koodia - osa 4
  frontend/src/e2e-test/pages/employee/child-information.ts
  frontend/src/employee-frontend/App.tsx
  frontend/src/employee-frontend/components/child-information/FamilyContacts.tsx
  frontend/src/employee-frontend/components/child-information/Guardians.tsx
  frontend/src/employee-frontend/components/child-information/PedagogicalDocumentRow.tsx
  frontend/src/employee-frontend/components/child-information/PedagogicalDocuments.tsx
  frontend/src/employee-frontend/components/child-information/queries.ts
  frontend/src/employee-frontend/components/personal-mobile-devices/PersonalMobileDevicesPage.tsx
Labels: tech

#6648 Bump dependency-check-gradle from v12.1.0 to v12.1.1
  service/gradle/libs.versions.toml
Labels: dependencies

#6615 Poistetaan käyttämättömät taulut language_emphasis and application_form
  service/src/integrationTest/kotlin/fi/espoo/evaka/shared/db/SchemaConventionsTest.kt
  service/src/main/kotlin/fi/espoo/evaka/reports/FuturePreschoolersReport.kt
  service/src/main/kotlin/fi/espoo/evaka/varda/VardaUnits.kt
  service/src/main/resources/db/migration/V516__drop_unused_tables.sql
  service/src/main/resources/dev-data/dev-data.sql
  service/src/main/resources/migrations.txt
  service/src/test/kotlin/fi/espoo/evaka/varda/VardaUnitModelTest.kt
Labels: tech

#6629 Viestinnän SQL-queryjen optimointia
  service/src/main/kotlin/fi/espoo/evaka/messaging/MessageQueries.kt
Labels: tech

#6647 Korjaus kuntalaiselle näkyvään hakemuksen tilaan
  service/src/main/kotlin/fi/espoo/evaka/application/ApplicationControllerCitizen.kt
Labels: bug

#6630 Korjataan ryhmää odottavien lasten ikäsarake
  frontend/src/employee-frontend/components/unit/tab-groups/MissingGroupPlacements.tsx
Labels: enhancement

#6634 Tuloselvityksen tekstimuutos
  frontend/src/lib-customizations/defaults/citizen/i18n/en.tsx
  frontend/src/lib-customizations/defaults/citizen/i18n/fi.tsx
  frontend/src/lib-customizations/defaults/citizen/i18n/sv.tsx
Labels: enhancement

#6622 Korjataan kuntalaisen täytettävän lomakkeen luonnoksen näkyvyys
  frontend/src/citizen-frontend/App.tsx
  frontend/src/citizen-frontend/child-documents/ChildDocumentEditPage.tsx
  frontend/src/citizen-frontend/child-documents/ChildDocumentPage.tsx
  frontend/src/citizen-frontend/child-documents/queries.ts
  frontend/src/citizen-frontend/generated/api-clients/document.ts
  frontend/src/e2e-test/specs/0_citizen/citizen-child-documents.spec.ts
  frontend/src/lib-common/generated/api-types/document.ts
  frontend/src/lib-customizations/defaults/citizen/i18n/en.tsx
  frontend/src/lib-customizations/defaults/citizen/i18n/fi.tsx
  frontend/src/lib-customizations/defaults/citizen/i18n/sv.tsx
  service/src/integrationTest/kotlin/fi/espoo/evaka/document/childdocument/ChildDocumentControllerCitizenIntegrationTest.kt
  service/src/main/kotlin/fi/espoo/evaka/Audit.kt
  service/src/main/kotlin/fi/espoo/evaka/document/childdocument/ChildDocumentControllerCitizen.kt
  service/src/main/kotlin/fi/espoo/evaka/document/childdocument/ChildDocumentQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/dev/DevApi.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/security/Action.kt
Labels: enhancement

#6628 Lisätään yksikköraportille yksikön laskennallinen kapasiteetti
  frontend/src/employee-frontend/components/reports/Units.tsx
  frontend/src/lib-common/generated/api-types/reports.ts
  frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
  service/src/main/kotlin/fi/espoo/evaka/reports/UnitsReport.kt
Labels: enhancement

#6649 Korjataan ryhmää odottavien lasten ikäsarake (v2)
  frontend/src/employee-frontend/components/unit/tab-groups/MissingGroupPlacements.tsx
Labels: enhancement

#6609 Laskujen uudelleenlähetys
  frontend/src/e2e-test/pages/employee/finance/finance-page.ts
  frontend/src/e2e-test/specs/4_finance/invoices.spec.ts
  frontend/src/employee-frontend/components/invoices/Actions.tsx
  frontend/src/employee-frontend/components/invoices/InvoiceFilters.tsx
  frontend/src/employee-frontend/components/invoices/InvoicesPage.tsx
  frontend/src/employee-frontend/components/invoices/queries.ts
  frontend/src/employee-frontend/generated/api-clients/invoicing.ts
  frontend/src/lib-common/generated/action.d.ts
  frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
  service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/InvoiceIntegrationTest.kt
  service/src/main/kotlin/fi/espoo/evaka/Audit.kt
  service/src/main/kotlin/fi/espoo/evaka/invoicing/controller/InvoiceController.kt
  service/src/main/kotlin/fi/espoo/evaka/invoicing/data/InvoiceQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/invoicing/service/InvoiceService.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/security/Action.kt
Labels: enhancement

#6653 Korjataan asiakirjan monivalinnan vastausten järjestys
  frontend/src/e2e-test/pages/employee/documents/child-document.ts
  frontend/src/e2e-test/specs/5_employee/child-documents.spec.ts
  frontend/src/lib-components/document-templates/question-descriptors/CheckboxGroupQuestionDescriptor.tsx
Labels: enhancement

#6654 Clean up frontend and apigw dependencies
  apigw/package.json
  frontend/package.json
  frontend/yarn.lock
Labels: dependencies

#6652 Lisätään lapsen tietoihin Nekku-integraation ei syö aamiaista -tiedon syöttö
  frontend/src/employee-frontend/components/child-information/person-details/AdditionalInformation.tsx
  frontend/src/lib-common/generated/api-types/daycare.ts
  frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
  service/src/main/kotlin/fi/espoo/evaka/daycare/ChildQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/daycare/controllers/ChildController.kt
  service/src/main/resources/db/migration/V517__nekku_eats_breakfast.sql
  service/src/main/resources/migrations.txt
Labels: enhancement

#6614 Lisätään kuntalaiselle mahdollisuus ladata keskusteluaikavaraus ulkopuoliseen kalenteriin
  frontend/package.json
  frontend/src/citizen-frontend/calendar/DayView.tsx
  frontend/src/citizen-frontend/calendar/DiscussionTimeExportButton.tsx
  frontend/src/citizen-frontend/calendar/discussion-reservation-modal/DiscussionSurveyModal.tsx
  frontend/src/e2e-test/pages/citizen/citizen-calendar.ts
  frontend/src/e2e-test/pages/citizen/citizen-discussion-surveys.ts
  frontend/src/e2e-test/specs/0_citizen/citizen-discussion-surveys.spec.ts
  frontend/src/lib-customizations/defaults/citizen/i18n/en.tsx
  frontend/src/lib-customizations/defaults/citizen/i18n/fi.tsx
  frontend/src/lib-customizations/defaults/citizen/i18n/sv.tsx
  frontend/yarn.lock
Labels: enhancement

#6655 Siivotaan käyttämättömiä endpointteja
  apigw/src/app.ts
  service/src/main/kotlin/fi/espoo/evaka/messaging/MessageController.kt
  service/src/main/kotlin/fi/espoo/evaka/messaging/MessageControllerCitizen.kt
Labels: tech

#6661 Sallitaan pieni kellopoikkeama dummy-idp:lle lokaalissa kehityksessä
  apigw/src/shared/__tests__/saml-slo.ts
  apigw/src/shared/config.ts
  apigw/src/shared/saml/index.ts
Labels: tech

#6650 Piilotetaan kuntalaisen lasten tulotieto-osio jos lapsia ei ole
  frontend/src/citizen-frontend/income-statements/ChildrenIncomeStatements.tsx
  frontend/src/citizen-frontend/income-statements/IncomeStatements.tsx
  frontend/src/lib-customizations/defaults/citizen/i18n/en.tsx
  frontend/src/lib-customizations/defaults/citizen/i18n/fi.tsx
  frontend/src/lib-customizations/defaults/citizen/i18n/sv.tsx
Labels: enhancement

#6663 Palautetaan henkilökunnan AD-kirjautumisen tarvitsema URL rewrite
  apigw/src/app.ts
Labels: tech

#6671 renovate: Use addLabels
  .github/renovate.json5
Labels: no-changelog

#6673 renovate: Disable semantic commits
  .github/renovate.json5
Labels: no-changelog

#6674 renovate: Fix globs
  .github/renovate.json5
Labels: no-changelog

#6667 Korjaa e2e laskutestin
  frontend/src/e2e-test/pages/employee/finance/finance-page.ts
Labels: no-changelog

#6675 renovate: Fix devDependencies matching
  .github/renovate.json5
Labels: no-changelog

#6625 Luo 1 viikon ruokatilaukset eVakasta Nekkuun
  frontend/src/e2e-test/dev-api/fixtures.ts
  frontend/src/e2e-test/generated/api-types.ts
  frontend/src/e2e-test/specs/7_messaging/messaging.spec.ts
  service/src/integrationTest/kotlin/fi/espoo/evaka/nekku/NekkuIntegrationTest.kt
  service/src/main/kotlin/fi/espoo/evaka/nekku/NekkuQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/nekku/NekkuService.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/async/AsyncJob.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/dev/DataInitializers.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/dev/DevApi.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/job/ScheduledJobs.kt
Labels: enhancement

#6618 Luetaan Särmän vastauskoodi oikeasta paikasta
  frontend/src/e2e-test/dev-api/fixtures.ts
  frontend/src/e2e-test/generated/api-types.ts
  frontend/src/e2e-test/specs/0_citizen/citizen-holiday-reservations.spec.ts
  service/build.gradle.kts
  service/evaka-bom/build.gradle.kts
  service/src/integrationTest/kotlin/fi/espoo/evaka/document/archival/ArchiveChildDocumentServiceIntegrationTest.kt
  service/src/main/kotlin/fi/espoo/evaka/document/archival/ArchiveChildDocumentService.kt
  service/src/main/kotlin/fi/espoo/evaka/document/archival/DocumentMetadataUtils.kt
  service/src/main/kotlin/fi/espoo/evaka/document/archival/SärmäHttpClient.kt
  service/src/main/kotlin/fi/espoo/evaka/document/archival/SärmäMockClient.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/dev/DataInitializers.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/dev/DevApi.kt
  service/src/test/kotlin/fi/espoo/evaka/document/archival/ArchiveChildDocumentServiceTest.kt
Labels: enhancement

#6696 Do full builds for renovate PRs and merges
  .github/workflows/build.yml
Labels: no-changelog

#6699 Korjattu e2e-testi laskuille
  frontend/src/e2e-test/pages/employee/finance/finance-page.ts
  frontend/src/e2e-test/specs/4_finance/invoices.spec.ts
Labels: no-changelog

#6692 Korjataan ajohetken päivämäärästä tai kellonajasta riippuvia testejä
  frontend/src/e2e-test/dev-api/fixtures.ts
  frontend/src/e2e-test/generated/api-types.ts
  frontend/src/e2e-test/specs/0_citizen/citizen-pedagogical-documents.spec.ts
  frontend/src/e2e-test/specs/0_citizen/foster-parents.spec.ts
  frontend/src/e2e-test/specs/5_employee/application-transitions.spec.ts
  frontend/src/e2e-test/specs/5_employee/child-information-assistance.spec.ts
  frontend/src/e2e-test/specs/5_employee/pedagogical-document.spec.ts
  service/src/integrationTest/kotlin/fi/espoo/evaka/linkity/LinkityServiceTest.kt
  service/src/main/kotlin/fi/espoo/evaka/pedagogicaldocument/PedagogicalDocumentController.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/dev/DataInitializers.kt
Labels: tech

#6702 Tekninen: Pieniä teknisiä Linkity-parannuksia
  service/src/main/kotlin/fi/espoo/evaka/espoo/EspooScheduledJobs.kt
  service/src/main/kotlin/fi/espoo/evaka/linkity/LinkityClient.kt
  service/src/main/kotlin/fi/espoo/evaka/linkity/LinkityService.kt
Labels: tech

#6678 UI-korjaus lomakepohjaeditoriin
  frontend/src/employee-frontend/components/document-templates/template-editor/TemplateSectionView.tsx
Labels: bug

#6665 Näytetään työvuoron kommentti
  frontend/src/e2e-test/pages/mobile/staff-page.ts
  frontend/src/e2e-test/specs/6_mobile/realtime-staff-attendances.spec.ts
  frontend/src/employee-mobile-frontend/staff-attendance/StaffAttendancesPage.tsx
  frontend/src/employee-mobile-frontend/staff-attendance/StaffMemberPage.tsx
  frontend/src/employee-mobile-frontend/staff-attendance/StaffMemberPlannedAttendancesPage.tsx
  frontend/src/lib-common/generated/api-types/attendance.ts
  service/src/main/kotlin/fi/espoo/evaka/attendance/StaffAttendance.kt
  service/src/main/kotlin/fi/espoo/evaka/attendance/StaffAttendanceQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/dev/DataInitializers.kt
Labels: enhancement

#6683 Luodaan joka päivä tarkennetut Nekku-tilaukset seuraavalle päivälle
  service/src/integrationTest/kotlin/fi/espoo/evaka/nekku/NekkuIntegrationTest.kt
  service/src/main/kotlin/fi/espoo/evaka/nekku/NekkuService.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/async/AsyncJob.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/job/ScheduledJobs.kt
Labels: enhancement

#6695 Lisätään filttereitä lomakepohjat sivulle
  frontend/src/employee-frontend/components/document-templates/template-editor/DocumentTemplatesPage.tsx
  frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
Labels: enhancement

#6708 Lisätään constraintteja child_document tauluun
  service/src/main/kotlin/fi/espoo/evaka/document/childdocument/ChildDocumentQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/dev/DataInitializers.kt
  service/src/main/resources/db/migration/V518__more_child_document_constraints.sql
  service/src/main/resources/migrations.txt
Labels: tech

#6750 Talouden viestinnän näkymien uudelleenjärjestys
  frontend/src/employee-frontend/components/messages/types-view.ts
Labels: enhancement

#6621 Logitetaan Särmään muodostuneen asiakirjan sisäinen tunniste
  service/src/integrationTest/kotlin/fi/espoo/evaka/document/archival/ArchiveChildDocumentServiceIntegrationTest.kt
  service/src/main/kotlin/fi/espoo/evaka/document/archival/ArchiveChildDocumentService.kt
Labels: enhancement

#6749 Korjataan tuloselvityslistauksen alue-sarakkeen haku
  service/src/integrationTest/kotlin/fi/espoo/evaka/incomestatement/IncomeStatementControllerIntegrationTest.kt
  service/src/main/kotlin/fi/espoo/evaka/incomestatement/IncomeStatementQueries.kt
Labels: bug

#6666 Tampereen seuturaportoinnin "koulun yhteydessä"- filtterin käyttöönotto
  frontend/src/e2e-test/dev-api/fixtures.ts
  frontend/src/e2e-test/generated/api-types.ts
  service/src/integrationTest/kotlin/fi/espoo/evaka/reports/TampereRegionalSurveyTest.kt
  service/src/main/kotlin/fi/espoo/evaka/reports/TampereRegionalSurvey.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/dev/DataInitializers.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/dev/DevApi.kt
Labels: bug

#6711 Varauksen muokkaaminen työntekijän mobiilissa ei muuta koko aikaväliä henkilökunnan merkinnöiksi
  service/src/integrationTest/kotlin/fi/espoo/evaka/reservations/AttendanceReservationsControllerIntegrationTest.kt
  service/src/main/kotlin/fi/espoo/evaka/reservations/AttendanceReservationController.kt
  service/src/main/kotlin/fi/espoo/evaka/reservations/Reservations.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/dev/DataInitializers.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/dev/DevApi.kt
Labels: bug

#6772 Update certificates script README and dependencies
  apigw/config/certificates/Pipfile
  apigw/config/certificates/Pipfile.lock
  apigw/config/certificates/README.md
  apigw/config/certificates/pyproject.toml
Labels: dependencies, apigw

#6754 Korjaus sijoitusehdotusten toimintopalkin vieritykseen
  frontend/src/employee-frontend/components/unit/tab-placement-proposals/PlacementProposals.tsx
Labels: bug

#6662 Käytetään uutta SQL query API:a, osa 5
  service/src/integrationTest/kotlin/fi/espoo/evaka/incomestatement/IncomeStatementControllerIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/shared/db/DbTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/shared/db/JdbiExtensionsTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/shared/db/JdbiReflectionTest.kt
  service/src/main/kotlin/fi/espoo/evaka/incomestatement/IncomeStatementQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/invoicing/data/FeeDecisionQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/invoicing/data/VoucherValueDecisionQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/pis/PersonQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/db/Database.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/db/Search.kt
Labels: tech

#6751 Nekku: Lapsi ei syö aamupalaa vähennykset tilauksesta. Mukaan myös 10 prosentin vähennys normaaleista tilauksista.
  frontend/src/e2e-test/dev-api/fixtures.ts
  frontend/src/e2e-test/generated/api-types.ts
  service/src/integrationTest/kotlin/fi/espoo/evaka/nekku/NekkuIntegrationTest.kt
  service/src/main/kotlin/fi/espoo/evaka/nekku/NekkuQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/nekku/NekkuService.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/FeatureConfig.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/dev/DataInitializers.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/dev/DevApi.kt
Labels: enhancement

#6651 Lisätään kalenterisivulle ilmoitus vastaamattomasta lomakkeesta
  frontend/src/citizen-frontend/calendar/CalendarNotifications.tsx
  frontend/src/citizen-frontend/calendar/queries.ts
  frontend/src/citizen-frontend/child-documents/ChildDocumentPage.tsx
  frontend/src/citizen-frontend/child-documents/queries.ts
  frontend/src/citizen-frontend/children/sections/ChildDocumentsSection.tsx
  frontend/src/citizen-frontend/generated/api-clients/document.ts
  frontend/src/e2e-test/specs/0_citizen/citizen-child-documents.spec.ts
  frontend/src/employee-frontend/components/child-information/ChildDocuments.tsx
  frontend/src/lib-common/generated/api-types/document.ts
  frontend/src/lib-customizations/defaults/citizen/i18n/en.tsx
  frontend/src/lib-customizations/defaults/citizen/i18n/fi.tsx
  frontend/src/lib-customizations/defaults/citizen/i18n/sv.tsx
  frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
  service/src/integrationTest/kotlin/fi/espoo/evaka/document/childdocument/ChildDocumentControllerCitizenIntegrationTest.kt
  service/src/main/kotlin/fi/espoo/evaka/document/childdocument/ChildDocumentCitizen.kt
  service/src/main/kotlin/fi/espoo/evaka/document/childdocument/ChildDocumentControllerCitizen.kt
  service/src/main/kotlin/fi/espoo/evaka/document/childdocument/ChildDocumentQueriesCitizen.kt
Labels: enhancement

#6792 Lisätään hakemukselle tuki muuttaa yksikön valinnan ohjeteksti hakemuksen tyypin mukaan
  frontend/src/citizen-frontend/applications/editor/unit-preference/UnitsSubSection.tsx
  frontend/src/lib-customizations/defaults/citizen/i18n/en.tsx
  frontend/src/lib-customizations/defaults/citizen/i18n/fi.tsx
  frontend/src/lib-customizations/defaults/citizen/i18n/sv.tsx
Labels: enhancement

#6785 Talouden viestin lähettämisen esto hetuttomilta henkilöiltä
  frontend/src/e2e-test/pages/employee/guardian-information.ts
  frontend/src/e2e-test/specs/4_finance/person-finance-notes-and-messages.spec.ts
  frontend/src/employee-frontend/components/person-profile/PersonFinanceNotesAndMessages.tsx
  frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
Labels: enhancement

#6793 Kuntalaiselle menevät lomakkeet -tekstimuutoksia
  frontend/src/citizen-frontend/child-documents/ChildDocumentPage.tsx
  frontend/src/employee-frontend/components/child-documents/ChildDocumentEditor.tsx
  frontend/src/lib-customizations/defaults/citizen/i18n/en.tsx
  frontend/src/lib-customizations/defaults/citizen/i18n/fi.tsx
  frontend/src/lib-customizations/defaults/citizen/i18n/sv.tsx
Labels: enhancement

#6781 Varhaiskasvatuksessa lopettavien lasten raportin laajennus
  frontend/src/e2e-test/pages/employee/reports.ts
  frontend/src/e2e-test/specs/5_employee/ended-placements-report.spec.ts
  frontend/src/employee-frontend/components/reports/EndedPlacements.tsx
  frontend/src/lib-common/generated/api-types/reports.ts
  frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
  service/src/main/kotlin/fi/espoo/evaka/reports/EndedPlacementsReport.kt
Labels: enhancement

#6795 Laskujen uudelleen lähetys on oletuksena estetty ja näytetään selkeämpi varoitus
  frontend/src/employee-frontend/components/invoices/InvoicesPage.tsx
  frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
  frontend/src/lib-customizations/espoo/employee.tsx
  service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/InvoiceIntegrationTest.kt
  service/src/main/kotlin/fi/espoo/evaka/espoo/EspooActionRuleMapping.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/security/Action.kt
Labels: enhancement

#6801 Revert "Update dependency dd-trace to v5.47.0"
  apigw/yarn.lock
Labels: dependencies, apigw

#6798 Korjataan flaky e2e testi
  frontend/src/e2e-test/specs/5_employee/income.spec.ts
Labels: tech

#6802 Change release and dependency update schedules
  .github/renovate.json5
  .github/workflows/release.yml
Labels: no-changelog

#6822 Update renovate config
  .github/renovate.json5
Labels: no-changelog

#6805 Korjaus aloittavien lasten viestintään
  service/src/integrationTest/kotlin/fi/espoo/evaka/messaging/MessageQueriesTest.kt
  service/src/main/kotlin/fi/espoo/evaka/messaging/MessageQueries.kt
Labels: bug

#6804 Estetään kansalaista muokkaamasta kyselyn avulla luotuja poissaoloja
  frontend/src/lib-common/generated/api-types/absence.ts
  frontend/src/lib-common/utils/absences-date-range.spec.ts
  service/src/integrationTest/kotlin/fi/espoo/evaka/reservations/CreateReservationsAndAbsencesTest.kt
  service/src/main/kotlin/fi/espoo/evaka/absence/AbsenceQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/absence/AbsenceService.kt
Labels: enhancement

#6825 Palataan käyttämään s3mock:ia
  REUSE.toml
  compose/docker-compose.e2e.yml
  compose/docker-compose.integration.yml
  compose/docker-compose.yml
  compose/minio-certs/private.key
  compose/minio-certs/public.crt
  service/src/main/resources/application.yaml
Labels: tech

#6827 Korjataan kuntalaisen täytettävän lomakkeen pdf-generointi
  service/src/main/kotlin/fi/espoo/evaka/document/childdocument/ChildDocumentControllerCitizen.kt
Labels: bug

#6794 Lisää sanity checkejä
  service/src/integrationTest/kotlin/fi/espoo/evaka/shared/db/SanityChecksTest.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/db/SanityChecks.kt
Labels: tech

#6826 Nekku muutokset asiakas, tuote ja tilausrajapintoihin
  service/src/integrationTest/kotlin/fi/espoo/evaka/nekku/NekkuIntegrationTest.kt
  service/src/main/kotlin/fi/espoo/evaka/nekku/NekkuQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/nekku/NekkuService.kt
  service/src/main/resources/db/migration/V520__nekku_customer_type_changes.sql
  service/src/main/resources/migrations.txt
Labels: enhancement

#6830 Lisätään asiakasmaksut-raportille suodatus toimintamuodon mukaan
  frontend/src/employee-frontend/components/reports/CustomerFees.tsx
  frontend/src/employee-frontend/generated/api-clients/reports.ts
  frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
  service/src/integrationTest/kotlin/fi/espoo/evaka/reports/CustomerFeesReportTest.kt
  service/src/main/kotlin/fi/espoo/evaka/reports/CustomerFeesReport.kt
Labels: enhancement

#6824 Korjataan yksikköroolin lisääminen itselle
  frontend/src/employee-frontend/components/employees/EmployeePage.tsx
  service/src/main/kotlin/fi/espoo/evaka/daycare/controllers/UnitAclController.kt
  service/src/main/kotlin/fi/espoo/evaka/pis/controllers/EmployeeController.kt
Labels: enhancement

#6799 Lisätään kuntalaiselle mahdollisuus ladata kalenteritapahtuma ulkopuoliseen kalenteriin
  frontend/src/citizen-frontend/calendar/CalendarEventExportButton.tsx
  frontend/src/citizen-frontend/calendar/DayView.tsx
  frontend/src/citizen-frontend/calendar/discussion-reservation-modal/DiscussionSurveyModal.tsx
  frontend/src/e2e-test/pages/citizen/citizen-calendar.ts
  frontend/src/lib-customizations/defaults/citizen/i18n/en.tsx
  frontend/src/lib-customizations/defaults/citizen/i18n/fi.tsx
  frontend/src/lib-customizations/defaults/citizen/i18n/sv.tsx
Labels: enhancement

#6797 Sallitaan lapsen läsnä- ja poissaolotietojen näkyminen henkilökunnalle
  service/src/main/kotlin/fi/espoo/evaka/shared/security/Action.kt
Labels: enhancement

#6831 Lisätään suodattimia lapsen palveluntarpeet ja iät -raportille
  frontend/src/employee-frontend/components/reports/ServiceNeeds.tsx
  frontend/src/employee-frontend/generated/api-clients/reports.ts
  service/src/integrationTest/kotlin/fi/espoo/evaka/reports/ServiceNeedReportTest.kt
  service/src/main/kotlin/fi/espoo/evaka/reports/ServiceNeedReport.kt
Labels: enhancement

#6832 Lisätään testitapaus lomavaraukseen maksuttomalle sijoitustyypille
  frontend/src/e2e-test/specs/0_citizen/citizen-holiday-reservations.spec.ts
Labels: tech

#6632 Päiväkohtaiset lapsen tulo- ja lähtöajat raportin laajennus
  frontend/src/employee-frontend/components/reports/AttendanceReservation.tsx
  frontend/src/employee-frontend/components/reports/AttendanceReservationByChild.tsx
  frontend/src/employee-frontend/components/unit/tab-unit-information/occupancy/OccupancyDayGraphPlanned.tsx
  frontend/src/employee-frontend/generated/api-clients/reports.ts
  frontend/src/lib-common/generated/api-types/reports.ts
  frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
  service/src/integrationTest/kotlin/fi/espoo/evaka/reports/AttendanceReservationReportByChildTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/reports/AttendanceReservationReportTest.kt
  service/src/main/kotlin/fi/espoo/evaka/occupancy/OccupancyController.kt
  service/src/main/kotlin/fi/espoo/evaka/reports/AttendanceReservationReportController.kt
Labels: enhancement

#6833 Korjataan gradle-varoitus
  service/settings.gradle.kts
Labels: tech

#6837 Nekku tuotehaulle lokikorjaus
  service/src/main/kotlin/fi/espoo/evaka/nekku/NekkuQueries.kt
Labels: bug

#6836 Lisätään työntekijätiedot lomakkeen vastaaja-kenttään
  frontend/src/citizen-frontend/children/sections/ChildDocumentsSection.tsx
  frontend/src/e2e-test/specs/0_citizen/citizen-child-documents.spec.ts
  frontend/src/e2e-test/specs/5_employee/child-documents.spec.ts
  frontend/src/lib-customizations/defaults/citizen/i18n/en.tsx
  frontend/src/lib-customizations/defaults/citizen/i18n/fi.tsx
  frontend/src/lib-customizations/defaults/citizen/i18n/sv.tsx
  service/src/integrationTest/kotlin/fi/espoo/evaka/document/childdocument/ChildDocumentControllerCitizenIntegrationTest.kt
  service/src/main/kotlin/fi/espoo/evaka/document/childdocument/ChildDocumentController.kt
  service/src/main/kotlin/fi/espoo/evaka/document/childdocument/ChildDocumentQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/document/childdocument/ChildDocumentQueriesCitizen.kt
Labels: enhancement

#6866 Update depencency flying-saucer to v9.12.0
  service/build.gradle.kts
  service/evaka-bom/build.gradle.kts
  service/gradle/libs.versions.toml
Labels: dependencies, service

#6867 Remove an unnecessary CVE suppression
  service/owasp-suppressions.xml
Labels: dependencies, service

#6828 Lisää asiakirjapohjiin ulkoisen arkistoinnin mahdollistavan flägin
  frontend/src/e2e-test/dev-api/fixtures.ts
  frontend/src/e2e-test/generated/api-types.ts
  frontend/src/e2e-test/pages/employee/documents/document-templates.ts
  frontend/src/e2e-test/specs/5_employee/child-documents.spec.ts
  frontend/src/employee-frontend/components/child-documents/ChildDocumentEditor.tsx
  frontend/src/employee-frontend/components/document-templates/template-editor/TemplateContentEditor.tsx
  frontend/src/employee-frontend/components/document-templates/template-editor/TemplateModal.tsx
  frontend/src/lib-common/generated/api-types/document.ts
  frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
  service/src/integrationTest/kotlin/fi/espoo/evaka/document/DocumentTemplateIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/document/childdocument/ChildDocumentControllerIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/pdfgen/PdfGeneratorTest.kt
  service/src/main/kotlin/fi/espoo/evaka/document/DocumentTemplate.kt
  service/src/main/kotlin/fi/espoo/evaka/document/DocumentTemplateQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/document/archival/ArchiveChildDocumentService.kt
  service/src/main/kotlin/fi/espoo/evaka/document/childdocument/ChildDocumentController.kt
  service/src/main/kotlin/fi/espoo/evaka/document/childdocument/ChildDocumentQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/document/childdocument/ChildDocumentQueriesCitizen.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/dev/DataInitializers.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/dev/DevApi.kt
  service/src/main/resources/db/migration/V521__document_template_archiveable.sql
  service/src/main/resources/migrations.txt
  service/src/test/kotlin/fi/espoo/evaka/document/archival/ArchiveChildDocumentServiceTest.kt
Labels: enhancement

#6868 Lisätään `renderResult`-funktion käyttöä
  frontend/src/citizen-frontend/applications/editor/ApplicationFormDaycare.tsx
  frontend/src/citizen-frontend/applications/editor/ApplicationFormPreschool.tsx
  frontend/src/citizen-frontend/children/sections/service-need-and-daily-service-time/AttendanceSummaryTable.tsx
  frontend/src/citizen-frontend/children/sections/service-need-and-daily-service-time/ServiceNeedAndDailyServiceTimeSection.tsx
  frontend/src/citizen-frontend/map/UnitList.tsx
  frontend/src/employee-frontend/components/Units.tsx
  frontend/src/employee-frontend/components/decision-draft/DecisionDraft.tsx
  frontend/src/employee-frontend/components/fee-decision-details/IncomeSection.tsx
  frontend/src/employee-frontend/components/voucher-value-decision/VoucherValueDecisionIncomeSection.tsx
Labels: tech

#6872 Parannetaan tiedosto-uploadien hallintaa e2e-testeissä
  frontend/src/e2e-test/pages/citizen/citizen-messages.ts
  frontend/src/e2e-test/pages/employee/applications/application-edit-view.ts
  frontend/src/e2e-test/pages/employee/child-information.ts
  frontend/src/e2e-test/pages/employee/guardian-information.ts
  frontend/src/e2e-test/pages/employee/messages/messages-page.ts
  frontend/src/e2e-test/specs/0_citizen/citizen-daycare-application.spec.ts
  frontend/src/e2e-test/specs/5_employee/application-attachments.spec.ts
  frontend/src/e2e-test/specs/5_employee/child-fee-alteration.spec.ts
  frontend/src/e2e-test/specs/5_employee/income.spec.ts
  frontend/src/e2e-test/specs/5_employee/pedagogical-document.spec.ts
  frontend/src/e2e-test/utils/page.ts
  frontend/src/lib-components/molecules/FileUpload.tsx
Labels: tech

#6871 Nekku: Ei tehdä tyhjää tilausta, jos lapsia ei ole ryhmässä.
  service/src/integrationTest/kotlin/fi/espoo/evaka/nekku/NekkuIntegrationTest.kt
  service/src/main/kotlin/fi/espoo/evaka/nekku/NekkuService.kt
Labels: bug

#6838 Korjattu kasvattajan mobiilin parituksen ohjeteksti vastaamaan nykyisen pituista varmistuskoodia
  frontend/src/lib-customizations/defaults/employee-mobile-frontend/i18n/fi.ts
Labels: bug

#6874 Korjataan uusien asiakkaiden tulotietomuistutus kun saman perheen aloittavia lapsia on useita
  service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/service/NewCustomerIncomeNotificationIntegrationTest.kt
  service/src/main/kotlin/fi/espoo/evaka/invoicing/service/IncomeQueries.kt
Labels: bug

#6875 Korvataan redis valkey:llä composessa
  compose/.env
  compose/docker-compose.e2e.yml
  compose/docker-compose.yml
Labels: tech

#6705 Lomakkeet 3.0: Muu päätös
  frontend/src/citizen-frontend/child-documents/ChildDocumentPage.tsx
  frontend/src/citizen-frontend/children/sections/ChildDocumentsSection.tsx
  frontend/src/e2e-test/dev-api/fixtures.ts
  frontend/src/e2e-test/generated/api-types.ts
  frontend/src/e2e-test/pages/employee/child-information.ts
  frontend/src/e2e-test/pages/employee/documents/child-document.ts
  frontend/src/e2e-test/specs/0_citizen/citizen-child-documents.spec.ts
  frontend/src/e2e-test/specs/5_employee/child-documents.spec.ts
  frontend/src/employee-frontend/components/child-documents/ChildDocumentEditor.tsx
  frontend/src/employee-frontend/components/child-documents/statuses.ts
  frontend/src/employee-frontend/components/child-information/ChildDocuments.tsx
  frontend/src/employee-frontend/components/child-information/queries.ts
  frontend/src/employee-frontend/generated/api-clients/document.ts
  frontend/src/lib-common/generated/action.d.ts
  frontend/src/lib-common/generated/api-types/document.ts
  frontend/src/lib-common/generated/api-types/shared.ts
  frontend/src/lib-components/atoms/Chip.tsx
  frontend/src/lib-components/document-templates/ChildDocumentStateChip.tsx
  frontend/src/lib-components/document-templates/documents.tsx
  frontend/src/lib-components/i18n.tsx
  frontend/src/lib-components/utils/TestContextProvider.tsx
  frontend/src/lib-customizations/defaults/citizen/i18n/en.tsx
  frontend/src/lib-customizations/defaults/citizen/i18n/fi.tsx
  frontend/src/lib-customizations/defaults/citizen/i18n/sv.tsx
  frontend/src/lib-customizations/defaults/components/i18n/en.tsx
  frontend/src/lib-customizations/defaults/components/i18n/fi.tsx
  frontend/src/lib-customizations/defaults/components/i18n/sv.tsx
  frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
  frontend/src/lib-customizations/espoo/featureFlags.tsx
  frontend/src/lib-customizations/types.d.ts
  service/src/integrationTest/kotlin/fi/espoo/evaka/document/childdocument/ChildDocumentControllerIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/document/childdocument/ChildDocumentServiceIntegrationTest.kt
  service/src/main/kotlin/fi/espoo/evaka/Audit.kt
  service/src/main/kotlin/fi/espoo/evaka/document/DocumentTemplate.kt
  service/src/main/kotlin/fi/espoo/evaka/document/childdocument/ChildDocument.kt
  service/src/main/kotlin/fi/espoo/evaka/document/childdocument/ChildDocumentCitizen.kt
  service/src/main/kotlin/fi/espoo/evaka/document/childdocument/ChildDocumentController.kt
  service/src/main/kotlin/fi/espoo/evaka/document/childdocument/ChildDocumentControllerCitizen.kt
  service/src/main/kotlin/fi/espoo/evaka/document/childdocument/ChildDocumentQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/document/childdocument/ChildDocumentQueriesCitizen.kt
  service/src/main/kotlin/fi/espoo/evaka/document/childdocument/ChildDocumentService.kt
  service/src/main/kotlin/fi/espoo/evaka/process/ArchivedProcesses.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/Id.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/dev/DataInitializers.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/dev/DevApi.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/security/Action.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/security/actionrule/IsEmployee.kt
  service/src/main/resources/db/migration/V522__other_decision_document_type_changes.sql
  service/src/main/resources/db/migration/V523__other_decision.sql
  service/src/main/resources/migrations.txt
Labels: enhancement

#6869 Päivitetään aromi-integraation käyttöönottopäivä
  service/src/main/kotlin/fi/espoo/evaka/aromi/AromiService.kt
Labels: enhancement

#6878 Korjataan kuntalaisen lomakkeiden duplikaatit
  frontend/src/e2e-test/specs/5_employee/child-documents.spec.ts
  frontend/src/employee-frontend/components/unit/tab-groups/child-documents/CreateChildDocumentsModal.tsx
  frontend/src/employee-frontend/components/unit/tab-groups/child-documents/queries.ts
  frontend/src/employee-frontend/generated/api-clients/document.ts
  service/src/main/kotlin/fi/espoo/evaka/document/childdocument/ChildDocumentController.kt
  service/src/main/kotlin/fi/espoo/evaka/document/childdocument/ChildDocumentQueries.kt
Labels: enhancement
