Repository espoon-voltti/evaka, pull requests merged in 2025-05, with the labels that each got.

#6881 Lisätään poissaolojen tallennukseen testejä
  service/src/integrationTest/kotlin/fi/espoo/evaka/reservations/ReservationControllerCitizenIntegrationTest.kt
Labels: tech

#6877 Lomakkeet 3: Päätösesityksen voi perua / palauttaa korjattavaksi muutkin kuin pääkäyttäjä
  service/src/main/kotlin/fi/espoo/evaka/shared/security/Action.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/security/actionrule/HasUnitRole.kt
Labels: enhancement

#6842 Massaviestinnän lisäfiltteri sijoitustyyppi
  frontend/src/employee-frontend/components/messages/MessageEditor.tsx
  frontend/src/lib-common/generated/api-types/messaging.ts
  frontend/src/lib-common/generated/api-types/placement.ts
  frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
  service/src/integrationTest/kotlin/fi/espoo/evaka/messaging/MessageQueriesTest.kt
  service/src/main/kotlin/fi/espoo/evaka/messaging/MessageController.kt
  service/src/main/kotlin/fi/espoo/evaka/messaging/MessageQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/placement/PlacementType.kt
Labels: enhancement

#6873 Parannuksia tuloselvityslomakkeen puuttuvien tietojen korostukseen
  frontend/src/citizen-frontend/income-statements/IncomeStatementComponents.tsx
  frontend/src/citizen-frontend/income-statements/IncomeStatementEditor.tsx
  frontend/src/citizen-frontend/income-statements/IncomeStatementForm.tsx
  frontend/src/e2e-test/pages/citizen/citizen-income.ts
  frontend/src/e2e-test/specs/0_citizen/citizen-income-statement.spec.ts
  frontend/src/lib-customizations/defaults/citizen/i18n/en.tsx
  frontend/src/lib-customizations/defaults/citizen/i18n/fi.tsx
  frontend/src/lib-customizations/defaults/citizen/i18n/sv.tsx
Labels: enhancement

#6911 Configure renovate to dedupe npm packages
  .github/renovate.json5
  apigw/yarn.lock
  frontend/yarn.lock
Labels: dependencies

#6882 Lisätään Nekku-ruokatilauksiin erikoisruokavaliot
  service/src/integrationTest/kotlin/fi/espoo/evaka/nekku/NekkuIntegrationTest.kt
  service/src/main/kotlin/fi/espoo/evaka/nekku/NekkuQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/nekku/NekkuService.kt
Labels: enhancement

#6913 SFI events -tietokantataulut
  service/src/integrationTest/kotlin/fi/espoo/evaka/pis/PersonIntegrationTest.kt
  service/src/main/resources/db/migration/V524__sfi_events.sql
  service/src/main/resources/migrations.txt
Labels: tech

#6884 Lisätään valmistavan opetuksen lapset esiopetuksen poissaoloraportille
  service/src/integrationTest/kotlin/fi/espoo/evaka/reports/PreschoolAbsenceReportTest.kt
  service/src/main/kotlin/fi/espoo/evaka/reports/PreschoolAbsenceReport.kt
Labels: enhancement

#6914 Korjaus Nekun erityisruokavalioiden kenttätyyppien käsittelyyn
  frontend/src/lib-common/generated/api-types/nekku.ts
  service/src/integrationTest/kotlin/fi/espoo/evaka/nekku/NekkuIntegrationTest.kt
  service/src/main/kotlin/fi/espoo/evaka/nekku/NekkuService.kt
  service/src/main/resources/db/migration/V525__nekku_special_diet_type_additions.sql
  service/src/main/resources/migrations.txt
Labels: bug

#6916 Fix sfi_message_event_type enum values
  service/src/main/resources/db/migration/V526__fix_sfi_message_event_type_enum.sql
  service/src/main/resources/migrations.txt
Labels: bug

#6786 Suomi.fi viestien tapahtumien haku
  frontend/src/e2e-test/generated/api-types.ts
  service/src/integrationTest/kotlin/fi/espoo/evaka/application/ApplicationOtherGuardianIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/application/ApplicationStateServiceIntegrationTests.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/assistanceneed/decision/AssistanceNeedDecisionIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/assistanceneed/decision/AssistanceNeedPreschoolDecisionIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/FeeDecisionIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/VoucherValueDecisionIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/sficlient/rest/SfiMessagesRestClientIntegrationTest.kt
  service/src/main/kotlin/fi/espoo/evaka/assistanceneed/decision/AssistanceNeedDecisionService.kt
  service/src/main/kotlin/fi/espoo/evaka/assistanceneed/preschooldecision/AssistanceNeedPreschoolDecisionService.kt
  service/src/main/kotlin/fi/espoo/evaka/decision/DecisionService.kt
  service/src/main/kotlin/fi/espoo/evaka/invoicing/service/FeeDecisionService.kt
  service/src/main/kotlin/fi/espoo/evaka/invoicing/service/VoucherValueDecisionService.kt
  service/src/main/kotlin/fi/espoo/evaka/sficlient/MockSfiMessagesClient.kt
  service/src/main/kotlin/fi/espoo/evaka/sficlient/SfiAsyncJobs.kt
  service/src/main/kotlin/fi/espoo/evaka/sficlient/SfiMessagesClient.kt
  service/src/main/kotlin/fi/espoo/evaka/sficlient/SfiQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/sficlient/rest/RestSchema.kt
  service/src/main/kotlin/fi/espoo/evaka/sficlient/rest/SfiMessagesRestClient.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/Id.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/dev/DevApi.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/job/ScheduledJobs.kt
Labels: enhancement

#6870 Korjataan maksuttoman poissaolon tyyppi
  service/src/integrationTest/kotlin/fi/espoo/evaka/holidayperiod/HolidayPeriodControllerIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/reservations/CreateReservationsAndAbsencesTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/reservations/ReservationControllerCitizenIntegrationTest.kt
  service/src/main/kotlin/fi/espoo/evaka/absence/AbsenceQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/holidayperiod/HolidayPeriodControllerCitizen.kt
  service/src/main/kotlin/fi/espoo/evaka/reservations/ReservationControllerCitizen.kt
  service/src/main/kotlin/fi/espoo/evaka/reservations/Reservations.kt
Labels: bug

#6885 Dokumenttipohjien validointiparannukset kun ulkoinen arkistointi valittu
  frontend/src/e2e-test/specs/5_employee/child-documents.spec.ts
  frontend/src/employee-frontend/components/document-templates/template-editor/TemplateModal.tsx
  frontend/src/lib-common/generated/api-types/document.ts
  service/src/integrationTest/kotlin/fi/espoo/evaka/document/DocumentTemplateIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/document/archival/ArchiveChildDocumentServiceIntegrationTest.kt
  service/src/main/kotlin/fi/espoo/evaka/document/DocumentTemplate.kt
  service/src/main/kotlin/fi/espoo/evaka/document/archival/ArchiveChildDocumentService.kt
  service/src/main/kotlin/fi/espoo/evaka/document/archival/DocumentMetadataUtils.kt
  service/src/main/kotlin/fi/espoo/evaka/document/childdocument/ChildDocumentQueries.kt
  service/src/main/resources/db/migration/V527__document_template_archive_constraints.sql
  service/src/main/resources/migrations.txt
Labels: enhancement

#6917 Tallennetaan hyvitys/korotusrivin luonti- ja muokkaustiedot
  frontend/src/lib-common/generated/api-types/invoicing.ts
  service/src/integrationTest/kotlin/fi/espoo/evaka/shared/db/SchemaConventionsTest.kt
  service/src/main/kotlin/fi/espoo/evaka/invoicing/controller/InvoiceCorrectionsController.kt
  service/src/main/kotlin/fi/espoo/evaka/invoicing/service/InvoiceCorrection.kt
  service/src/main/kotlin/fi/espoo/evaka/invoicing/service/InvoiceCorrectionQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/invoicing/service/InvoiceService.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/dev/DataInitializers.kt
  service/src/main/resources/db/migration/V528__invoice_correction_modified_metadata.sql
  service/src/main/resources/migrations.txt
Labels: enhancement

#6919 Merkitse viesti lukemattomaksi (työntekijä)
  frontend/src/e2e-test/pages/employee/messages/messages-page.ts
  frontend/src/e2e-test/specs/7_messaging/messaging.spec.ts
  frontend/src/employee-frontend/components/messages/MessageContext.tsx
  frontend/src/employee-frontend/components/messages/SingleThreadView.tsx
  frontend/src/employee-frontend/components/messages/queries.ts
  frontend/src/employee-frontend/generated/api-clients/messaging.ts
  frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
  service/src/integrationTest/kotlin/fi/espoo/evaka/messaging/MessageIntegrationTest.kt
  service/src/main/kotlin/fi/espoo/evaka/messaging/MessageController.kt
Labels: enhancement

#6918 Kielistetyt tilapäiset ilmoitukset kuntalaiselle
  frontend/src/citizen-frontend/generated/api-clients/systemnotifications.ts
  frontend/src/citizen-frontend/login/LoginPage.tsx
  frontend/src/e2e-test/pages/citizen/citizen-header.ts
  frontend/src/e2e-test/pages/employee/SystemNotificationsPage.ts
  frontend/src/e2e-test/specs/5_employee/system-notifications.spec.ts
  frontend/src/employee-frontend/components/system-notifications/SystemNotificationsPage.tsx
  frontend/src/employee-frontend/components/system-notifications/queries.ts
  frontend/src/employee-frontend/generated/api-clients/systemnotifications.ts
  frontend/src/employee-mobile-frontend/generated/api-clients/systemnotifications.ts
  frontend/src/lib-common/generated/api-types/systemnotifications.ts
  frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
  service/src/integrationTest/kotlin/fi/espoo/evaka/systemnotifications/SystemNotificationsControllerIntegrationTest.kt
  service/src/main/kotlin/fi/espoo/evaka/systemnotifications/SystemNotificationsController.kt
  service/src/main/resources/db/migration/V529__citizen_system_notification_i18n.sql
  service/src/main/resources/migrations.txt
Labels: enhancement

#6921 Lisätään e2e-testejä Nekku-erikoisruokavalion käsittelyyn
  frontend/src/e2e-test/dev-api/fixtures.ts
  frontend/src/e2e-test/generated/api-clients.ts
  frontend/src/e2e-test/generated/api-types.ts
  frontend/src/e2e-test/pages/employee/child-information.ts
  frontend/src/e2e-test/specs/5_employee/child-information-nekku.spec.ts
  frontend/src/employee-frontend/components/child-information/person-details/AdditionalInformation.tsx
  frontend/src/employee-frontend/components/child-information/person-details/NekkuSpecialDiet.tsx
  service/src/main/kotlin/fi/espoo/evaka/nekku/NekkuQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/dev/DevApi.kt
Labels: tech

#6924 Nekku-tilaus tehdään vaikka kaikille aterioille ei löytyisi tuotteita
  service/src/integrationTest/kotlin/fi/espoo/evaka/nekku/NekkuIntegrationTest.kt
  service/src/main/kotlin/fi/espoo/evaka/nekku/NekkuService.kt
Labels: bug

#6920 Poistetaan arkistoinnin metadata xml logitus
  service/src/main/kotlin/fi/espoo/evaka/document/archival/ArchiveChildDocumentService.kt
Labels: tech

#6956 Lisää lokitusta ajastuspalveluun
  service/src/main/kotlin/fi/espoo/evaka/EvakaEnv.kt
Labels: tech

#6922 Korjataan päivämäärävalitsimen näyttö modaalien sisällä
  frontend/src/citizen-frontend/App.tsx
  frontend/src/citizen-frontend/children/sections/placement-termination/PlacementTerminationForm.tsx
  frontend/src/e2e-test/pages/employee/units/unit-week-calendar-page.ts
  frontend/src/employee-frontend/App.tsx
  frontend/src/employee-frontend/components/person-profile/PersonFeeDecisions.tsx
  frontend/src/employee-frontend/components/person-profile/PersonVoucherValueDecisions.tsx
  frontend/src/employee-mobile-frontend/App.tsx
  frontend/src/lib-components/molecules/date-picker/DatePickerDay.tsx
  frontend/src/lib-components/molecules/date-picker/DatePickerInput.tsx
  frontend/src/lib-components/molecules/date-picker/DatePickerLowLevel.tsx
Labels: enhancement

#6925 Korjataan asiakirjan salassapidettävyyden näyttäminen
  service/src/integrationTest/kotlin/fi/espoo/evaka/document/childdocument/ChildDocumentControllerCitizenIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/document/childdocument/ChildDocumentControllerIntegrationTest.kt
  service/src/main/kotlin/fi/espoo/evaka/document/childdocument/ChildDocumentQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/document/childdocument/ChildDocumentQueriesCitizen.kt
Labels: bug

#6926 Muu päätös: päätösnumero
  frontend/src/citizen-frontend/child-documents/ChildDocumentPage.tsx
  frontend/src/employee-frontend/components/child-documents/ChildDocumentEditor.tsx
  frontend/src/lib-common/generated/api-types/document.ts
  frontend/src/lib-customizations/defaults/citizen/i18n/en.tsx
  frontend/src/lib-customizations/defaults/citizen/i18n/fi.tsx
  frontend/src/lib-customizations/defaults/citizen/i18n/sv.tsx
  frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
  service/src/integrationTest/kotlin/fi/espoo/evaka/document/childdocument/ChildDocumentControllerIntegrationTest.kt
  service/src/main/kotlin/fi/espoo/evaka/document/childdocument/ChildDocument.kt
  service/src/main/kotlin/fi/espoo/evaka/document/childdocument/ChildDocumentController.kt
  service/src/main/kotlin/fi/espoo/evaka/document/childdocument/ChildDocumentQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/document/childdocument/ChildDocumentQueriesCitizen.kt
  service/src/main/kotlin/fi/espoo/evaka/document/childdocument/DocumentHtmlGenerator.kt
  service/src/main/resources/db/migration/V530__child_document_decision_number.sql
  service/src/main/resources/migrations.txt
Labels: enhancement

#6883 Muut päätökset raportti
  frontend/src/citizen-frontend/child-documents/ChildDocumentPage.tsx
  frontend/src/citizen-frontend/children/sections/ChildDocumentsSection.tsx
  frontend/src/e2e-test/pages/employee/employee-nav.ts
  frontend/src/e2e-test/pages/employee/reports.ts
  frontend/src/e2e-test/specs/5_employee/child-documents.spec.ts
  frontend/src/employee-frontend/App.tsx
  frontend/src/employee-frontend/components/Header.tsx
  frontend/src/employee-frontend/components/Reports.tsx
  frontend/src/employee-frontend/components/child-documents/ChildDocumentEditor.tsx
  frontend/src/employee-frontend/components/child-information/ChildDocuments.tsx
  frontend/src/employee-frontend/components/child-information/queries.ts
  frontend/src/employee-frontend/components/document-templates/template-editor/TemplateModal.tsx
  frontend/src/employee-frontend/components/reports/AssistanceNeedDecisionsReportDecision.tsx
  frontend/src/employee-frontend/components/reports/AssistanceNeedDecisionsReportPreschoolDecision.tsx
  frontend/src/employee-frontend/components/reports/ChildDocumentDecisionsReport.tsx
  frontend/src/employee-frontend/components/reports/ReportNotificationContext.tsx
  frontend/src/employee-frontend/components/reports/queries.ts
  frontend/src/employee-frontend/generated/api-clients/reports.ts
  frontend/src/employee-frontend/queries.ts
  frontend/src/employee-frontend/state/StateProvider.tsx
  frontend/src/lib-common/generated/action.d.ts
  frontend/src/lib-common/generated/api-types/document.ts
  frontend/src/lib-common/generated/api-types/reports.ts
  frontend/src/lib-common/query.ts
  frontend/src/lib-components/atoms/dropdowns/Combobox.tsx
  frontend/src/lib-components/document-templates/ChildDocumentStateChip.tsx
  frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
  frontend/src/lib-customizations/espoo/featureFlags.tsx
  service/src/integrationTest/kotlin/fi/espoo/evaka/document/childdocument/ChildDocumentControllerIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/reports/ChildDocumentDecisionsReportTest.kt
  service/src/main/kotlin/fi/espoo/evaka/Audit.kt
  service/src/main/kotlin/fi/espoo/evaka/document/childdocument/ChildDocument.kt
  service/src/main/kotlin/fi/espoo/evaka/document/childdocument/ChildDocumentQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/document/childdocument/ChildDocumentQueriesCitizen.kt
  service/src/main/kotlin/fi/espoo/evaka/reports/ChildDocumentDecisionsReportController.kt
  service/src/main/kotlin/fi/espoo/evaka/reports/ReportPermissions.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/dev/DevApi.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/security/Action.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/security/actionrule/IsEmployee.kt
Labels: enhancement

#6961 Salassapitoperuste ja -aika kentät dokumenttipohjaeditoriin
  frontend/src/employee-frontend/components/document-templates/template-editor/TemplateContentEditor.tsx
Labels: bug

#6958 Piilotetaan footer tulosteista
  frontend/src/citizen-frontend/Footer.tsx
Labels: bug

#6962 Lähetetään yksikön johtajalle sähköposti jos ryhmän Nekku-asiakasnumero poistuu
  service/src/integrationTest/kotlin/fi/espoo/evaka/nekku/NekkuIntegrationTest.kt
  service/src/main/kotlin/fi/espoo/evaka/nekku/NekkuQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/nekku/NekkuService.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/async/AsyncJob.kt
Labels: enhancement

#6960 Haetaan aikuisen sivun tiedot kun niitä tarvitaan
  frontend/src/employee-frontend/components/person-profile/FosterChildren.tsx
  frontend/src/employee-frontend/components/person-profile/PersonApplications.tsx
  frontend/src/employee-frontend/components/person-profile/PersonDecisions.tsx
  frontend/src/employee-frontend/components/person-profile/PersonDependants.tsx
  frontend/src/employee-frontend/components/person-profile/PersonFamilyOverview.tsx
  frontend/src/employee-frontend/components/person-profile/PersonFeeDecisions.tsx
  frontend/src/employee-frontend/components/person-profile/PersonFinanceNotesAndMessages.tsx
  frontend/src/employee-frontend/components/person-profile/PersonFridgeChild.tsx
  frontend/src/employee-frontend/components/person-profile/PersonFridgePartner.tsx
  frontend/src/employee-frontend/components/person-profile/PersonIncome.tsx
  frontend/src/employee-frontend/components/person-profile/PersonInvoiceCorrections.tsx
  frontend/src/employee-frontend/components/person-profile/PersonInvoices.tsx
  frontend/src/employee-frontend/components/person-profile/PersonProfile.tsx
  frontend/src/employee-frontend/components/person-profile/PersonVoucherValueDecisions.tsx
  frontend/src/employee-frontend/components/person-profile/income/IncomeList.tsx
  frontend/src/employee-frontend/components/person-profile/queries.ts
  frontend/src/employee-frontend/components/person-profile/state.tsx
Labels: tech

#6966 Erotellaan normaalit ja migratoidut dokumenttipohjat toisistaan
  frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
Labels: bug

#6968 Tekninen: testi tulevaisuuden sijoituksia koskeville muistutuksille
  service/src/integrationTest/kotlin/fi/espoo/evaka/reservations/MissingReservationsRemindersTest.kt
Labels: tech

#6965 Muu päätös: suomi.fi viesti
  service/service-lib/src/main/kotlin/fi/espoo/voltti/auth/JwtTokenDecoder.kt
  service/service-lib/src/test/kotlin/fi/espoo/voltti/logging/loggers/AppMiscLoggersTest.kt
  service/service-lib/src/test/kotlin/fi/espoo/voltti/logging/loggers/AuditLoggerTest.kt
  service/service-lib/src/test/kotlin/fi/espoo/voltti/logging/utils/TestAppender.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/document/childdocument/ChildDocumentControllerIntegrationTest.kt
  service/src/main/kotlin/fi/espoo/evaka/document/childdocument/ChildDocumentService.kt
  service/src/main/kotlin/fi/espoo/evaka/sficlient/SfiQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/async/AsyncJob.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/message/EvakaMessageProvider.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/message/IMessageProvider.kt
Labels: enhancement

#6970 React 19
  frontend/.yarn/patches/@fortawesome-react-fontawesome-npm-0.2.2-e1863961b2.patch
  frontend/.yarn/patches/@react-leaflet-core-npm-3.0.0-4e3f2d62b5.patch
  frontend/Dockerfile
  frontend/package.json
  frontend/src/citizen-frontend/calendar/DayElem.tsx
  frontend/src/employee-frontend/components/child-information/assistance/OtherAssistanceMeasureSection.tsx
  frontend/src/employee-frontend/components/common/StickyActionBar.tsx
  frontend/src/employee-frontend/components/reports/AttendanceReservation.tsx
  frontend/src/lib-common/utils/useDebouncedCallback.ts
  frontend/src/lib-common/utils/useInterval.ts
  frontend/src/lib-components/Notifications.tsx
  frontend/src/lib-components/atoms/ExpandableList.tsx
  frontend/src/lib-components/atoms/buttons/LegacyButton.tsx
  frontend/src/lib-components/atoms/dropdowns/Combobox.tsx
  frontend/src/lib-components/molecules/date-picker/DatePickerLowLevel.tsx
  frontend/src/lib-components/molecules/modals/BaseModal.tsx
  frontend/yarn.lock
Labels: dependencies, frontend

#6963 Nekku tilausraportti
  frontend/src/employee-frontend/App.tsx
  frontend/src/employee-frontend/components/Reports.tsx
  frontend/src/employee-frontend/components/reports/NekkuOrders.tsx
  frontend/src/employee-frontend/generated/api-clients/reports.ts
  frontend/src/lib-common/generated/action.d.ts
  frontend/src/lib-common/generated/api-types/reports.ts
  frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
  service/src/integrationTest/kotlin/fi/espoo/evaka/nekku/NekkuIntegrationTest.kt
  service/src/main/kotlin/fi/espoo/evaka/Audit.kt
  service/src/main/kotlin/fi/espoo/evaka/nekku/NekkuQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/nekku/NekkuService.kt
  service/src/main/kotlin/fi/espoo/evaka/reports/NekkuOrderReport.kt
  service/src/main/kotlin/fi/espoo/evaka/reports/ReportPermissions.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/security/Action.kt
  service/src/main/resources/db/migration/V531__nekku_order_report.sql
  service/src/main/resources/migrations.txt
Labels: enhancement

#6955 Lisätään esiopetuksen poissaolohakemukset
  frontend/src/citizen-frontend/App.tsx
  frontend/src/citizen-frontend/children/ChildPage.tsx
  frontend/src/citizen-frontend/children/sections/absence-applications/AbsenceApplicationsSection.tsx
  frontend/src/citizen-frontend/children/sections/absence-applications/NewAbsenceApplicationPage.tsx
  frontend/src/citizen-frontend/children/sections/absence-applications/queries.ts
  frontend/src/citizen-frontend/generated/api-clients/absence.ts
  frontend/src/e2e-test/pages/citizen/citizen-children.ts
  frontend/src/e2e-test/pages/citizen/citizen-header.ts
  frontend/src/e2e-test/pages/citizen/citizen-new-absence-application.ts
  frontend/src/e2e-test/pages/employee/child-information.ts
  frontend/src/e2e-test/pages/employee/units/unit.ts
  frontend/src/e2e-test/specs/8_access/access.spec.ts
  frontend/src/e2e-test/specs/absence-application/absence-application.spec.ts
  frontend/src/employee-frontend/components/child-information/AbsenceApplicationsSection.tsx
  frontend/src/employee-frontend/components/child-information/ChildInformation.tsx
  frontend/src/employee-frontend/components/child-information/queries.ts
  frontend/src/employee-frontend/components/unit/TabAbsenceApplications.tsx
  frontend/src/employee-frontend/components/unit/TabApplicationProcess.tsx
  frontend/src/employee-frontend/generated/api-clients/absence.ts
  frontend/src/lib-common/generated/action.d.ts
  frontend/src/lib-common/generated/api-types/absence.ts
  frontend/src/lib-common/generated/api-types/children.ts
  frontend/src/lib-common/generated/api-types/pis.ts
  frontend/src/lib-common/generated/api-types/shared.ts
  frontend/src/lib-components/molecules/ConfirmedMutation.tsx
  frontend/src/lib-customizations/defaults/citizen/i18n/en.tsx
  frontend/src/lib-customizations/defaults/citizen/i18n/fi.tsx
  frontend/src/lib-customizations/defaults/citizen/i18n/sv.tsx
  frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
  frontend/src/lib-customizations/types.d.ts
  service/codegen/src/main/kotlin/evaka/codegen/actionenum/Definitions.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/absence/AbsenceApplicationControllersTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/children/ChildControllerCitizenTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/pis/PersonIntegrationTest.kt
  service/src/main/kotlin/fi/espoo/evaka/Audit.kt
  service/src/main/kotlin/fi/espoo/evaka/absence/application/AbsenceApplication.kt
  service/src/main/kotlin/fi/espoo/evaka/absence/application/AbsenceApplicationControllers.kt
  service/src/main/kotlin/fi/espoo/evaka/absence/application/AbsenceApplicationQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/children/ChildControllerCitizen.kt
  service/src/main/kotlin/fi/espoo/evaka/children/Children.kt
  service/src/main/kotlin/fi/espoo/evaka/daycare/controllers/DaycareController.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/Id.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/dev/DataInitializers.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/security/Action.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/security/actionrule/HasUnitRole.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/security/actionrule/IsCitizen.kt
  service/src/main/resources/db/migration/V532__absence_application.sql
  service/src/main/resources/migrations.txt
Labels: enhancement

#6973 Tallennetaan useat Nekku asiakastyypit tietokantaan
  service/src/integrationTest/kotlin/fi/espoo/evaka/nekku/NekkuIntegrationTest.kt
  service/src/main/kotlin/fi/espoo/evaka/nekku/NekkuQueries.kt
  service/src/main/resources/db/migration/V533__remove_nekku_customer_number_constraint.sql
  service/src/main/resources/migrations.txt
Labels: bug

#6975 Korjataan päiväkohtaiset lapsen tule- ja lähtöajat raportti
  service/src/integrationTest/kotlin/fi/espoo/evaka/reports/AttendanceReservationReportTest.kt
  service/src/main/kotlin/fi/espoo/evaka/reports/AttendanceReservationReportController.kt
Labels: bug

#6972 Lisätään esiopetuksen poissaolohakemuksen käsittelyyn sähköposti-ilmoitus
  service/src/integrationTest/kotlin/fi/espoo/evaka/absence/AbsenceApplicationControllersTest.kt
  service/src/main/kotlin/fi/espoo/evaka/absence/application/AbsenceApplicationControllers.kt
  service/src/main/kotlin/fi/espoo/evaka/absence/application/AbsenceApplicationService.kt
  service/src/main/kotlin/fi/espoo/evaka/emailclient/EvakaEmailMessageProvider.kt
  service/src/main/kotlin/fi/espoo/evaka/emailclient/IEmailMessageProvider.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/async/AsyncJob.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/dev/DevApi.kt
Labels: enhancement

#6999 Hiljennetään owasp-häly
  service/owasp-suppressions.xml
Labels: no-changelog

#6997 Lisätään henkilökunnalle käyttöoikeudet esiopetuksen poissaolohakemuksiin
  frontend/src/lib-common/generated/action.d.ts
  service/src/integrationTest/kotlin/fi/espoo/evaka/absence/AbsenceApplicationControllersTest.kt
  service/src/main/kotlin/fi/espoo/evaka/absence/application/AbsenceApplicationControllers.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/security/Action.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/security/actionrule/HasGroupRole.kt
Labels: enhancement

#6978 Lasten tuen tarpeet ja tukitoimet -raportin lisäykset
  frontend/src/e2e-test/pages/employee/reports.ts
  frontend/src/e2e-test/specs/5_employee/assistance-need-and-actions-report.spec.ts
  frontend/src/employee-frontend/components/reports/AssistanceNeedsAndActions.tsx
  frontend/src/employee-frontend/generated/api-clients/reports.ts
  frontend/src/lib-common/generated/api-types/reports.ts
  frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
  service/src/integrationTest/kotlin/fi/espoo/evaka/reports/AssistanceNeedsAndActionsReportControllerTest.kt
  service/src/main/kotlin/fi/espoo/evaka/reports/AssistanceNeedsAndActionsReportController.kt
Labels: enhancement

#6979 Korjataan Nekku-erikoisruokavaliovalinnat poistumaan, jos vastaavat kentät eivät ole enää valittavissa
  service/src/integrationTest/kotlin/fi/espoo/evaka/nekku/NekkuIntegrationTest.kt
  service/src/main/kotlin/fi/espoo/evaka/nekku/NekkuQueries.kt
  service/src/main/resources/db/migration/V534__fix_nekku_special_diet_choices.sql
  service/src/main/resources/migrations.txt
Labels: bug

#6974 Kaikki tulotietomuistutukset yhteen listaan päämiehen sivulla
  frontend/src/e2e-test/pages/employee/guardian-information.ts
  frontend/src/e2e-test/specs/5_employee/income.spec.ts
  frontend/src/employee-frontend/components/person-profile/PersonIncome.tsx
  frontend/src/employee-frontend/components/person-profile/income/IncomeList.tsx
  frontend/src/employee-frontend/components/person-profile/income/IncomeNotifications.tsx
  frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
Labels: enhancement

#6969 Lapsen id audit-lokiin
  service/src/main/kotlin/fi/espoo/evaka/Audit.kt
  service/src/main/kotlin/fi/espoo/evaka/absence/AbsenceController.kt
  service/src/main/kotlin/fi/espoo/evaka/application/ApplicationControllerCitizen.kt
  service/src/main/kotlin/fi/espoo/evaka/application/ApplicationControllerV2.kt
  service/src/main/kotlin/fi/espoo/evaka/application/ApplicationStateService.kt
  service/src/test/kotlin/fi/espoo/evaka/shared/logging/AuditIdTest.kt
Labels: tech

#7002 Korjataan esiopetuksen poissaolohakemuksien näkyminen henkilökunnalle
  frontend/src/e2e-test/specs/8_access/access.spec.ts
  frontend/src/employee-frontend/components/child-information/ChildInformation.tsx
Labels: bug

#7001 Vahvistus kuntalaisen lomakkeen lähetykseen
  frontend/src/citizen-frontend/child-documents/ChildDocumentPage.tsx
  frontend/src/e2e-test/pages/employee/documents/child-document.ts
  frontend/src/e2e-test/specs/0_citizen/citizen-child-documents.spec.ts
  frontend/src/lib-customizations/defaults/citizen/i18n/en.tsx
  frontend/src/lib-customizations/defaults/citizen/i18n/fi.tsx
  frontend/src/lib-customizations/defaults/citizen/i18n/sv.tsx
Labels: enhancement

#6967 Korjataan tietokannan tauluja noudattamaan konventioita - osa 1
  frontend/src/citizen-frontend/applications/editor/service-need/PreferredStartSubSection.tsx
  frontend/src/citizen-frontend/applications/editor/service-need/ServiceTimeSubSectionDaycare.tsx
  frontend/src/citizen-frontend/applications/editor/service-need/ServiceTimeSubSectionPreschool.tsx
  frontend/src/e2e-test/dev-api/fixtures.ts
  frontend/src/e2e-test/generated/api-types.ts
  frontend/src/e2e-test/specs/5_employee/assistance-need-and-actions-report.spec.ts
  frontend/src/e2e-test/specs/7_messaging/messaging.spec.ts
  frontend/src/e2e-test/specs/7_messaging/service-worker-messaging.spec.ts
  frontend/src/employee-frontend/components/application-page/ApplicationNoteBox.tsx
  frontend/src/employee-frontend/components/child-information/AssistanceNeedDecisionSection.tsx
  frontend/src/employee-frontend/components/child-information/AssistanceNeedPreschoolDecisionSection.tsx
  frontend/src/employee-frontend/components/child-information/assistance/AssistanceFactorRow.tsx
  frontend/src/lib-common/generated/api-types/application.ts
  frontend/src/lib-common/generated/api-types/assistance.ts
  frontend/src/lib-common/generated/api-types/assistanceneed.ts
  service/src/integrationTest/kotlin/fi/espoo/evaka/assistanceaction/AssistanceActionIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/assistanceneed/decision/AssistanceNeedPreschoolDecisionIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/service/FeeDecisionGenerationForDataChangesIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/service/VoucherValueDecisionGenerationForDataChangesIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/shared/db/SchemaConventionsTest.kt
  service/src/main/kotlin/fi/espoo/evaka/application/Application.kt
  service/src/main/kotlin/fi/espoo/evaka/application/ApplicationQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/application/notes/ApplicationNoteQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/application/notes/NoteController.kt
  service/src/main/kotlin/fi/espoo/evaka/assistance/Assistance.kt
  service/src/main/kotlin/fi/espoo/evaka/assistance/AssistanceController.kt
  service/src/main/kotlin/fi/espoo/evaka/assistance/AssistanceQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/assistanceaction/AssistanceActionQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/assistanceaction/AssistanceActionService.kt
  service/src/main/kotlin/fi/espoo/evaka/assistanceneed/decision/AssistanceNeedDecision.kt
  service/src/main/kotlin/fi/espoo/evaka/assistanceneed/decision/AssistanceNeedDecisionQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/assistanceneed/preschooldecision/AssistanceNeedPreschoolDecision.kt
  service/src/main/kotlin/fi/espoo/evaka/assistanceneed/preschooldecision/AssistanceNeedPreschoolDecisionQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/assistanceneed/vouchercoefficient/AssistanceNeedVoucherCoefficient.kt
  service/src/main/kotlin/fi/espoo/evaka/attachment/AttachmentQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/backupcare/BackupCareController.kt
  service/src/main/kotlin/fi/espoo/evaka/backupcare/BackupCareQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/espoo/bi/EspooBi.kt
  service/src/main/kotlin/fi/espoo/evaka/incomestatement/IncomeStatementQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/invoicing/data/FeeAlterationQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/invoicing/data/IncomeQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/invoicing/data/InvoiceQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/messaging/DraftQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/messaging/MessageService.kt
  service/src/main/kotlin/fi/espoo/evaka/placement/PlacementController.kt
  service/src/main/kotlin/fi/espoo/evaka/placement/PlacementControllerCitizen.kt
  service/src/main/kotlin/fi/espoo/evaka/placement/PlacementQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/placement/PlacementService.kt
  service/src/main/kotlin/fi/espoo/evaka/placement/PlacementTermination.kt
  service/src/main/kotlin/fi/espoo/evaka/process/ProcessMetadataController.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/dev/DataInitializers.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/dev/DevApi.kt
  service/src/main/resources/db/migration/V535__schema_convention_fixes.sql
  service/src/main/resources/migrations.txt
Labels: tech

#7000 Korjataan esiopetuksen poissaolohakemuksen poissaolotyypit
  service/src/integrationTest/kotlin/fi/espoo/evaka/absence/AbsenceApplicationControllersTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/reservations/ReservationControllerCitizenIntegrationTest.kt
  service/src/main/kotlin/fi/espoo/evaka/absence/AbsenceService.kt
  service/src/main/kotlin/fi/espoo/evaka/absence/application/AbsenceApplicationControllers.kt
  service/src/main/kotlin/fi/espoo/evaka/reservations/ReservationControllerCitizen.kt
Labels: enhancement

#7005 Hiljennetään owasp-häly
  service/owasp-suppressions.xml
Labels: no-changelog

#7004 Lisätään kehotus käyttää esiopetuksen poissaolohakemusta
  frontend/src/citizen-frontend/calendar/AbsenceModal.tsx
  frontend/src/citizen-frontend/calendar/ChildSelector.tsx
  frontend/src/citizen-frontend/calendar/ReservationModal.tsx
  frontend/src/citizen-frontend/calendar/reservation-modal/form.ts
  frontend/src/e2e-test/pages/citizen/citizen-calendar.ts
  frontend/src/e2e-test/specs/absence-application/absence-application.spec.ts
  frontend/src/lib-customizations/defaults/citizen/i18n/en.tsx
  frontend/src/lib-customizations/defaults/citizen/i18n/fi.tsx
  frontend/src/lib-customizations/defaults/citizen/i18n/sv.tsx
  service/src/integrationTest/kotlin/fi/espoo/evaka/absence/AbsenceApplicationControllersTest.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/security/actionrule/HasGroupRole.kt
Labels: enhancement

#7003 Vite lokaaliin kehitykseen
  frontend/.dockerignore
  frontend/.gitignore
  frontend/assetsTransformer.js
  frontend/build.js
  frontend/eslint-plugin/tsconfig.json
  frontend/eslint.config.js
  frontend/package.json
  frontend/public/employee/mobile/evaka-180px.png
  frontend/public/employee/mobile/evaka-180px.png.license
  frontend/public/employee/mobile/evaka-192px.png
  frontend/public/employee/mobile/evaka-192px.png.license
  frontend/public/employee/mobile/evaka-512px.png
  frontend/public/employee/mobile/evaka-512px.png.license
  frontend/public/employee/mobile/manifest.json
  frontend/public/employee/mobile/manifest.json.license
  frontend/src/citizen-frontend/index-vite.html
  frontend/src/e2e-test/jest-environment.cjs
  frontend/src/e2e-test/jest.config.ts
  frontend/src/employee-frontend/index-vite.html
  frontend/src/employee-mobile-frontend/index-vite.html
  frontend/src/lib-common/env.d.ts
  frontend/src/lib-common/globals.ts
  frontend/tsconfig.json
  frontend/vite.config.ts
  frontend/webpack.config.js
  frontend/yarn.lock
Labels: tech

#7008 Korjataan Nekun integraatiotestejä
  service/src/integrationTest/kotlin/fi/espoo/evaka/nekku/NekkuIntegrationTest.kt
Labels: bug

#7009 Korjaus käännökseen
  frontend/src/lib-customizations/defaults/citizen/i18n/en.tsx
Labels: bug

#7014 Korjataan palveluntarpeen muutoshakemuksen ja esiopetuksen poissaolohakemuksen näkyvyys
  frontend/src/employee-frontend/components/child-information/ChildInformation.tsx
Labels: bug

#7015 Nopeampi ensimmäinen sivunlataus lokaalissa kehityksessä
  frontend/vite.config.ts
Labels: tech

#7007 "Virallisia" lomakepohjia ei voi luoda englanninkielisinä
  frontend/src/employee-frontend/components/document-templates/template-editor/TemplateContentEditor.tsx
  frontend/src/employee-frontend/components/document-templates/template-editor/TemplateModal.tsx
  service/src/main/kotlin/fi/espoo/evaka/document/DocumentTemplateController.kt
Labels: enhancement

#7016 Päiväkodin seuraavalle aukiolopäivälle pitää tehdä tarkennustilaus
  service/src/integrationTest/kotlin/fi/espoo/evaka/nekku/NekkuIntegrationTest.kt
  service/src/main/kotlin/fi/espoo/evaka/nekku/NekkuQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/nekku/NekkuService.kt
Labels: bug

#7011 Yöllisten ajojen ajaminen peräkkäin
  service/src/integrationTest/kotlin/fi/espoo/evaka/shared/job/ScheduledJobRunnerTest.kt
  service/src/main/kotlin/fi/espoo/evaka/EvakaEnv.kt
  service/src/main/kotlin/fi/espoo/evaka/espoo/EspooScheduledJobs.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/async/AsyncJob.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/config/AsyncJobConfig.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/job/JobSchedule.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/job/Nightly.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/job/ScheduledJobRunner.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/job/ScheduledJobs.kt
Labels: enhancement

#7018 Lisätään puuttuvat viewport meta-tagit
  frontend/src/citizen-frontend/index-vite.html
  frontend/src/employee-mobile-frontend/index-vite.html
Labels: tech

#7023 Tekninen: Ajetaan Linkity-jobit yöllisessä ajossa
  service/src/main/kotlin/fi/espoo/evaka/espoo/EspooScheduledJobs.kt
Labels: tech

#7026 Nekku tilaus ei muodostu, jos operaatiopäiviä ei ole asetettu ja lomapäivien huomiointi tilauksissa
  service/src/integrationTest/kotlin/fi/espoo/evaka/nekku/NekkuIntegrationTest.kt
  service/src/main/kotlin/fi/espoo/evaka/nekku/NekkuQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/nekku/NekkuService.kt
Labels: bug

#7010 Järjestetään yksiköt aakkosjärjestykseen henkilökohtaisen mobiilin yksikkölistassa
  frontend/src/employee-mobile-frontend/units/UnitList.tsx
Labels: enhancement

#7022 Sisällytetään polyfillit käytön perusteella
  frontend/src/citizen-frontend/index.tsx
  frontend/src/employee-frontend/index.tsx
  frontend/src/employee-mobile-frontend/index.tsx
  frontend/webpack.config.js
  frontend/yarn.lock
Labels: tech

#7061 Korjataan tyyppitarkastusvirhe jos maksulliset ikonit on asennettu
  frontend/vite.config.ts
Labels: tech

#7059 Varmistetaan service workerin toiminta lokaalissa kehityksessä
  frontend/vite.config.ts
Labels: tech

#7025 Audit-lokiin objectId pakolliseksi valittuihin tapahtumiin
  service/src/main/kotlin/fi/espoo/evaka/Audit.kt
  service/src/main/kotlin/fi/espoo/evaka/application/ApplicationControllerCitizen.kt
  service/src/main/kotlin/fi/espoo/evaka/application/ApplicationControllerV2.kt
Labels: tech

#7065 Tieto päiväkirjalle jos huoltajat eivät ole vastanneet poissaolokyselyyn
  frontend/src/e2e-test/pages/employee/units/unit-month-calendar-page.ts
  frontend/src/e2e-test/specs/5_employee/month-calendar.spec.ts
  frontend/src/employee-frontend/components/absences/MonthCalendarCell.tsx
  frontend/src/employee-frontend/components/absences/UnitCalendarDayCellTooltip.tsx
  frontend/src/lib-common/generated/api-types/absence.ts
  frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
  frontend/src/lib-customizations/espoo/featureFlags.tsx
  frontend/src/lib-customizations/types.d.ts
  service/src/integrationTest/kotlin/fi/espoo/evaka/absence/AbsenceServiceIntegrationTest.kt
  service/src/main/kotlin/fi/espoo/evaka/absence/AbsenceController.kt
  service/src/main/kotlin/fi/espoo/evaka/absence/AbsenceService.kt
  service/src/main/kotlin/fi/espoo/evaka/holidayperiod/HolidayQuestionnaireQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/holidayperiod/HolidayQuestionnaires.kt
Labels: enhancement

#7068 Lisätään järjestäminen henkilökunnan mobiiliin
  frontend/src/e2e-test/pages/mobile/list-page.ts
  frontend/src/e2e-test/specs/6_mobile/child-attendances.spec.ts
  frontend/src/employee-mobile-frontend/child-attendance/AttendanceList.tsx
  frontend/src/employee-mobile-frontend/child-attendance/AttendancePageWrapper.tsx
  frontend/src/employee-mobile-frontend/child-attendance/ChildList.tsx
  frontend/src/lib-customizations/defaults/employee-mobile-frontend/i18n/fi.ts
  frontend/src/lib-icons/fontawesome.d.ts
  frontend/src/lib-icons/free-icons.ts
  frontend/src/lib-icons/pro-icons.ts
Labels: enhancement
