Repository espoon-voltti/evaka, pull requests merged in 2025-09, with the labels that each got.

#7698 Netty versiopäivitys, korjaa OWASP CVE checkin
  service/evaka-bom/build.gradle.kts
Labels: dependencies

#7697 Korjataan kuntalaisen saavutettavuusselosteen näkyvyys
  frontend/src/citizen-frontend/AccessibilityStatement.tsx
  frontend/src/citizen-frontend/router.tsx
  frontend/src/e2e-test/specs/0_citizen/citizen-links.spec.ts
Labels: bug

#7720 Update react-fontawesome to v3
  frontend/.yarn/patches/@fortawesome-react-fontawesome-npm-0.2.2-e1863961b2.patch
  frontend/package.json
  frontend/yarn.lock
Labels: dependencies, frontend

#7725 Korjaus huoltajien täytettävät dokumentit-toiminnon nimeen
  frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
Labels: bug

#7660 Validoi luotavan tai muokattavan esiopetussijoituksen päivämäärät
  frontend/src/e2e-test/pages/employee/placement-draft-page.ts
  frontend/src/e2e-test/specs/5_employee/application-transitions.spec.ts
  frontend/src/e2e-test/specs/5_employee/child-information-placements.spec.ts
  frontend/src/employee-frontend/components/child-information/placements/CreatePlacementModal.tsx
  frontend/src/employee-frontend/components/child-information/placements/PlacementRow.tsx
  frontend/src/employee-frontend/components/placement-draft/PlacementDraft.tsx
  frontend/src/employee-frontend/components/placement-draft/PlacementDraftRow.tsx
  frontend/src/employee-frontend/components/unit/queries.ts
  frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
Labels: enhancement

#7721 Tulotietomuistutus lähetetään vain maksullisille sijoituksille
  service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/service/NewCustomerIncomeNotificationIntegrationTest.kt
  service/src/main/kotlin/fi/espoo/evaka/invoicing/service/IncomeQueries.kt
Labels: bug

#7729 Pieniä parannuksia oid-inputtiin ja lasten nimien ulkoasuun
  frontend/src/e2e-test/specs/5_employee/guardian-income-statements.spec.ts
  frontend/src/employee-frontend/components/fee-decision-details/IncomeSection.tsx
  frontend/src/employee-frontend/components/fee-decisions/FeeDecisionFilters.tsx
  frontend/src/employee-frontend/components/person-profile/FosterChildren.tsx
  frontend/src/employee-frontend/components/person-profile/PersonFridgeChild.tsx
  frontend/src/employee-frontend/components/person-profile/PersonIncome.tsx
  frontend/src/employee-frontend/components/person-profile/PersonInvoiceCorrections.tsx
  frontend/src/employee-frontend/components/person-shared/PersonDetails.tsx
Labels: enhancement

#7726 Korjaus henkilökunnan lukemattomien viestien laskentaan
  service/src/integrationTest/kotlin/fi/espoo/evaka/application/PlacementToolServiceIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/messaging/MessageAccountQueriesTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/messaging/MessageIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/messaging/MessageQueriesTest.kt
  service/src/main/kotlin/fi/espoo/evaka/messaging/MessageController.kt
  service/src/main/kotlin/fi/espoo/evaka/messaging/MessageControllerCitizen.kt
  service/src/main/kotlin/fi/espoo/evaka/messaging/MessageQueries.kt
Labels: bug

#7768 Lisätään Nekku tilausraporttiin järjestys myös ruoka-ajan mukaan
  service/src/main/kotlin/fi/espoo/evaka/reports/NekkuOrderReport.kt
Labels: enhancement

#7769 Rajataan Nekku-tilausraportin filtterit auki oleviin yksiköihin ja ryhmiin
  frontend/src/employee-frontend/components/reports/NekkuOrders.tsx
Labels: enhancement

#7771 Koski-integraation korjaus liittyen lapsikohtainen tuki + pidennetty oppivelvollisuus
  service/src/main/kotlin/fi/espoo/evaka/koski/KoskiData.kt
Labels: bug

#7731 Varmistusvalinta lapsen dokumentin luontidialogiin
  frontend/src/e2e-test/pages/employee/child-information.ts
  frontend/src/e2e-test/specs/5_employee/child-documents.spec.ts
  frontend/src/employee-frontend/components/child-information/ChildDocuments.tsx
  frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
Labels: enhancement

#7772 Korjataan yksiköt-sivun uudelleenohjaus ainokaiseen yksikköön
  frontend/src/e2e-test/specs/5_employee/units.spec.ts
  frontend/src/employee-frontend/components/Units.tsx
Labels: enhancement

#7770 Päivitetään palveluntarpeen poisto automaattisesti käyttöliittymässä
  frontend/src/e2e-test/pages/employee/child-information.ts
  frontend/src/e2e-test/specs/5_employee/service-need.spec.ts
  frontend/src/employee-frontend/components/child-information/placements/service-needs/ServiceNeedReadRow.tsx
  frontend/src/employee-frontend/components/child-information/queries.ts
Labels: bug

#7764 Estetään palveluseteliyksikön työntekijän valitseminen päätöksentekijäksi
  service/src/main/kotlin/fi/espoo/evaka/document/childdocument/ChildDocumentQueries.kt
Labels: enhancement

#7810 Lisätään päätösten arkistointi
  frontend/src/employee-frontend/components/child-documents/ChildDocumentReadView.tsx
  frontend/src/employee-frontend/components/person-profile/PersonDecisions.tsx
  frontend/src/employee-frontend/components/person-profile/queries.ts
  frontend/src/employee-frontend/generated/api-clients/decision.ts
  frontend/src/lib-common/generated/action.d.ts
  frontend/src/lib-common/generated/api-types/decision.ts
  frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
  frontend/src/lib-customizations/espoo/featureFlags.tsx
  frontend/src/lib-customizations/types.d.ts
  service/src/integrationTest/kotlin/fi/espoo/evaka/document/archival/ArchivalServiceIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/pdfgen/PdfGeneratorTest.kt
  service/src/main/kotlin/fi/espoo/evaka/decision/Decision.kt
  service/src/main/kotlin/fi/espoo/evaka/decision/DecisionController.kt
  service/src/main/kotlin/fi/espoo/evaka/decision/DecisionQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/document/archival/ArchivalIntegrationClient.kt
  service/src/main/kotlin/fi/espoo/evaka/document/archival/ArchivalService.kt
  service/src/main/kotlin/fi/espoo/evaka/espoo/archival/SärmäChildDocumentClient.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/async/AsyncJob.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/dev/DataInitializers.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/security/Action.kt
  service/src/main/resources/db/migration/V555__decision_archived_at.sql
  service/src/main/resources/migrations.txt
Labels: enhancement

#7800 Näytetään oletuspalvelusetelikertoimet viivana lapsikohtaisella tukitoimiraportilla
  frontend/src/e2e-test/specs/5_employee/assistance-need-and-actions-report.spec.ts
  frontend/src/employee-frontend/components/reports/AssistanceNeedsAndActions.tsx
Labels: enhancement

#7844 Arkistometadata: Keskitetty, process history pohjainen luontipäivämäärän poimintalogiikka
  service/src/main/kotlin/fi/espoo/evaka/espoo/archival/DocumentMetadataUtils.kt
  service/src/test/kotlin/fi/espoo/evaka/document/archival/DocumentMetadataUtilsTest.kt
Labels: bug
