Repository espoon-voltti/evaka, pull requests merged in 2025-03, with the labels that each got.

#6441 Lisätty Aromi-ruokatilausten asiakastunnus ryhmille ja nostettu se näkyville raakaraportille
  frontend/src/e2e-test/dev-api/fixtures.ts
  frontend/src/e2e-test/generated/api-types.ts
  frontend/src/e2e-test/specs/7_messaging/messaging.spec.ts
  frontend/src/employee-frontend/components/reports/Raw.tsx
  frontend/src/employee-frontend/components/unit/queries.ts
  frontend/src/employee-frontend/components/unit/tab-groups/groups/GroupModal.tsx
  frontend/src/employee-frontend/components/unit/tab-groups/groups/group/GroupUpdateModal.tsx
  frontend/src/lib-common/generated/api-types/daycare.ts
  frontend/src/lib-common/generated/api-types/reports.ts
  frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
  frontend/src/lib-customizations/espoo/featureFlags.tsx
  service/src/integrationTest/kotlin/fi/espoo/evaka/daycare/controllers/DaycareControllerIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/reports/RawReportControllerTest.kt
  service/src/main/kotlin/fi/espoo/evaka/daycare/DaycareGroupQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/daycare/controllers/DaycareController.kt
  service/src/main/kotlin/fi/espoo/evaka/daycare/service/DaycareService.kt
  service/src/main/kotlin/fi/espoo/evaka/reports/RawReport.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/dev/DataInitializers.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/dev/DevApi.kt
  service/src/main/resources/db/migration/V501__aromi_customer_id.sql
  service/src/main/resources/migrations.txt
Labels: enhancement

#6454 Lisätään ei tuloja -vaihtoehto tuloselvityslomakkeeseen
  frontend/src/citizen-frontend/income-statements/IncomeStatementForm.tsx
  frontend/src/citizen-frontend/income-statements/IncomeStatementView.tsx
  frontend/src/employee-frontend/components/IncomeStatementPage.tsx
  frontend/src/lib-common/generated/api-types/incomestatement.ts
  frontend/src/lib-common/income-statements/body.ts
  frontend/src/lib-common/income-statements/form.ts
  frontend/src/lib-customizations/defaults/citizen/i18n/en.tsx
  frontend/src/lib-customizations/defaults/citizen/i18n/fi.tsx
  frontend/src/lib-customizations/defaults/citizen/i18n/sv.tsx
  frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
  service/src/integrationTest/kotlin/fi/espoo/evaka/incomestatement/IncomeStatementControllerCitizenIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/incomestatement/IncomeStatementControllerIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/service/OutdatedIncomeNotificationsIntegrationTest.kt
  service/src/main/kotlin/fi/espoo/evaka/incomestatement/IncomeStatement.kt
  service/src/main/kotlin/fi/espoo/evaka/incomestatement/IncomeStatementQueries.kt
  service/src/main/resources/db/migration/V502__income_statement_gross_no_income.sql
  service/src/main/resources/migrations.txt
Labels: enhancement

#6444 Espoon työvuorojen haku Linkitystä
  service/src/integrationTest/kotlin/fi/espoo/evaka/linkity/LinkityServiceTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/linkity/MockLinkityClient.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/titania/TitaniaQueriesTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/titania/TitaniaServiceTest.kt
  service/src/main/kotlin/fi/espoo/evaka/EvakaEnv.kt
  service/src/main/kotlin/fi/espoo/evaka/attendance/StaffAttendancePlan.kt
  service/src/main/kotlin/fi/espoo/evaka/attendance/StaffAttendancePlanQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/linkity/Linkity.kt
  service/src/main/kotlin/fi/espoo/evaka/linkity/LinkityClient.kt
  service/src/main/kotlin/fi/espoo/evaka/linkity/LinkityService.kt
  service/src/main/kotlin/fi/espoo/evaka/pis/EmployeeQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/config/EnvConfig.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/utils/Kotlin.kt
  service/src/main/kotlin/fi/espoo/evaka/titania/TitaniaQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/titania/TitaniaService.kt
Labels: enhancement

#6474 Korjaus latauslinkkeihin
  frontend/src/citizen-frontend/generated/api-clients/application.ts
  frontend/src/citizen-frontend/generated/api-clients/assistanceneed.ts
  frontend/src/citizen-frontend/generated/api-clients/attachment.ts
  frontend/src/citizen-frontend/generated/api-clients/childimages.ts
  frontend/src/citizen-frontend/generated/api-clients/document.ts
  frontend/src/e2e-test/generated/api-clients.ts
  frontend/src/employee-frontend/generated/api-clients/aromi.ts
  frontend/src/employee-frontend/generated/api-clients/assistanceneed.ts
  frontend/src/employee-frontend/generated/api-clients/attachment.ts
  frontend/src/employee-frontend/generated/api-clients/decision.ts
  frontend/src/employee-frontend/generated/api-clients/document.ts
  frontend/src/employee-frontend/generated/api-clients/invoicing.ts
  frontend/src/employee-frontend/generated/api-clients/pis.ts
  frontend/src/employee-mobile-frontend/generated/api-clients/attachment.ts
  frontend/src/employee-mobile-frontend/generated/api-clients/childimages.ts
  frontend/src/lib-common/uri.spec.ts
  frontend/src/lib-common/uri.ts
  service/codegen/src/main/kotlin/evaka/codegen/api/ApiFiles.kt
Labels: bug

#6453 Hae Nekku asiakastiedot tietokantaan
  frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
  frontend/src/lib-customizations/espoo/featureFlags.tsx
  frontend/src/lib-customizations/types.d.ts
  service/src/integrationTest/kotlin/fi/espoo/evaka/nekku/NekkuIntegrationTest.kt
  service/src/main/kotlin/fi/espoo/evaka/EvakaEnv.kt
  service/src/main/kotlin/fi/espoo/evaka/nekku/NekkuQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/nekku/NekkuService.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/async/AsyncJob.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/config/EnvConfig.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/job/ScheduledJobs.kt
  service/src/main/resources/db/migration/V503__nekku_customer.sql
  service/src/main/resources/migrations.txt
Labels: enhancement

#6470 Aromi-integraation läsnäolotietojen keräämisen testiversio
  frontend/src/employee-frontend/components/reports/AttendanceReservationByChild.tsx
  frontend/src/employee-frontend/generated/api-clients/aromi.ts
  frontend/src/lib-common/generated/action.d.ts
  service/src/integrationTest/kotlin/fi/espoo/evaka/aromi/AromiControllerTest.kt
  service/src/main/kotlin/fi/espoo/evaka/aromi/AromiController.kt
  service/src/main/kotlin/fi/espoo/evaka/aromi/AromiService.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/security/Action.kt
  service/src/test/resources/aromi/ok-admin.csv
Labels: enhancement

#6466 Pääkäyttäjä voi poistaa vielä kirjautumattoman hetullisen palveluntuottajakäyttäjän
  frontend/src/e2e-test/pages/employee/employees.ts
  frontend/src/e2e-test/specs/5_employee/employees.spec.ts
  frontend/src/employee-frontend/components/employees/EmployeeList.tsx
  frontend/src/employee-frontend/components/employees/queries.ts
  frontend/src/lib-common/generated/api-types/pis.ts
  frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
  service/src/integrationTest/kotlin/fi/espoo/evaka/pis/controller/EmployeeControllerIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/vtjclient/VtjClientServiceTest.kt
  service/src/main/kotlin/fi/espoo/evaka/pis/Employee.kt
  service/src/main/kotlin/fi/espoo/evaka/pis/EmployeeQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/pis/controllers/EmployeeController.kt
  service/src/main/resources/db/migration/V504__nullable_last_login.sql
  service/src/main/resources/migrations.txt
Labels: enhancement

#6452 Muutos henkilökunnan viestinnän vastaanottajalistalla näkyviin sijoitusta muuttaviin lapsiin
  service/src/integrationTest/kotlin/fi/espoo/evaka/messaging/MessageReceiversIntegrationTest.kt
  service/src/main/kotlin/fi/espoo/evaka/messaging/MessageQueries.kt
Labels: enhancement

#6467 Espoon työaikakirjausten lähetys Linkityyn
  service/src/integrationTest/kotlin/fi/espoo/evaka/linkity/LinkityServiceTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/linkity/MockLinkityClient.kt
  service/src/main/kotlin/fi/espoo/evaka/linkity/Linkity.kt
  service/src/main/kotlin/fi/espoo/evaka/linkity/LinkityClient.kt
  service/src/main/kotlin/fi/espoo/evaka/linkity/LinkityQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/linkity/LinkityService.kt
Labels: enhancement

#6475 Lähetetään tulotietomuistutukset vain laskutetaan eVakasta -yksiköiden asiakkaille
  service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/service/OutdatedIncomeNotificationsIntegrationTest.kt
  service/src/main/kotlin/fi/espoo/evaka/invoicing/service/IncomeQueries.kt
Labels: bug

#6476 Lisätään Aromi-ateriapalvelun ruokatilausten lähetys
  REUSE.toml
  compose/docker-compose.integration.yml
  compose/docker-compose.yml
  compose/sftp/ssh_host_ed25519_key
  compose/sftp/ssh_host_ed25519_key.pub
  compose/sftp/ssh_host_rsa_key
  compose/sftp/ssh_host_rsa_key.pub
  service/build.gradle.kts
  service/evaka-bom/build.gradle.kts
  service/src/integrationTest/kotlin/fi/espoo/evaka/aromi/AromiServiceTest.kt
  service/src/integrationTest/resources/application-integration-test.yaml
  service/src/main/kotlin/fi/espoo/evaka/EvakaEnv.kt
  service/src/main/kotlin/fi/espoo/evaka/aromi/AromiService.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/config/EnvConfig.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/job/ScheduledJobs.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/sftp/SftpClient.kt
Labels: enhancement

#6455 Jos käyttäjällä on jo vahvistettu sähköpostiosoite, ei sallita sen muuttamista hakemuksen kautta
  frontend/src/citizen-frontend/applications/editor/contact-info/GuardianSubSection.tsx
  frontend/src/e2e-test/pages/citizen/citizen-applications.ts
  frontend/src/e2e-test/specs/0_citizen/citizen-daycare-application.spec.ts
  frontend/src/lib-customizations/defaults/citizen/i18n/en.tsx
  frontend/src/lib-customizations/defaults/citizen/i18n/fi.tsx
  frontend/src/lib-customizations/defaults/citizen/i18n/sv.tsx
  service/src/main/kotlin/fi/espoo/evaka/pis/PersonQueries.kt
Labels: enhancement

#6480 Lähetetään tulotietomuistutukset palveluseteliyksiköiden asiakkaille
  service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/service/OutdatedIncomeNotificationsIntegrationTest.kt
  service/src/main/kotlin/fi/espoo/evaka/invoicing/service/IncomeQueries.kt
Labels: bug

#6481 Nekku hae asiakastiedot ryhmän korjaus
  service/src/main/kotlin/fi/espoo/evaka/nekku/NekkuQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/nekku/NekkuService.kt
Labels: bug

#6469 Näytetän kuntalaiselle varoitus jos puoliso ei ole koskaan toimittanut tuloselvitystä
  frontend/src/citizen-frontend/generated/api-clients/incomestatement.ts
  frontend/src/citizen-frontend/income-statements/IncomeStatements.tsx
  frontend/src/citizen-frontend/income-statements/queries.ts
  frontend/src/lib-common/generated/api-types/incomestatement.ts
  frontend/src/lib-customizations/defaults/citizen/i18n/en.tsx
  frontend/src/lib-customizations/defaults/citizen/i18n/fi.tsx
  frontend/src/lib-customizations/defaults/citizen/i18n/sv.tsx
  service/src/integrationTest/kotlin/fi/espoo/evaka/incomestatement/IncomeStatementControllerCitizenIntegrationTest.kt
  service/src/main/kotlin/fi/espoo/evaka/Audit.kt
  service/src/main/kotlin/fi/espoo/evaka/incomestatement/IncomeStatementControllerCitizen.kt
  service/src/main/kotlin/fi/espoo/evaka/incomestatement/IncomeStatementQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/security/Action.kt
Labels: enhancement

#6471 Lisätään yksikköhakuun kunta-sarake
  frontend/src/employee-frontend/components/Units.tsx
  frontend/src/employee-frontend/state/units.tsx
  frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
Labels: enhancement

#6472 Järjestetään laskut päämiehen sivulla uusimmasta vanhimpaan
  service/src/main/kotlin/fi/espoo/evaka/invoicing/data/InvoiceQueries.kt
Labels: enhancement

#6473 Helpotetaan yksikkökalenterin ajanjakson valitsemista
  frontend/src/employee-frontend/components/unit/TabCalendar.tsx
Labels: enhancement

#6478 Ei-kunnallisissa yksiköissä vain pääkäyttäjä voi luvittaa henkilökuntaa yksiköihin
  service/src/main/kotlin/fi/espoo/evaka/shared/security/Action.kt
Labels: enhancement

#6416 Salassapitoaika ja -peruste
  frontend/src/citizen-frontend/child-documents/ChildDocumentPage.tsx
  frontend/src/e2e-test/dev-api/fixtures.ts
  frontend/src/e2e-test/generated/api-types.ts
  frontend/src/e2e-test/pages/employee/documents/document-templates.ts
  frontend/src/e2e-test/specs/5_employee/child-documents.spec.ts
  frontend/src/employee-frontend/components/archive-metadata/MetadataSection.tsx
  frontend/src/employee-frontend/components/child-documents/ChildDocumentEditor.tsx
  frontend/src/employee-frontend/components/document-templates/template-editor/TemplateContentEditor.tsx
  frontend/src/employee-frontend/components/document-templates/template-editor/TemplateModal.tsx
  frontend/src/lib-common/generated/api-types/document.ts
  frontend/src/lib-common/generated/api-types/process.ts
  frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
  service/src/integrationTest/kotlin/fi/espoo/evaka/assistanceneed/decision/AssistanceNeedDecisionIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/assistanceneed/decision/AssistanceNeedPreschoolDecisionIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/document/DocumentTemplateIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/document/childdocument/ChildDocumentControllerIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/pdfgen/PdfGeneratorTest.kt
  service/src/main/kotlin/fi/espoo/evaka/document/DocumentTemplate.kt
  service/src/main/kotlin/fi/espoo/evaka/document/DocumentTemplateQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/document/archival/ArchiveChildDocumentService.kt
  service/src/main/kotlin/fi/espoo/evaka/document/childdocument/DocumentHtmlGenerator.kt
  service/src/main/kotlin/fi/espoo/evaka/process/ProcessMetadataController.kt
  service/src/main/kotlin/fi/espoo/evaka/process/ProcessMetadataQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/dev/DataInitializers.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/dev/DevApi.kt
  service/src/main/resources/db/migration/V505__confidentiality_duration_and_basis.sql
  service/src/main/resources/migrations.txt
  service/src/test/kotlin/fi/espoo/evaka/document/archival/ArchiveChildDocumentServiceTest.kt
Labels: enhancement

#6482 Espoon työvuorojen haun ajastus (ei vielä käytössä)
  service/src/integrationTest/kotlin/fi/espoo/evaka/linkity/LinkityServiceTest.kt
  service/src/main/kotlin/fi/espoo/evaka/EspooConfig.kt
  service/src/main/kotlin/fi/espoo/evaka/EvakaEnv.kt
  service/src/main/kotlin/fi/espoo/evaka/espoo/EspooAsyncJob.kt
  service/src/main/kotlin/fi/espoo/evaka/espoo/EspooScheduledJobs.kt
  service/src/main/kotlin/fi/espoo/evaka/linkity/LinkityService.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/config/EnvConfig.kt
Labels: enhancement

#6488 Espoon työaikakirjausten lähetyksen ajastus (ei vielä käytössä)
  service/src/integrationTest/kotlin/fi/espoo/evaka/linkity/LinkityServiceTest.kt
  service/src/main/kotlin/fi/espoo/evaka/EspooConfig.kt
  service/src/main/kotlin/fi/espoo/evaka/espoo/EspooScheduledJobs.kt
  service/src/main/kotlin/fi/espoo/evaka/linkity/LinkityService.kt
Labels: enhancement

#6486 Nekku hae asiakkaat- rajapinta hakee vain varhaiskasvatuksen asiakkaat
  service/src/main/kotlin/fi/espoo/evaka/nekku/NekkuQueries.kt
Labels: enhancement

#6487 Vanhempainvapaata voi pitää vielä lapsen toisena syntymäpäivänä
  service/src/main/kotlin/fi/espoo/evaka/invoicing/service/DraftInvoiceGenerator.kt
Labels: bug

#6468 Siirretään yrittäjyyden kysyminen alemmas, ei kysytä pää-/sivutoimisuutta
  frontend/src/citizen-frontend/income-statements/ChildIncomeStatementForm.tsx
  frontend/src/citizen-frontend/income-statements/ChildIncomeStatementView.tsx
  frontend/src/citizen-frontend/income-statements/IncomeStatementAttachments.tsx
  frontend/src/citizen-frontend/income-statements/IncomeStatementForm.tsx
  frontend/src/citizen-frontend/income-statements/IncomeStatementView.tsx
  frontend/src/e2e-test/pages/citizen/citizen-income.ts
  frontend/src/e2e-test/specs/0_citizen/citizen-income-statement.spec.ts
  frontend/src/employee-frontend/components/IncomeStatementPage.tsx
  frontend/src/lib-common/generated/api-types/incomestatement.ts
  frontend/src/lib-common/income-statements/body.ts
  frontend/src/lib-common/income-statements/form.ts
  frontend/src/lib-customizations/defaults/citizen/i18n/en.tsx
  frontend/src/lib-customizations/defaults/citizen/i18n/fi.tsx
  frontend/src/lib-customizations/defaults/citizen/i18n/sv.tsx
  frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
  service/src/integrationTest/kotlin/fi/espoo/evaka/incomestatement/IncomeStatementControllerCitizenIntegrationTest.kt
  service/src/main/kotlin/fi/espoo/evaka/incomestatement/IncomeStatement.kt
  service/src/main/kotlin/fi/espoo/evaka/incomestatement/IncomeStatementQueries.kt
Labels: enhancement

#6490 Korjataan kirjoitusvirhe tuloselvityksellä
  frontend/src/lib-customizations/defaults/citizen/i18n/fi.tsx
Labels: bug

#6494 Korjauksia palveluseteliarvojen editoriin
  frontend/src/employee-frontend/components/finance-basics/ServiceNeedItem.tsx
  frontend/src/employee-frontend/components/finance-basics/VoucherValueEditor.tsx
  service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/VoucherValueIntegrationTest.kt
  service/src/main/kotlin/fi/espoo/evaka/invoicing/controller/FinanceBasicsController.kt
Labels: bug

#6492 Raporttien CSV-tiedostojen muodostuksen parannuksia
  frontend/package.json
  frontend/src/e2e-test/pages/employee/reports.ts
  frontend/src/employee-frontend/components/employees/EmployeesPage.tsx
  frontend/src/employee-frontend/components/reports/Applications.tsx
  frontend/src/employee-frontend/components/reports/AssistanceNeedsAndActions.tsx
  frontend/src/employee-frontend/components/reports/AttendanceReservation.tsx
  frontend/src/employee-frontend/components/reports/AttendanceReservationByChild.tsx
  frontend/src/employee-frontend/components/reports/ChildAgeLanguage.tsx
  frontend/src/employee-frontend/components/reports/ChildAttendanceReport.tsx
  frontend/src/employee-frontend/components/reports/ChildrenInDifferentAddress.tsx
  frontend/src/employee-frontend/components/reports/CsvFormation.spec.ts
  frontend/src/employee-frontend/components/reports/CustomerFees.tsx
  frontend/src/employee-frontend/components/reports/Decisions.tsx
  frontend/src/employee-frontend/components/reports/EndedPlacements.tsx
  frontend/src/employee-frontend/components/reports/ExceededServiceNeeds.tsx
  frontend/src/employee-frontend/components/reports/FamilyConflicts.tsx
  frontend/src/employee-frontend/components/reports/FamilyContacts.tsx
  frontend/src/employee-frontend/components/reports/FamilyDaycareMealCount.tsx
  frontend/src/employee-frontend/components/reports/FuturePreschoolersReport.tsx
  frontend/src/employee-frontend/components/reports/IncompleteIncomeReport.tsx
  frontend/src/employee-frontend/components/reports/Invoices.tsx
  frontend/src/employee-frontend/components/reports/MealReport.tsx
  frontend/src/employee-frontend/components/reports/MissingHeadOfFamily.tsx
  frontend/src/employee-frontend/components/reports/MissingServiceNeed.tsx
  frontend/src/employee-frontend/components/reports/NonSsnChildren.tsx
  frontend/src/employee-frontend/components/reports/Occupancies.tsx
  frontend/src/employee-frontend/components/reports/PartnersInDifferentAddress.tsx
  frontend/src/employee-frontend/components/reports/PlacementCount.tsx
  frontend/src/employee-frontend/components/reports/PlacementGuarantee.tsx
  frontend/src/employee-frontend/components/reports/PlacementSketching.tsx
  frontend/src/employee-frontend/components/reports/PreschoolAbsenceReport.tsx
  frontend/src/employee-frontend/components/reports/PreschoolApplicationReport.tsx
  frontend/src/employee-frontend/components/reports/PresenceReport.tsx
  frontend/src/employee-frontend/components/reports/Raw.tsx
  frontend/src/employee-frontend/components/reports/ReportDownload.tsx
  frontend/src/employee-frontend/components/reports/ServiceNeeds.tsx
  frontend/src/employee-frontend/components/reports/Sextet.tsx
  frontend/src/employee-frontend/components/reports/StartingPlacements.tsx
  frontend/src/employee-frontend/components/reports/TampereRegionalSurvey.tsx
  frontend/src/employee-frontend/components/reports/Units.tsx
  frontend/src/employee-frontend/components/reports/VoucherServiceProviderUnit.tsx
  frontend/src/employee-frontend/components/reports/VoucherServiceProviders.tsx
  frontend/src/employee-frontend/components/reports/csv.spec.ts
  frontend/src/employee-frontend/components/reports/csv.ts
  frontend/tsconfig.base.json
  frontend/yarn.lock
Labels: enhancement

#6491 Kuntalainen voi merkitä viestin lukemattomaksi
  frontend/src/citizen-frontend/generated/api-clients/messaging.ts
  frontend/src/citizen-frontend/messages/ThreadView.tsx
  frontend/src/citizen-frontend/messages/queries.ts
  frontend/src/e2e-test/pages/citizen/citizen-header.ts
  frontend/src/e2e-test/pages/citizen/citizen-messages.ts
  frontend/src/e2e-test/specs/7_messaging/messaging.spec.ts
  frontend/src/lib-customizations/defaults/citizen/i18n/en.tsx
  frontend/src/lib-customizations/defaults/citizen/i18n/fi.tsx
  frontend/src/lib-customizations/defaults/citizen/i18n/sv.tsx
  service/src/main/kotlin/fi/espoo/evaka/Audit.kt
  service/src/main/kotlin/fi/espoo/evaka/messaging/MessageControllerCitizen.kt
  service/src/main/kotlin/fi/espoo/evaka/messaging/MessageQueries.kt
Labels: enhancement

#6510 Päivitetään cookie-parser -kirjasto versioon 1.4.7
  apigw/package.json
  apigw/src/internal/mobile-device-session.ts
  apigw/yarn.lock
Labels: tech

#6509 Korjataan työaikamerkintöjen päivitys kun data ei muutu
  service/src/integrationTest/kotlin/fi/espoo/evaka/attendance/RealtimeStaffAttendanceQueriesTest.kt
  service/src/main/kotlin/fi/espoo/evaka/attendance/MobileRealtimeStaffAttendanceController.kt
  service/src/main/kotlin/fi/espoo/evaka/attendance/RealtimeStaffAttendanceController.kt
  service/src/main/kotlin/fi/espoo/evaka/attendance/StaffAttendanceQueries.kt
Labels: bug

#6511 Raporttien CSV-latauksen korjauksia
  frontend/src/employee-frontend/components/reports/csv.spec.ts
  frontend/src/employee-frontend/components/reports/csv.ts
Labels: no-changelog

#6512 Estetään hyvityslaskuduplikaattien muodostuminen
  service/src/main/kotlin/fi/espoo/evaka/invoicing/service/InvoiceGenerator.kt
  service/src/main/resources/db/migration/V507__replaced_invoice_id_unique.sql
  service/src/main/resources/migrations.txt
Labels: enhancement

#6484 Poistetaan vanhan testauskoodin jäänne
  service/src/main/kotlin/fi/espoo/evaka/jamix/JamixService.kt
Labels: no-changelog

#6489 Lisätään kuusikkoraporttiin suodatus yksikön järjestämismuodolla
  frontend/src/e2e-test/pages/employee/reports.ts
  frontend/src/e2e-test/specs/5_employee/sextet-report.spec.ts
  frontend/src/employee-frontend/components/reports/Sextet.tsx
  frontend/src/employee-frontend/components/reports/queries.ts
  frontend/src/employee-frontend/generated/api-clients/reports.ts
  service/src/integrationTest/kotlin/fi/espoo/evaka/reports/SextetReportTest.kt
  service/src/main/kotlin/fi/espoo/evaka/reports/SextetReport.kt
Labels: enhancement

#6514 Korjataan SFTP-yhteys
  service/src/main/kotlin/fi/espoo/evaka/shared/sftp/SftpClient.kt
Labels: enhancement

#6493 Toimintojen avauksien huomioiminen Linkity-integraatiossa
  service/src/integrationTest/kotlin/fi/espoo/evaka/linkity/LinkityServiceTest.kt
  service/src/main/kotlin/fi/espoo/evaka/linkity/LinkityQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/linkity/LinkityService.kt
Labels: enhancement

#6518 Tuloselvityksen tekstipäivityksiä
  frontend/src/citizen-frontend/income-statements/IncomeStatementForm.tsx
  frontend/src/lib-customizations/defaults/citizen/i18n/en.tsx
  frontend/src/lib-customizations/defaults/citizen/i18n/fi.tsx
  frontend/src/lib-customizations/defaults/citizen/i18n/sv.tsx
  frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
  frontend/src/lib-customizations/espoo/citizen.tsx
Labels: enhancement

#6516 Lisätään esiopetushakemukselle täydentävän varhaiskasvatuksen aloituspäivämäärän validointi
  frontend/src/citizen-frontend/applications/editor/service-need/ServiceTimeSubSectionPreschool.tsx
  frontend/src/citizen-frontend/applications/editor/validations.ts
  frontend/src/lib-common/form-validation.ts
  frontend/src/lib-components/i18n.tsx
  frontend/src/lib-components/utils/TestContextProvider.tsx
  frontend/src/lib-customizations/defaults/components/i18n/en.tsx
  frontend/src/lib-customizations/defaults/components/i18n/fi.tsx
  frontend/src/lib-customizations/defaults/components/i18n/sv.tsx
  service/src/main/kotlin/fi/espoo/evaka/application/ApplicationStateService.kt
Labels: enhancement

#6519 Espoon Linkity-rajapinnan apikey-tunnistautuminen
  service/src/main/kotlin/fi/espoo/evaka/linkity/LinkityClient.kt
Labels: tech

#6517 Digitransit APIn v2 käyttöönotto
  apigw/src/enduser/mapRoutes.ts
  frontend/src/citizen-frontend/map/api.ts
  frontend/src/e2e-test/generated/api-clients.ts
  service/src/main/kotlin/fi/espoo/evaka/shared/dev/DevApi.kt
Labels: tech

#6521 Korjataan sopimuspäivälaskurin näkyvyys
  frontend/src/citizen-frontend/children/sections/service-need-and-daily-service-time/AttendanceSummaryTable.tsx
  frontend/src/citizen-frontend/children/sections/service-need-and-daily-service-time/ServiceNeedAndDailyServiceTimeSection.tsx
  frontend/src/citizen-frontend/children/sections/service-need-and-daily-service-time/queries.ts
  frontend/src/lib-common/generated/api-types/placement.ts
  frontend/src/lib-common/generated/api-types/serviceneed.ts
  service/src/main/kotlin/fi/espoo/evaka/children/ChildControllerCitizen.kt
  service/src/main/kotlin/fi/espoo/evaka/placement/Placement.kt
  service/src/main/kotlin/fi/espoo/evaka/placement/PlacementQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/serviceneed/ServiceNeed.kt
  service/src/main/kotlin/fi/espoo/evaka/serviceneed/ServiceNeedQueries.kt
Labels: enhancement

#6495 Näytetään tulevien päivien suunnitellut työvuorot työntekijän mobiilissa
  frontend/src/e2e-test/pages/mobile/staff-page.ts
  frontend/src/e2e-test/specs/6_mobile/planned-staff-attendances.spec.ts
  frontend/src/e2e-test/specs/6_mobile/realtime-staff-attendances.spec.ts
  frontend/src/employee-mobile-frontend/App.tsx
  frontend/src/employee-mobile-frontend/common/BottomNavbar.tsx
  frontend/src/employee-mobile-frontend/generated/api-clients/attendance.ts
  frontend/src/employee-mobile-frontend/staff-attendance/StaffAttendanceEditPage.tsx
  frontend/src/employee-mobile-frontend/staff-attendance/StaffAttendancesPage.tsx
  frontend/src/employee-mobile-frontend/staff-attendance/StaffMarkDepartedPage.tsx
  frontend/src/employee-mobile-frontend/staff-attendance/StaffMemberPage.tsx
  frontend/src/employee-mobile-frontend/staff-attendance/StaffPreviousAttendancesPage.tsx
  frontend/src/lib-common/generated/api-types/attendance.ts
  frontend/src/lib-customizations/defaults/employee-mobile-frontend/i18n/fi.ts
  service/src/integrationTest/kotlin/fi/espoo/evaka/attendance/MobileRealtimeStaffAttendanceControllerIntegrationTest.kt
  service/src/main/kotlin/fi/espoo/evaka/attendance/MobileRealtimeStaffAttendanceController.kt
  service/src/main/kotlin/fi/espoo/evaka/attendance/StaffAttendance.kt
  service/src/main/kotlin/fi/espoo/evaka/attendance/StaffAttendanceQueries.kt
Labels: enhancement

#6522 Lisätty tilastointipäiväykset seutuselvitysraportin tuloksiin
  frontend/src/employee-frontend/components/reports/TampereRegionalSurvey.tsx
  frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
Labels: enhancement

#6525 Lisätään aromi-integraatioon toimituspisteen nimi
  service/src/main/kotlin/fi/espoo/evaka/aromi/AromiService.kt
  service/src/test/resources/aromi/ok-admin.csv
Labels: enhancement

#6526 Espoo: Muutos arvopäätöksien päivämäärä ja pykälä
  service/src/main/resources/WEB-INF/templates/fee-decision/voucher-value-decision.properties
  service/src/main/resources/WEB-INF/templates/fee-decision/voucher-value-decision_sv.properties
Labels: no-changelog

#6513 Korvataan xjctool Gradle plugin suoralla xjc käytöllä
  service/sarmamodel/build.gradle.kts
Labels: tech

#6520 Modernisoidaan raporttien fronttikoodia
  frontend/src/employee-frontend/components/reports/Applications.tsx
  frontend/src/employee-frontend/components/reports/AssistanceNeedDecisionsReport.tsx
  frontend/src/employee-frontend/components/reports/AttendanceReservation.tsx
  frontend/src/employee-frontend/components/reports/ChildAgeLanguage.tsx
  frontend/src/employee-frontend/components/reports/ChildrenInDifferentAddress.tsx
  frontend/src/employee-frontend/components/reports/Decisions.tsx
  frontend/src/employee-frontend/components/reports/DuplicatePeople.tsx
  frontend/src/employee-frontend/components/reports/EndedPlacements.tsx
  frontend/src/employee-frontend/components/reports/FamilyConflicts.tsx
  frontend/src/employee-frontend/components/reports/FamilyDaycareMealCount.tsx
  frontend/src/employee-frontend/components/reports/Invoices.tsx
  frontend/src/employee-frontend/components/reports/ManualDuplicationReport.tsx
  frontend/src/employee-frontend/components/reports/MissingServiceNeed.tsx
  frontend/src/employee-frontend/components/reports/Occupancies.tsx
  frontend/src/employee-frontend/components/reports/PartnersInDifferentAddress.tsx
  frontend/src/employee-frontend/components/reports/PlacementCount.tsx
  frontend/src/employee-frontend/components/reports/PlacementGuarantee.tsx
  frontend/src/employee-frontend/components/reports/PresenceReport.tsx
  frontend/src/employee-frontend/components/reports/ServiceNeeds.tsx
  frontend/src/employee-frontend/components/reports/VoucherServiceProviderUnit.tsx
  frontend/src/employee-frontend/components/reports/queries.ts
Labels: tech

#6524 Tulevat työvuorot mobiiliin - osa 2
  frontend/src/e2e-test/pages/mobile/staff-page.ts
  frontend/src/e2e-test/specs/6_mobile/planned-staff-attendances.spec.ts
  frontend/src/employee-mobile-frontend/App.tsx
  frontend/src/employee-mobile-frontend/staff-attendance/StaffAttendancesPage.tsx
  frontend/src/employee-mobile-frontend/staff-attendance/StaffMemberPage.tsx
  frontend/src/employee-mobile-frontend/staff-attendance/StaffMemberPlannedAttendancesPage.tsx
  frontend/src/lib-customizations/defaults/employee-mobile-frontend/i18n/fi.ts
Labels: enhancement

#6535 Espoo: enabloidaan usean lapsen lähteneeksi merkitseminen
  frontend/src/lib-customizations/espoo/featureFlags.tsx
Labels: no-changelog

#6532 Massaviestintään mahdollisuus lähettää viesti vanhemmille lapsille
  frontend/src/employee-frontend/components/messages/MessageEditor.tsx
Labels: enhancement

#6528 Espoo: Muutokset eskarin ja valmistavan päätöksiin
  service/src/main/resources/WEB-INF/templates/preparatory/decision.properties
  service/src/main/resources/WEB-INF/templates/preparatory/decision_sv.properties
  service/src/main/resources/WEB-INF/templates/preschool/decision.properties
Labels: no-changelog

#6530 Ei lisätä automaattisesti VTJ-huoltajaa päämieheksi jos lapsella on myös sijaishuoltaja
  service/src/integrationTest/kotlin/fi/espoo/evaka/pis/service/FridgeFamilyServiceIntegrationTest.kt
  service/src/main/kotlin/fi/espoo/evaka/pis/service/FridgeFamilyService.kt
Labels: enhancement

#6533 Korjaus viestien lähettämiseen ryhmittämättömille lapsille
  service/src/main/kotlin/fi/espoo/evaka/messaging/MessageQueries.kt
Labels: bug

#6529 Lisätään yksikön hakuprosessi-sivulle siirtohakemukset listaus
  frontend/src/e2e-test/pages/employee/units/unit.ts
  frontend/src/e2e-test/specs/5_employee/unit-transfer-applications.spec.ts
  frontend/src/employee-frontend/components/unit/TabApplicationProcess.tsx
  frontend/src/employee-frontend/components/unit/TabTransferApplications.tsx
  frontend/src/lib-common/generated/action.d.ts
  frontend/src/lib-common/generated/api-types/application.ts
  frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
  service/src/integrationTest/kotlin/fi/espoo/evaka/application/UnitTransferApplicationsIntegrationTest.kt
  service/src/main/kotlin/fi/espoo/evaka/application/Application.kt
  service/src/main/kotlin/fi/espoo/evaka/application/ApplicationControllerV2.kt
  service/src/main/kotlin/fi/espoo/evaka/application/ApplicationQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/security/Action.kt
Labels: enhancement

#6536 Korjataan hakemustekstin lihavointi
  frontend/src/lib-customizations/defaults/citizen/i18n/en.tsx
  frontend/src/lib-customizations/defaults/citizen/i18n/fi.tsx
  frontend/src/lib-customizations/defaults/citizen/i18n/sv.tsx
Labels: bug

#6531 Nekku allergioiden haku ja tallennus eVakaan
  service/src/integrationTest/kotlin/fi/espoo/evaka/nekku/NekkuIntegrationTest.kt
  service/src/main/kotlin/fi/espoo/evaka/nekku/NekkuQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/nekku/NekkuService.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/async/AsyncJob.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/job/ScheduledJobs.kt
  service/src/main/resources/db/migration/V508__nekku_special_diet.sql
  service/src/main/resources/migrations.txt
Labels: enhancement

#6552 Korjaus Nekku erikoisruokavalion mappaukseen
  service/src/main/kotlin/fi/espoo/evaka/nekku/NekkuService.kt
Labels: bug

#6551 Muutetaan yksikön siirtohakemusten listauksen otsikko
  frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
Labels: enhancement

#6557 Spring-boot päivitys 3.4.1 -> 3.4.3
  service/gradle/libs.versions.toml
Labels: dependencies

#6549 Sijoitusehdotusten massahyväksynnän parantaminen
  frontend/src/employee-frontend/components/unit/tab-placement-proposals/PlacementProposals.tsx
  frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
Labels: enhancement

#6555 Nekku hae tuotteet rajapinta
  service/src/integrationTest/kotlin/fi/espoo/evaka/nekku/NekkuIntegrationTest.kt
  service/src/main/kotlin/fi/espoo/evaka/nekku/NekkuQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/nekku/NekkuService.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/async/AsyncJob.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/job/ScheduledJobs.kt
  service/src/main/resources/db/migration/V509__nekku_product.sql
  service/src/main/resources/migrations.txt
Labels: enhancement

#6561 Muutetaan yksikön siirtohakemusten listauksen sarakkeen nimi
  frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
Labels: enhancement

#6563 Päivitetään spring boot 3.4.3 -> 3.4.4
  service/gradle/libs.versions.toml
Labels: dependencies

#6562 Näytä lapsen osoite tooltipissä hakemuslistauksessa
  frontend/src/employee-frontend/components/applications/ApplicationsList.tsx
  frontend/src/lib-common/generated/api-types/application.ts
  service/src/main/kotlin/fi/espoo/evaka/application/Application.kt
  service/src/main/kotlin/fi/espoo/evaka/application/ApplicationQueries.kt
Labels: enhancement

#6564 Lisätään palveluntarpeen konfigurointimahdollisuus esiopetushakemusten tuontiin
  service/src/integrationTest/kotlin/fi/espoo/evaka/FullApplicationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/application/PlacementToolServiceIntegrationTest.kt
  service/src/main/kotlin/fi/espoo/evaka/EvakaEnv.kt
  service/src/main/kotlin/fi/espoo/evaka/application/PlacementToolService.kt
Labels: enhancement

#6537 Tekninen: Eslint LocalDate triple equals sääntö
  frontend/eslint-plugin/index.js
  frontend/eslint-plugin/rules/no-localdate-triple-equals.js
  frontend/eslint-plugin/rules/no-localdate-triple-equals.spec.js
  frontend/src/lib-common/local-date.spec.ts
Labels: tech

#6550 Korjaus tulotietovertailusta syntyviin turhiin luonnoksiin
  service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/service/VoucherValueDecisionGeneratorIntegrationTest.kt
  service/src/main/kotlin/fi/espoo/evaka/invoicing/domain/FeeDecisions.kt
  service/src/main/kotlin/fi/espoo/evaka/invoicing/domain/FinanceDecisions.kt
  service/src/main/kotlin/fi/espoo/evaka/invoicing/domain/VoucherValueDecisions.kt
  service/src/main/kotlin/fi/espoo/evaka/invoicing/service/FinanceDecisionGenerator.kt
  service/src/main/kotlin/fi/espoo/evaka/invoicing/service/generator/FeeDecisionGeneratorV2.kt
  service/src/main/kotlin/fi/espoo/evaka/invoicing/service/generator/SharedLogic.kt
  service/src/main/kotlin/fi/espoo/evaka/invoicing/service/generator/VoucherValueDecisionGeneratorV2.kt
  service/src/test/kotlin/fi/espoo/evaka/invoicing/service/generator/FeeDecisionGeneratorV2Test.kt
Labels: bug

#6578 Run `yarn dedupe`
  apigw/yarn.lock
  frontend/yarn.lock
Labels: no-changelog

#6568 Korjaus avoimen välin poissaolokyselyyn vastaamiseen
  frontend/src/citizen-frontend/calendar/holiday-modal/OpenRangesSelectionModal.tsx
  frontend/src/citizen-frontend/calendar/holiday-modal/RangesSelector.tsx
Labels: bug

#6560 Modernisoidaan koodia
  frontend/src/citizen-frontend/calendar/discussion-reservation-modal/DiscussionReservationModal.tsx
  frontend/src/employee-frontend/App.tsx
  frontend/src/employee-frontend/components/ai/AIPage.tsx
  frontend/src/employee-frontend/components/application-page/ApplicationActionsBar.tsx
  frontend/src/employee-frontend/components/application-page/ApplicationDecisionsSection.tsx
  frontend/src/employee-frontend/components/application-page/ApplicationPage.tsx
  frontend/src/employee-frontend/components/application-page/ApplicationReadView.tsx
  frontend/src/employee-frontend/components/application-page/DecisionResponse.tsx
  frontend/src/employee-frontend/components/application-page/VTJGuardian.tsx
  frontend/src/employee-frontend/components/application-page/queries.ts
  frontend/src/employee-frontend/components/employee-pin-code/EmployeePinCodePage.tsx
  frontend/src/employee-frontend/components/employee-pin-code/queries.ts
  frontend/src/employee-frontend/components/employee-preferred-first-name/EmployeePreferredFirstNamePage.tsx
  frontend/src/employee-frontend/components/employee-preferred-first-name/queries.ts
  frontend/src/employee-frontend/components/income-statements/IncomeStatementPage.tsx
  frontend/src/employee-frontend/components/income-statements/queries.ts
  frontend/src/employee-frontend/components/person-profile/FosterChildren.tsx
  frontend/src/employee-frontend/components/person-profile/queries.ts
  frontend/src/employee-frontend/components/reports/csv.ts
  frontend/src/employee-frontend/components/unit-features/UnitFeaturesPage.tsx
  frontend/src/employee-frontend/components/unit-features/queries.ts
  frontend/src/employee-frontend/components/unit/group-caretakers/GroupCaretakers.tsx
  frontend/src/employee-frontend/components/unit/group-caretakers/GroupCaretakersModal.tsx
  frontend/src/employee-frontend/components/unit/group-caretakers/queries.ts
  frontend/src/employee-frontend/components/unit/tab-calendar/discussion-surveys/survey-editor/DiscussionSurveyEditor.tsx
  frontend/src/employee-frontend/components/unit/tab-calendar/discussion-surveys/survey-editor/DiscussionSurveyForm.tsx
  frontend/src/employee-frontend/components/unit/tab-calendar/discussion-surveys/survey-editor/form.tsx
  frontend/src/employee-frontend/components/unit/tab-unit-information/acl-modals/AddTemporaryEmployeeModal.tsx
  frontend/src/employee-frontend/components/unit/tab-unit-information/acl-modals/EditTemporaryEmployeeModal.tsx
  frontend/src/employee-frontend/components/utils.ts
  frontend/src/employee-frontend/constants.ts
  frontend/src/employee-frontend/generated/api-clients/application.ts
  frontend/src/employee-frontend/queries.ts
  frontend/src/employee-mobile-frontend/child-attendance/AttendancePageWrapper.tsx
  frontend/src/employee-mobile-frontend/child-attendance/ChildSubListItem.tsx
  frontend/src/employee-mobile-frontend/child-attendance/DayList.tsx
  frontend/src/employee-mobile-frontend/common/components.tsx
  frontend/src/lib-common/api.ts
  frontend/src/lib-components/layout/FullWidthDiv.tsx
  frontend/src/lib-components/layout/StickyFooter.tsx
  service/src/main/kotlin/fi/espoo/evaka/application/ApplicationControllerV2.kt
Labels: tech

#6565 Korjaus kuntalaisen viestinnän nappien asetteluun
  frontend/src/citizen-frontend/messages/ThreadList.tsx
  frontend/src/citizen-frontend/messages/ThreadView.tsx
  frontend/src/e2e-test/pages/citizen/citizen-messages.ts
  frontend/src/e2e-test/specs/0_citizen/foster-parents.spec.ts
  frontend/src/e2e-test/specs/6_mobile/messages.spec.ts
  frontend/src/e2e-test/specs/7_messaging/messaging-by-staff.spec.ts
  frontend/src/e2e-test/specs/7_messaging/messaging.spec.ts
  frontend/src/e2e-test/specs/7_messaging/municipal-messaging.spec.ts
  frontend/src/e2e-test/specs/7_messaging/out-of-office.spec.ts
  frontend/src/e2e-test/specs/7_messaging/service-worker-messaging.spec.ts
Labels: bug

#6465 Talouden viestintä aikuisen sivulta
  frontend/src/citizen-frontend/messages/MessageEditor.tsx
  frontend/src/citizen-frontend/messages/MessagesPage.tsx
  frontend/src/citizen-frontend/messages/ThreadView.tsx
  frontend/src/e2e-test/pages/employee/guardian-information.ts
  frontend/src/e2e-test/specs/4_finance/person-finance-notes-and-messages.spec.ts
  frontend/src/e2e-test/specs/8_access/access.spec.ts
  frontend/src/employee-frontend/components/messages/MessageContext.tsx
  frontend/src/employee-frontend/components/messages/MessageEditor.tsx
  frontend/src/employee-frontend/components/messages/MessagesPage.tsx
  frontend/src/employee-frontend/components/messages/Sidebar.tsx
  frontend/src/employee-frontend/components/messages/queries.ts
  frontend/src/employee-frontend/components/messages/types-view.ts
  frontend/src/employee-frontend/components/person-profile/PersonFinanceNotesAndMessages.tsx
  frontend/src/employee-frontend/generated/api-clients/messaging.ts
  frontend/src/lib-common/generated/api-types/messaging.ts
  frontend/src/lib-components/messages/types.ts
  frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
  service/src/integrationTest/kotlin/fi/espoo/evaka/messaging/MessageAccountQueriesTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/messaging/MessageIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/messaging/MessageQueriesTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/pis/InactivePeopleCleanupIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/pis/service/MergeServiceIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/shared/config/SharedIntegrationTestConfig.kt
  service/src/main/kotlin/fi/espoo/evaka/EspooConfig.kt
  service/src/main/kotlin/fi/espoo/evaka/messaging/Message.kt
  service/src/main/kotlin/fi/espoo/evaka/messaging/MessageAccountQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/messaging/MessageController.kt
  service/src/main/kotlin/fi/espoo/evaka/messaging/MessageControllerCitizen.kt
  service/src/main/kotlin/fi/espoo/evaka/messaging/MessageNotificationEmailService.kt
  service/src/main/kotlin/fi/espoo/evaka/messaging/MessageQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/messaging/MessageService.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/FeatureConfig.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/dev/DevApi.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/security/Action.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/security/actionrule/IsEmployee.kt
  service/src/main/resources/db/migration/R__message_account_name_view.sql
  service/src/main/resources/db/migration/V510__finance_message_account_type.sql
  service/src/main/resources/db/migration/V511__finance_message_account.sql
  service/src/main/resources/migrations.txt
Labels: enhancement

#6570 Poistetaan käyttämättömät endpointit
  frontend/src/citizen-frontend/generated/api-clients/calendarevent.ts
  frontend/src/employee-frontend/api/attachments.ts
  frontend/src/employee-frontend/components/person-profile/person-fridge-child/FridgeChildModal.tsx
  frontend/src/employee-frontend/generated/api-clients/assistanceneed.ts
  frontend/src/employee-frontend/generated/api-clients/daycare.ts
  frontend/src/employee-frontend/generated/api-clients/invoicing.ts
  frontend/src/employee-frontend/generated/api-clients/pis.ts
  frontend/src/lib-common/generated/action.d.ts
  frontend/src/lib-common/generated/api-types/assistanceneed.ts
  frontend/src/lib-common/generated/api-types/invoicing.ts
  frontend/src/lib-common/generated/api-types/pis.ts
  service/src/integrationTest/kotlin/fi/espoo/evaka/calendarevent/CalendarEventServiceIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/pis/PersonIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/pis/controller/EmployeeControllerIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/pis/controller/ParentshipControllerIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/pis/controller/PartnershipsControllerIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/pis/dao/PersonQueriesIntegrationTest.kt
  service/src/main/kotlin/fi/espoo/evaka/Audit.kt
  service/src/main/kotlin/fi/espoo/evaka/assistanceneed/preschooldecision/AssistanceNeedPreschoolDecisionController.kt
  service/src/main/kotlin/fi/espoo/evaka/calendarevent/CalendarEventController.kt
  service/src/main/kotlin/fi/espoo/evaka/daycare/controllers/LocationController.kt
  service/src/main/kotlin/fi/espoo/evaka/invoicing/controller/FeeDecisionGeneratorController.kt
  service/src/main/kotlin/fi/espoo/evaka/invoicing/messaging/FeeDecisionGenerationJobProcessor.kt
  service/src/main/kotlin/fi/espoo/evaka/pis/Person.kt
  service/src/main/kotlin/fi/espoo/evaka/pis/PersonQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/pis/controllers/EmployeeController.kt
  service/src/main/kotlin/fi/espoo/evaka/pis/controllers/ParentshipController.kt
  service/src/main/kotlin/fi/espoo/evaka/pis/controllers/PartnershipsController.kt
  service/src/main/kotlin/fi/espoo/evaka/pis/controllers/PersonController.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/security/Action.kt
  service/src/main/kotlin/fi/espoo/evaka/shared/security/actionrule/IsEmployee.kt
Labels: tech

#6559 Muutos tuloselvityksen täytön järjestykseen
  frontend/src/citizen-frontend/income-statements/IncomeStatementForm.tsx
  frontend/src/citizen-frontend/income-statements/IncomeStatementView.tsx
  frontend/src/e2e-test/specs/0_citizen/citizen-income-statement.spec.ts
  frontend/src/e2e-test/specs/0_citizen/citizen-income.spec.ts
  frontend/src/lib-customizations/defaults/citizen/i18n/en.tsx
  frontend/src/lib-customizations/defaults/citizen/i18n/fi.tsx
  frontend/src/lib-customizations/defaults/citizen/i18n/sv.tsx
Labels: enhancement

#6580 Korjaus yksittäisen päämiehen oikaisulaskujen muodostukseen
  service/src/main/kotlin/fi/espoo/evaka/invoicing/data/InvoiceQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/invoicing/service/InvoiceGenerator.kt
Labels: bug

#6569 Seutuselvitysraportin muutoksia
  service/src/integrationTest/kotlin/fi/espoo/evaka/reports/TampereRegionalSurveyTest.kt
  service/src/main/kotlin/fi/espoo/evaka/reports/TampereRegionalSurvey.kt
Labels: enhancement

#6581 Säilytetään hakutoiveiden järjestys
  frontend/src/citizen-frontend/applications/editor/unit-preference/UnitsSubSection.tsx
  frontend/src/lib-common/api-types/application/ApplicationFormData.ts
Labels: bug

#6589 Mahdollistetaan Nekku-asiakasnumeron poistaminen ryhmältä
  frontend/src/employee-frontend/components/unit/tab-groups/groups/group/GroupUpdateModal.tsx
Labels: enhancement

#6585 Lisätty lapsen tietoihin valitsin Nekku-ruokatilausten ruokavaliolle
  frontend/src/employee-frontend/components/child-information/person-details/AdditionalInformation.tsx
  frontend/src/employee-frontend/components/child-information/person-details/queries.ts
  frontend/src/employee-frontend/generated/api-clients/nekku.ts
  frontend/src/lib-common/generated/api-types/daycare.ts
  frontend/src/lib-common/generated/api-types/nekku.ts
  frontend/src/lib-customizations/defaults/employee/i18n/fi.tsx
  service/src/main/kotlin/fi/espoo/evaka/daycare/ChildQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/daycare/controllers/ChildController.kt
  service/src/main/kotlin/fi/espoo/evaka/nekku/NekkuController.kt
  service/src/main/kotlin/fi/espoo/evaka/nekku/NekkuService.kt
  service/src/main/resources/db/migration/V512__nekku_diet.sql
  service/src/main/resources/migrations.txt
Labels: enhancement

#6556 Lapseen liittyvät viestit henkilökunnan mobiilissa
  frontend/src/e2e-test/pages/mobile/child-messages-page.ts
  frontend/src/e2e-test/pages/mobile/child-page.ts
  frontend/src/e2e-test/specs/6_mobile/messages.spec.ts
  frontend/src/employee-mobile-frontend/App.tsx
  frontend/src/employee-mobile-frontend/child-info/ChildButtons.tsx
  frontend/src/employee-mobile-frontend/common/ChildNameBackButton.tsx
  frontend/src/employee-mobile-frontend/generated/api-clients/messaging.ts
  frontend/src/employee-mobile-frontend/messages/ChildMessagesPage.tsx
  frontend/src/employee-mobile-frontend/messages/MessagesPage.tsx
  frontend/src/employee-mobile-frontend/messages/ReceivedThreadsList.tsx
  frontend/src/employee-mobile-frontend/messages/ThreadView.tsx
  frontend/src/employee-mobile-frontend/messages/queries.ts
  frontend/src/employee-mobile-frontend/pairing/components.tsx
  frontend/src/lib-customizations/defaults/employee-mobile-frontend/i18n/fi.ts
  service/src/main/kotlin/fi/espoo/evaka/messaging/MessageController.kt
  service/src/main/kotlin/fi/espoo/evaka/messaging/MessageQueries.kt
Labels: enhancement

#6592 Korjataan puuttuva import
  service/src/main/kotlin/fi/espoo/evaka/messaging/MessageController.kt
Labels: no-changelog

#6594 Korjaus tulojen vertailuun talouspäätöksissä
  service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/service/FeeDecisionGeneratorIntegrationTest.kt
  service/src/integrationTest/kotlin/fi/espoo/evaka/invoicing/service/VoucherValueDecisionGeneratorIntegrationTest.kt
  service/src/main/kotlin/fi/espoo/evaka/invoicing/domain/FeeDecisions.kt
  service/src/main/kotlin/fi/espoo/evaka/invoicing/domain/FinanceDecisions.kt
  service/src/main/kotlin/fi/espoo/evaka/invoicing/domain/Incomes.kt
  service/src/main/kotlin/fi/espoo/evaka/invoicing/domain/VoucherValueDecisions.kt
  service/src/main/kotlin/fi/espoo/evaka/invoicing/service/FinanceDecisionGenerator.kt
  service/src/main/kotlin/fi/espoo/evaka/invoicing/service/generator/FeeDecisionGeneratorV2.kt
  service/src/main/kotlin/fi/espoo/evaka/invoicing/service/generator/SharedLogic.kt
  service/src/main/kotlin/fi/espoo/evaka/invoicing/service/generator/VoucherValueDecisionGeneratorV2.kt
  service/src/test/kotlin/fi/espoo/evaka/invoicing/service/generator/FeeDecisionGeneratorV2Test.kt
Labels: bug

#6591 Piilotetaan hakemuksen liitteet toiselta huoltajalta
  frontend/src/citizen-frontend/applications/editor/service-need/ServiceTimeSubSectionDaycare.tsx
  frontend/src/citizen-frontend/applications/editor/verification/ApplicationVerificationView.tsx
  frontend/src/citizen-frontend/applications/editor/verification/ServiceNeedAttachments.tsx
  frontend/src/citizen-frontend/applications/editor/verification/ServiceNeedSection.tsx
  frontend/src/citizen-frontend/applications/read-view/ApplicationReadViewContents.tsx
  frontend/src/e2e-test/pages/citizen/citizen-applications.ts
  frontend/src/e2e-test/specs/0_citizen/citizen-daycare-application.spec.ts
  service/src/main/kotlin/fi/espoo/evaka/application/Application.kt
  service/src/main/kotlin/fi/espoo/evaka/application/ApplicationControllerCitizen.kt
  service/src/main/kotlin/fi/espoo/evaka/application/ApplicationQueries.kt
Labels: enhancement

#6607 Näytetään yksikön ruoka-ajat myös Nekku integraation ollessa aktiivinen
  frontend/src/employee-frontend/components/unit/unit-details/UnitEditor.tsx
Labels: enhancement

#6608 Jaa Nekku-integraation enum-luokat APIn ja eVakan käyttämiin enumeihin
  service/src/integrationTest/kotlin/fi/espoo/evaka/nekku/NekkuIntegrationTest.kt
  service/src/main/kotlin/fi/espoo/evaka/nekku/NekkuController.kt
  service/src/main/kotlin/fi/espoo/evaka/nekku/NekkuQueries.kt
  service/src/main/kotlin/fi/espoo/evaka/nekku/NekkuService.kt
Labels: tech
